### PR TITLE
Update P3 microphysics for release v4.5

### PR DESCRIPTION
**Pull request by hmorrison100**
The first line should be a single-line "purpose" for this change

TYPE: Bug fix + enhancement 

KEYWORDS: P3, microphysics

SOURCE: Hugh Morrison (NCAR)

DESCRIPTION OF CHANGES:
Problem:
Further enhancements and minor bug fixes to P3 microphysics (P3v4.5.1+). Minor bugs in the change in rain number during ice melting when ice amounts are tiny (almost no impact), 3-moment category interaction and merging (not relevant to WRF), the GEM wrapper (not relevant to WRF), and a minor bug in lookup table 2 (formula for diagnostic mu_i). Inaccurate units and description for output qzi variable (non-answer changing). Streamline and code cleanup in the lookup table generation codes and P3.

Solution:
 - P3 code cleanup (consistent spacing, clarifying comments, etc) (non answer changing)
 - Change in the internal P3 module name (thus requiring changes in the "use" statements in module_microphysics_driver.F 
    and module_physics_init.F)
 - Minor bug fixes (addressing bugs noted above)
 - Refactoring of the GEM wrapper (not relevant to WRF)
 - Feature change to the lookup table 1 for 3-moment ice (changing number of mu indices from 11 to 10)
 - Cleanup of lookup table generation codes
 - Fix to description and units for output variable 'qzi' in Registry.EM_COMMON
 - Linked to new lookup table file names in top-level Makefile

ISSUE: N/A

LIST OF MODIFIED FILES: list of changed files (use `git diff --name-status master` to get formatted list)

Modified/replaced: module_mp_p3.F, module_microphysics_driver.F, module_physics_init.F, Registry.EM_COMMON, top-level Makefile

Removed: create_p3_lookupTable_1-2mom_v5.3.f90, create_p3_lookupTable_1-3mom_v5.1.7.f90, create_p3_lookupTable_2-v5.2.3.f90, p3_lookupTable_1.dat-5.3-2momI, p3_lookupTable_1.dat-3momI_v5.1.7, p3_lookupTable_2.dat-2momI_v5.2.3

Added (to replace the above lookup table generation source code files and lookup table files): create_p3_lookupTable_1.f90-v5.4, create_p3_lookupTable_2.f90-v5.3, p3_lookupTable_1.dat-v5.4_2momI, p3_lookupTable_1.dat-v5.4_3momI, p3_lookupTable_2.dat-v5.3

TESTS CONDUCTED: 
1. All problems and issues have been resolved. P3v4.5.1 has been extensively tested in the GEM model for a large suite of real-weather test cases. All 4 P3 mp options run successfully and give good results for the idealized supercell test case (only very minor changes from the previous version of P3).
2. ??

RELEASE NOTE: Update of P3 (P3v4.5.1+bf)

### CODE REVIEW

**Comment by weiwangncar** [comment]
@hmorrison100 There are two places in the top level Makefile that need change: it links the p3* data files to the run directory. If you search for 'p3_lookupTable_1', you should find them. The missing of correctly linked files caused a regtest failure for mp option 52.

**Comment by hmorrison100** [comment]
@weiwangncar Thanks for letting me know. I fixed this in the top-level Makefile and added to the commit (in my testing, I had directly copied the new lookup table files to the directory I ran the code in, so didn't catch this problem). Let me know if there are any other problems.

**Comment by mgduda** [comment]
@hmorrison100 @weiwangncar I think this work should have been committed to a new development branch (and not to `release-v4.5` in @hmorrison100's fork); see the [Workflow for WRF Code Modifications](https://github.com/wrf-model/WRF/wiki/Workflow-for-WRF-Code-Modification) page (in particular, the section "Creating a Branch for Development Work").

**Comment by hmorrison100** [comment]
@mgduda @weiwangncar This isn't development work though, it's minor bug fixes and code clean up. There's no new features or major development pieces. I've cleaned up the PR notes to clarify. Does this still need to be done on a development branch?

**Comment by mgduda** [comment]
@hmorrison100 In general, changes should always be committed to a new branch. (See the section "Creating a Branch for Bug Fix Modifications" of the wiki page linked above).

**Comment by dudhia** [comment]
@mgduda We approved this delayed update to Hugh's scheme in the newly
created release branch.

**Comment by mgduda** [comment]
> @mgduda We approved this delayed update to Hugh's scheme in the newly created release branch.

The issue isn't whether the changes can go in to the `release-v4.5` branch, but that the changes should have been committed to a new branch (and not directly to the head of the `release-v4.5` branch in @hmorrison100's fork).

**Comment by dudhia** [comment]
He updated his code to release-4.5 before sending the PR. I am not sure I understand the issue. However, the name of the PR should not be so generic.

**Comment by hmorrison100** [comment]
@dudhia @mgduda It will be easy to just redo this and create a new branch (off of release-v4.5) in my fork. So I can do that, and will start a new PR and kill this one. Might take me a few days to get to this though, I'm a bit underwater with things at the moment. Will this be ok?

**Comment by dudhia** [comment]
I would like to hear the problem from @mgduda before @hmorrison100 does it over.

**Comment by weiwangncar** [comment]
@hmorrison100 @mgduda @dudhia If I understand Michael's concern, you can simply create a new PR from your current fork like this: git push origin release-v4.5:p3-update-for-4.5, for example. This assumes the origin is your fork on Github, and your branch on the fork is now p3-update-for-4.5. In the future, the best practice would be to check out release-v4.5 (or develop), and create a branch from that before making your own update/changes.
But I will have to insist that @hmorrison100 to redo Makefile change: Get the original one, and only make changes to the relevant lines, instead removing the entire file, and creating a new one - we may lose the file change history this way. 
@mgduda What is the best way to do this?

**Comment by hmorrison100** [comment]
@weiwangncar yes, understood. What happened is I was not using command line Git, and it was not obvious how to modify files w/o deleting them first. But I think there's an easy work-around and I'll try that, or else just use command line Git when it shouldn't be a problem. Will try and get to it next week, but seems like there's not a huge hurry.

**Review by dudhia — COMMENTED** [review]
I am ready to approve this if the tests passed.

**Comment by hmorrison100** [comment]
@dudhia Sorry for the delay here. I'm actually planning to close this PR and redo it to address @mgduda and @weiwangncar 's concerns. Working on it this afternoon so should have something new soon.

**Pull request closed without merging**
