### PR TITLE
MP Thompson: mean snow size init; limit max values of snow/graupel/cloud; terminal velocity for rimed snow 

### PR DESCRIPTION
**Pull request by gthompsnWRF**
TYPE: bug fix

KEYWORDS:  MP, Thompson, xDs, vts_boost

SOURCE:  Greg Thompson (NCAR-RAL)

DESCRIPTION OF CHANGES:  Some relatively minor bug fixes and safety checks
1. xDs (mass-weighted mean size snow) was only set if both cloud water and snow coexist in grid 
box, so its calculation was moved out of IF-test to be calculated at any grid box with any 
reasonable amount of snow.
2. couple small safety checks to avoid exceeding max amount of possible snow, graupel, or cloud 
water in a few places (e.g., prs_scw, prr_sml, tmg_gacs)
3. vts_boost should always default 1.0, not 1.5. vts_boost is the factor applied to snow terminal 
fallspeed due to riming of snow (up to 50% faster).
4. ensure snow moment variables get initialized to zero in calc_refl10cm
5. density calculation moved up (out of IF-test) in preparation for additional future changes where it 
is always needed.
6. permitting larger max value of ice crystal concentration (999 per Liter)
7. small constant change related to rimed snow boost terminal velocity

LIST OF MODIFIED FILES:  
M  phys/module_mp_thompson.F

TESTS CONDUCTED:  
1. After these mods, the code compiles and produces indistinguishable changes in final WRF runs.
There were such small changes that nothing can be easily found in any real model simulation 
results to see any impacts.

### CODE REVIEW

**Comment by davegill** [comment]
@gthompsnWRF 
Greg,
Would you add comments concerning 
1. moving the density computation from one place to another
2. 500 e3 -> 999 e3
3. 0.14 -> 0.16

Also, explicitly state after these mods that 
1. the code still compiles
2. still gives reasonable results

**Comment by gthompsnWRF** [comment]
Additional FYI:
1)  density calculation moved up (out of IF-test) in preparation for additional future changes where it is always needed.
2)  permitting larger max value of ice crystal concentration (999 per Liter)
3)  small constant change related to rimed snow boost terminal velocity

After these mods, code compiles and produces indistinguishable changes in final WRF runs.

**Comment by davegill** [comment]
@dudhia @weiwangncar @gthompsnWRF 
Folks,
The PR message accurately reflects the modifications. These mods seem typical of small tweaks to include in the next release. Greg said virtually no noticeable changes in his tests. I am OK to have this code merged.

**Comment by weiwangncar** [comment]
@gthompsnWRF What is vts_boost?

**Comment by gthompsnWRF** [comment]
@weiwangncar  vts_boost is the factor applied to snow terminal fallspeed due to riming of snow (up to 50% faster).

**Comment by weiwangncar** [comment]
@gthompsnWRF Could you then add that info to your number 3 in the PR just so that we know what that variable is? Thanks.

**Comment by gthompsnWRF** [comment]
@weiwangncar  it was always in the code so I don't see that an explanation of that variable alone as very meaningful.  It's just been default to 1.5 for melting snow, but now that a code fix was made (last release) for melting snow, this should now get a default of 1.0, not 1.5 as before.

**Comment by weiwangncar** [comment]
@gthompsnWRF It just helps people who reads the PR more easily. But it's ok without it. I'm ok with the PR.

**Comment by davegill** [comment]
@weiwangncar @gthompsnWRF 
Wei,
I agree with the request to more clearly define vts_boost. I added Greg's descriptive comment into the commit message.

**Comment by davegill** [comment]
@dudhia @weiwangncar 
Jimy,
Wei and I have both approved this. Would you please provide a review.

**Pull request merged**
