### PR TITLE
Adding a fast surface shortwave parameterization (FARMS)

### PR DESCRIPTION
**Pull request by pedro-jm**
TYPE: new feature

KEYWORDS: Fast surface shortwave irradiance parameterization

SOURCE: FARMS code provided by Yu Xie (NREL). Pedro Jimenez (NCAR/RAL) coupled FARMS to WRF.

DESCRIPTION OF CHANGES: 
Due to the large computation cost, radiation parameterizations are not typically called every time 
step. As a result, the surface irradiances time series show discontinuities that depend on the 
radiation calls frequency. This new parameterization, FARMS, provides fast calculation of the 
surface shortwave irradiance allowing to call it every model time step. 

The scheme is activated by setting `swint_opt` in the WRF namelist.input file:
```
 &physics
 swint_opt  = 2
 /
```

LIST OF MODIFIED FILES: 
M       Registry/Registry.EM_COMMON
M       dyn_em/module_first_rk_step_part1.F
M       phys/Makefile
M       phys/module_ra_aerosol.F
A       phys/module_ra_farms.F
M       phys/module_radiation_driver.F
M       run/README.namelist

TESTS CONDUCTED: 
1. WRF run shows updates in the shortwave irradiances from FARMS every time step. The figure below shows the irradainces from RRTMG called every 15 min (left), and from FARMS (right) which is always called every model time step.

Screen Shot 2019-12-02 at 3 55 26 PM
This shows results of downward shortwave at some US surface sites. RRTMG is swint_opt=1. Generally FARMS has more cloud effect (thanks to Ju-Hye Kim for this plot).
Screen Shot 2020-02-06 at 10 02 01 AM

RELEASE NOTE: A new parameterization, FARMS (Fast All-sky Radiation Model for Solar applications), provides fast calculation of the surface shortwave irradiance allowing the WRF model to call the scheme every model time step, resulting in a temporally smooth irradiance. The scheme is activated by setting `swint_opt = 2` in the WRF namelist.input file.

### CODE REVIEW

**Comment by dudhia** [comment]
I have to note that we also expect the Physics Review Panel to approve this, but that has been delayed.

**Comment by davegill** [comment]
@pedro-jm @kkeene44 
Pedro,
Provide a couple of figures that show the time series of the irradiances, a before vs after. Include this in the PR commit message.

In the commit message, include how a user would call / activate this scheme.

Augment your description in the README.namelist file (just a sentence would be OK). 

Send Kelly a few sentences on what you would like the User's Guide to say.

**Comment by davegill** [comment]
@pedro-jm 
Pedro,
One last small piece. Here is the Registry.EM_COMMON file with the swint_opt definition:
```
Registry.EM_COMMON:rconfig   integer swint_opt               namelist,physics      1             0       -      "swint_opt"    "interpolation option for sw radiation"      ""
```

Instead of 
```
"interpolation option for sw radiation"
```
would you make this line:
```
"interpolation option for sw radiation: 0=off, 1=blah, 2=other blah"
```

**Comment by pedro-jm** [comment]
@kkeene44 

The User's Guide could say:

swint_opt = 2 activates the Fast All-sky Radiation Model for Solar applications (FARMS). FARMS is a fast radiative transfer model that allows one to simulate the broaband solar radiation every model time step. The model uses lookup tables of cloud transmittances and reflectances by varying cloud optical thicknesses, cloud particle sizes, and solar zenit angles. A more detailed description of FARMS is provided in Xie et al. (2016).

Xie, Y., M. Sengupta and J. Dudhia, 2016: A Fast All-sky Radiation Model for Solar applicatins (FARMS): Algorithm and performance evaluation. Solar Energy, 135, 435 - 445.

**Comment by kkeene44** [comment]
@pedro-jm @davegill 
I've updated the UG in the git repository. The changes will appear in V4.2 version of the UG.

**Comment by davegill** [comment]
@dudhia 
Jimy,
Is this eligible for v4.2? Has the Physics Review Board decided?

**Comment by dudhia** [comment]
Yes, this has passed the review panel.

**Comment by davegill** [comment]
@pedro-jm @weiwangncar @dudhia 
Folks,
I do not think that the `mut` variable is sufficient in general with the available hybrid vertical coordinate to do the integrated quantities. 

Here's the call usinging `mut`:
```
               ! PMW
             pmw = ONE_OVER_G * integrate_1var (mut(i, j), dnw, qv(i, :, j), kms, kme, kts, kte)
```

Here's the routine:
```
    function Integrate_1var(mut_val, dnw, var1_1d, kms, kme, kts, kte) &
        result (return_value)
      
      implicit none

      real, intent(in) :: mut_val
      integer, intent(in) :: kts, kte, kms, kme
      real, dimension(kms:kme), intent(in) :: var1_1d, dnw

        ! Local
      real :: return_value
      integer :: k

      return_value = 0.0
      do k = kts, kte - 1
        return_value = return_value + var1_1d(k) * dnw(k)
      end do
      return_value = - mut_val * return_value

    end function Integrate_1var
```

From a github point of view, I am OK with this PR:
1. The PR is to the right branch.
2. Requested pieces (figs, user's guide, review panel status, updated comments) are all either answered favorably or have been completed.
3. The PR message is complete and an accurate reflection of the mods.
4. New variables in the Registry are packaged.
5. A README.namelist entry is supplied for the new scheme.

**Comment by dudhia** [comment]
Thanks. So this may return the wrong result if the hybrid coordinate is
used.
Later we have to figure out how to change this to generalize it, probably
as a bug-fix after
committing, or a check-a-mundo for hybrid coords could be added.
Jimy

**Comment by davegill** [comment]
@dudhia 
Jimy,
I am OK with this going in AS-IS. We need to clean up the usage of MUT so that this option works with a hybrid coordinate.

**Comment by weiwangncar** [comment]
@pedro-jm Sorry for this late comment, but do you have a plot comparing to swint_opt = 1?

**Comment by dudhia** [comment]
Wei, is the original image with the commit sufficient?

**Comment by weiwangncar** [comment]
@dudhia That comparison appears to be with swint_opt = 0, right?

**Comment by dudhia** [comment]
Isn't that sufficient to show it was working?
Would you want a time series comparison or just a map plot. Ju-Hye has
done map comparisons, but not time series,
Jimy

**Comment by dudhia** [comment]
Pedro,
It would be better to see time series of swint_opt=1 and swint_opt=2 with
clouds because that is where they may look different. No rush, but maybe
Juhye
can do this.
Jimy

**Comment by davegill** [comment]
@dudhia @weiwangncar 
Folks,
I resolved a conflict that was introduced with my mods to the radiation driver for the 2d dx. Even though this is approved, let's make sure Jenkins is OK before merging.

**Comment by davegill** [comment]
@weiwangncar @dudhia 
Folks,
Are the results from the swint_opt=1 test insufficient for a merge?

**Comment by dudhia** [comment]
Looks OK to me. This is code that WRF-Solar uses regularly.

**Pull request merged**
