### PR TITLE
Bring local Noah-MP snowmelt to output & add accumulated snowmelt output

### PR DESCRIPTION
**Pull request by cenlinhe**
Bring local snowmelt variable in Noah-MP to output variable and add accumulated snowmelt output in diagnostics

TYPE: enhancement

KEYWORDS: snowmelt, Noah-MP, output

SOURCE: Cenlin He (NCAR)

DESCRIPTION OF CHANGES:
Add two new output variables for Noah-MP package for snowmelt

ASSOCIATED REPOSITORY CHANGE:
[NCAR/noahmp#42](https://github.com/NCAR/noahmp/pull/42)

LIST OF MODIFIED FILES: list of changed files (use git diff --name-status master to get formatted list)
M Registry/Registry.EM_COMMON
M Registry/registry.noahmp
M dyn_em/module_first_rk_step_part1.F
M phys/module_diag_misc.F
M phys/module_diagnostics_driver.F
M phys/module_surface_driver.F
M phys/noahmp

### CODE REVIEW

**Comment by cenlinhe** [comment]
This version seems working. I closed the previous PR.

**Comment by weiwangncar** [comment]
Jenkins tests have passed:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@cenlinhe This is great! Did you do anything differently?

**Comment by cenlinhe** [comment]
I separate the update of the link to NoahMP submodule commit and the change in WRF files into two separate commits. But not sure why I cannot put all the changes (WRF files + NoahMP submodule commit link update) in one single commit.

**Comment by cenlinhe** [comment]
@dudhia Sorry for the confusion. The link change I meant is the link to an updated commit in the same Noah-MP branch "release-v4.4-WRF", not a new link to a new branch. It is the normal update for syncing with noahmp submodule based on Dave Gill's method.

**Comment by dudhia** [comment]
I see. How do you change the link? Is it a git command or a commit. Do you
have to update it each time the 4.4 branch changes?

**Comment by dudhia** [comment]
I think I understand now. Thanks.
Technically how is the sync done?

**Comment by cenlinhe** [comment]
@dudhia Here is the technical steps:

In your own WRF branch planned for PR submission:

1. Get the NoahMP repo available and in the WRF source code. Go to the
top-most level of the WRF directory structure to issue the following command:
git submodule update --init --recursive

2. Get the correct NoahMP branch (currently it is the release-v4.4-WRF branch from NoahMP)
cd phys/noahmp
git checkout release-v4.4-WRF
cd ..
(Note that "git checkout release-v4.4-WRF" will update the link to the latest commit in the release-v4.4-WRF in NoahMP Github)

3. Stage this modification:
git add noahmp

4. add the commit and submit the PR:
git commit -m 'sync with NoahMP recent update'

**Comment by dudhia** [comment]
Thanks.

**Comment by cenlinhe** [comment]
What confused me though is that if I do the above NoahMP commit sync update along with some WRF file changes (e.g., Registry, surface driver) together in one single WRF commit, the issue in the previous PR I ran into occurred saying something "not able to pull Noah-MP" during compilation. But when I do the NoahMP sync as a single commit first and then add WRF file changes as a second commit (as I did here for this PR), the issue is gone. I did not see this issue in our HRLDAS offline NoahMP host model update, which also puts the NoahMP github as a submodule. Anyway, I think in the future, I will just do this two-step way for WRF PR to prevent potential issue.

**Comment by cenlinhe** [comment]
I also have another PR with the NoahMP glacier bug fix that was just identified by Kevin Manning and Jordan yesterday. But I will wait until this current PR to be merged before I submit that bug fix PR, since last time Wei seems not able to merge two PRs with NoahMP commit link updates together.

**Comment by dudhia** [comment]
It is possible that not being able to pull noahmp was related to an
internet issue, so it could have been temporary(?)

**Review by weiwangncar — APPROVED** [review]
Changes are mostly passing two variables around..

**Review by dudhia — APPROVED** [review]

**Pull request merged**
