### PR TITLE
Remove unsupported -auto icx flag from Intel oneAPI stanza

### PR DESCRIPTION
**Pull request by islas**
TYPE: bug fix

KEYWORDS: intel, compilation, oneapi

SOURCE: internal

DESCRIPTION OF CHANGES:
Problem:
The `-auto` flag is not supported by the Intel C compilers. See https://www.intel.com/content/www/us/en/docs/cpp-compiler/developer-guide-reference/2021-10/alphabetical-option-list.html for full list of supported icx flags.

Solution:
Remove the flag, no output changes should happen as the flag was previously being ignored if it didn't cause an error.

### CODE REVIEW

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@islas For an older version of Intel C compiler, would removing -auto cause any trouble?

**Comment by islas** [comment]
@weiwangncar I can't find any reference to `-auto` being part of the icc compiler, so I suspect removing it would have no impact. Also, on Derecho I get this warning as well :
`icc: command line warning #10006: ignoring unknown option '-auto'`

**Review by weiwangncar — APPROVED** [review]

**Review by mgduda — APPROVED** [review]
I can confirm that the `icx` compiler rejects the `-auto` option:
```
icx: error: unknown argument: '-auto'
```

**Pull request merged**
