### PR TITLE
Varbc bugfix

### PR DESCRIPTION
**Pull request by YaliWu0219**
TYPE: bug fix

KEYWORDS: varbc, num_fgat_time>1

SOURCE: Yali Wu (NCAR)

DESCRIPTION OF CHANGES: The general procedure for doing varbc in WRFDA is: (1) calculate bias predictors (da_varbc_pred); (2) call da_varbc_coldstart; (3) apply bias correction to radiance innovations (da_varbc_direct); (4) da_qc procedures; (5) calculate covariance matrix b/w bias predictors for VarBC preconditioning (da_varbc_precond).

Previously, varbc worked correctly for cases when num_fgat_time=1. However, when num_fgat_time > 1, there are two bugs that need to be fixed. First, bias is applied to innovations before cold_varbc is calculated in cases of time slot >1. Second, the order of conducting varbc and da_qc is unclear: for the first time slot, varbc is done before da_qc, but for other time slots when num_fgat_time>1, da_qc is done before varbc. 

This PR fixed the issues mentioned above and worked properly in 4DVAR experiments.

ISSUE: No issue.

LIST OF MODIFIED FILES: 
M       var/da/da_minimisation/da_get_innov_vector.inc
M       var/da/da_minimisation/da_minimisation.f90
M       var/da/da_radiance/da_get_innov_vector_radiance.inc

TESTS CONDUCTED: Conducted regression tests on Cheyenne.

### CODE REVIEW

**Comment by YaliWu0219** [comment]
Reports of regression tests on Cheyenne: 
/glade/p/mmm/parc/wuyl/wrfda_test/REGTEST/REGTEST.backup.V4-gnu-develop/diffwrf.txt

**Comment by davegill** [comment]
@liujake 
Jake,
Do you want this PR to go to the develop or release-4.2.1 branch? If it is a bug fix, perhaps release-v4.2.1 would be better.

**Comment by liujake** [comment]
@davegill It would be good if we can have this bugfix in both 4.2.1 and develop branches. After it is committed to 4.2.1, can we merge changes from 4.2.1 into develop soon? or we have to wait for the next release to merge it into develop?

**Comment by davegill** [comment]
@liujake 
Jake,
Take a look at https://github.com/wrf-model/WRF/wiki/WRF-Branch-Flow
After we post release-v4.2.1, then those mods are merged into develop.

**Comment by davegill** [comment]
@YaliWu0219 @liujake 
Since this is a "bug fix", we want this to use the base branch: "release-v.4.2.1".
Take a look at wiki page
https://github.com/wrf-model/WRF/wiki/Workflow-for-WRF-Code-Modification
Focus on the "bug fix" part when there is a choice of "develop" or "bug fix".

It might be easier to close this PR and start a new one.

**Comment by YaliWu0219** [comment]
@davegill @liujake Ok, thank you. I will switch to the base "release-v.4.2.1".

**Pull request closed without merging**
