### PR TITLE
Hydro: Update WRF-Hydro code to v5.0.3

### PR DESCRIPTION
**Pull request by kafitzgerald**
TYPE: enhancement

KEYWORDS: WRF-Hydro, hydro, model coupling

SOURCE: 
WRF-Hydro development team, NCAR/RAL
contact: Katelyn FitzGerald

DESCRIPTION OF CHANGES: 
* Update hydro code to WRF-Hydro v5.0.3 (latest release)
* Reapply changes to make netCDF large file support the default option
* Minor edits to WRF-Hydro README in doc folder

LIST OF MODIFIED FILES: 
M       doc/README.hydro
A       hydro/.version
M       hydro/CPL/WRF_cpl/Makefile
M       hydro/CPL/WRF_cpl/module_wrf_HYDRO.F
D       hydro/Data_Rec/module_GW_baseflow_data.F
M       hydro/Data_Rec/module_namelist.F
M       hydro/Data_Rec/namelist.inc
M       hydro/Data_Rec/rt_include.inc
A       hydro/Doc/link_to_documentation.txt
M       hydro/HYDRO_drv/module_HYDRO_drv.F
A       hydro/MPP/Makefile.NoahMP
M       hydro/MPP/module_mpp_GWBUCKET.F
M       hydro/MPP/module_mpp_ReachLS.F
M       hydro/MPP/mpp_land.F
A       hydro/Makefile
D       hydro/README.hydro
A       hydro/Rapid_routing/.rapid_init.F90.swp
D       hydro/Rapid_routing/hrldas_RAPID_drv.F90
D       hydro/Rapid_routing/hrldas_RAPID_wrapper.F90
D       hydro/Rapid_routing/rapid_arrays.F90
D       hydro/Rapid_routing/rapid_close_Qfor_file.F90
D       hydro/Rapid_routing/rapid_close_Qhum_file.F90
D       hydro/Rapid_routing/rapid_close_Qobs_file.F90
D       hydro/Rapid_routing/rapid_close_Qout_file.F90
D       hydro/Rapid_routing/rapid_close_Vlat_file.F90
D       hydro/Rapid_routing/rapid_create_Qout_file.F90
D       hydro/Rapid_routing/rapid_create_obj.F90
D       hydro/Rapid_routing/rapid_destro_obj.F90
D       hydro/Rapid_routing/rapid_final.F90
D       hydro/Rapid_routing/rapid_get_Qdam.F90
D       hydro/Rapid_routing/rapid_hsh_mat.F90
D       hydro/Rapid_routing/rapid_init.F90
D       hydro/Rapid_routing/rapid_main.F90
D       hydro/Rapid_routing/rapid_net_mat.F90
D       hydro/Rapid_routing/rapid_net_mat_brk.F90
D       hydro/Rapid_routing/rapid_obs_mat.F90
D       hydro/Rapid_routing/rapid_open_Qfor_file.F90
D       hydro/Rapid_routing/rapid_open_Qhum_file.F90
D       hydro/Rapid_routing/rapid_open_Qobs_file.F90
D       hydro/Rapid_routing/rapid_open_Qout_file.F90
D       hydro/Rapid_routing/rapid_open_Vlat_file.F90
D       hydro/Rapid_routing/rapid_phiroutine.F90
D       hydro/Rapid_routing/rapid_read_Qfor_file.F90
D       hydro/Rapid_routing/rapid_read_Qhum_file.F90
D       hydro/Rapid_routing/rapid_read_Qobs_file.F90
D       hydro/Rapid_routing/rapid_read_Vlat_file.F90
D       hydro/Rapid_routing/rapid_read_namelist.F90
D       hydro/Rapid_routing/rapid_routing.F90
D       hydro/Rapid_routing/rapid_routing_param.F90
D       hydro/Rapid_routing/rapid_set_Qext0.F90
D       hydro/Rapid_routing/rapid_var.F90
D       hydro/Rapid_routing/rapid_write_Qout_file.F90
M       hydro/Routing/Makefile
M       hydro/Routing/Noah_distr_routing.F
M       hydro/Routing/module_GW_baseflow.F
M       hydro/Routing/module_HYDRO_io.F
A       hydro/Routing/module_NWM_io.F
A       hydro/Routing/module_NWM_io_dict.F
M       hydro/Routing/module_RT.F
M       hydro/Routing/module_UDMAP.F
M       hydro/Routing/module_channel_routing.F
M       hydro/Routing/module_date_utilities_rt.F
M       hydro/Routing/module_lsm_forcing.F
D       hydro/Routing/rtFunction.F
D       hydro/Run/HYDRO.TBL
D       hydro/Run/hydro.namelist
M       hydro/arc/Makefile.Noah
M       hydro/arc/Makefile.NoahMP
A       hydro/arc/macros.gordon
A       hydro/arc/macros.gordon.debug
M       hydro/arc/macros.mpp.IBM.xlf90_r
M       hydro/arc/macros.mpp.gfort
M       hydro/arc/macros.mpp.ifort
M       hydro/arc/macros.mpp.ifort.luna
M       hydro/arc/macros.mpp.linux
A       hydro/arc/macros.mpp.mpiifort
M       hydro/arc/macros.seq.IBM.xlf90_r
M       hydro/arc/macros.seq.gfort
M       hydro/arc/macros.seq.ifort
M       hydro/arc/macros.seq.linux
A       hydro/arc/macros.theia
A       hydro/arc/macros.theia.debug
A       hydro/arc/macros.yellowstone
A       hydro/arc/macros.yellowstone.debug
M       hydro/configure
A       hydro/nudging/Makefile
A       hydro/nudging/Nudging_frxst_gage.csv
A       hydro/nudging/module_date_utils_nudging.F
A       hydro/nudging/module_nudging_io.F
A       hydro/nudging/module_nudging_utils.F
A       hydro/nudging/module_stream_nudging.F
A       hydro/template/HYDRO/CHANPARM.TBL
M       hydro/template/HYDRO/HYDRO.TBL
A       hydro/template/HYDRO/HYDRO_MODIS.TBL
M       hydro/template/HYDRO/hydro.namelist
A       hydro/template/Noah/namelist.hrldas
A       hydro/template/NoahMP/namelist.hrldas
A       hydro/template/setEnvar.sh
M       hydro/wrf_hydro_config

TESTS CONDUCTED: 
I'm unfamiliar with WRF testing (though happy to run a test suite if someone can point me in the right direction). We've been doing regression testing on the WRF-Hydro side as well as running some additional manual tests.  I can elaborate on this if helpful.

RELEASE NOTE: 
Updated WRF-Hydro code to v5.0.3 - associated WRF-Hydro release notes can be found [here](https://github.com/NCAR/wrf_hydro_nwm_public/blob/bugfix-5.0.x/NEWS.md)

### CODE REVIEW

**Comment by davegill** [comment]
@kafitzgerald 
This is a huge replacement of the WRF Hydro code, so it would not be realistic to assume that we would be able to conduct an actual code review. Except for a single modification to the doc directory, all other files are located within or underneath the hydro directory.

 - [ ] Demonstrate no impact on a WRF (non hydro) build. Basically, would you build a WRF executable.
 - [ ] Kelly will grab the "release note" information as clear text. Would you please expand the "here" hyperlink to the github release page that is referenced.

If no one else makes any comments, I'll approve this early next week.

**Comment by davegill** [comment]
@kafitzgerald @kkeene44 
Katelyn,
One more thing ... we will have a PR soon that adds you as the code owner for anything that is either under the hydro directory or if there are any changes to the doc/README.hydro file.

**Comment by kafitzgerald** [comment]
Great, thank you!  Will do this morning.

Also, I did confirm that (as expected) there was no impact on a standard WRF build.

**Comment by kafitzgerald** [comment]
@kkeene44 
It looks like merging is blocked for me.  I'm happy with the PR as it stands though so if someone else would like to merge go for it.  Also happy to do so if granted the appropriate permissions.

**Comment by kkeene44** [comment]
@kafitzgerald 
No problem. I did it for you! Thanks!

**Pull request merged**
