### PR TITLE
Pxlsm lcz61 ii

### PR DESCRIPTION
**Pull request by coastwx**
Pleim-Xiu LSM MODIS LCZ Compatibility  & Surface Evaporation Update

TYPE: bug fix & physics refinement

KEYWORDS: MODIS, LCZ, P-X LSM, Latent Heat Flux

SOURCE: Robert Gilliam & Jon Pleim, US EPA

DESCRIPTION OF CHANGES:
Problem: 

1. User indicated that the P-X LSM errored for MODIS LCZ 61 NUM_LAND_CAT configuration.
2. Currently, we account for evaporation from transpiration, soil in both vegetated and non-veg parts, and wet leaves. But we only account for the latent heat effects on Tg from transpiration and evaporation from non-veg soil.
This fix adds latent heat effects on Tg from soil in vegetated parts and from wet leaves.
3. Fix for rare case where GRDFLX goes NaN because of a divide by zero based on a soil parameter when a water cell turns to sea ice.

Solution:
Logic checks in module_physics_init.F and module_sf_pxlsm.F were adjusted for 61 category inputs. P-X LSM data table, module_sf_pxlsm_data.F was updated for MODIS 61 categories. Default for LCZ 51-61 was set to MODIS urban class. We also added updates for the evaporation from vegetation and wet canopy. 

ISSUE: 
Fixes: [#1965](https://github.com/wrf-model/WRF/issues/1965)

LIST OF MODIFIED FILES:
M phys/module_physics_init.F
M phys/module_sf_pxlsm.F
M phys/module_sf_pxlsm_data.F

TESTS CONDUCTED:

- Tested 61 class LCZ with PX LSM for a 1 day simulation with updated codes. Ran base MODIS 21 class scheme with same code before and after LCZ update. The results were identical after a 24 hour simulation. This confirms updates do not impact other MODIS settings in the P-X LSM. The MODIS 21 was by nature not identical to the MODIS 61, but similar enough and differences follow underlying differences in MODIS datasets.

Followed with another longer July 2018 test of the update surface evaporation in the P-X LSM.
image

- The Jenkins tests are all passing.

RELEASE NOTE:
Pleim-Xiu LSM is now compatible with 61 category MODIS LCZ landuse dataset. A mode of latent heat effects on Tg from vegetated parts and from wet leaves is added to Pleim-Xiu LSM.

### CODE REVIEW

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by coastwx** [comment]
Thanks Wei. Looks like it passed the testing.

With the reservations of adding RA and RS and sensitivity to other user's default output size, I just left the registry out of the pull request. Also thought about LANDUSEF more. Since our domains are static, this can be used from other inputs. MCIP that processes WRF for CMAQ has an option to use the geogrid file for these geographical data inputs. RA and RS are different obviously, but sensitive to other user's. We plan to update the P-X LSM run notes documentation with the other method of using text file to remove and add variables to the output. This is preferable anyhow because we can reduce the output size a lot.

**Comment by weiwangncar** [comment]
@coastwx That works with us. Thanks!

**Comment by coastwx** [comment]
This is great news. Now the packaged variables make more sense.

I’ll test and if appropriate I can do a simple pull request on that change.

Rob

**Review by dudhia — APPROVED** [review]
I will approve it. I mentioned it to @cenlinhe but I think it is OK.

**Review by weiwangncar — APPROVED** [review]

**Comment by coastwx** [comment]
Super. Thanks Wei and Jimy for the advice and consultation.

**Pull request merged**
