### PR TITLE
MYNN-EDMF Update from CCPP to WRF

### PR DESCRIPTION
**Pull request by joeolson42**
MYNN-EDMF Update from CCPP to WRF

TYPE: bug fix/enhancement/new feature

KEYWORDS: MYNN EDMF closure subgrid clouds CCPP universalization 

SOURCE: Joseph Olson (NOAA-GSL), Wayne Angevine (NOAA-CSL)

DESCRIPTION OF CHANGES:

- Vacate bl_pbl_physics = 6; will instead regulate the closure level with new namelist variable “bl_mynn_closure”; now has 3 options: level 2.5, 2.6, 3.0. This alone required changes in many files beyond the MYNN code.
- TKE budget fix; change bl_mynn_tkebudget to tke_budget (logical), so it’s a generic flag for other schemes to use
- Universalization of MYNN-EDMF for CCPP and WRF-ARW/MPAS
- Added a new WRF-specific wrapper called in module_pbl_driver.F
- Added a new WRF-specific module for defining constants
- Reordering of subroutines; bring driver to the top
- Improved conservation of heat/moisture
- Greatly improved global/medium-range performance
- Improved performance for hurricanes - but still not directly tuned for hurricanes
- New higher-order moment cloud PDF; improved SGS clouds
- New downdraft MF option for turbulence related to cloud-top cooling (still work in progress)
- Many misc tuning
- Many updated comments
- Bug fix for mixing in WRF_CHEM applications
- Merged in new qnbca additions since last update  - will probably need to modify again soon
- Lingering (but not required for this commit): 
    - Kind_physics (still different between WRF and CCPP)

LIST OF MODIFIED FILES:
M       Registry/Registry.EM_COMMON
M       Registry/registry.chem
M       dyn_em/module_big_step_utilities_em.F
M       dyn_em/module_first_rk_step_part1.F
M       dyn_em/solve_em.F
M       main/depend.common
M       phys/Makefile
M       phys/module_bl_fogdes.F
M       phys/module_bl_mynn.F
M       phys/module_pbl_driver.F
M       phys/module_physics_addtendc.F
M       phys/module_physics_init.F
M       phys/module_sf_fogdes.F
M       phys/module_shcu_camuwshcu.F
M       share/module_check_a_mundo.F
M       wrftladj/module_pbl_driver_ad.F
M       wrftladj/module_pbl_driver_tl.F
M       wrftladj/module_physics_addtendc_tl.F
M       wrftladj/solve_em_ad.F
M       wrftladj/solve_em_tl.F
M      chem/chemics_init.F
M      chem/dry_dep_driver.F
A       phys/module_bl_mynn_common.F
A       phys/module_bl_mynn_wrapper.F

TESTS CONDUCTED: 
1. Most of the rigorous scientific testing was done in the CCPP framework before merging into WRF
2. Several case studies in WRF were performed after merging with strict debugging
2. All regression tests have now passed.

RELEASE NOTE: overview of changes:
A substantial update to the MYNN-EDMF, including a reorganization of the subroutines, as part of the “universalization efforts” which are meant to keep the scheme similar in all dycores. The major physics changes include (1) improved conservation of scalars which improves performance in medium-range global forecasting, (2) revised subgrid clouds which leverages the prognostic q’2, (3) vacate bl_pbl_physics = 6 (now only run with bl_pbl_physics = 5); will instead regulate the closure level with new namelist variable “bl_mynn_closure” set to 2.5, 2.6, or 3.0, (4) important bug fixes for the TKE budget and the bl_mynn_tkebudget flag is not renamed to tke_budget for use in other schemes (although may not be hooked up for other schemes yet), (5) new downdraft option (hidden hard-coded flag in module_bl_mynn.F) but still under development to best fit within the MYNN-EDMF, (6) and many miscellaneous tuning/minor bug fixes. For its performance evaluation, please see the following: [Examples of MYNN improvements.pdf](https://github.com/wrf-model/WRF/files/10125487/Examples.of.MYNN.improvements.pdf)

### CODE REVIEW

**Comment by dudhia** [comment]
This one also looks like the tests are running slow. A problem we have seen sometimes.

**Comment by weiwangncar** [comment]
> This one also looks like the tests are running slow. A problem we have seen sometimes.

I have received test results for this PR, and there is some compilation issues. I'm talking to Joe. The problem is not that the test is running slow, the problem is that the Github page is not updated with test status.

**Comment by weiwangncar** [comment]
@joeolson42 The regression tests have passed:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by jordanschnell** [comment]
@rschwant @jianheACM

**Comment by weiwangncar** [comment]
The Jenkins test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by dudhia — APPROVED** [review]
Checked that the changes outside the scheme are related to this PR.

**Comment by weiwangncar** [comment]
@joeolson42 Can you add a few sentences for our RELEASE NOTE? We can provide the pdf file for reference too.

**Pull request merged**
