### PR TITLE
Bug fix for LAI initialization for urban pixel in Noah-MP

### PR DESCRIPTION
**Pull request by cenlinhe**
Bug fix for LAI initialization for urban pixel in Noah-MP.
(This PR needs to be merged after a previous Noah-MP bug fix PR: https://github.com/wrf-model/WRF/pull/1929)

TYPE: bug fix

KEYWORDS: LAI, urban, Noah-MP

SOURCE: Cenlin He (NCAR/RAL)

DESCRIPTION OF CHANGES:
Problem:
Before bug fix, Noah-MP (v4.5 and earlier versions) initializes leaf mass from the table parameter based on land type. However, this causes model crash if the LCZ capability is activated for urban pixel, because the LCZ land type index (51-61) is out of the MODIS or USGS land type number. This code is in module_sf_noahmpdrv.F file.

Solution:
Add an if-statement to assign default natural vegetation type for urban pixels with large land type index to represent rural portion of the urban pixel.

This is related to a reported Noah-MP issue (https://github.com/NCAR/noahmp/issues/104).

LIST OF MODIFIED FILES: list of changed files (use `git diff --name-status master` to get formatted list)
phys/noahmp/drivers/wrf/module_sf_noahmpdrv.F

TESTS CONDUCTED: 
1. The mods fix the problem
2. It passed the regression tests.

RELEASE NOTE: This PR fixed a bug in Noah-MP for uninitialized leaf mass when LCZ is used.

### CODE REVIEW

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by dudhia — APPROVED** [review]
changes just in NoahMP.

**Comment by weiwangncar** [comment]
@cenlinhe I added RELEASE NOTE in your PR. Can you check? Thanks.

**Comment by cenlinhe** [comment]
> @cenlinhe I added RELEASE NOTE in your PR. Can you check? Thanks.

Looks good. Thanks!

**Review by weiwangncar — APPROVED** [review]

**Comment by weiwangncar** [comment]
@cenlinhe This PR shows conflicts with files in phys/noahmp/. Can you check?

**Comment by cenlinhe** [comment]
> This PR needs to be merged after a previous Noah-MP bug fix PR: #1929

This PR needs to be merged after a previous Noah-MP bug fix PR: https://github.com/wrf-model/WRF/pull/1929

**Comment by cenlinhe** [comment]
> @cenlinhe This PR shows conflicts with files in phys/noahmp/. Can you check?

This PR needs to be merged after a previous Noah-MP bug fix PR: https://github.com/wrf-model/WRF/pull/1929

**Comment by weiwangncar** [comment]
> > @cenlinhe This PR shows conflicts with files in phys/noahmp/. Can you check?
> 
> This PR needs to be merged after a previous Noah-MP bug fix PR: #1929

@cenlinhe PR-1929 has been merged. Can you take a look at the conflict?

**Comment by cenlinhe** [comment]
> > > @cenlinhe This PR shows conflicts with files in phys/noahmp/. Can you check?
> > 
> > 
> > This PR needs to be merged after a previous Noah-MP bug fix PR: #1929
> 
> @cenlinhe PR-1929 has been merged. Can you take a look at the conflict?

I will look at this conflict issue today.

**Comment by cenlinhe** [comment]
@weiwangncar I double checked and did not see any conflicting issues for phys/noahmp. 
The current WRF develop branch is connected to noahmp commit 4ecebec7072e507ed7607012e5a89379348391bf
This PR update is connected to noahmp commit 6f2bf7c575a0099d60b51efe8811c6519d531abe, this is one updated commit right after the above 4ecebec commit in Noah-MP GitHub repo: https://github.com/NCAR/noahmp/commits/release-v4.5-WRF/

**Comment by cenlinhe** [comment]
@weiwangncar Are you able to see what specific part in phys/noahmp shows the conflicts? I cannot see it from my end.

**Comment by cenlinhe** [comment]
OK, I am not sure what is going on. But I am going to resubmit a PR with latest develop and this Noah-MP update to see if it works.

**Comment by weiwangncar** [comment]
This PR has been replaced by PR-[1990](https://github.com/wrf-model/WRF/pull/1990).

**Pull request closed without merging**
