### PR TITLE
Bug fix for chem_opt=100 (vbs_het), racm_soa_vbs_het_kpp initialization

### PR DESCRIPTION
**Pull request by SeregaOsipov**
TYPE:bug fix

KEYWORDS: racm_soa_vbs_het_kpp, aerosols

SOURCE: Sergey Osipov (KAUST)

DESCRIPTION OF CHANGES:
Problem:
The bug was introduced after splitting chem_opt 100 and 106. Currently, the chemistry initialization always calls for module_aerosol_soa_vbs routine, leaving the module_aerosol_soa_vbs_HET and corresponding data constants unitialized. As a result, aerosol concentrations are set to 0 after the first time integration (10**-16).

To verify the bug fix, initialize WRF-Chem with non-trivial IC and save the next time step into nc. Check that values are non-trivial (e.g., so4aj, soila).

Solution:
Differentiate between module_aerosol_soa_vbs and module_aerosol_soa_vbs_het initialization routines

LIST OF MODIFIED FILES:
M    Registry/registry.chem
M    chem/chemics_init.F
M    chem/module_aerosols_soa_vbs_het.F

TESTS CONDUCTED: 
- The Jenkins tests are all passing.

RELEASE NOTE: Include a stand-alone message suitable for the inclusion in the minor and annual releases. A publication citation is appropriate.

### CODE REVIEW

**Review by jordanschnell — DISMISSED** [review]
Approved - waiting on reg test

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@jordanschnell This one requires approval again because of the base branch change.

**Review by jordanschnell — APPROVED** [review]
approved (rebase)

**Review by jordanschnell — APPROVED** [review]
approve (conflict)

**Pull request merged**
