### PR TITLE
Fix urban diagnostic

### PR DESCRIPTION
**Pull request by dudhia**
TYPE: bug fix

KEYWORDS: lh_urb2d diagnostic for urban models

SOURCE: internal (reported by Xin-Zhong Liang)

DESCRIPTION OF CHANGES:
Problem:
lh_urb2d was inconsistent with other urban budget arrays sh_urb2d, g_urb2d, and rn_urb2d by being the only one 
multiplied by the urban fraction making it a grid cell average instead of urban area average. This is only a diagnostic 
for output.

Solution:
Divide lh_urb2d by frc_urb2d
Won't affect model run results apart from this diagnostic. These arrays are not in default history output.

LIST OF MODIFIED FILES: 
phys/module_sf_noahmpdrv.F

TESTS CONDUCTED: 
1. Jenkins is all pass?

RELEASE NOTE: 
Fix lh_urb2d diagnostic to be urban area average instead of grid cell average consistent with other urb2d diagnostics. No effect on run results.

### CODE REVIEW

**Comment by davegill** [comment]
@dudhia @weiwangncar 
Jimy looks fine to me.
However, the history of the PR has changes dating back almost a year. Could you close this one, start with a clean 422 branch and add in the single line mod again? You can cut and paste from this PR for the message.

**Comment by dudhia** [comment]
Those were just mistaken commits to my master that I have locally and
reverted.
I guess they show up even when I make a branch from it. I was hoping I
could
just have one local version as a record of my changes.

**Comment by dudhia** [comment]
Tried something else but it made it worse. Will start from a clean fork. Ignore for now.

**Comment by davegill** [comment]
@dudhia 
> Tried something else but it made it worse.

Jimy,
ALWAYS this is what happens with github!

**Comment by dudhia** [comment]
cleaner PR coming from urban-fix2

**Pull request closed without merging**
