### PR TITLE
Halo comms bugs (h_mom_adv_order vs. h_sca_adv_order)

### PR DESCRIPTION
**Pull request by MicroTed**
TYPE:  bug fix

KEYWORDS: HALO, h_mom_adv_order

SOURCE: Ted Mansell

DESCRIPTION OF CHANGES:  Halo exchange had inconsistent use of h_mom_adv_order when it should have h_sca_adv_order, and in a couple cases should check both. Consequently the MPI results would not match (for different number of patches) if h_mom_adv_order=3 and h_sca_adv_order=5. These changes fix that result, but should be checked by the experts.

LIST OF MODIFIED FILES: 
dyn_em/module_first_rk_step_part1.F
dyn_em/module_first_rk_step_part2.F
dyn_em/solve_em.F

TESTS CONDUCTED: 
Tested ideal case (em_quarter_ss) with 
h_mom_adv_order=3
h_sca_adv_order=5
On 4 vs. 1 MPI process. Without changes, diffwrf found differences. After changes the wrfout files match exactly. (Also tested for h_mom_adv_order=5, h_sca_adv_order=3)

### CODE REVIEW

**Comment by MicroTed** [comment]
I also have a question here about the halo entries in the Registry that have more than one type (i.e., momentum and scalar). For example:

halo      HALO_EM_D2_3 dyn_em 24:u_2,v_2,w_2,t_2,ph_2;24:moist,chem,tracer,scalar,tke_2;4:mu_2,al
halo      HALO_EM_D2_5 dyn_em 48:u_2,v_2,w_2,t_2,ph_2;24:moist,chem,tracer,scalar,tke_2;4:mu_2,al

Here, the first number (24, 48, 80, for 3-4th, 5-6th, 7-8th order) would appear to apply only to u,v,w, etc., whereas the second number is 24 in all three for moist,chem, etc. The include files appear to apply the first order number to everything, however, if I'm interpreting the rsl calls correctly. So does the '24' in '24:moist' actually have any effect?

Part of the reason for asking this is that I'm also working on adding the infrastructure for 7th and 9th order advection, and will want to be able to have h_mom_adv_order .ne. h_sca_adv_order

-- Ted Mansell

**Comment by weiwangncar** [comment]
@davegill It seems we should review this. What was the reason it was left out of 4.1.4?

**Comment by davegill** [comment]
@weiwangncar 
> It seems we should review this. What was the reason it was left out of 4.1.4?

I never tested it thoroughly.

**Comment by MicroTed** [comment]
@weiwangncar  @davegill 

Most users would never have a problem, since they probably almost all use 5th-order horizontal stencils for both momentum and scalars. Could either of you tell me about the registry entries that I asked about in my first comment? I have a branch that adds 7th and 9th-order advection options (still under testing) that I'm not sure I have the entries correct. Perhaps that should be a separate conversation (email?).

**Comment by weiwangncar** [comment]
@MicroTed We are currently making a branch from the develop for 4.2 release. We will test your bug fix and hopefully to include it in 4.2. So your fix is not only for WRF-Chem, but for other scalar advection options too, right?
Yes, we should discuss the other question in a separate email. Thanks.

**Comment by MicroTed** [comment]
@weiwangncar 
Correct, it is for moist and scalar (and probably tke), not just chem.

**Comment by davegill** [comment]
When I tried this PR with the jenkins automated regression testing, the following failures resulted:
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: 0b39c65cf66eef873475b79b9479901e71661005, requested by: MicroTed for PR: https://github.com/wrf-model/WRF/pull/998. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           18
    Number of Builds       : 48           46
    Number of Simulations  : 166           164         28
    Number of Comparisons  : 105           87         0

    Failed Simulations are: 
    output_1:9 = STATUS test_001s em em_real 32 3dtke
output_1:9 = STATUS test_001s em em_real 32 rap
output_1:9 = STATUS test_001o em em_real 33 3dtke
output_1:9 = STATUS test_001o em em_real 33 rap
output_1:9 = STATUS test_001m em em_real 34 3dtke
output_1:9 = STATUS test_001m em em_real 34 rap
output_14:9 = STATUS test_014s em em_real 32 50
output_14:9 = STATUS test_014s em em_real 32 51
output_14:9 = STATUS test_014o em em_real 33 50
output_14:9 = STATUS test_014o em em_real 33 51
output_14:9 = STATUS test_014m em em_real 34 50
output_14:9 = STATUS test_014m em em_real 34 51
output_15:9 = STATUS test_015s em em_real 32 60
output_15:9 = STATUS test_015s em em_real 32 60NE
output_15:9 = STATUS test_015o em em_real 33 60
output_15:9 = STATUS test_015o em em_real 33 60NE
output_15:9 = STATUS test_015m em em_real 34 60
output_15:9 = STATUS test_015m em em_real 34 60NE
output_17:9 = STATUS test_017s em em_real 32 kiaps1NE
output_17:9 = STATUS test_017s em em_real 32 kiaps2
output_17:9 = STATUS test_017o em em_real 33 kiaps1NE
output_17:9 = STATUS test_017o em em_real 33 kiaps2
output_17:9 = STATUS test_017m em em_real 34 kiaps1NE
output_17:9 = STATUS test_017m em em_real 34 kiaps2
output_18:9 = STATUS test_018s em em_real 32 urb3bNE
output_18:9 = STATUS test_018m em em_real 34 urb3bNE
output_2:2 = STATUS test_002m hwrf nmm_real 34 1NE
output_2:2 = STATUS test_002m hwrf nmm_real 34 2NE
```

The following tests were conducted on the merged ARW code:
```
[wrfuser@7985763f0703 ~]$ foreach t ( 3dtke rap 50 51 60 60NE kiaps1NE kiaps2 urb3bNE )
foreach? echo test $t
foreach? rm WRF/test/em_real/wrf.print.out ; ./script.csh RUN em_real 32 em_real $t ; ls -ls /wrf/wrfoutput | grep $t
foreach? echo
foreach? end
```
The results of the previously failing ARW tests are now passing.
```
test 3dtke
0 -rw-r--r-- 1 wrfuser wrf  0 Oct 19 03:21 SUCCESS_RUN_REAL_em_real_32_em_real_3dtke
4 -rw-r--r-- 1 wrfuser wrf 72 Oct 19 03:22 SUCCESS_RUN_WRF_d01_em_real_32_em_real_3dtke

test rap
0 -rw-r--r-- 1 wrfuser wrf  0 Oct 19 03:22 SUCCESS_RUN_REAL_em_real_32_em_real_rap
4 -rw-r--r-- 1 wrfuser wrf 72 Oct 19 03:23 SUCCESS_RUN_WRF_d01_em_real_32_em_real_rap

test 50
0 -rw-r--r-- 1 wrfuser wrf  0 Oct 19 03:23 SUCCESS_RUN_REAL_em_real_32_em_real_50
4 -rw-r--r-- 1 wrfuser wrf 72 Oct 19 03:25 SUCCESS_RUN_WRF_d01_em_real_32_em_real_50

test 51
0 -rw-r--r-- 1 wrfuser wrf  0 Oct 19 03:25 SUCCESS_RUN_REAL_em_real_32_em_real_51
4 -rw-r--r-- 1 wrfuser wrf 72 Oct 19 03:26 SUCCESS_RUN_WRF_d01_em_real_32_em_real_51

test 60
0 -rw-r--r-- 1 wrfuser wrf  0 Oct 19 03:26 SUCCESS_RUN_REAL_em_real_32_em_real_60
4 -rw-r--r-- 1 wrfuser wrf 72 Oct 19 03:27 SUCCESS_RUN_WRF_d01_em_real_32_em_real_60

test 60NE
0 -rw-r--r-- 1 wrfuser wrf  0 Oct 19 03:28 SUCCESS_RUN_REAL_em_real_32_em_real_60NE
4 -rw-r--r-- 1 wrfuser wrf 72 Oct 19 03:29 SUCCESS_RUN_WRF_d01_em_real_32_em_real_60NE

test kiaps1NE
0 -rw-r--r-- 1 wrfuser wrf  0 Oct 19 03:29 SUCCESS_RUN_REAL_em_real_32_em_real_kiaps1NE
4 -rw-r--r-- 1 wrfuser wrf 72 Oct 19 03:30 SUCCESS_RUN_WRF_d01_em_real_32_em_real_kiaps1NE

test kiaps2
0 -rw-r--r-- 1 wrfuser wrf  0 Oct 19 03:30 SUCCESS_RUN_REAL_em_real_32_em_real_kiaps2
4 -rw-r--r-- 1 wrfuser wrf 72 Oct 19 03:31 SUCCESS_RUN_WRF_d01_em_real_32_em_real_kiaps2

test urb3bNE
0 -rw-r--r-- 1 wrfuser wrf  0 Oct 19 03:31 SUCCESS_RUN_REAL_em_real_32_em_real_urb3bNE
4 -rw-r--r-- 1 wrfuser wrf 72 Oct 19 03:33 SUCCESS_RUN_WRF_d01_em_real_32_em_real_urb3bNE
```

The NMM tests that failed have nothing to do with these mods, as the changes are ONLY in the ARW code:
LIST OF MODIFIED FILES:
dyn_em/module_first_rk_step_part1.F
dyn_em/module_first_rk_step_part2.F
dyn_em/solve_em.F

**Comment by MicroTed** [comment]
I had almost forgotten about this. So does "The NMM tests that failed have nothing to do with these mods, as the changes are ONLY in the ARW code" mean that the NMM problem is from something else?

**Comment by davegill** [comment]
@MicroTed 
Ted,
These are just notes to myself. I am surprised with the NMM fails. I might need to do a bit more testing, perhaps a clean merge. Anyways, I am taking a look now.

**Comment by MicroTed** [comment]
@davegill 
Ok! I could transfer these into the current release, if that would help. I don't think it would take much time.

**Comment by davegill** [comment]
@MicroTed 
Ted,
That would be fantastic! Putting these mods into the top if the repo is _exactly_ what I was planning to do.
1. Use the release-v4.2.2 as the base branch
2. Re-insert these mods into the v4.2.2 branch manually (don't try to do any fancy merging, cherry picking)
3. Make a brand new PR with the mods that are now in the v4.2.2 branch
4. Steal the pull request commit message from this PR
5. Close this PR 
6. Post the results of the jenkins testing in the comments section

**Comment by MicroTed** [comment]
I have the changes into 4.2.2:

https://github.com/MicroTed/WRFV4.git/release-v4.2.2-halo

I'll do the new PR.

**Comment by davegill** [comment]
Cleaner PR made for v4.2.2

**Pull request closed without merging**
