### PR TITLE
Clean up lightning option in chem registry

### LINKED ISSUE #1021: lightning broken in WRF Chem after v4.0
In the Registry.EM_COMMON, the lightning method option (ICCG_METHOD) was put into the source in the physics directory almost 7 years ago by Jimy:
```
c83d404d9 Registry/Registry.EM_COMMON (Jimy Dudhia      2013-01-25 23:38:03 +0000 2904) rconfig  integer    iccg_method              namelist,physics   max_domains    0       -   "iccg_method"               "IC:CG partitioning method" 
```

In registry.chem, the lightning method option (ICCG_METHOD) was put into the source in the chem directory 10 years ago by Steve Peckham:
```
b3ef563ff (Steven Peckham 2009-11-20 23:24:26 +0000 3767) rconfig   integer     iccg_method         namelist,chem        max_domains        1       rh      "iccg_method"        ""    ""
```

So, this has ALWAYS been wrong (we should not have two locations for the namelist definition of the variables). What has changed is that Registry.EM and Registry.EM_CHEM were modified to use a new file: registry.em_shared_collection. This new file reorganized the order of the registry files that were included into what becomes the master registry from which WRF is built.

What we need to do is decide which way we want to support this option. I would vote for Registry.EM_COMMON and the physics namelist, if we would likely run into build troubles without the use of WRF Chem. However, if iccg_method is ENTIRELY and ONLY EVER run when chemistry is active, then I vote for keeping this option declaration only in registry.chem in the chem namelist record. 

It looks like there are additional namelist options associated with ICCG_METHOD (ICCG_PRESCRIBED_NUM and ICCG_PRESCRIBED_DEN) and a couple of 2d arrays associated with ICCG_METHOD (ICCG_IN_NUM and ICCG_IN_DEN). Since these other ICCG* variables are ONLY in the Registry.EM_COMMON, that should be part of our calculus.

Per Mary Barth:
>In my opinion, the namelist variables associated with calculating lightning flashes (iccg_method, lightning_start_seconds, etc, etc) should be in the &physics section.

>There are some papers that do just use WRF and run lightning diagnostics to analyze storm parameter - lightning correlations. And there are other papers that use the lightning diagnostics to get lightning-NOx in the chemistry. However, since there is a lot of tuning with this latter effort, it is common for the modeler to set chem_opt=0 and tune the lightning predictions to something close to observations. So, even before calculating the NOx emissions, there are several runs with just testing the lightning.

>I also think the namelist variables associated with calculating lightning flashes should be in only one place, ensuring consistency no matter how WRF or WRF-Chem is run.

### PR DESCRIPTION
**Pull request by zxdawn**
TYPE: bug fix

KEYWORDS: ltng, lightning, registry.chem

SOURCE: Xin Zhang (NUIST)

DESCRIPTION OF CHANGES:
1.  Output of the time step ratio, instead of a numerator, denominator.
2. Remove unnecessary lightning options `registry.chem`

ISSUE:
Fixes #1021 "lightning broken in WRF Chem after v4.0"
The "fix" is mostly indicating how to use the lightning option via the namelist settings 
contained in this PR.

LIST OF MODIFIED FILES:
M       Registry/registry.chem
M       phys/module_lightning_driver.F
M       run/README.namelist
M       test/em_real/examples.namelist

TESTS CONDUCTED:
1. Running wrf.exe with these options in &physics:
```
 iccg_method                         = 1,
 iccg_prescribed_num                 = 3,
 iccg_prescribed_den                 = 1,
```

Output after corrected:
```
d01 2019-07-25_00:11:25  lightning_driver: partitioning IC:CG
d01 2019-07-25_00:11:25   lightning_driver: using user-prescribed IC:CG ratio =    3.000000
```

2. Running real.exe with iccg_method is in &physics
Error:
```
 module_io_quilt_old.F        2931 T
  ------ ERROR while reading namelist physics ------
Maybe here?:      lightning_option                    = 12,
Maybe here?:      iccg_method                         = 1,
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:   11783
ERRORS while reading one or more namelists from namelist.input.
-------------------------------------------
```

Output after corrected:
```
d01 2019-07-25_00:11:25 --> CALL DIAGNOSTICS PACKAGE: LIGHTNING_DRIVER
d01 2019-07-25_00:11:25  lightning_driver: determining cloud extents for CRM
d01 2019-07-25_00:11:25   lightning_driver: Max cell count =   0.0000000E+00
d01 2019-07-25_00:11:25  lightning_driver: calculating flash rate
d01 2019-07-25_00:11:25  lightning_driver: calling Price and Rind 1992 (w_max, CRM)
d01 2019-07-25_00:11:25  lightning_driver: partitioning IC:CG
d01 2019-07-25_00:11:25   lightning_driver: using user-prescribed IC:CG ratio =    3.000000
d01 2019-07-25_00:11:25  lightning_driver: converting flash rates to flash counts
d01 2019-07-25_00:11:25  lightning_driver: returning from
```

Namelist setting:
```
&physics
 ...
 lightning_option                    = 1,
 iccg_method                         = 1,
 iccg_prescribed_num                 = 3,
 iccg_prescribed_den                 = 1,
 cldtop_adjustment                   = 0,
 lightning_dt                        = 5,
 lightning_start_seconds             = 600,
 flashrate_factor                    = 1.0,
/

&chem
 ...
 lnox_opt                           = 1,
 n_ic                               = 200,
 n_cg                               = 200,
/
```

### CODE REVIEW

**Comment by davegill** [comment]
@zxdawn 
Xin,
You provide good namelist suggestions. Please incorporate these settings into both test/em_real/examples.namelist and also run/README.namelist. Update the PR message to include the two newly modified files.

**Comment by zxdawn** [comment]
@davegill Thanks, I will update these files tomorrow :)

**Comment by zxdawn** [comment]
@davegill I add the specific `iccg_method` and `lnox_opt` options in `test/em_real/examples.namelist ` to show all possible lighting choices.

**Comment by davegill** [comment]
@kayeekayee @jordanschnell @weiwangncar @dudhia 
Folks,
This seems OK to me. This modifies physics and chemistry, so each should chime in.

**Comment by davegill** [comment]
@kayeekayee @jordanschnell @weiwangncar @dudhia
Folks,
We need a review. This looks to be a very simple modification. Most of the important work is actually in the nicely documented namelist information files.

**Comment by davegill** [comment]
@zxdawn 
Xin,
Please add the following to the commit message:
```
SOURCE: Xin Zhang (affiliation)
```

**Pull request merged**
