### PR TITLE
Bug fix: Update urban LCZ number in parameter tables

### PR DESCRIPTION
**Pull request by cenlinhe**
Update urban LCZ numbers in parameter tables to avoid overlapping with existing NLCD land types.

TYPE: bug fix

KEYWORDS: urban, LCZ, parameter table

SOURCE: Cenlin He (NCAR)

This addressed the issue #1782.

DESCRIPTION OF CHANGES:
Problem:
The original urban local climate zone (LCZ) numbers are 31-41 which overlap with NLCD land categories of 31~40 causing errors.

Solution:
Update urban LCZ numbers to 51-61 in parameter tables to avoid potential overlapping with any existing land type data. The future global LCZ map to be implemented into WRF/WPS system will also be consistent with this update (i.e., LCZ of 51-61).

LIST OF MODIFIED FILES: list of changed files:
run/VEGPARM.TBL
run/LANDUSE.TBL
run/MPTABLE.TBL

TESTS CONDUCTED: 
1. The mods fix the problem.
2. The regression tests have passed.

RELEASE NOTE: Bug fix by updating urban LCZ numbers in parameter tables to avoid overlapping with existing NLCD land types. Starting from this version (v4.4.2), the LCZ numbers in WRF-urban has been changed from 31-41 to 51-61.

### CODE REVIEW

**Comment by weiwangncar** [comment]
The Jenkins tests have passed:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@cenlinhe Does this PR fully address Issue #1782? If so, can you please add that in the PR message?

**Comment by cenlinhe** [comment]
Yes, it fully addressed the issue #1782. I have added this in the PR message above

**Comment by weiwangncar** [comment]
@cenlinhe So this update doesn't require any change in the LSMs themselves?

**Comment by cenlinhe** [comment]
No, it does not require any code changes in LSMs. It only needs to change the table value and then the users need to also use the updated LCZ number when they generating geo_em file through WPS. The upcoming global 100-m LCZ map has already taken care of this LCZ number update, so once it is implemented, things should be all fine.

**Comment by dudhia** [comment]
This test is running slow @weiwangncar ?

**Review by weiwangncar — APPROVED** [review]

**Comment by weiwangncar** [comment]
@dudhia I have received the test results, and they all passed (as shown above). But somehow this page isn't updated. I've contacted Scala but I'm not sure the issue is resolved. The same happened to the PR the DA group has merged. I'm not sure how that is possible. You can approve it if you think the PR is ok, and we can see if we can merge it.

**Review by dudhia — APPROVED** [review]
If WPS needs to be run again for v4.4.2 that should be added to the release note.

**Comment by weiwangncar** [comment]
@dudhia It looks like after two approvals it allows me to merge.

**Comment by vyesubabu** [comment]
There is an linking issue (URBPARM_LCZ.TBL) with wrf version 4.4.2 and enabling use_wudapt_lcz =1, The WRF code (wrf.exe) stops with displaying an error (in rsl.out.0000; please see the attached rsl.out.0000).  The same combination of namelist and wrf inputs are working fine with WRF 4.4 and 4.4.1 versions.     
-----------------------------------------------------------------------------------------------------------------------------
USING URBPARM_LCZ.TBL WITH OLD 3 URBAN CLASSES. SET USE_WUDAPT_LCZ=0 
[rsl.out.0000.txt](https://github.com/wrf-model/WRF/files/10939691/rsl.out.0000.txt)
[namelist.input.txt](https://github.com/wrf-model/WRF/files/10939692/namelist.input.txt)

**Comment by weiwangncar** [comment]
@vyesubabu Do you see a URBPARM_LCZ.TBL file in your running directory? The file is located in WRF/run/, and linked to test/em_real/ after compilation. If you are not running in either of the directories, you need to copy the file to your working directory. If you have further issue, please post the problem in the Forum: https://forum.mmm.ucar.edu/.

**Comment by vyesubabu** [comment]
Thank you Weiwang for the quick response,

Yes, URBPARM_LCZ.TBL file is there in my wrf running directory. I am
running the WRF.exe in WRF/run and I am getting this error only with the
most recent version (4.4.2). The same namelist configuration and inputs are
running successfully with the previous versions of WRF (4.4 and 4.4.1).

I have copied my inputs in the dropbox link, if possible verify the same. I
feel the update WRF version 4.4.2 has some issue in use_wudapt_lcz =1,
https://www.dropbox.com/s/1xu7l2a9eg77dmr/wrf-inputs.tar.gz?dl=0

Best regards,
Dr. Yesubabu Viswanadhapalli,
Scientist, Weather & Climate Research Group,
National Atmospheric Research Laboratory (NARL)
Gadanki- 517 112, Andhra Pradesh, India

**Comment by cenlinhe** [comment]
The LCZ numbering has been changed from 31-41 to 51-61 starting from version 4.4.2 to avoid overlapping with 40-category NLCD land cover dataset numbering. In your input data, you need to update your urban pixel LCZ numbering.

**Comment by cenlinhe** [comment]
@vyesubabu If you do not want to modify your input data file, you can also change the LCZ numbering in your own WRF parameter table (if you use Noah LSM, change run/VEGPARM.TBL and run/LANDUSE.TBL; if you use NoahMP LSM, change run/MPTABLE.TBL) to make it work. Basically, you just reverse the change in this pull request.

**Comment by vyesubabu** [comment]
@ cenlinhe  : Yes I don't want to change my input and I am not aware of "how to reverse the change in this pull request"
But I just copied the TBL files (VEGPARM.TBL and LANDUSE.TBL) from WRF4.4.1/run and copied at WRF4.4.2/run. 
The WRF (4.4.2) code is working fine and successfully generated all wrfout files.

**Pull request merged**
