### PR TITLE
Wudapt greenroof pvp

### PR DESCRIPTION
**Pull request by andreazonato**
This update includes urban new capabilities for solar panel, green roof, and local climate zone (LCZ). Moreover, we added a new building drag coefficient for wind and TKE, the permeability of building materials (latent heat flux released depending on rainrate), and the separation between direct and diffuse radiation within urban canyons. All modifications took place in module_sf_bep_bem.F

TYPE: new feature

KEYWORDS: urban, green roof, solar panel, local climate zone, new building drag coefficient

SOURCE: Developer: Andrea Zonato (University of Trento, Italy, andrea.zonato@unitn.it)

DESCRIPTION OF CHANGES:
This update includes new capabilities to account for urban solar panel, green roof, new building drag coefficient, and local climate zone (LCZ). The first three new capabilities are for BEP+BEM. The new building drag coefficient is based on Santiago and Martilli (2010) and Guti ́errez et al. (2015). The newly added LCZs are all related to urban and all urban updates are still controlled by sf_urban_physics options. More details will be available in the User's Guide. Briefly, a new urban parameter table (URBPARAM_LCZ.TBL) has been added for using the new LCZ urban category. The new LCZ definition has LU_INDEX=LCZ+30. If a user still wants to keep using the traditional 33 classes (31st-33rd for urban), please specify the namelist option "use_wudapt_lcz = 0". If a user wants to use the new LCZ, please specify the namelist option "use_wudapt_lcz = 1". If the number of urban category in the input files is inconsistent with the namelist option, error messages will occur. Only the LCZ modeling capability is provided here, not the dataset which is the responsibility of users. The method to create the LCZ data is described in the World Urban Database website: http://www.wudapt.org/

LIST OF MODIFIED FILES: list of changed files (use git diff --name-status master to get formatted list)
M Registry/Registry.EM_COMMON
M Registry/Registry.NMM
M Registry/registry.dimspec
M dyn_em/module_first_rk_step_part1.F
M dyn_em/module_initialize_real.F
M dyn_em/start_em.F
M dyn_nmm/module_PHYSICS_CALLS.F
M dyn_nmm/start_domain_nmm.F
M phys/module_physics_init.F
M phys/module_sf_bem.F
M phys/module_sf_bep.F
M phys/module_sf_bep_bem.F
M phys/module_sf_clm.F
M phys/module_sf_noahdrv.F
M phys/module_sf_noahlsm.F
M phys/module_sf_noahmpdrv.F
M phys/module_sf_noahmplsm.F
M phys/module_sf_urban.F
M phys/module_surface_driver.F
M run/LANDUSE.TBL
M run/MPTABLE.TBL
M run/URBPARM.TBL
A run/URBPARM_LCZ.TBL
M run/VEGPARM.TBL
M share/module_check_a_mundo.F

TESTS CONDUCTED:

The model compilation has been tested successfully (tested in Cheyenne by both the developer and Cenlin He, NCAR)
The model simulation has been tested successfully (tested in Cheyenne by the developer)
The model simulation has been tested successfully (tested in WRF Docker by Cenlin He, NCAR)
RELEASE NOTE: WRF-urban updates for green roof, solar panel, and new building drag coefficient for BEP+BEM, and local climate zone for all urban schemes. The paper describing the roof and LCZ update is under development. The new building drag coefficient is based on Santiago and Martilli (2010) and Guti ́errez et al. (2015).
Santiago, J. L. and Martilli, A. (2010). A Dynamic Urban Canopy Parameterization for Mesoscale Models Based on Computational Fluid Dynamics Reynolds-Averaged Navier-Stokes Microscale Simulations. Boundary- Layer Meteorology, 137(3):417–439.
Guti ́errez, E., Martilli, A., Santiago, J. L., and Gonz ́alez, J. E. (2015). A Mechanical Drag Coefficient Formu- lation and Urban Canopy Parameter Assimilation Technique for Complex Urban Environments. Boundary- Layer Meteorology, 157(2):333–341.
The PVP/Greenroof module paper will be submitted soon

### CODE REVIEW

**Comment by dudhia** [comment]
There are issues here with all the .mod and .f90 files in the A list.
Need to make sure these are not in your fork as committed files.

**Comment by davegill** [comment]
@andreazonato @dudhia @weiwangncar 

1. There are 145 files that are changed. That seems like too many. Here is a suggested workflow. This will generate a new pull request (PR). You may use the PR commit message on this page on the second PR. After you are happy with the second PR, then you may close this PR.

git clone https://github.com/wrf-model/WRF WRF_greenroof
cd WRF_greenroof
git checkout develop
git checkout -b greenroof_mods
_EDIT THE FILES YOU NEED TO CHANGE - DO NOT JUST COPY FILES INTO THE REPO_
git remote add andrea https://github.com/universita-di-trento/WRF
git add _THE_LONG_LIST_OF_ALL_OF_THE_CHANGED_FILES_FOR_GREENROOF_
git commit
git push -u andrea greenroof_mods

2. It looks like there are some failures with the testing:
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: 3a616de146f0c7d839514bfbbbacfcfc17bfce76, requested by: andreazonato for PR: https://github.com/wrf-model/WRF/pull/1382. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           18
    Number of Builds       : 48           46
    Number of Simulations  : 163           161         11
    Number of Comparisons  : 103           97         0

    Failed Simulations are: 
    output_11:9 = STATUS test_011s em em_real 32 07NE
output_11:9 = STATUS test_011o em em_real 33 07NE
output_11:9 = STATUS test_011m em em_real 34 07NE
output_17:9 = STATUS test_017s em em_real 32 kiaps2
output_17:9 = STATUS test_017o em em_real 33 kiaps2
output_17:9 = STATUS test_017m em em_real 34 kiaps2
output_18:9 = STATUS test_018s em em_real 32 urb3bNE
output_18:9 = STATUS test_018m em em_real 34 urb3bNE
output_2:2 = STATUS test_002m hwrf nmm_real 34 1NE
output_2:2 = STATUS test_002m hwrf nmm_real 34 2NE
output_2:2 = STATUS test_002m hwrf nmm_real 34 3NE
    Which comparisons are not bit-for-bit: 
    None
```
All of the NMM jobs are failing to compile. A few of the ARW jobs are failing to run. They all have an urban option turned on. Here is a README with some info on how to run the NMM and broken cases: https://github.com/davegill/wrf-coop/blob/master/README_user.md

There is a github repo with the Namelist settings: https://github.com/davegill/SCRIPTS (and go into Namelists/weekly/em_real/MPI for 07NE, kiaps2, and urb3bNE; and Namelists/weekly/nmm_hwrf for tests 1NE, 2NE, and 3NE).

**Comment by davegill** [comment]
@andreazonato 
Even though you state that your most recent changes fix the NMM, there is a need to re submit a new pull request. There are now nearly 400 files changed!

Screen Shot 2021-01-25 at 8 15 53 AM

As stated above, follow these instructions:

git clone https://github.com/wrf-model/WRF WRF_greenroof
cd WRF_greenroof
git checkout develop
git checkout -b greenroof_mods
_EDIT THE FILES YOU NEED TO CHANGE - DO NOT JUST COPY FILES INTO YOUR REPO_
git diff
_WHICH ALLOWS YOU TO VERIFY THAT ONLY YOUR MODIFICATIONS HAVE BEEN ADDED_
git remote add andrea https://github.com/universita-di-trento/WRF
git add _THE_LONG_LIST_OF_ALL_OF_THE_CHANGED_FILES_FOR_GREENROOF_
git commit
git push -u andrea greenroof_mods
_THEN GET ONTO GITHUB TO COMPLETE THE PR PROCESS_

Once you are happy with the new PR (for example, use the PR commit message from the top of this PR), you may close this PR.

**Comment by andreazonato** [comment]
I trided to do il, but I couldnt. How can I remove the *f90, *mod and *o
files?

Andrea

Il giorno lun 25 gen 2021 alle ore 16:22 Dave Gill <notifications@github.com>
ha scritto:

**Comment by dudhia** [comment]
You have to use git to remove them from your fork, probably.

**Comment by davegill** [comment]
@andreazonato 

Start from a new clone! This PR is too broken for you to easily fix.

When you get to this line of your process in your new PR
```
git add _THE_LONG_LIST_OF_ALL_OF_THE_CHANGED_FILES_FOR_GREENROOF_
```
specifically add in the files that you edited (for example, *F, the *.TBL files, the Registy files, the Makefiles, etc). Do not type `git add -a`. Only include the files that you specifically edited.

**Comment by andreazonato** [comment]
Dear all,
I submitted a new pull request starting from a new clone

Il giorno lun 25 gen 2021 alle ore 19:08 Dave Gill <notifications@github.com>
ha scritto:

**Comment by davegill** [comment]
@andreazonato 
Andrea,
If you are happy with PR #1385, you can close this PR. At the bottom of each comment block is a "Close with comment" button. Just be in this #1382 PR, and you can close this older version.

**Pull request closed without merging**
