### PR TITLE
Bugfix: Correct code in module_bl_mynn.F .

### PR DESCRIPTION
**Pull request by Nuanyang00**
Correct code in module_bl_mynn.F .

TYPE: bug fix

KEYWORDS: MYNN, EDMF

SOURCE:  Yahua Wang,  NUDT-China

DESCRIPTION OF CHANGES:
Problem:
(1) In DMP_mp subroutine module of module_bl_mynn.F, calculation of fltv，fltv = flt + svp1*flq，is wrong.
(2) In mynn_tendencies subroutine module of module_bl_mynn.F, calculation of Dqc，
Dqc(k)=(sqc2(k)/(1.-sqv2(k)) - qc(k))/delt，is wrong.

Solution:
(1) The buoyancy flux is fltv = flt + svp1*flq*ts .
(2) The cloud water tendence is Dqc(k)=(sqc2(k)/(1.-sqc2(k)) - qc(k))/delt .

LIST OF MODIFIED FILES: 
M phys/module_bl_mynn.F

TESTS CONDUCTED: 
1. Do mods fix problem? How can that be demonstrated, and was that test conducted?
2. Are the Jenkins tests all passing?

RELEASE NOTE:  Code correction in module_bl_mynn.F.

### CODE REVIEW

**Comment by dudhia** [comment]
You should check out the current version because your git summary seems to
indicate an old version.
If you see changes to V4.4 make a PR for that instead.

**Comment by weiwangncar** [comment]
The Jenkins tests have passed:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by Nuanyang00** [comment]
These tow bugs also exist in V4.4. 
















At 2022-05-27 23:07:17, "dudhia" ***@***.***> wrote:

You should check out the current version because your git summary seems to
indicate an old version.
If you see changes to V4.4 make a PR for that instead.

**Comment by Nuanyang00** [comment]
In my opinion, it is the conversion between mixing ratio and specific humidity.




























At 2022-05-27 23:55:18, "dudhia" ***@***.***> wrote:

If it is conversion to or from mixing ratio this would not be a bug. I did
not look closely.

**Comment by dudhia** [comment]
This still needs to be updated to the last release and the PR submitted again. As it is, over 1000 files are changed.

**Comment by dudhia** [comment]
@joeolson42 or @Nuanyang00 can we have fix number 1 as a clean change to the latest release as this PR is on an old version? We are preparing for a bug-fix release 4.4.1 soon.

**Comment by dudhia** [comment]
I  notice that the target is V4.1.2. Perhaps we can change that to 4.4.1 to solve this problem.

**Comment by weiwangncar** [comment]
@Nuanyang00 This PR is not done correctly. Can you redo this PR following the instructions described in the following page: https://github.com/wrf-model/WRF/wiki/Workflow-for-WRF-Code-Modification. If you encounter any difficulty, let us know soon. Also since the reviewers have only agreed on one of the proposed fixes, please only make that one change. Thanks.

**Comment by weiwangncar** [comment]
@Nuanyang00 You will need to first fork the latest WRF repository on Github, then clone it on your own computer. Create a branch, add the code change, and push it up to your fork on Github. Make a PR from the code of your fork. You cannot make changes directly to the main branch of the WRF repository - like you did in this PR.

**Comment by dudhia** [comment]
release-v4.4.1 is the branch to be committed to.

**Comment by weiwangncar** [comment]
@dudhia @joeolson42 Can either of you let me know what the correct code change is for item #1?

**Comment by joeolson42** [comment]
In my latest code, I compute this once (and once only) in the main driver and then pipe it into the subroutine DMP_mf. They are computed as follows:

          ! Surface turbulent fluxes                                   
          flq =flqv+flqc !! LATENT      
          flt =hfx(i)/(rho1(kts)*cpm )-xlvcp*flqc/ex1(kts)  !! Temperature flux                    
          fltv=flt + flqv*p608*th_sfc                       !! Virtual temperature flux

I wouldn't worry about it. I promise to commit an MYNN update very soon. I just tested the updates more in some EUREC4A cases and the clouds look great. Sorry about the delayed update, there just hasn't been as much testing in WRF recently...

**Comment by weiwangncar** [comment]
@joeolson42 Thanks, Joe. I will close this PR, since it is not done correctly.

**Comment by Nuanyang00** [comment]
Sorry for putting forward a wrong view.

After careful inspection of the module_bl_mynn. F program, the calculation formula of sqc in the program is correct.

In module_bl_mynn.F, the specific humidity variables sqc and sqv are defined as :  
sqv=qv/(1+qv),      sqc=qc/(1+qv), 
where qv is mixing ratios of vapor and qc is mixing ratio of cloud water.

And, the mixing ratios can be obtained by inverse calculation:
qv=sqv/(1-sqv),   qc=sqc/(1-sqv)

**Pull request closed without merging**
