### PR TITLE
Develop new CLM / MEGANv2.1 interface

### PR DESCRIPTION
**Pull request by brigaudet**
TYPE: new feature 

KEYWORDS: CLM surface scheme, MEGANv2.1 biogenic emissions

SOURCE: Brian Gaudet (PNNL) 

DESCRIPTION OF CHANGES:  The CLM surface scheme and associated subroutines in the physics and chemistry packages were modified to be made consistent with the MEGANv2.1 biogenic emission model, as opposed to earlier code which uses MEGANv2.0.  This upgrade to WRF-CLM parallels the use of MEGANv2.1 in CLM4.0, as described in Guenther et al. (2012, GMD).  Within module_sf_clm.F, the emissions for 150 species are computed, and then mapped to the chemistry packages (e.g., SARPC99) in WRF-Chem.  Emissions are a function of plant functional type (PFT) and emission factors that depend on temperature, light, and LAI.  

Among the key changes to module_sf_clm.F are:  a MEGANv2.1 emissions factor file containing standard emissions as a function of PFT and 20 classes of compounds is read in; new modules for handling the MEGAN categories are created (and the use of these modules by other modules necessitated the re-ordering of the subroutines in the source file);  the environmental emissions factors are tracked through running averaged variables; PFTs can now be determined from a geographical mapping in the wrfinput file rather than from an internal vegetation type-based table; and mappings of MEGAN species to WRF-Chem species packages are included.  An option ('bio_emiss_opt = 4') to invoke MEGANv2.1 biogenic emissions is included in the &chem namelist section; the user retains the option of using old MEGAN emissions ('bio_emiss_opt = 3').  When a user runs the new CLM but without selecting bio_emiss_opt = 4, the old CLM method of mapping land use to PFTs is use, in order to reproduce the meteorology of previous versions of the model.

ISSUE: For use when this PR closes an issue. For issue number 123
```
Fixes #123
```

LIST OF MODIFIED FILES: 

M       Registry/Registry.EM_COMMON
M       Registry/Registry.NMM
M       Registry/registry.chem
M       Registry/registry.clm
M       Registry/registry.dimspec
M       chem/KPP/mechanisms/saprc99/saprc99.eqn
M       chem/KPP/mechanisms/saprc99/saprc99.spc
M       chem/chem_driver.F
M       chem/chemics_init.F
M       chem/emissions_driver.F
M       chem/module_dep_simple.F
M       chem/module_emissions_anthropogenics.F
M       chem/module_ftuv_driver.F
M       dyn_em/module_first_rk_step_part1.F
M       dyn_em/start_em.F
M.      dyn_nmm/module_PHYSICS_CALLS.F
M       frame/module_driver_constants.F
M       phys/module_physics_init.F
M       phys/module_sf_clm.F
M       phys/module_surface_driver.F
M       share/module_check_a_mundo.F

TESTS CONDUCTED: Tests with the changes merged into the develop branch reproduced the meteorology of the pure develop branch when bio_emiss_opt = 4 was <<not>> selected.  When bio_emiss_opt = 4 <<was>> selected, the meteorology and emissions of PNNL reference simulations was reproduced.  Tests of code merged with the up-to-moment version of develop are pending.
Examples of a meteorological tests and a chemistry test are attached.

NewPNNL4 2chem_5h
NewPNNL4 2met_12h_newMEGAN
NewPNNL4 2met_12h_oldMEGAN

### CODE REVIEW

**Comment by andrewsoong** [comment]
Hello,
I am a PhD staudent,major in land-atmospere interactions.
Is there any plans to update WRF-CLM4 to WRF-CLM5 or adds a now land surface scheme(CLM5) to WRF ? I know CLM5.0 has released last year with significant improvement.

**Comment by dudhia** [comment]
There is no plan for this within NCAR, but we would welcome developers to
contribute
this version.
Jimy

**Comment by brigaudet** [comment]
Hello!

We at PNNL do not have an immediate plan to do that as far as I know, though I can check.
(Our involvement has mainly been on the WRF-Chem side and so our main interest was on the MEGANv2.1 biogenic emissions related to the PFTs in WRF CLM.
So the land surface modeling group might be best to speak to CLM upgrades, though I could assist in porting the MEGANv2.1 code to future CLM versions if this would be helpful.)


Brian

**Comment by davegill** [comment]
@jordanschnell 
`bio_emiss_opt` is only defined in the WRF Chem Registry. We can't check that namelist setting in check_a_mundo without ifdefs.

**Comment by davegill** [comment]
@jordanschnell 
Looks like lots of chem-only fields not inside of ifdefs in module_sf_clm.F:
megan2_clm, cbmz_*, saprc*, radm2*, mozart_*

**Comment by jordanschnell** [comment]
Closed with pull 1425

**Pull request closed without merging**
