### PR TITLE
Adding Ristic microphysics scheme

### PR DESCRIPTION
**Pull request by davegill**
TYPE: New feature

KEYWORDS: microphysic, forecast, cloud, precipitation

SOURCE: Ivan Ristic (Weather2 - www.weather2.rs)

DESCRIPTION OF CHANGES:
Original PR _Adding new Ristic microphysics scheme_ (#1308) was more than a year out of date, and the effort to "merge everything in" did not go well. This PR started with the develop branch and cherry-picked the two (non-NMM) commits from the original Ristic PR.

In order to improve cloud and precipitation forecast we developed new cloud prediction scheme and we implemented it in WRF model. Fractional cloud cover, cloud liquid water, cloud ice and cloud snow are explicitly predicted by adding three
prognostic equations for fractional cloud cover, cloud mixing ratio and snow per cloud fraction to the model. Sedimentation of ice and snow is also included in parameterization. Precipitation of rain and snow are determined from cloud fields. Clouds predicted like this can be used also in radiation parameterization.

Thermodynamic wet bulb temperature will be used for describing clouds because it is constant during water phase changes. By using this temperature moist static energy of model grid box and cloudy part inside the grid box is the same and principle of energy conservation is satisfied.

A complete description is now found in Ristic I., Kordic I., 2018: Cloud parameterization and cloud prediction scheme in the Eta numerical weather model. NWCM - Serbian Academy of Sciences and Arts which can be found at https://www.sanu.ac.rs/wp-content/uploads/2018/10/11_Cloud%20parameterization%20and%20cloud%20prediction%20scheme%20in%20Eta%20numerical%20weather%20model.pdf .

LIST OF MODIFIED FILES:
modified:   Registry/Registry.EM_COMMON
modified:   dyn_em/solve_em.F
modified:   phys/Makefile
modified:   phys/module_microphysics_driver.F
new file:   phys/module_mp_ivanr_micro.F

TESTS CONDUCTED:
All the wrf-coop tests passed and the microphysics is being actively used for running a model with NMM.
Integration of the model for test cases indicate that new cloud prediction scheme improved forecast compared to the original model. New fractional cloud cover formula showed good results in practice, since the fractional cloud cover, predicted in this way, was much closer to the real cloud cover values. Significant progress has been made in stratiform precipitation forecast. Positive impact on convection scheme is also noticed.
One test was run on 17. November 2011 with the  Wrf model with ECMWF as boundary data. Model run for 72 hours in horizontal resolution of about 22 km and vertical resolution of 38 layers for the Europe domain. Fog was first to be tested.
image
image

The second test was run on 24. June 2015 with Wrf model with ECMWF as boundary data. Model was run for 24 hours in
horizontal resolution of about 22 km and a vertical resolution of 38 layers for the Europe domain. The second test situation tested  mid-morning precipitation over northern Serbia.
image

More details can be found in the aforementioned pdf file.

RELEASE NOTE: Ivan Ristic: Custom implementation of microphysics

### CODE REVIEW

**Comment by davegill** [comment]
@Nikolar97 
Nikola,
Would you please verify that this PR still is able to work correctly. Since your original PR only had two small commits, they were easier to handle with a "git cherry-pick".

**Comment by davegill** [comment]
jenkins
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: 49e02f166c778bbbd7c39c757aca13b71697baff, requested by: davegill for PR: https://github.com/scala-computing/WRF/pull/1619. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 159           155        0
    Number of Comparisons  : 96           93        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```

**Comment by davegill** [comment]
@Nikolar97 @weiwangncar @dudhia 
Is this scheme suitable for use with ARW? We have removed the NMM dynamical core. We will not merge in a MP scheme designed specifically for NMM.

**Comment by dudhia** [comment]
This is not for V4.4. It can be made compatible with V4.3.2 if they need NMM.

**Comment by davegill** [comment]
@Nikolar97 @dudhia @weiwangncar 
> This is not for V4.4. It can be made compatible with V4.3.2 if they need NMM.

Jimy,
Thanks! I'll close this PR.

**Comment by Nikolar97** [comment]
We would like to to make it compatible with ARW , is it enough for us to put our CLD  variable into the existing CLDFRAC array. Do you have any pointers how we could go along with these changes, it would be greatly appreciated. Thanks in advance.

**Comment by dudhia** [comment]
I have not looked at the code, but use the existing variables as much as
possible. CLDFRAC is used by the radiation schemes.

**Comment by davegill** [comment]
Apparently, we are OPEN for business!

**Comment by Nikolar97** [comment]
In Ristic microphysics, the cloud fraction is a prognostic quantity. This is a
new approach and we need advice on how to best implement
the cloud fraction in the radiation driver module_radiation_driver.F . We need
brief advice on how to insert a CLD variable from Ristic microphysics into
CLDFRA variable.
The problem is also the ICLOUD variable, whether to assign a new value to be
used by our microphysics or to use one of the existing ones and just add the
part related to the equalization of CLDFRC and CLD variable.
With these changes, Ristic microphysics will be totally compatible with all
radiation parameterizations and the ARW core, which is the goal.
Is there anyone we can talk to about this topic?

**Comment by davegill** [comment]
@weiwangncar @dudhia 
Ristic questions

**Comment by weiwangncar** [comment]
@Nikolar97 We will get back to you soon.

**Comment by Nikolar97** [comment]
Hello, we are currently  waiting for an answer in regards to our last question so we can try to continue with our integration of Ristic microphysics with the ARW core. Is there any update on the current situation?

**Comment by dudhia** [comment]
Our plan with this is to have it as a feature branch.
We are still finalizing our V4.4 release this month and after that you may
be able to upgrade and
have an up-to-date branch.
Jimy

**Comment by Nikolar97** [comment]
@dudhia Thank you for your answer, we will wait for the new release to come out and then start implementing our microphysics.

**Comment by Nikolar97** [comment]
@davegill  @weiwangncar Hello, we have finished porting our microphysics to the V4.4 release and successfully tested. What are the next steps we should take to have it as a feature branch?

**Comment by weiwangncar** [comment]
@Nikolar97 Thank you for updating your branch to v4.4. Let us discuss some ways to maintain your code outside the main repository, and get back to you, hopefully soon.

**Comment by Nikolar97** [comment]
@weiwangncar  @davegill  @dudhia Hello, we would like to know if there are any updates on the current situation. We are eager to continue our discussions on the maintenance of the branch.

**Comment by dudhia** [comment]
We are looking at how best to do this.

**Comment by dudhia** [comment]
@Nikolar97 do you have your updated code in your own github fork?

**Comment by Nikolar97** [comment]
@dudhia Sorry for replaying so late, we were on a holiday vacation. We updated the current fork to the newest WRF version and then pushed our changes on it(with the new microphysics integrated with the 4.4 WRF).

**Comment by dudhia** [comment]
Maybe you can do a new pull request, which will also test the compilation.
If you have your own fork, it is preferable to do it from there.
    I am on vacation now, so my replies may be slow.
Jimy

**Comment by Nikolar97** [comment]
@dudhia On which branch should i do my new pull request if it matters?

**Comment by dudhia** [comment]
Since it is just for testing you can use the master branch which is the
latest release.

**Comment by Nikolar97** [comment]
@dudhia  Created the pull request for testing at #1757.

**Comment by dudhia** [comment]
Superseded by #1757

**Pull request closed without merging**
