### PR TITLE
Add git hash and a summary of files changed

### PR DESCRIPTION
**Pull request by davegill**
TYPE: enhancement

KEYWORDS: commit hash, source files verification, provenance, user support, development, version control

SOURCE: Jan Mandel (University of Colorado Denver) and internal

DESCRIPTION OF CHANGES: 

User support is more difficult without knowing if the user may have changed any files in the distribution. For 
developers, it is not possible to check if the binary executable is the same version as the source files, leading to 
unnecessary rebuilds. 

This PR includes a line in the WRF print output next to the WRF release version with the git commit hash. If any files 
are not part of a commit (local files changed), this modification prints a short diff statistic. Finally, if the files are not 
under git version control, the print out indicates that the git commit identification is not available. 

The command 
```
strings wrf.exe | grep -w 'git commit'
``` 
outputs the version of the source code from which the binary was constructed. This same identification line is also 
printed in the output of `./compile` step.

The new functionality is implemented by generating a new file, `inc/commit_decl`, during the `./compile` stage, and using 
this new file similarly as the `inc/version_decl` file. This new file is deleted by `./clean`.

Examples:

In WRF output: 
```
WRF V4.2 MODEL
git commit a599473c3c6db6cf00da79a7a7244085ba800f11
```

To identify the binary executable without running it:
```
strings wrf.exe | grep "git commit"
git commit a599473c3c6db6cf00da79a7a7244085ba800f11
```

In ./compile output, with some file changed: 
```
V4.2
git commit ccc58d749be86c1d5ddd45b4c3f82b2c4f9ca980 1 file changed, 1 insertion(+)
```
Content of the generated ```commit_decl``` file: 
```
    CHARACTER (LEN=*), PARAMETER :: commit_version = 'git commit e5d6fe01f5d319405af4f0e7d60aac8d9df02e43'
```

Content of the generated ```commit_decl``` file, with source files not from github, or no git on the system:
```
    CHARACTER (LEN=*), PARAMETER :: commit_version = 'No git found or not a git repository, git commit version not available.'
```

LIST OF MODIFIED FILES:
Scripts:   
modified:   clean
modified:   compile

Files that are associated with the top-level executables:
modified:   chem/chemics_init.F
modified:   chem/convert_emiss.F
modified:   main/ideal_em.F
modified:   main/ideal_nmm.F
modified:   main/module_wrf_top.F
modified:   main/ndown_em.F
modified:   main/real_em.F
modified:   main/real_nmm.F
modified:   main/tc_em.F

Files that are associated with the git:
modified:   inc/.gitignore 

Files removing unnecessary `#include`:
modified:   share/input_wrf.F 

TESTS CONDUCTED: 
1. Built and run with Intel and GNU compilers, with and without git available, in a cloned repository, and in a directory 
not under git control.
2. Jenkins regression test passed.

RELEASE NOTE: The git commit information is part of the WRF modeling system standard output, part of the strings within the executables, and also in the output of the ./compile command.

### CODE REVIEW

**Comment by davegill** [comment]
jenkins
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: 118e3c6db4259f059be08008fa88925f62186f39, requested by: davegill for PR: https://github.com/wrf-model/WRF/pull/1399. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           18
    Number of Builds       : 48           46
    Number of Simulations  : 163           161        0
    Number of Comparisons  : 103           102        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```

**Comment by davegill** [comment]
@smileMchen @kkeene44 
Folks,
This is ready for a review. I modified the original PR to bring this up-to-date. Most of the executables that would be built are tested by the regression test.
The ndown and tc_bogus executables were built separately to demonstrate that the mods are OK.

**Comment by davegill** [comment]
@kkeene44 @smileMchen 
```
==========================================================================
build started:   Mon Feb 15 15:05:12 UTC 2021
build completed: Mon Feb 15 15:30:40 UTC 2021
 
--->                  Executables successfully built                  <---
 
-rwxr-xr-x 1 root root 39924808 Feb 15 15:30 main/ndown.exe
-rwxr-xr-x 1 root root 39805928 Feb 15 15:30 main/real.exe
-rwxr-xr-x 1 root root 39282032 Feb 15 15:30 main/tc.exe
-rwxr-xr-x 1 root root 43846576 Feb 15 15:29 main/wrf.exe
 
==========================================================================
```

**Review by smileMchen — APPROVED** [review]

**Comment by smileMchen** [comment]
@davegill 
Dave, I have approved this PR.

**Pull request merged**
