### PR TITLE
Remove UM trajectory initialization from real

### PR DESCRIPTION
**Pull request by smileMchen**
TYPE: feature removed

KEYWORDS: UM trajectory, NCAR ACOM trajectory

SOURCE: Internal

DESCRIPTION OF CHANGES: 
The UM trajectory option has been replaced by NCAR ACOM trajectory option.  Therefore, the initialization for UM 
trajectory (in the real program) is no longer needed.

LIST OF MODIFIED FILES:
M   dyn_em/module_initialize_real.F

TESTS CONDUCTED: 
(1) A single test case has been conducted to demonstrate that the UM trajectory no longer works. NCAR ACOM trajectory option gives expected results. 
(2) Jenkins test is done successfully.

RELEASE NOTE: Not necessary

### CODE REVIEW

**Comment by smileMchen** [comment]
@davegill @weiwangncar @dudhia @kkeene44 
All,
Since WRFv3.9.1, the UM trajectory option has been replaced by the NCAR ACOM trajectory option. While the ACOM trajectory option works fine, the UM trajectory does have its advantages. 
Dave and I discussed this issue whether to recover the UM trajectory option. We are not sure yet how much coding work will involve. Our initial attempt failed due to problems possibly related to memory and MPI issues. We don't know yet the exact reason. 
We leave the discussion to the group whether to keep both trajectory options, or it is just fine to stay with the NCAR ACOM option.

**Comment by dudhia** [comment]
Can you say what the advantages of the UM option are?
Thanks.

**Comment by smileMchen** [comment]
@dudhia 
Jimy,
The UM trajectory is easily initialized and the output can be controlled by the history interval. 
The ACOM option needs wrfinput_traj as input and output is every time step.

**Comment by davegill** [comment]
@dudhia @weiwangncar @kkeene44 @smileMchen 
The original simple UM trajectory:
1. just i,j,k location
2. initialized in real

The new ACOM trajectory:
1. values of user selectable fields at each trajectory point
2. initialization is via lat/lon and a separate input file

**Comment by dudhia** [comment]
Seems worth a try in my opinion

**Comment by davegill** [comment]
Folks,
Ming pointed me to the original PR
https://github.com/wrf-model/WRF/pull/84

There was no attempt to provide traj_opt=2 and keep the original traj_opt=1. There are lots of places where the original trajectory code was overwritten. It would be a large effort to bring back the original capability.

**Comment by weiwangncar** [comment]
@dudhia @davegill @smileMchen Apart from initialization, the ACOM code can compute meteorological values along the trajectory, which was the major enhancement.

**Comment by dudhia** [comment]
Maybe just making it easier to use or having reasonable defaults and
example files is sufficient.

**Comment by davegill** [comment]
@weiwangncar @dudhia @smileMchen 
Folks,
None of the new trajectory is handled via the registry. A number of mods overwrote the original code. There is no way to tease out traj_opt=1 vs traj_opt=2 (for example), they are all mixed together. I ran a simple trajectory. I got all of the info for the ACOM trajectory. However, I also got the original data in the standard wrfout_d01* file.

This seems like quite an effort to split them apart. This PR cleans up code that is no longer used. I think that should be done, as users are going to be very confused why no trajectories are initialized after they have put them into the real program.

Do we have utilities to process the ACOM traj output files?

**Comment by weiwangncar** [comment]
No, we don't. We didn't have anything to plot the UM trajectories either, at least not that I'm aware of. I've already changed my Option talk to reflect the new option. Also should we leave this PR to 4.3?

**Comment by davegill** [comment]
@weiwangncar @smileMchen @dudhia @kkeene44 
> should we leave this PR to 4.3?

That would give us time to decide what to do. However, I think that the decision is clear - UM traj is gone, and ACOM traj is the way we operate.

**Comment by dudhia** [comment]
I agree with this. We need to try to make the ACOM trajectories easy to use
with some default settings and example files that work.
Jimy

**Comment by davegill** [comment]
@smileMchen @weiwangncar @dudhia 
Folks,
Regardless of the documentation status for the ACOM trajectory, this PR should be merged. It gets rid of code that would be confusing, as it is not utilized. If we are in agreement, I'll approve it.

**Comment by weiwangncar** [comment]
@davegill @smileMchen @dudhia I'm ok with it...

**Review by davegill — APPROVED** [review]

**Comment by matzegoebel** [comment]
In module_initialize_ideal.F the template for initializing trajectories is still there. Shouldn't it also be removed then?

**Pull request merged**
