### PR TITLE
TSLIST: add pressure field to vertical profile output files

### PR DESCRIPTION
**Pull request by davegill**
TYPE: enhancement

KEYWORDS: tslist, pressure, profile

SOURCE: Suggested by Gokhan Sever, implemented internal

DESCRIPTION OF CHANGES: 
1. Add the pressure field to those that are included in the vertical profiles.
2. Fixed the printout for the (i,j) case, where (lat,lon) was printed as (0.000,0.000)
3. The Registry.EM_COMMON description for W said "earth relative", but not any more

LIST OF MODIFIED FILES:
M Registry/Registry.EM_COMMON
M run/README.tslist
M share/wrf_timeseries.F

TESTS CONDUCTED: 
1. Pressure field looks reasonable.
2. Bit-wise identical results when using (i,j) vs (lat,lon)
3. For the (i,j) case, the (lat,lon) print out is correct (tested Lambert)

RELEASE NOTES: Add "pressure" to list of profile fields that are available (release notes from SHA 43ac4e93fb29, PR #712 "new tslist options: add W; cell-centered u,v; (i,j) and (lat,lon) locations")

### CODE REVIEW

**Comment by davegill** [comment]
@kkeene44 @weiwangncar @smileMchen 
Kelly and Wei,
Is there an NCL script that plots these profiles? If so, we should be sure to include vertical velocity ("WW") and pressure ("PR") as defaults with this release.

**Comment by davegill** [comment]
@mgduda 
Michael,
Since you are the codeowner of this capability

**Comment by kkeene44** [comment]
@davegill 
Isn't WW already included in this option since commit 43ac4e[https://github.com/wrf-model/WRF/commit/43ac4e93fb29a753893152d8e228f3b8c8b96f42](url)?

**Comment by davegill** [comment]
@gsever
Gokhan,
If you are able, please test this capability.

**Comment by davegill** [comment]
> Isn't WW already included in this option since commit 43ac4ehttps://github.com/wrf-model/WRF/commit/43ac4e93fb29a753893152d8e228f3b8c8b96f42?

@weiwangncar 
Wei,
Yes, W is included in the previous commit. In this PR, I just changed the Registry description. This PR's release note should basically be to change "W is now a profile field" to "W and P are now profile fields".

**Comment by gsever** [comment]
> @gsever
> Gokhan,
> If you are able, please test this capability.

Hi Dave,

Just to confirm you that pressure variable is output successfully using these changes. 
Following steps summarizes my approach:

1) clone release-v4.1 branch
`$ git clone -b release-v4.1 --single-branch https://github.com/wrf-model/WRF.git`

2) copy 2 modified files from this merge request into their respective folders (Registry.EM_COMMON and wrf_timeseries.F)

3) compile and test :)


A simple Python script helps to plot the 2D fields or time-series output:

import numpy as np
import matplotlib.pyplot as plt

data = np.loadtxt("gis.d01.PR", skiprows=1)
print (data.shape)
print (data[:,0][:10])

fig1, ax = plt.subplots(1, 1, figsize=(12, 4))
pr = ax.imshow(data[:,1:21].T, origin='lower', aspect='auto', extent = [data[:,0][0], data[:,0][-1], 0, 20])
cb = fig1.colorbar(pr, orientation='vertical', format="%d")

plt.tight_layout()
#plt.savefig("plot_gis_PR.jpg", dpi=100)
plt.show()


Thanks for fixing this quickly and sorry for my delayed response.

**Comment by davegill** [comment]
@gsever 
Gokhan,
Thanks for the confirmation!

**Comment by gsever** [comment]
> @gsever
> Gokhan,
> Thanks for the confirmation!

Perhaps, TKE or a simple mechanism to output any prognosed variable can be added in the future.

Now going through this code, I am curious how the model determines (in MPI parallel mode) which rank has the output grid location. It would be great if you could give me some pointers to understand the logic here.

**Pull request merged**
