### PR TITLE
Update the Noah-MP submodule link to the new v4.5 branch/tag

### PR DESCRIPTION
**Pull request by cenlinhe**
Update the Noah-MP submodule link to the new v4.5 branch/tag

TYPE: no impact

KEYWORDS: Noah-MP submodule, tag update

SOURCE: Cenlin He (NCAR)

DESCRIPTION OF CHANGES:
Originally, WRF v4.4 series code is linked to Noah-MP v4.4 branch/tag. Now, for the upcoming WRF v4.5 release, this PR updates the Noah-MP submodule link to the new v4.5 branch/tag.

LIST OF MODIFIED FILES:
/phys/noahmp

TESTS CONDUCTED: 
1. Jenkins tests all passing

RELEASE NOTE: The Noah-MP submodule is updated to the v4.5 branch/tag.

### CODE REVIEW

**Review by weiwangncar — APPROVED** [review]

**Comment by weiwangncar** [comment]
The Jenkins test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@dudhia Can you review this PR?
@cenlinhe Have you tried the change in this PR? Does it pull out the right NoahMP code?

**Comment by cenlinhe** [comment]
Yes, I re-downloaded this PR GitHub code and it pulled out the correct NoahMP code.

**Review by dudhia — APPROVED** [review]
I will assume it is OK

**Pull request merged**
