### PR TITLE
 Makes mp_zero_out affect only the 'moist' array. New separate flags for scalar/chem/tracer

### PR DESCRIPTION
**Pull request by MicroTed**
TYPE:  bug fix

KEYWORDS: mp_zero_out

SOURCE: Ted Mansell (NOAA)

DESCRIPTION OF CHANGES:

This fixes the side-effect of mp_zero_out being applied not only to the moist array, but also to the scalar/chem/tracer arrays using the same threshold. This behavior would be unexpected from the documentation (readme) which indicated that only mixing ratios were affected.  This PR restricts mp_zero_out to the moist array and adds a separate mp_zero_out_all flag to apply it to all the arrays in the off chance that somebody needs to replicate the previous behavior.

ISSUE: Addresses https://github.com/wrf-model/WRF/issues/2007

LIST OF MODIFIED FILES: 
  Registry/Registry.EM_COMMON 
  dyn_em/solve_em.F 
  run/README.namelist
  wrftladj/solve_em_ad.F
  wrftladj/solve_em_tl.F

TESTS CONDUCTED: 
The Jenkins tests have passed.

RELEASE NOTE: The behavior of the  mp_zero_out flag was changed affect only the 'moist' array, whereas previously it also caused the scalar/chem/tracer arrays to also be set to zero for values below threshold. Now there is a separate flag (mp_zero_out_all) if one wishes to reproduce the old behavior.

### CODE REVIEW

**Comment by dudhia** [comment]
Thanks. I would advocate eliminating the other new zero_out options completely. The existing routine has too many moisture references and even uses p_qv. Hard to anticipate anyone needing this for other 4d arrays, as I doubt it is used much anyway.

**Comment by dudhia** [comment]
I understand your caution about backward compatibility. Another alternative is to leave the old calls in there but commented out in case someone wants to reactivate them easily.

**Comment by MicroTed** [comment]
Or maybe just a 'mp_zero_out_all' flag to turn it on for all the arrays? (Basically the same as commenting out the extra calls)

**Comment by dudhia** [comment]
I like that idea.

**Comment by weiwangncar** [comment]
@MicroTed The regression tests are failing for DA/4DVAR compilation. When the changes are finalized, some of the registry changes should be added to registry.wrfplus and/or registry.var.

**Comment by MicroTed** [comment]
@weiwangncar Thanks for noting that. I tend to forget about var.
@dudhia I'll make that change to a single extra flag -- much simpler

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by weiwangncar — APPROVED** [review]

**Review by dudhia — APPROVED** [review]

**Pull request merged**
