### PR TITLE
Regularized WSM6 and its TL/AD for 4DVar

### PR DESCRIPTION
**Pull request by expertyang**
TYPE: new feature

KEYWORDS: WSM6, TL/AD,  4DVAR

Description of Change:
This PR adds a regularized version (i.e., change discontinuous functions to continuous functions) of WSM6 microphysics scheme (MP option 106, named as 'WSM6R') and its tangent linear and adjoint (TL/AD), which enables WRF-4DVar to run with ice-phase hydrometeor analysis variables. Note that the non-linear version of WSM6R is kept just for the code reference of deriving TL/AD, and it is NOT recommended to be used for the WRF model forecast. In addition, there is an improved handling of the file unit related to the background error covariance.

SOURCE:  Sen YANG, Deqin LI, Liqiang CHEN (Institute of Atmospheric Environment, China Meteorological Administration, Shenyang)

LIST OF MODIFIED FILES: 
M       Registry/Registry.EM_COMMON
M       Registry/registry.var
M       Registry/registry.wrfplus
M       main/depend.common
M       phys/Makefile
M       phys/module_microphysics_driver.F
A       phys/module_mp_wsm6s.F
M       var/da/da_setup_structures/da_scale_background_errors.inc
M       var/da/da_setup_structures/da_setup_be_regional.inc
M       var/da/da_transfer_model/da_transfer_wrftltoxa.inc
M       var/da/da_transfer_model/da_transfer_wrftltoxa_adj.inc
M       var/da/da_transfer_model/da_transfer_xatowrftl.inc
M       var/da/da_transfer_model/da_transfer_xatowrftl_adj.inc
M       wrftladj/Makefile
M       wrftladj/depend.wrftladj
M       wrftladj/module_microphysics_driver_ad.F
M       wrftladj/module_microphysics_driver_tl.F
A       wrftladj/module_mp_wsm6s_ad.F
A       wrftladj/module_mp_wsm6s_tl.F
M       wrftladj/solve_em_ad.F
M       wrftladj/solve_em_tl.F

TESTS CONDUCTED: 
1. Jenkins tests all passed;
2. WRFDA regression test passed on Cheyenne;
3. wrfplus and 4dvar tests succeeded using mp_physics & mp_physics_ad=106.

RELEASE NOTE: Add a regularized version of WSM6 and its TL/AD for 4DVar with ice-phase hydrometeor analysis variables.
Yang, S., D. Q. Li, L. Q. Chen, Z. Liu, X.-Y. Huang, and X. Pan, 2022: The regularized WSM6 microphysical scheme and its validation in WRF 4D-Var. Adv. Atmos. Sci., in press.

### CODE REVIEW

**Comment by dudhia** [comment]
It appears that this adds a new scheme called wsm6s. Please say more about why this new scheme is needed and how it differs from WSM6, and add a description in the PR message.

**Comment by weiwangncar** [comment]
This passed regression tests:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by liujake** [comment]
@dudhia I will take care of this PR and add/request more info in PR message.

**Comment by liujake** [comment]
@expertyang 
```
M wrftladj/adBuffer.F
M wrftladj/adStack.c
A wrftladj/adStack.h
```
I have issues to compile these code with gfortran with quite some error message below:
```
gfortran -c -ffixed-form -fdefault-real-8 -O0 adBuffer.for
adBuffer.for:232:25:

  232 |          CALL PUSHNARRAY(ads1buf, 512, 1)
      |                         1
......
  273 |          CALL PUSHNARRAY(adbitbuf, 4, 1)
      |                         2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (CHARACTER(1)/INTEGER(4)).
adBuffer.for:245:24:

  245 |          CALL POPNARRAY(ads1buf, 512, 1)
      |                        1
......
  286 |          CALL POPNARRAY(adbitbuf, 4, 1)
      |                        2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (CHARACTER(1)/INTEGER(4)).
```
After I recovered the old code. It compiled successfully.

**Comment by liujake** [comment]
@expertyang  How about rename 'WSM6S' to 'WSM6R' meaning 'Regularized WSM6'.

**Comment by dudhia** [comment]
The regressions tests seem to be running slowly. Not sure why.

**Comment by liujake** [comment]
I compiled Ok 'wrfplus' and 'wrfda-4dvar' on Cheyenne. wrfplus compilation took about 1-h with '-j 2' using gfortran+mpt. 4dvar compilation took about 10 min with '-j 4' using gofrtran+mpt. I am doing WRFDA regression tests now.

**Comment by weiwangncar** [comment]
The Jenkins tests have passed according to the email below (but not sure why this page is not updated - have contacted the relevant people and is waiting for an answer):

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by liujake** [comment]
WRFDA regression tests passed and wrfplus & 4dvar with new wsm6r scheme succeeded. Ready to merge.

**Review by liujake — APPROVED** [review]
Looks very good. Ready to merge.

**Review by junmeiban — APPROVED** [review]

**Comment by liujake** [comment]
@dudhia I'd like to merge this Today if you approve.

**Review by dudhia — APPROVED** [review]
Interaction with rest of model looks OK

**Pull request merged**
