### PR TITLE
Bug fix for ozone input option o3input = 0

### PR DESCRIPTION
**Pull request by weiwangncar**
Bug fix for o3input=0

TYPE: bug fix

KEYWORDS: RRTMG radiation, o3input=0

SOURCE: reported by Mauro Morichetti of Institute of Atmospheric Sciences and Climate (ISAC), ITALY, fixed internally

DESCRIPTION OF CHANGES:
Problem:
The ozone input option 0 (o3input=0) has been broken since 3.5.1 after a different ozone input option was introduced in 3.5. The code checks the presence of the ozone array O33D, and if it is not present, then the ozone is computed using o3input option 0. But the array is always present, so that code never reaches the other branch. Note also that the default o3input option was changed to 2 since 3.7.

Solution:
This PR fixes the option by checking the ozone input option rather than the presence of the array O33D. As there is an interest to see the output from this option, code is added to pass out the data, which is based on 1-d ozone profile. 

LIST OF MODIFIED FILES: 
M       phys/module_ra_rrtmg_lw.F
M       phys/module_ra_rrtmg_lwf.F
M       phys/module_ra_rrtmg_sw.F
M       phys/module_ra_rrtmg_swf.F

TESTS CONDUCTED: 
1. Do mods fix problem? Tested and it fixed the bug.
2. The Jenkins tests have passed.

RELEASE NOTE: Fixed a bug associated with ozone input option o3input = 0. When o3input is set to 0, ozone is effectively not used in the RRTMG radiation option before this fix.

### CODE REVIEW

**Review by kkeene44 — APPROVED** [review]

**Comment by dudhia** [comment]
I think you are only outputting it from the longwave, so if someone just chose only the shortwave, they would not have it. Is this OK?

**Comment by weiwangncar** [comment]
@dudhia Note that O3RAD isn't a default output variable. One needs to add it to output stream. I had the following thoughts: 1. We do encourage use the RRTMG pairs; 2. When one outputs ozone from shortwave scheme, you won't see any values unless it is during the day, so it could add confusion.

**Comment by weiwangncar** [comment]
Jenkins tests have passed:
    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by dudhia — APPROVED** [review]
Sounds fine.

**Comment by sael9740** [comment]
@dudhia, @weiwangncar -- The changes in https://github.com/wrf-model/WRF/commit/e46673998931fa54b5c6d0f49a71228836130b79 are still buggy for `o3input=0`.

https://github.com/wrf-model/WRF/blob/6233639c599119e76fca17dba9ea211af53a0ba9/phys/module_ra_rrtmg_lw.F#L11729-L11741

https://github.com/wrf-model/WRF/blob/6233639c599119e76fca17dba9ea211af53a0ba9/phys/module_ra_rrtmg_lw.F#L12402-L12426

Since `nlayers > kte`, line 12417 causes a segfault. Based on the usage of `o31d`, do I assume correctly that this assignment on line 12417 is intended to occur only for `k<=kte`?

**Comment by weiwangncar** [comment]
@sael9740 You're probably right. I will take another look. Thanks for spotting it.

**Comment by weiwangncar** [comment]
@sael9740 Can you take a look at PR#[1803](https://github.com/wrf-model/WRF/pull/1803) and see if it is ok. Thanks.

**Comment by sael9740** [comment]
> @sael9740 Can you take a look at PR#[1803](https://github.com/wrf-model/WRF/pull/1803) and see if it is ok. Thanks.

Looks good to me!

**Pull request merged**
