### PR TITLE
Use Qv or specific humidity in interpolation if they are available

### PR DESCRIPTION
**Pull request by weiwangncar**
TYPE: enhancement

KEYWORDS: Qv, specific humidity, vertical interpolation

SOURCE: internal

DESCRIPTION OF CHANGES:
Problem:
In current real program, if either water mixing ratio (Qv) or specific humidity (SH) is available, it first converts it to RH, perform vertical interpolation using RH, and then compute Qv for the model input. Assuming Qv and SH are coming from other model's native levels, which tends to be plenty and generally true, it should not be necessary to go through this Qv (SH) to RH, and RH to Qv steps.

Solution:
Use the flag_qv and flag_sh to avoid using interpolated RH (even though RH is still computed and vertically interpolated). If flag_sh is 1, SH is converted to Qv or mixing ratio. Then Qv is interpolated vertically. A namelist, use_sh_qv, is added for user to choose to do so if SH or Qv data is available. A test case shows that there is some differences in the final Qv in the lower levels (a bit less Qv), particularly near terrain slopes.

LIST OF MODIFIED FILES: 
M      Registry/Registry.EM_COMMON
M      dyn_em/module_initialize_real.F
M      run/README.namelist

TESTS CONDUCTED: 
1. It doesn't affect existing option if RH is the only incoming variable. Tested the code, and it gives bit-for-bit results before and after this change.
2. The Jenkins tests are all passing.

RELEASE NOTE: If water mixing ratio or specific humidity is available in the metgrid output, they can be used directly in vertical interpolation. Previously these fields are first converted to RH, interpolated vertically, and the water vapor mixing ratio is computed at model levels. Now one can use the new namelist, use_sh_qv = T to choose to use SH or Qv data directly.

### CODE REVIEW

**Comment by dudhia** [comment]
When incoming pressure levels are coarse it is always better to interpolate RH.

**Comment by jimbresch** [comment]
That is correct (since qv and sh decrease exponentially with height). But then we will need a definition of “coarse”.Also, the wrf system assumes moisture is computed with respect to water. For some models qv and sh might need to be recomputed wrt water. These kind of details are often poorly documented by the operational centers. Currently the rh is adjusted for the GFS and EC.On Dec 27, 2023, at 5:36 AM, dudhia ***@***.***> wrote:﻿
When incoming pressure levels are coarse it is always better to interpolate RH.

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by dudhia** [comment]
We need to think about this one more. We should convert to RH when the vertical resolution is not coarse. Maybe we need a check for whether native levels are coming in.

**Comment by weiwangncar** [comment]
@dudhia So far the datasets we've seen which provide SH data are from NCEP, EC model level data, which tend to have many more vertical levels. The capability of using MPAS model data to drive WRF also falls in this category. We could add a namelist here (MPAS also has one) to confirm that the user wants to use SH or mixing ratio data instead of converting them to RH and back to mixing ratio.

**Comment by dudhia** [comment]
I would prefer it to be a choice to use SH rather than changing the default.

**Comment by weiwangncar** [comment]
@dudhia I will add a namelist to this option and make the default to use RH. But I think many users could miss the opportunity and benefit to use SH/mixing ratio data directly.

**Review by dudhia — APPROVED** [review]

**Comment by dudhia** [comment]
approved assuming it passes tests

**Comment by weiwangncar** [comment]
@dudhia Yes, it has passed the tests.

**Comment by weiwangncar** [comment]
@jimbresch Do you have more comment on this PR?

**Comment by weiwangncar** [comment]
> @dudhia Yes, it has passed the tests.

Yes, it passed the tests.

**Review by smileMchen — APPROVED** [review]

**Pull request merged**
