### PR TITLE
add HLC.TBL and wind-turbine-1.tbl to clean list

### PR DESCRIPTION
**Pull request by weiwangncar**
TYPE: enhancement

KEYWORDS: clean script, HLC.TBL, wind-turbine-1.tbl

SOURCE: internal

DESCRIPTION OF CHANGES:
Problem:
When executing 'clean -a', two files are not removed: HLC.TBL, and wind-turbine-1.tbl

Solution:
Add these two files to the list of files to be removed in the clean script

LIST OF MODIFIED FILES: 
M clean

TESTS CONDUCTED: 
1. It does remove the two files.
2. Jenkins tests are passing.

RELEASE NOTE: The files HLC.TBL, and wind-turbine-1.tbl are now removed from the test/* directories when doing 'clean -a'.

### CODE REVIEW

**Comment by davegill** [comment]
@weiwangncar 
Wei,
Greg has a new file for his scheme: `qr_acr_qgV3.dat`.
Would you add that also to the `clean -a` part. The MP=8 files take a while to rebuild, so leave it there for a a simple `clean`.

**Comment by weiwangncar** [comment]
@davegill There is only one place the physics data files are removed. The older Thompson files are not part of it.

**Comment by davegill** [comment]
@weiwangncar 
> The older Thompson files are not part of it.

OK, maybe the idea is that this is TOO hard to recompute. I withdraw the request to include Thompson files in the clean script.

**Review by davegill — APPROVED** [review]

**Comment by weiwangncar** [comment]
@davegill Thanks. I just found another file left over after doing clean -a: create_p3_lookupTable_1.f90. Should I add this file to this PR?

**Pull request merged**
