### PR TITLE
Addition of README.md file with quick info for users

### PR DESCRIPTION
**Pull request by kkeene44**
TYPE: text only

KEYWORDS: README.md, citation, web site, references, doi, registration

SOURCE: internal

DESCRIPTION OF CHANGES: Our current README file has extensive information in it, including a public domain notice, and information regarding each release. This is likely off-putting to a user and we assume they don't read much of it. We want to ask users to register if they are new to the WRF modeling system, and also want to provide quick/easy access to our web page, citation information, etc. The addition of this README.md file only includes this very basic information, which will hopefully attract users to read it more closely, and specifically to become a registered user.

LIST OF MODIFIED FILES: 
A     README.md

TESTS CONDUCTED: None - text only

### CODE REVIEW

**Comment by weiwangncar** [comment]
@kkeene44 Did you intend to change 485 files? What is the README.md file in WRF directory?

**Comment by kkeene44** [comment]
@weiwangncar 
The 485 lines was corrected when I changed the base branch to develop (instead of master). The README.md file is the reason for this PR (you can see information above).

**Comment by davegill** [comment]
@weiwangncar @kkeene44 @powersjg
We should have a clean and direct README.md that is the file that is always displayed on github by default when folks look at code. I don't want to remove any info from other files, but to additionally have more of a higher-level and actionable file.
1. We want WRF citations
2. We want metrics for registrations for NSF
3. We want users to know to go to our web site
4. We want the WRF doi used in pubs

**Comment by davegill** [comment]
:shipit:

**Comment by powersjg** [comment]
Kelly,
The latest version with the reference to the public domain and trademark info looks good.
I would approve.

-Jordan

**Pull request merged**
