### PR TITLE
Updated FSBM (33-bins) scheme -- bug fix for release v4.2 

### PR DESCRIPTION
**Pull request by JS-WRF-SBM**
TYPE: bug fix

KEYWORDS: spectral-bin microphysics

SOURCE: 
Jacob Shpund and Alexander Khain (The Hebrew University, Jerusalem, Israel)
kobby.shpund@mail.huji.ac.il

DESCRIPTION OF CHANGES: 
The changes related to aerosol BC and for the FSBM scheme to be able to run using 33- or 43-bins. 
The default version is 33-bins (see RELEASE NOTES for more info).

LIST OF MODIFIED FILES:
M phys/module_mp_fast_sbm.F

TESTS CONDUCTED: 
1. Compiled ideal / real cases using Intel compiler (ifort (IFORT) 19.1.0.166 20191121).
A mesoscale convective system simulation was conducted by integrating for 10h the MC3E-0520 
test case. The simulation produced results as expected (see RELEASE NOTES for more info). 
2. Jenkins is all PASS

RELEASE NOTE: 
1.   For simulating deep continental convective systems (as opposed to maritime convection), it is 
advised to use a 43-bins version of the updated FSBM scheme. In order to run the code using 43 
bins, one needs to modify:
   * The registry (to include more bins for the advection)
   * The corresponding loop indices inside the scheme, and the bin-space parameter (NKR) placed 
at the top of the main module 
   * Switch between the 33-bins input tables with 43-bins

2.   More info about the updated scheme and corresponding results:
Shpund, J., Khain, A., Lynn, B., Fan, J., Han, B., Ryzhkov, A., Snyder, J., Dudhia, J. and Gill, D., 2019. Simulating a Mesoscale Convective System Using WRF With a New Spectral Bin Microphysics: 1: 
Hail vs Graupel. Journal of Geophysical Research: Atmospheres.
https://doi.org/10.1029/2019JD030576

3.   The 43 lookup tables can be downloaded here:
https://drive.google.com/drive/folders/1qxYyQwKI1wKQYasDUkQvVgHs11prLiqA?usp=sharing

### CODE REVIEW

**Comment by davegill** [comment]
@JS-WRF-SBM @weiwangncar @dudhia 
Kobby,
Would you please include the text from the jenkins email in this lower set of comments.

**Comment by JS-WRF-SBM** [comment]
@davegill 

Dave, the jenkins email was sent prior to the minor fix, for which the code didn't compile correctely.
Can you generate a new test? or should I nevertheless include the original one?

**Comment by davegill** [comment]
@JS-WRF-SBM 
> Can you generate a new test?

Kobby,
Just modify your local copy, then
```
git add phys/module_mp_fast_sbm.F
git commit
git push -u origin FSM-bug-fix-2
```
In 90 minutes the test should complete again

**Comment by JS-WRF-SBM** [comment]
> git push -u origin FSM-bug-fix-2

@davegill 
Can't push into origin >> permission denied.
Pushed to here. Not sure if this can generate a new Jenkins test.

**Comment by JS-WRF-SBM** [comment]
@davegill 
[wrf_output.zip](https://github.com/wrf-model/WRF/files/4333105/wrf_output.zip)
 
This build is for Commit ID: 44461ec4338683b28311ba06db1764238242fb79, requested by: JS-WRF-SBM for PR: https://github.com/wrf-model/WRF/pull/1135

Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 10           10
    Number of Builds       : 23           23
    Number of Simulations  : 143           143         125
    Number of Comparisons  : 91           10         0

The zip file is attached

**Comment by JS-WRF-SBM** [comment]
@davegill 

In `Registry/registry.sbm`, the vars` th_old,qv_old,tempc,height` for package `fast_khain_lynn_shpund` are in the `scalar` array. 
This a bug from previous versions which I overlooked, since (at least) `qv_old` and `th_old` shouldn't be advected. These are the current state vars before advection which we use for tendencies.

Does the state vars at the package level in `Registry/registry.sbm` are advected?
If not, the above vars needs to be define as `"state"` NOT `"scalar"`.
Pls. acknowledge and I will correct this.

**Comment by JS-WRF-SBM** [comment]
> In `Registry/registry.sbm`, the vars` th_old,qv_old,tempc,height` for package `fast_khain_lynn_shpund` are in the `scalar` array.
> This a bug from previous versions which I overlooked, since (at least) `qv_old` and `th_old` shouldn't be advected. These are the current state vars before advection which we use for tendencies.
> 
> Does the state vars at the package level in `Registry/registry.sbm` are advected?
> If not, the above vars needs to be define as `"state"` NOT `"scalar"`.
> Pls. acknowledge and I will correct this.

False alarm for the FAST-sbm, but for the FULL-sbm this is a bug (will not correct this now).

**Comment by davegill** [comment]
@JS-WRF-SBM  @weiwangncar @dudhia 

```
Test Type | Expected | Received | Failed
= = = = = = = = = = = = = = = = = = = = = = = = = = = =
Number of Tests : 10 10
Number of Builds : 23 23
Number of Simulations : 143 143 125
Number of Comparisons : 91 10 0
```

This says that 125 tests failed. Something is not right.

**Comment by JS-WRF-SBM** [comment]
@davegill  @weiwangncar @dudhia
> This says that 125 tests failed. Something is not right.

Dave,
From my end `ideal` and `real` builds as expected.
The odd thing is that after `./clean`  and `./configure` the cpp flag stays "1":
`-DBUILD_SBM_FAST=1`

**Comment by davegill** [comment]
@JS-WRF-SBM 
> The odd thing is that after ./clean and ./configure the cpp flag stays "1":

Kobby,
Yes, the code has FSBM built by default.

The failures could be the run or the build. That information is in the attached file with the email.

**Comment by davegill** [comment]
@JS-WRF-SBM 
Kobby,
Again, show the email with the jenkins test results after this commit.

**Comment by JS-WRF-SBM** [comment]
@davegill 
> Kobby,
> Again, show the email with the jenkins test results after this commit.

Waiting for the Jenkins per last commit (cbbab8a).

**Comment by JS-WRF-SBM** [comment]
@davegill 

Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: cbbab8a62c2cbf23135eedf223bee404b609c6ff, requested by: JS-WRF-SBM for PR: https://github.com/wrf-model/WRF/pull/1135. 

  ```
  Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 10           10
    Number of Builds       : 23           23
    Number of Simulations  : 143           143         125
    Number of Comparisons  : 91           10         0
```
The zip file is attached.
Please let me know how can I help.
[wrf_output_PR1135_cbbab8a.zip](https://github.com/wrf-model/WRF/files/4334785/wrf_output_PR1135_cbbab8a.zip)

**Comment by davegill** [comment]
@kobby,
Every EM case is failing, all 125 of them. That usually means a compile error. I looked in the file you sent:

Screen Shot 2020-03-17 at 11 14 07 AM

Your declarations can't use the same name as those available from the WRF model via the Registry. Locally rename those values.

**Comment by JS-WRF-SBM** [comment]
@davegill  
> Your declarations can't use the same name as those available from the WRF model via the Registry. Locally rename those values.

OK, but these are private to the fast_sbm scheme (it was fine for previous submissions).
Let me just ask the following: the only relevant change is at the top of the `fast_sbm` routine:
`USE module_domain`
`USE module_dm`

Which one of these` USE `statement holds the `(defined(DM_PARALLEL))` ?
I need it for the EM 3D cases for aerosols BC (around line #4303).
Maybe this is what causing the problem?

**Comment by davegill** [comment]
@JS-WRF-SBM 
> Which one of these USE statements holds the (defined(DM_PARALLEL)) ?

Kobby,
The cpp directive [(defined(DM_PARALLEL))] does not come from a module via USE association. That directive is one of the compiler arguments.

**Comment by davegill** [comment]
@JS-WRF-SBM 
Kobby,
Let us know how that mod works for you.

**Comment by JS-WRF-SBM** [comment]
@davegill 

> Let us know how that mod works for you.

Indeed, the aerosol BC are intact even after the removal of the `USE` statements.
Waiting for the automatic Jenkins test.

Thanks!

**Comment by davegill** [comment]
@JS-WRF-SBM 
Kobby,
🤞

**Comment by JS-WRF-SBM** [comment]
@davegill 

> Kobby,
> crossed_fingers

Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: 56348c4e01cbe4e74bcdbfc17434ccce676f7f0a, requested by: JS-WRF-SBM for PR: https://github.com/wrf-model/WRF/pull/1135.

    ```
Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 10           10
    Number of Builds       : 23           23
    Number of Simulations  : 143           143        0
    Number of Comparisons  : 91           91        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```
NOTE: if the ~WRF's god crosses figures, it means that someone messed up in a dum way.
Thanks !

**Comment by davegill** [comment]
@JS-WRF-SBM 
Kobby,
Great news!

**Comment by weiwangncar** [comment]
@JS-WRF Yes, please. Any information you can provide will be helpful.

**Pull request merged**
