### PR TITLE
Add Dynamic Lightning Scheme Files to CODEOWNERS

### PR DESCRIPTION
**Pull request by kkeene44**
TYPE: no impact

KEYWORDS: phys, module_ltng_pe.F, module_ltng_strokes.F, CODEOWNERS

SOURCE: internal

DESCRIPTION OF CHANGES: As the new Dynamic Lightning Scheme #1226  is being put into the develop branch, added the developer (barryhlynn) and wrf-model/physics to the CODEOWNERS list for the 2 files that are being added (phys/module_ltng_pe.F and phys/module_ltng_strokes.F)

LIST OF MODIFIED FILES: 
M    .github/CODEOWNERS

TESTS CONDUCTED: None - text only

### CODE REVIEW

**Comment by davegill** [comment]
@kkeene44 
Kelly,
Would you line those files up? I don't know of they are spaces and should be tabs - or vice versa.

**Comment by kkeene44** [comment]
@davegill omg, I tried to edit through the web interface and there's no clear answer to how many tabs/spaces it needs. I'll try from my local.

**Comment by davegill** [comment]
@kkeene44 
>  I tried to edit through the web interface and there's no clear answer to how many tabs/spaces it needs. I'll try from my local.

Kelly,
Whenever there is a space vs tab issue, I always bring the code back down locally. I can NEVER figure it out with the github web editor.

**Comment by kkeene44** [comment]
@davegill 
I give up. I can't get this right. I'm just going to close this PR and do another one. This is really stupid.

**Pull request closed without merging**
