### PR TITLE
After space removal top of dev repo

### PR DESCRIPTION
**Pull request by smileMchen**
### No comments on this PR

### CODE REVIEW

**Comment by dudhia** [comment]
Careful not to remove valid changes. I think the WSM and WDM changes at
least
were related to recent mods, and I saw some others.
Jimy

**Comment by davegill** [comment]
@dudhia @smileMchen 

>Careful not to remove valid changes. I think the WSM and WDM changes at least were related to recent mods, and I saw some others.

Look only at PR #1085 "AFTER space removal - FSBM candidate alternate"

Because of the messed up develop branch, the GNU compiler issues, the zillions of whitespace induced conflicts, etc we needed to generate a temporary branch to test.

**Comment by davegill** [comment]
testing purposes only

**Comment by davegill** [comment]
testing

**Pull request closed without merging**
