### PR TITLE
Fix wrong Ott lightning NOx distribution

### PR DESCRIPTION
**Pull request by zxdawn**
TYPE: bug fix

KEYWORDS: chem; lightning;

SOURCE: Ott et al. (2010)

DESCRIPTION OF CHANGES:
Problem:
The lightning NOx percent profile is inconsistent with the paper and some summations are not 1.

Solution:
Correct the profiles according to the table.
image

LIST OF MODIFIED FILES:
M       chem/module_lightning_nox_ott.F

TESTS CONDUCTED: 
1. Do mods fix problem? (Yes)
image

2. Are the Jenkins tests all passing?

RELEASE NOTE: minor bug-fix in Ott lightning NOx distribution

### CODE REVIEW

**Comment by weiwangncar** [comment]
Jenkins tests have passed:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@jordanschnell Can you review and see if this PR should be included in the 4.4 release, please?

**Review by jordanschnell — APPROVED** [review]
approved by chem

**Comment by weiwangncar** [comment]
@jordanschnell For release 4.4?

**Comment by jordanschnell** [comment]
@weiwangncar Yes, only a very minor change. For 4.4.

**Review by jordanschnell — APPROVED** [review]
Approved

**Review by jordanschnell — APPROVED** [review]

**Review by kayeekayee — APPROVED** [review]

**Pull request merged**
