### PR TITLE
MP=8,28 initialize_real additions for cloud droplet number, cloud ice number, rain number.

### PR DESCRIPTION
**Pull request by gthompsnWRF**
TYPE: NEW FEATURE

KEYWORDS: number concentrations, initial and boundary conditions, microphysics, 2-moment

SOURCE:  Greg Thompson (gthompsn; NCAR-RAL)

DESCRIPTION OF CHANGES:  Problem: some incoming data from WPS/ungrib/metgrid, especially RAP/HRRR pressure level data only have mass mixing ratios but not number concentrations.  This forces a number to be made up later for 2-moment microphysics (MP) schemes. For more fully integrated approach with initial and boundary conditions, we can calculate very logical number from mass together with other variables to get number in module_initialize_real.  Very simple functions, one each to create number of cloud droplets, cloud ice, and rain number concentrations are isolated functions added for IC/BC creation time. The solution implemented herein also permits more direct integration with DA codes.

ISSUE: (not a previously known issue)

LIST OF MODIFIED FILES:
dyn_em/module_initialize_real.F

TESTS CONDUCTED:  Pending, however gthompsn using this code for past 2 months without problems.

RELEASE NOTE:  Most GRIB files contain mass mixing ratios for cloud/precip variables, but not all of them contain number concentrations.  A good example is pressure level RAP/HRRR files whereas the native level model files contain both mass and number.  Furthermore, FV3 people want to start the regional version FV3 with global model results using the GFDL 1-moment microphysics scheme while switching to Thompson-Eidhammer 2-moment microphysics.  Doing so will cause greatly inferior assumptions at run time versus fixing the number concentration variables with something sensible during real.exe to get both initial and boundary condition 2-moment variables reasonably in sync.  This same approach could also be applied with multiple other WRF microphysics schemes including Milbrandt-Yau, Morrison 2-moment, NSSL, and others.  The solution here is creating number of cloud droplets, cloud ice, and rain for any of those which have mass but not number; only for Thompson versions of microphysics at this time.

### CODE REVIEW

**Comment by davegill** [comment]
@gthompsnWRF @kkeene44 @weiwangncar 
Folks,
There are changed files in here that should not be included. This is supposed to modify a single file, dyn_em/module_initialize_real.F, but there are 22 files that are part of this PR.

**Comment by davegill** [comment]
@gthompsnWRF 
Greg,
Any way to shorten the title?
Fix for MP=8,28: if input moist constituent exists, then ensure associated number concentration does

**Comment by gthompsnWRF** [comment]
@davegill yes, I did not know why the list of all files/changes was massive compared to my single file change. I must have made mistake with branching from develop? Still too new with GitHub clearly.

**Comment by davegill** [comment]
@gthompsnWRF 
Greg,
You are only changing one file.  Do it all again
```
git clone https://github.com/wrf-model/WRF WRF_again
cd WRF_again
git remote add dave https://github.com/davegill/WRF
git checkout release-v4.1
git checkout -b mp_8_28_again
```
Swap in your new mods to dyn_em/module_initialize_real.F
```
git add dyn_em/module_initialize_real.F
git commit -m "yet again"
git push -u dave  mp_8_28_again
```
Do another PR. Copy your title and PR message from the old to the new. Close the old PR.

**Pull request closed without merging**
