### PR TITLE
last MYNN-EDMF updates for v4.6

### PR DESCRIPTION
**Pull request by joeolson42**
This commit contains the final tuning of the MYNN for RRFSv1.

TYPE: bug fix + tuning

KEYWORDS: MYNN EDMF

SOURCE: Joseph Olson (NOAA-GSL)

DESCRIPTION OF CHANGES:
Problems:
1) overly diminished TKE in stable PBL - always dropping to the lower limit
2) negative mass flux area fractions found (rarely) with activation criteria change from flt to fltv.
3) edmf diagnostics erroneously included rho.

Solution:
1) retuning of mixing lengths and stability function for momentum - mostly just limit changes.
2) check for mf transfer of heat out of the lowest layer was modified
3) removed rho.

LIST OF MODIFIED FILES: 
phys/module_bl_mynn.F

TESTS CONDUCTED: 
1. Do mods fix problem? How can that be demonstrated, and was that test conducted?
2. Are the Jenkins tests all passing?

RELEASE NOTE: Include a stand-alone message suitable for the inclusion in the minor and annual releases. A publication citation is appropriate.

### CODE REVIEW

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by weiwangncar — DISMISSED** [review]

**Comment by dudhia** [comment]
There are changes in PXLSM that may be unintended. Please check.

**Comment by islas** [comment]
@weiwangncar Ideally the redone PR would use @coastwx 's branch (`PXLSM_LCZ61_II`) and merge that into `release-v4.6.0`, but as the branch was deleted I think your approach is sufficient.

**Comment by weiwangncar** [comment]
@islas Thanks! 
@dudhia @smileMchen Can you approve PR-2035 so that we can move to merge this PR? Thanks!

**Review by smileMchen — DISMISSED** [review]

**Review by dudhia — DISMISSED** [review]

**Comment by weiwangncar** [comment]
@islas I have merged PR-2035 to the release-v4.6.0, but this PR would still show the differences from those files. Did I do something wrong?

**Comment by islas** [comment]
@weiwangncar I'm not entirely sure but I suspect it has something to do the complex history and squash merges. This [comment](https://stackoverflow.com/questions/16306012/github-pull-request-showing-commits-that-are-already-in-target-branch#comment114580372_46782679) on stackoverflow leads me to suspect that. 

I think it comes down to GitHub doesn't realize that the edits are "more or less the same" since they are all actually different commits under the hood (different SHAs). I would hope that this at least would lead to a merge conflict but it seems like that isn't showing up. 

A potential solution would be to rebase the incoming changes to the `release-v4.6.0` branch, but this type of solution should be used with caution when done in a PR and ideally do everything to avoid this situation.

**Comment by weiwangncar** [comment]
@islas Thanks for the comments. I checked out Joe's branch, and diff'ed the three routines, and they are identical. Would it be safe to just merge this PR then?

**Comment by islas** [comment]
It should be safe.

**Comment by weiwangncar** [comment]
@islas Thanks! Does changing base void the PR approval?
@dudhia @smileMchen Can you again approve this PR?

**Comment by dudhia** [comment]
I am still seeing those PX changes.

**Comment by weiwangncar** [comment]
@dudhia I know. But the PXLSM change is already in release-v4.6.0 branch. Not sure why (see comments above by Anthony and me).

**Comment by dudhia** [comment]
Still waiting for it to pass.

**Comment by joeolson42** [comment]
It's bizarre. Let me know if you want me to do anything on my side.

**Pull request closed without merging**
