### PR TITLE
NSSL Microphysics update (Release v4.3)

### PR DESCRIPTION
**Pull request by MicroTed**
NSSL Microphysics update (April 2021)

TYPE: Bug fixes and minor enhancements

KEYWORDS: mp_physics 17/18 (NSSL 2-moment), CCN regeneration (mp_physics 18)

SOURCE: Ted Mansell (NOAA/NSSL)

DESCRIPTION OF CHANGES:

Fixes:
 - Fall speed air density factor limited to air density of 0.05 (for very high model top) to mitigate excessive fall speeds
 - Fixed issue of spurious creation of large concentrations of very small droplets and transient large condensation 
   (also increased minimum droplet size) (mp_physics = 17/18)
 - Fixed issue of negligible "seed" values of graupel from Bigg freezing at relatively high temperatures (thanks to 
    S. Lasher-Trapp)
 - Minor bug fix in effective radius calculation of snow.  (thanks to T. Iguchi)

Updates:
 - Enabled regeneration of CCN by droplet evaporation and background restore (default time constant of 3600s), only 
    for mp_physics = 18 (can be disabled by setting restoreccn=.false.)
 - Updated the routine that handles single-moment variables on the first time step. This sets a higher threshold for 
    meaningful mixing ratios and sets a more realistic droplet concentration (also activating CCN as needed).
 - Enabled radar reflectivity from cloud ice (new formulation) ( idbzci = 1 )
 - Added internal option for ice crystal nucleation by DeMott et al. (2010, PNAS) (inucopt=4)
 - Allow greater fraction of hail to melt in one time step
 - Reduced minimum number concentration from 1e-4 to 1e-8 (based on CAPS input)
 - Increased resolution of lookup table for incomplete gamma functions

IMPACT: 
For option mp_physics=18, the previous lack of CCN regeneration could cause artificially low droplet number (and 
more rapid rain formation) in secondary convection that entrains outflow (downdraft air) from primary convection. 
The new behavior adds immediate restoration of CCN when droplets evaporate (1 nucleus per droplet) along with a 
slow restore (time constant of 1hr) in air that has no hydrometeor content.

LIST OF MODIFIED FILES:
  module_mp_nssl_2mom.F
  module_physics_init.F

TESTS CONDUCTED: 
1. Gives very similar simulation results
2. Jenkins testing is OK

RELEASE NOTE: NSSL physics updates: enabled regeneration of CCN by droplet evaporation and by nudged restore in cloud-free air (mp_physics=18; default 1-hr time constant for nudging), enabled radar reflectivity from cloud ice, added internal option for ice crystal nucleation by DeMott et al. (2010, PNAS), allow greater fraction of hail to melt in one time step, reduced minimum number concentration (based on CAPS input), and increased resolution of lookup table for incomplete gamma functions. A few bug fixes were added: limit fall speed air density factor for high model lids, fixed issue of spurious creation of large concentrations of very small droplets and transient large condensation, fixed issue of negligible "seed" values of graupel, and fixed effective radius calculation of snow.

### CODE REVIEW

**Comment by MicroTed** [comment]
Previous PR #1480 can be deleted -- forgot to select correct branch

**Comment by MicroTed** [comment]
Jenkins test results:

  Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           18
    Number of Builds       : 48           46
    Number of Simulations  : 163           161        0
    Number of Comparisons  : 103           102        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by davegill** [comment]
@weiwangncar @dudhia
Folks,
The single line change in physics init is just to restrict a USE association with an ONLY clause. Everything else is entirely internal to the NSSL MP scheme. There are no changes to the Registry, no mods to the interface from the MP driver. I think that we can take this entire thing AS-IS for v43.

The PR message is well put together. The target is the correct branch. There are no conflicts.

**Comment by dudhia** [comment]
Maybe just need a bit more idea of diffs expected because it is a lot of
changes.

**Comment by dudhia** [comment]
KEYWORDS could include the mp_physics options affected by this.

**Comment by weiwangncar** [comment]
@MicroTed Thanks for the comment. Do you think you could add an 'impact' comment in the PR message?

**Comment by MicroTed** [comment]
@weiwangncar 
Sure. Impact comment added.

**Review by weiwangncar — APPROVED** [review]

**Comment by davegill** [comment]
@MicroTed 
> Added internal namelist for easier access to internal variables for development/testing and easier setup for ensemble 
    microphysics diversity (namelist read is disabled by default)

Is this mostly for your use? If so, OK. If this is for others, then this is a bit dicey.

**Comment by MicroTed** [comment]
@davegill 

> Is this mostly for your use? If so, OK. If this is for others, then this is a bit dicey.

You're not wrong about that. It is something I use, of course. My thinking for including it in a release is that I've either been asked about parameters or seen results where someone has changed parameters, so this would be a method for such tinkerers to do that easily without having to recompile. (It also prints the values to namelist.output to provide a record of settings.) It is also disabled by default, but I'll remove the mention from the update list, so that only those who poke into the code will discover that functionality.

**Comment by davegill** [comment]
@weiwangncar @dudhia 
Folks,
This is ready for a review

**Comment by davegill** [comment]
@weiwangncar @dudhia 
Wei,
Sorry, you have reviewed this PR.

Jimy, 
Let Ted know if he has sufficiently addressed your issues.

**Comment by dudhia** [comment]
I am fine with this.

**Comment by kkeene44** [comment]
@MicroTed 
Can you let me know the affiliations for S. Lasher-Trapp and T. Iguchi? We'd like to acknowledge all of you in our release notes. Thanks!

**Comment by kkeene44** [comment]
@MicroTed 
Thank you for the quick response!

**Pull request merged**
