### PR TITLE
add salinity effect in sfclay and sfclayrev

### PR DESCRIPTION
**Pull request by weiwangncar**
TYPE: enhancement

KEYWORDS: salinity effect, saturation vapor pressure, ocean

SOURCE: internal

DESCRIPTION OF CHANGES:
Problem:
The salinity effect of ocean is not considered when computing saturation vapor pressure.

Solution:
Add the effect in the MM5 and revised MM5 surface layer schemes. The 0.98 factor is an approximation for salinity of 34 part per thousands, and applied for saturation specific humidity. Here the approximation is applied to saturation mixing ratio. The lakemask field is used to exclude this effect from inland lakes.

LIST OF MODIFIED FILES: 
M     phys/module_sf_sfclay.F
M     phys/module_sf_sfclayrev.F
M     phys/module_surface_driver.F

TESTS CONDUCTED: 
1. Tested in many tropical cyclone cases.
2. The Jenkins tests are all passing.

RELEASE NOTE: Add salinity effect in MM5 and revised MM5 surface layer schemes. The effect is lower the saturation vapor pressure over ocean by about 2%.

### CODE REVIEW

**Comment by dudhia** [comment]
Not doing sfclayrev?
Could 0.98 be made a parameter?
Should this be a switch to allow easy comparisons between versions?

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by dudhia — DISMISSED** [review]
I will approve it, but maybe we should have it as a switch and a parameter as in my comments.

**Comment by weiwangncar** [comment]
@dudhia To reply to your earlier comments: 1. I would like to add this to sfclayrev through shared physics. 2. 0.98 is the only parameter I know, and cited in several document and papers. 3. I'm trying to avoid adding namelist, unless it is absolutely necessary.

**Review by smileMchen — DISMISSED** [review]

**Comment by dudhia** [comment]
OK, so the sfclayrev in shared physics will have this?
I was suggesting 0.98 to be a parameter because then it can have a variable name too which could be descriptive.

**Review by dudhia — APPROVED** [review]

**Comment by weiwangncar** [comment]
@smileMchen Can you approve this PR one more time? Thanks.

**Comment by weiwangncar** [comment]
> @smileMchen Can you approve this PR one more time? Thanks.

@smileMchen Can you help?

**Review by smileMchen — APPROVED** [review]

**Comment by smileMchen** [comment]
@weiwangncar 
I agree that we should be cautious not to add too many namelist options.

**Pull request merged**
