### PR TITLE
New DA ep_format option to read in ensemble perturbation (ep)

### PR DESCRIPTION
**Pull request by jamiebresch**
TYPE: new feature

KEYWORDS: WRFDA, ep, ep_format

SOURCE: Jamie Bresch (NCAR)

DESCRIPTION OF CHANGES:

ep_format=1:  (default) original format, double precision, each ep file is for one variable and one member, as the output from the current gen_be_ep2.
ep_format=11: same as ep_format=1 except data are in single precision
ep_format=2:  single precision, each ep file is for one variable and all members
ep_format=3:  single precision, each ep file is for one variable and all members but on decomposed patch domain

No impact on existing ep reading results.
New WRFDA code should work without any changes from the user when ep files are generated using the existing very inefficient gen_be_ep2 program.
New utility for generating ep in new formats (ep_format=1, 11, 2, 3 through namelist option) is proposed in PR #912.

LIST OF MODIFIED FILES:

modified:   Registry/registry.var
modified:   var/build/depend.txt
modified:   var/da/da_main/da_solve.inc
modified:   var/da/da_main/da_wrfvar_top.f90
modified:   var/da/da_setup_structures/da_setup_flow_predictors.inc
new file:   var/da/da_setup_structures/da_setup_flow_predictors_ep_format2.inc
new file:   var/da/da_setup_structures/da_setup_flow_predictors_ep_format3.inc
modified:   var/da/da_setup_structures/da_setup_structures.f90

TESTS CONDUCTED:

A case with 80-member 414x324x50 running with nproc=216.
The ep reading time:

| EP Format     | Time (s)  |   
| -------------:|----------:|
|     1         |   52.0    |
|     11        |   45.0    |
|     2         |   24.0    |
|     3         |    0.3    |

ep_format=1   ~ 52 sec
ep_format=11  ~ 45 sec
ep_format=2   ~ 24 sec
ep_format=3   ~ 0.3 sec 
Another major benefit to ep_format=3 is the reduced memory requirement.
New ep_format=11,2,3 produce identical analysis results.

RELEASE NOTE: New DA ep_format option to read in ensemble perturbation (ep) generated by existing gen_be_ep2 and new gen_be_v3 utilities.

### CODE REVIEW

**Comment by jjguerrette** [comment]
Jamie, this is a great update to have in develop.  Is it possible for you to also include corresponding writers for these different formats (i.e. replacements/alternatives to the current gen_be_ep2.inc)?

**Comment by liujake** [comment]
@jjguerrette this one shall be now ready to merge.

**Comment by jjguerrette** [comment]
@jamiebresch, does gen_be_v3 (https://github.com/wrf-model/WRF/pull/912) also write these new formats of ensemble perturbations?

**Comment by jamiebresch** [comment]
> @jamiebresch, does gen_be_v3 (#912) also write these new formats of ensemble perturbations?

Yes, as implied by messages in both PR#900 and PR#912.
ep_format setting is described in var/gen_be_v3/README.gen_be_v3

**Comment by jjguerrette** [comment]
Thank you for updating the PR message here!

**Pull request merged**
