### PR TITLE
add defaults for armclang/armflang; permute loops for better mem acce…

### PR DESCRIPTION
**Pull request by juntangc**
Purpose: Add compiler defaults for armclang/armflang; various optimization for open source compiler (for better memory access and vectorization)

TYPE: enhancement

KEYWORDS: compiler default for Armflang

SOURCE: Jun Tang, Amazon

DESCRIPTION OF CHANGES:
Problem:
Add compile defaults for Arm Compiler for Linux. Various code changes to allow better memory access and vectorization.

Solution:
Adjust loop order and break down larger loop to allow part of the loop to be vectorized by GCC.

ISSUE: N/A

LIST OF MODIFIED FILES: 
M       arch/configure.defaults
M       dyn_em/module_advect_em.F
M       dyn_em/module_big_step_utilities_em.F
M       dyn_em/module_em.F
M       phys/module_ra_rrtmg_lw.F
M       phys/module_ra_rrtmg_sw.F
M       phys/module_radiation_driver.F

TESTS CONDUCTED: 
1. Do mods fix problem? How can that be demonstrated, and was that test conducted?
2. Are the Jenkins tests all passing?
Yes. I have tested the latest Arm compiler with the default configuration. I have also tested the code patches and the output model are identical as before; performance improvement for GCC with the patch 2 - 3%.

RELEASE NOTE: N/A

### CODE REVIEW

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by islas** [comment]
@juntangc Could you break this out into two pull requests that each come in from an aptly named branch (not from `develop` in your fork).

**Comment by juntangc** [comment]
sure.

**Comment by juntangc** [comment]
split this PR into two separate PRs.

**Comment by juntangc** [comment]
links to the new PRs -
https://github.com/wrf-model/WRF/pull/1888
https://github.com/wrf-model/WRF/pull/1889

**Pull request closed without merging**
