### PR TITLE
bring local Noah-MP snowmelt (QMELT) to output & add accumulated snowmelt output

### PR DESCRIPTION
**Pull request by cenlinhe**
Bring local snowmelt variable in Noah-MP to output variable and add accumulated snowmelt output in diagnostics

TYPE: enhancement

KEYWORDS: snowmelt, Noah-MP, output

SOURCE: Cenlin He (NCAR)

DESCRIPTION OF CHANGES:
Add two new output variables for Noah-MP package for snowmelt

LIST OF MODIFIED FILES: list of changed files (use `git diff --name-status master` to get formatted list)
M       Registry/Registry.EM_COMMON
M       Registry/registry.noahmp
M       dyn_em/module_first_rk_step_part1.F
M       phys/module_diag_misc.F
M       phys/module_diagnostics_driver.F
M       phys/module_surface_driver.F
M       phys/noahmp

### CODE REVIEW

**Comment by cenlinhe** [comment]
@weiwangncar @dudhia I used gfortran and "configure -d" and the compilation did not show any problems. Not sure why it did not pass the regression test.

**Comment by cenlinhe** [comment]
Just checked the .zip log file Wei sent to me and it shows the following:
"
------------------------------------------------------------------------------
Error Error Error NoahMP submodule files not populating WRF directories
------------------------------------------------------------------------------
 "

**Comment by weiwangncar** [comment]
@cenlinhe It's possible that somehow the tests failed to access the noahmp submodule. Can you first make sure that the submodule this particular PR needs can be correctly pulled. If that is the case, perhaps you can wait a while, try make a change to the PR (remove a space, a line, etc.) and see if a new Jenkins test will work.

**Comment by cenlinhe** [comment]
I will try a new PR instead.

**Pull request closed without merging**
