### PR TITLE
Update HONO, TERP, and CO2 emissions

### PR DESCRIPTION
**Pull request by rschwant**
TYPE: enhancement

KEYWORDS: anthropogenic emissions

SOURCE: Rebecca Schwantes (CIRES/NOAA CSL)

DESCRIPTION OF CHANGES:
Update code to add HONO, TERP, and CO2 anthropogenic emissions for RACM mechanisms.

Problem:
HONO, TERP, and CO2 anthropogenic emissions were not automatically pulled into the RACM mechanisms.

Solution:
Added some if statements such that if HONO, TERP, and CO2 are in the anthropogenic emission file and hono, 
api, lim, and co2 are chemical species in the selected RACM mechanism, then the HONO, TERP, and CO2 
anthropogenic emissions would be included in the simulation.

LIST OF MODIFIED FILES: 
M Registry/registry.chem
M chem/module_emissions_anthropogenics.F

TESTS CONDUCTED: 
1. The modifications fix the problem of missing (but available) anthropogenic emissions.
2.  jenkins tests are all passing.
3. Attached are some plots that show that with the updates HONO, CO2, API, and LIM now all increase in regions impacted by anthropogenic emissions (namely you can clearly see increases in cities) compared to the default case.

[anthropogenic_emission_quick_QC.pdf](https://github.com/wrf-model/WRF/files/7900930/anthropogenic_emission_quick_QC.pdf)

RELEASE NOTE: Previously, HONO, TERP, and CO2 were not automatically pulled into the RACM mechanisms even when they were in the anthropogenic emissions file. This has been fixed.

### CODE REVIEW

**Comment by davegill** [comment]
@rschwant 
Rebecca,
Is there a simple before vs after plot, or before vs after printout that shows the availability and usage of these anthropogenic emissions?

**Comment by rschwant** [comment]
Good question. I was comparing to an older version, but I'm sure you want a clean compare with the current develop branch. Let me run this quickly and I'll make you a cleaner plot hopefully by tomorrow. Thanks!

**Comment by davegill** [comment]
@rschwant 
Rebecca,
Take a look at the PR message for https://github.com/wrf-model/WRF/pull/1625
We just want something SIMPLE that we can point to that says "ah ha, it does do what was said".

**Comment by rschwant** [comment]
I attached some plots that show that with the updates HONO, CO2, API, and LIM now all increase in regions impacted by anthropogenic emissions (namely you can clearly see increases in cities) compared to the default case. Let me know if you have any questions. Thanks!

[anthropogenic_emission_quick_QC.pdf](https://github.com/wrf-model/WRF/files/7900930/anthropogenic_emission_quick_QC.pdf)

**Review by jordanschnell — APPROVED** [review]
Approved by /chem

**Pull request merged**
