### PR TITLE
Fix runtime error when using sf_surface_mosaic = 1 with use_wudapt_lcz = 0

### LINKED ISSUE #1633: Segfault with sf_surface_mosaic in WRF4.3.1.
**Describe the bug**
- Error when using `sf_surface_mosaic = 1`.
- There is no error if `sf_surface_mosaic = 0`.

**To Reproduce**
1. Use compiler and version: ifort version 2021.3.0
2. Use namelist options
```
 sf_surface_physics = 2 2 ,
 sf_surface_mosaic = 1,
```
3. Output is '....'
```
forrtl: severe (408): fort: (2): Subscript #1 of the array ZR_TBL has value 5 which is greater than the upper bound of 3

Image              PC                Routine            Line        Source
wrf.exe            000000000CEB4CEF  Unknown               Unknown  Unknown
wrf.exe            000000000494070F  module_sf_urban_m        1875  module_sf_urban.f90
wrf.exe            000000000492E47E  module_sf_urban_m         607  module_sf_urban.f90
wrf.exe            000000000BAEC8B5  module_sf_noahdrv        3653  module_sf_noahdrv.f90
wrf.exe            000000000855B5CD  module_surface_dr        2477  module_surface_driver.f90
wrf.exe            00000000051BE069  module_first_rk_s         380  module_first_rk_step_part1.f90
wrf.exe            000000000401F69C  solve_em_                 883  solve_em.f90
wrf.exe            0000000003906047  solve_interface_          122  solve_interface.f90
wrf.exe            00000000005B447E  module_integrate_         329  module_integrate.f90
wrf.exe            0000000000414478  module_wrf_top_mp         326  module_wrf_top.f90
wrf.exe            00000000004138A5  MAIN__                     29  wrf.f90
wrf.exe            0000000000413852  Unknown               Unknown  Unknown
libc-2.26.so       000014D71E3E234A  __libc_start_main     Unknown  Unknown
wrf.exe            000000000041376A  Unknown               Unknown  Unknown
```

**Expected behavior**
- There should be no error.

**Attachments**
- Namelist: https://pastebin.com/uGb4eutB

**Additional context**
I think the error is due to #1419, particularly this change:
- Before (line 3604): https://github.com/wrf-model/WRF/blob/236c1de421675961fc975d3f77d695f07c79b4e8/phys/module_sf_noahdrv.F#L3601-L3607
- After (line 3632): https://github.com/wrf-model/WRF/blob/c2f9b9904450b515a6c050d454058c5f92ed96f6/phys/module_sf_noahdrv.F#L3624-L3634

### PR DESCRIPTION
**Pull request by epn09**
TYPE: bug fix

KEYWORDS: noah mosaic, wudapt

SOURCE: Do Ngoc Khanh (Tokyo Institute of Technology)

DESCRIPTION OF CHANGES:
Fix runtime error when using sf_surface_mosaic = 1 with use_wudapt_lcz = 0.

Problem:
Segmentation fault occurs when running the model using sf_surface_mosaic = 1 with use_wudapt_lcz = 0 as described in detail in #1633. 

Solution:
The code now checks for use_wudapt_lcz and uses different code to define urban categories in lsm_mosaic routine in module_sf_noahdrv.F.

ISSUE: 
Fixes #1633 

LIST OF MODIFIED FILES:
M       dyn_em/module_first_rk_step_part1.F
M       phys/module_sf_noahdrv.F
M       phys/module_surface_driver.F

TESTS CONDUCTED: 
1. When use_wudapt_lcz = 1: bit-by-bit identical output before and after modification.
2. When use_wudapt_lcz = 0: Segmentation fault is fixed.
3. The Jenkins tests are all passing.

RELEASE NOTE: Fix runtime error when using sf_surface_mosaic = 1 with use_wudapt_lcz = 0.

### CODE REVIEW

**Comment by weiwangncar** [comment]
@epn09 Thank you for making this PR. Have you looked how the non-mosaic version of Noah LSM handles the urban categories? That code did not need to check the namelist option use_wudapt_lcz and it appears to work fine.

**Comment by epn09** [comment]
@weiwangncar In the non-mosaic version of Noah LSM, `IVGTYP` is constant and assignment of `FRC_URB2D` is done in `urban_var_init` in module_sf_urban.F (https://github.com/wrf-model/WRF/blob/master/phys/module_sf_urban.F#L2686) and use_wudapt_lcz is checked there.

**Comment by weiwangncar** [comment]
@epn09 This probably makes sense. Thanks. Would you be interested in testing an urban option using mosaic Noah LSM?

**Comment by epn09** [comment]
@weiwangncar I have run the mosaic Noah LSM with single layer UCM urban option (using the bug-fixed code) for a 3-day run. Comparing with the run without mosaic option, the result looks reasonable to me.

**Comment by weiwangncar** [comment]
@epn09 Thank you for doing that test.

**Review by weiwangncar — DISMISSED** [review]

**Comment by davegill** [comment]
@weiwangncar 
Wei,
I swapped the base branch from master to develop, and that means github tossed out your review. Would you do your review again please?

**Review by weiwangncar — APPROVED** [review]

**Review by dudhia — APPROVED** [review]

**Review by weiwangncar — APPROVED** [review]

**Comment by pvahmanilbl** [comment]
@davegill and @weiwangncar I hope this is the right place to raise this issue: I have been getting segmentation fault error:
Program received signal SIGSEGV: Segmentation fault - invalid memory reference
when I use  
SF_SURFACE_MOSAIC  = 1
This happens when the radiation scheme is called for the first time (6 min in the simulation). I checked and the fix above is already in the WRFv44 I am using. 

I am using 
use_wudapt_lcz=1
num_land_cat=61
sf_urban_physics=1
When I remove SF_SURFACE_MOSAIC=1 there are no issues. I would really appreciate it if you can help me with this!

**Comment by kkeene44** [comment]
@pvahmanilbl 
The subject for this PR is specific to when use_wudapt_lcz=0. I just want to check that you're actually using =1.

**Comment by pvahmanilbl** [comment]
@kkeene44  I am using use_wudapt_lcz=1. I have not tried it use_wudapt_lcz=0. My configuration works with non-mosaic (SF_SURFACE_MOSAIC=0) option but when I use mosaic (SF_SURFACE_MOSAIC=1) it crashes with seg fault. I posted here since this is the closest I found to the issue I am facing.

**Comment by kkeene44** [comment]
@pvahmanilbl 
I ran a test case with those settings and I'm able to run without problems for a case using sf_surface_mosaic=1 and use_wudapt_lcz=1. This must be related to your specific case. Can you post your issue to the [WRF & MPAS-A Support Forum](https://forum.mmm.ucar.edu/) so we can look into the problem there? When you do, please attach your namelist.input file, and if you'd like to share larger files (e.g., wrfinput, wrfbdy), take a look at the home page of the forum for instructions on sharing large files. Thanks!

**Comment by pvahmanilbl** [comment]
@kkeene44 thank you so much for your response! (sorry I am being slow; I was on paternity leave)
I will try the Forum one more time but can I ask a quick question? when you run real.exe with the mosaic option do you get the new variables (e.g., LANDUSEF2, MOSAIC_CAT_INDEX, etc) in wrfinput **with values** in them? for me, all of these new variables in wrfinput have only zeros.

**Comment by pvahmanilbl** [comment]
@kkeene44 thanks so much for your response! I was trying to use CONUS physics and it didn't work with MOSAIC until I used:
>  sf_sfclay_physics                   = 1,       1,       1,       1,
>  bl_pbl_physics                      = 1,       1,       1,       1,
and it worked!

**Pull request merged**
