### PR TITLE
Add number of tasks to WRF history global attributes

### PR DESCRIPTION
**Pull request by davegill**
TYPE: enhancement

KEYWORDS: ntasks, metadata, global attributes

SOURCE: internal

DESCRIPTION OF CHANGES:
In the global attributes for the WRF history stream, include the number of total
tasks, and the number of tasks in both the X and Y directions.

LIST OF MODIFIED FILES:
modified:   share/output_wrf.F

TESTS CONDUCTED:
1. Jenkins PASS
2. Example of new metadata in WRF history file:

```
> mpirun -np 1 wrf.exe
 starting wrf task            0  of            1

> ncdump wrfo* | grep NTASKS
		:NTASKS_X = 1 ;
		:NTASKS_Y = 1 ;
		:NTASKS = 1 ;
```

```
> mpirun -np 3 wrf.exe
 starting wrf task            1  of            3
 starting wrf task            2  of            3
 starting wrf task            0  of            3

> ncdump wrfo* | grep NTASKS
		:NTASKS_X = 1 ;
		:NTASKS_Y = 3 ;
		:NTASKS = 3 ;
```

### CODE REVIEW

**Comment by davegill** [comment]
@weiwangncar 
Wei,
Is this acceptable? Please review.

**Comment by davegill** [comment]
@weiwangncar 
I get all PASS from Jenkins:
```
    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 10           10
    Number of Builds       : 23           23
    Number of Simulations  : 140           140        0
    Number of Comparisons  : 89           89        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```

**Comment by weiwangncar** [comment]
@davegill This looks good. Thanks! Can we rename the last one, NTASKS, to TOTAL_NTASKS? Maybe it is not necessary...

**Comment by davegill** [comment]
@weiwangncar 
> Can we rename the last one, NTASKS, to TOTAL_NTASKS?

Wei,
Good idea. The new name is now "NTASKS_TOTAL"

**Pull request merged**
