### PR TITLE
Fix non-initialized mixing ratio in p/z-lev interp

### PR DESCRIPTION
**Pull request by jesusff**
Fix non-initialized 3D moisture field in pressure- and height-level diagnostic interpolation

TYPE: bug fix

KEYWORDS: mixing ratio, interpolation, pressure level, height level, missing value

SOURCE: Jesus Fernandez, Andrés Simón-Moral and Josipa Milovac  (Instituto de Física de Cantabria, CSIC-Universidad de Cantabria, Spain)

DESCRIPTION OF CHANGES:
Problem:
3D interpolated moisture fields show strange patterns. E.g. for 1000 hPa interpolation (see northern part of the domain):
hus1000bug

The mixing ratio field is not being initialized in the interpolation routine. This leads to no missing values below ground and values from previous time steps filling these areas. Thanks to @AndresSimon and @yoselita for spotting the problem and running the tests.

Solution:
The mixing ratio has been initialized to missing values, as for the rest of variables.

LIST OF MODIFIED FILES:
```
M       phys/module_diag_pld.F
M       phys/module_diag_zld.F
```

TESTS CONDUCTED: 
1. Do mods fix problem? How can that be demonstrated, and was that test conducted?
The mods fix the problem. I.e the areas below ground are now filled with missing values and the rest of the field is identical to the current version.

2. The Jenkins tests are all passing.

RELEASE NOTE: Fix non-initialized 3D moisture field in pressure- and height-level diagnostic interpolation.

### CODE REVIEW

**Comment by dudhia** [comment]
Thanks, this looks like a good bug-fix.

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@jesusff Thanks for the fix. Can you update the image file? It cannot be found.

**Comment by jesusff** [comment]
yes, sorry, it should be visible now

**Comment by weiwangncar** [comment]
@jesusff Thanks! Do you happen to have a plot after the fix?

**Comment by yoselita** [comment]
We rerun 2 test simulations without and with the fix. Here is the figure before (left) and after (right) the fix for the Q_PL variable from the wrfpress file: 
q_pl_before after

**Comment by weiwangncar** [comment]
@yoselita Thanks for the graphics.

**Review by weiwangncar — APPROVED** [review]

**Review by dudhia — APPROVED** [review]

**Comment by weiwangncar** [comment]
@AndresSimon Can you spell out your name? 
@yoselita and @AndesSimon If your affiliation is different from that if Jesus Fernandez, let us know so that we can properly acknowledge your contribution.

**Comment by AndresSimon** [comment]
@weiwangncar my name is:
Andrés Simón-Moral

My affiliation is the same as Jesús Fernández

**Comment by yoselita** [comment]
Thank you @weiwangncar. May affiliation is the same as Jesús Fernández as well.

**Pull request merged**
