### PR TITLE
Fix build and run of ARW caused Fire Fuel Model mods

### PR DESCRIPTION
**Pull request by davegill**
TYPE: bug fix

KEYWORDS: Fire, fuel model, GNU

SOURCE: internal

DESCRIPTION OF CHANGES:
Problem:
1. Cannot build with GNU
2. Seg-faults with standard non-fire runs.

These problems occurred with commit 53d63b053fcb, PR #792 "Fuel moisture model".

Solution:
1. The use of LOGICALs in the option choices for some of the fire variables
is inapropriate for eventual usage when those namelist options are part of
a Registry package statement. The WRF code assumes that the packages are
INTEGER values - not LOGICAL.
2. The number of elements in a few DATA statements needed to be increased by 1.
The "no fuel" entry (currently set to zero) is defined in column 14 of the DATA statement.

LIST OF MODIFIED FILES:
modified:   Registry/registry.fire
modified:   phys/module_fr_fire_phys.F
modified:   share/module_check_a_mundo.F

TESTS CONDUCTED:
 - [x] Without mods, code does not build; with mods, code builds.
 - [x] Without mods, code seg faults; with mods, non-fire code runs.

### CODE REVIEW

**Comment by davegill** [comment]
@janmandel
Jan,
Please take a look at this mods

**Comment by janmandel** [comment]
@davegill
I will change fmoist_run and fmoist_interp to integer everywhere and submit a new PR as a bug fix based on 975f0c6e994985d99ac3cbbf4a458ee0bca4c463.

**Comment by davegill** [comment]
@janmandel 
This is ALREADY merged. The integer vs logical issue is handled.

**Comment by janmandel** [comment]
@davegill
I see your changes in share/module_check_a_mundo.F that patch this.
Do you want me to just let it be?

**Comment by janmandel** [comment]
OK I'll let it be.

**Comment by janmandel** [comment]
@davegill 
OK, will let it be.
Thanks for fixing the DATA one column short. I see it caused copying uninitialized memory later on.

**Pull request merged**
