### PR TITLE
Memory cleanup for urban physics

### PR DESCRIPTION
**Pull request by smileMchen**
TYPE: bug fix

KEYWORDS: urban physics, clean memory

SOURCE: internal

DESCRIPTION OF CHANGES: 
A few variables associated with urban surface characteristics are declared in Registry and specified in REAL. However, these variables are never used in any urban physics module. This PR removes these variables from Registry and modifies REAL correspondingly:
FAD0_URB2D
FAD135_URB2D
FAD45_URB2D
PAD_URB2D
FAD90_URB2D
RAD_URB2D
CAR_URB2D
H2W_URB2D
SVF_URB2D
Z0S_URB2D
Z0R_URB2D
Z0M_URB2D
ZDS_URB2D
ZDM_URB2D
ZDR_URB2D

LIST OF MODIFIED FILES:
M       Registry/Registry.EM_COMMON
M       dyn_em/module_initialize_real.F

TESTS CONDUCTED:
 -[x] Small GNU-only regression test passed on cheyenne; serial, openmp, mpi; all builds, single test case per build; bit for bit where appropriate

### CODE REVIEW

**Comment by weiwangncar** [comment]
@smileMchen Can you test the model with and without urban physics option 1 before and after this change? Both should produce identical results. We can also check the memory usage (allocated).

**Comment by smileMchen** [comment]
@weiwangncar 
Wei,
 I have run four cases with and without the urban option (sf_urban_physics=0 and 1) using the original and revised codes. The changes in Registry and REAL have no impact on the results.

**Comment by weiwangncar** [comment]
@barlage Can you review this PR and see if more needs to be done?

**Comment by dudhia** [comment]
Have these tests used the NUDAPT data?

**Comment by smileMchen** [comment]
@dudhia 
Jimy,
I run the tests using NLCD (derived from NUDAPT) as input.

**Comment by weiwangncar** [comment]
@smileMchen Will this run fill the *_URB2D fields?

**Comment by dudhia** [comment]
Ming is also removing unused fields from realonly package list

**Pull request merged**
