### PR TITLE
Remove ASCII chars outside of 32-127 range

### PR DESCRIPTION
**Pull request by davegill**
TYPE: text only

KEYWORDS: ASCII

SOURCE: internal

DESCRIPTION OF CHANGES:
Remove instances of non Fortran character set entries in the WRF source. All of these changes are comments.
1. The \textemdash becomes "-"
2. The non-American keyboard letters become a, e, i, o, u without the dots or accents
3. The superscript 2 is removed, and replaced by a regular 2: W/m2
4. Extra DOS carriage returns are removed (likely when the files come from windows machines)
5. The degree symbol was removed
6. An extra handy vim command was added

LIST OF MODIFIED FILES:
	modified:   chem/chemics_init.F
	modified:   chem/module_mosaic_newnucb.F
	modified:   hydro/Routing/module_gw_gw2d.F
	modified:   phys/module_fr_fire_phys.F
	modified:   phys/module_gocart_coupling.F
	modified:   phys/module_mp_fast_sbm.F
	modified:   phys/module_mp_gsfcgce_4ice_nuwrf.F
	modified:   phys/module_mp_ntu.F
	modified:   phys/module_ra_eclipse.F
	modified:   phys/module_sf_bep_bem.F
	modified:   phys/module_sf_noahmplsm.F
	modified:   share/module_check_a_mundo.F
	modified:   tools/non_ascii_finder.F

TESTS CONDUCTED: 
1. Text only, no changes to compiled code
2. Jenkins is all PASS

### CODE REVIEW

**Comment by davegill** [comment]
@weiwangncar @kkeene44 @smileMchen @dudhia 
Small changes to the source code, but all of the changes are to comments - so no impact.

**Comment by davegill** [comment]
@louiswicker
Does this fix the carriage return problem you saw?

**Comment by davegill** [comment]
jenkins
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: c86ae1d6f5ba579d0815c23ff0c25576ffd84ac2, requested by: davegill for PR: https://github.com/wrf-model/WRF/pull/1445. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           18
    Number of Builds       : 48           46
    Number of Simulations  : 163           161        0
    Number of Comparisons  : 103           102        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```

**Comment by weiwangncar** [comment]
@davegill You may want to wait for tzuchin's PR#1441 to go through first. I will approve that PR now.

**Comment by davegill** [comment]
closed due to conflicts, argh

**Pull request closed without merging**
