### PR TITLE
Update of P3 module

### PR DESCRIPTION
**Pull request by hmorrison100**
TYPE: enhancement

KEYWORDS: P3, microphysics

SOURCE: Hugh Morrison (NCAR)

DESCRIPTION OF CHANGES:
Very minor changes only.
1. code comments
2. removal of debug check (non-answer-changing)
3. scaling of rain and ice evaporation/sublimation when the mass change from evap/sub is 
limited to prevent over- or under-shoots of saturation (answer changing, but negligible)
4. changed some arguments for the P3 initialization subroutine to optional
(non-answer-changing).

LIST OF MODIFIED FILES: 
phys/module_mp_p3.F

TESTS CONDUCTED: 
1. Our standard test suite of cases for P3. Verified that simulation changes from the previous 
version are nonzero but negligible.
2. The modified codes are merged with develop and Release4.1.4 branches to include all the bug fixes we have. Regression test is done successfully as expected. 
3. Test cases with mp_physics=50 and mp_physics=51 yield bit-for-bit results.  

RELEASE NOTE: This version of P3 is designated as V3.1.14.

### CODE REVIEW

**Comment by smileMchen** [comment]
@hmorrison100 
Hugh,
I  wonder whether the p3_lookup_table_1.dat and p3_lookup_table_2.dat have been changed? If so, where can I get the new look-up tables?

**Comment by hmorrison100** [comment]
> @hmorrison100
> Hugh,
> I wonder whether the p3_lookup_table_1.dat and p3_lookup_table_2.dat have been changed? If so, where can I get the new look-up tables?

Hi, the lookup tables haven't changed - they're the same as the last WRF release.

Thanks,
Hugh

**Comment by smileMchen** [comment]
@hmorrison100 @davegill @dudhia @weiwangncar 
The modified P3 code from Hugh's folk is merged with Release4.1.4 to include all the bug fixes we have. Regression test is done successfully as expected.  
I think this code is ready to be merged into the develop branch. Please review and approve.

**Comment by davegill** [comment]
@hmorrison100 @davegill @dudhia @weiwangncar
From the infrastructure perspective, I am OK with this PR.
1. It is to the right repo.
2. No conflicts.
3. The mods are entirely within the developer's scheme.
4. The argument lists are not changed (as above would imply).
5. Mostly clean up
6. I fixed the PR message

Still need Wei and Jimy to sign-off

**Comment by davegill** [comment]
@smileMchen 
Ming,
Please update the PR with regtest info.

**Comment by smileMchen** [comment]
@davegill 
Dave,
I post the message of regression test yesterday. It is done successfully.

**Comment by davegill** [comment]
@smileMchen 

>Dave,
I post the message of regression test yesterday. It is done successfully.

Ming,
Please post that information in the PR message.

**Comment by davegill** [comment]
@smileMchen 
>Ming,
Please post that information in the PR message.

Ming,
I see where that info is in the PR already - my bad.

**Comment by davegill** [comment]
@dudhia @weiwangncar @smileMchen 
Folks,
I am OK with this PR from a infrastructure perspective.
Need Jimy and Wei for a sign-off

**Comment by davegill** [comment]
@dudhia @weiwangncar @smileMchen 
Folks,
On this PR, we are waiting for a longer run.

**Pull request merged**
