### PR TITLE
Add more developers to CODEOWNERS file

### PR DESCRIPTION
**Pull request by davegill**
TYPE: enhancement

KEYWORDS: CODEOWNERS

SOURCE: internal

DESCRIPTION OF CHANGES: 
Add in a few more active developers

LIST OF MODIFIED FILES: 
M .github/CODEOWNERS

TESTS CONDUCTED: 
MMM Classroom regtest; em_real, nmm, em_chem; GNU only

Individual tests:
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_1
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_2
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_5
SUCCESS_RUN_WRF_d01_em_real_32_em_real_03FD
SUCCESS_RUN_WRF_d01_em_real_32_em_real_07NE
SUCCESS_RUN_WRF_d01_em_real_32_em_real_10
SUCCESS_RUN_WRF_d01_em_real_32_em_real_11
SUCCESS_RUN_WRF_d01_em_real_33_em_real_03FD
SUCCESS_RUN_WRF_d01_em_real_33_em_real_07NE
SUCCESS_RUN_WRF_d01_em_real_33_em_real_10
SUCCESS_RUN_WRF_d01_em_real_33_em_real_11
SUCCESS_RUN_WRF_d01_em_real_34_em_chem_1
SUCCESS_RUN_WRF_d01_em_real_34_em_chem_2
SUCCESS_RUN_WRF_d01_em_real_34_em_chem_5
SUCCESS_RUN_WRF_d01_em_real_34_em_real_03FD
SUCCESS_RUN_WRF_d01_em_real_34_em_real_07NE
SUCCESS_RUN_WRF_d01_em_real_34_em_real_10
SUCCESS_RUN_WRF_d01_em_real_34_em_real_11
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_01
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_03
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_04a
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_06
SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_01
SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_03
SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_04a
SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_06

Comparison tests:
SUCCESS_RUN_WRF_d01_em_real_32_em_real_03FD vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_03FD status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_03FD vs SUCCESS_RUN_WRF_d01_em_real_34_em_real_03FD status = 0
Files SUCCESS_RUN_WRF_d01_em_real_32_em_real_07NE and SUCCESS_RUN_WRF_d01_em_real_33_em_real_07NE differ
SUCCESS_RUN_WRF_d01_em_real_32_em_real_07NE vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_07NE status = 1
SUCCESS_RUN_WRF_d01_em_real_32_em_real_07NE vs SUCCESS_RUN_WRF_d01_em_real_34_em_real_07NE status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_10 vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_10 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_10 vs SUCCESS_RUN_WRF_d01_em_real_34_em_real_10 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_11 vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_11 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_11 vs SUCCESS_RUN_WRF_d01_em_real_34_em_real_11 status = 0
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_01 vs SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_01 status = 0
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_03 vs SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_03 status = 0
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_04a vs SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_04a status = 0
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_06 vs SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_06 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_1 vs SUCCESS_RUN_WRF_d01_em_real_34_em_chem_1 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_2 vs SUCCESS_RUN_WRF_d01_em_real_34_em_chem_2 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_5 vs SUCCESS_RUN_WRF_d01_em_real_34_em_chem_5 status = 0

### CODE REVIEW

**Comment by davegill** [comment]
@weiwangncar @dudhia @smileMchen 
Folks,
If there are other developers who should be associated with specific schemes - add them in. Seems like we could do the NOAA HRRR/RAP folks with their schemes, stochastic, all of the YSU codes, and a host of names physics schemes.

**Comment by weiwangncar** [comment]
@davegill We can definitely add Joe Olson to his routines: module_bl_mynn.F, module_sf_mynn.F. We can perhaps add coastwx for module_sf_px*, module_bl_acm.F.

**Comment by davegill** [comment]
@weiwangncar 
Wei,
Here are the physics so far:
```
/phys/module_mp_thompson.F              @gthompsnWRF @wrf-model/physics
/phys/module_mp_jensen_ishmael.F        @graupely @wrf-model/physics
/phys/module_mp_gsfcgce_4ice_nuwrf.F    @cacruz @wrf-model/physics
/phys/module_sf_noahmp*                 @barlage @wrf-model/physics
/phys/module_fr_*                       @pedro-jm @brankokosovic @domingom @wrf-model/physics
/phys/module_bl_mynn.F                  @joeolson42 @wrf-model/physics
/phys/module_sf_mynn.F                  @joeolson42 @wrf-model/physics
/phys/module_sf_px*                     @coawstwx @wrf-model/physics
/phys/module_bl_acm.F                   @coawstwx @wrf-model/physics
```

It seems like we could add Georg, Tanya, and Hugh (for example) easily. I understanda that this inclusion process does not have to be completed immediately. We can incrementally add people in.

**Comment by weiwangncar** [comment]
@davegill I'm not sure if they have github account.

**Comment by kkeene44** [comment]
@davegill 
Tanya's user name is tanyasmirnova. I'm not sure about Georg or Hugh, but we could shoot them a quick email, or can add them later.

**Comment by davegill** [comment]
@weiwangncar 
Wei,
Thanks - 
I have added Tanya and Joe from NOAA, and I added coastwx for px and acm.
I think we just keep on adding these

**Comment by weiwangncar** [comment]
@davegill Do you want me to approve this for 4.1.1?

**Comment by davegill** [comment]
@weiwangncar 
Wei,
I'd be OK to approve this as-is. Let's just keep adding individuals as we move forward to the CODEOWNERS file

**Comment by weiwangncar** [comment]
@davegill It doesn't look that I can approve this change.

**Pull request merged**
