### PR TITLE
Use urban modules to define run-time configuration dimensions

### PR DESCRIPTION
**Pull request by davegill**
TYPE: enhancement

KEYWORDS: BEP, BEM, urban, dimensions

SOURCE: internal

DESCRIPTION OF CHANGES: 
Motivation: 
With the effort to reduce memory for the urban models (SHA a500a27c, PR #745 "Improve 
memory usage for urban models"), the previously existing hard-coded array dimensions no 
longer exist in the Registry. This PR uses the existing INTEGER PARAMETERs in each of the 
urban models (BEP and BEM) to fill in _derived_ rconfig Registry entries. Users never have to 
be concerned that the namelist sizes of the arrays are inconsistent with the physics scheme.

1. Add access functions for each of BEP and BEM schemes
    a. The access functions pick up the dimensions for urban arrays
    b. The functions are within the files, but not within the modules
2. Change the Registry so that the urban dimensions are `derived`, not `namelist,physics`
3. Remove unused `ulay` from dimension specification Registry
4. Add in a single print out line in the urban driver to explain  what that print-out is for
    a. By the way - this entire print-out construct is not thread safe, but it is only a print
5. For balance in the world, removed some remnants of debugging prints
6. Assign the correct dimensions urban in check_a_mundo, based on sf_urban_physics option

LIST OF MODIFIED FILES:
M Registry/Registry.EM_COMMON
M Registry/registry.dimspec
M phys/module_sf_bep.F
M phys/module_sf_bep_bem.F
M phys/module_sf_urban.F
M share/module_check_a_mundo.F
M test/em_real/examples.namelist

TESTS CONDUCTED: 
1. Tested with sf_urban_physics = 1, and 2, and 3

### CODE REVIEW

**Comment by davegill** [comment]
@barlage @dudhia @smileMchen 
Mike and Jimy,
Ming and I have worked together to put together two different PRs (this one and #877). Which do you want to go with?

**Comment by barlage** [comment]
Though I don't completely understand the Fortran, I like #878 better. It removes the namelist requirements, which is a nice feature, and guarantees consistency with the BEP and BEM modules so if users want to change the module dimensions, the memory allocation dimensions are done automatically.

**Comment by davegill** [comment]
@barlage 
Mike,
Thanks for the info

**Comment by dudhia** [comment]
Looks clever. As long as it works, I'm fine with it.

**Comment by davegill** [comment]
@dudhia @barlage @smileMchen 
> Looks clever. As long as it works, I'm fine with it.

Jimy,
Ming is going to do some simple tests to verify that everything is OK.

**Comment by smileMchen** [comment]
@davegill 
Dave,
I run a test case with BEP, which is done successfully.

**Pull request merged**
