### PR TITLE
Fix DA default gen_be_vertloc function

### PR DESCRIPTION
**Pull request by jamiebresch**
TYPE: enhancement

KEYWORDS: WRFDA_EnVar, gen_be_vertloc, alpha_vertloc

SOURCE: Jamie Bresch (NCAR)

DESCRIPTION OF CHANGES:
To change the default function in a stand-alone utility for generating
be.vertloc.dat, an input file required when alpha_vertloc=.true. and ensdim_alpha > 0.
Old default: kscale = 10.0 * real(k) * nk_inv
New default: kscale = 5.0 + real(nk)/real(k+3)
An example of log-P method (dependent on vertical level configuration) is also provided in the code.

The old default suppresses increments at low levels above surface where vertical correlation
exists in ensemble perturbations.

LIST OF MODIFIED FILES:
M       var/gen_be/gen_be_vertloc.f90

TESTS CONDUCTED:
Month-long hourly cycling over CONUS domain to discover the problem in the original default gen_be_vertloc
and to test the impact of various alpha vertical localization settings.

RELEASE NOTE: For WRFDA EnVar applications, gen_be_vertloc is fixed to allow proper increments from ensemble contributions at low levels above surface. Users are encouraged to modify the empirical 5.0 + real(nk)/real(k+3) function in the code for their own model levels and ensemble configurations.

### CODE REVIEW

**Comment by jamiebresch** [comment]
One example of u/v/t/rh vertical correlation of an 80-member ensemble perturbations.
ep_vert_corr_d01

**Comment by jamiebresch** [comment]
Correlation of several vertical localization as specified in gen_be_vertloc.f90.

gen_be_vertloc

**Comment by jjguerrette** [comment]
@jamiebresch this definitely looks like an improvement, but it seems like the vertical correlation length scale is too large relative to the 80-member ensemble.  Are the choices of 5 and 3 in the parameterization taken from GSI? Or from literature?  If not, then it seems to me there needs to be an adjustment still.

**Comment by jamiebresch** [comment]
@jjguerrette 
The vertical localization does not increase the correlation that does not
exist in the ensemble perturbations.

I don't know how Dale Barker (the original vertloc developer) decided the
model-level based (a), (b), (c) function and kept (a) as the default.
I made up the (d) relation and it is totally empirical.
The logP method is taken from GSI. The 0.388 shown is the plot is also
a user-defined value. It can also be level-dependent rather than one
value for all levels.

I did not intend to implement a comprehensive vertical localization for WRFDA.
The main purpose is to replace the very bad default and raise the awareness
that users should look at their ensembles and decide their localization scales.

**Comment by liujake** [comment]
@jamiebresch @davegill I am Ok to put this into V4.1 release repo for users' convenience, but think it is more appropriate to categorize this as 'enhancement' instead of 'bug-fix'.

**Comment by liujake** [comment]
@jamiebresch Can you also plot default localization function at each level before/after your change?

**Comment by jjguerrette** [comment]
While the correlations will not be increased, making the localization length scale longer than the correlation length scale defeats the purpose of doing localization.  The number of ensemble members required for convergence could actually increase.

**Comment by jamiebresch** [comment]
@jjguerrette Yes, I agree with your comment.
When the ensemble size is large enough, the localization does not matter much.
I don't insist on the 5 and 3 values. The kscale relation should actually be user input values.

**Comment by jamiebresch** [comment]
Red: kscale = 10.0 * real(k) * nk_inv
Blue: kscale = 5.0 + real(nk)/real(k+3)
vert_corr_levels

**Comment by jjguerrette** [comment]
Sorry, I'm not completely right on this as the new localization clearly will remove some spurious correlations from a small ensemble.  However, I'm wondering whether the localization is filtering out enough of those noisy correlations?  For example, at a fixed number of ensembles (40? 80?), is there a degradation to the analysis when used in a forecast?

I'm fine with this change to go in, but it would be nice to have a more rigorous analysis.

**Comment by liujake** [comment]
From the localization functions before/after change, this is a quite significant change for levels below 30. This will likely substantially affect the results. I would suggest this not going into V4.1 or develop branch before we have more evidence it is really an improvement to the forecast results.

**Comment by jjguerrette** [comment]
@jamiebresch, have you had more experience with these vertical localization lengthscales since closing the PR?  I wonder if the lengthscales need to be increased for all-sky radiance experiments.  It is possible the vertical correlation of hydrometeors is getting truncated.

**Comment by jjguerrette** [comment]
Please see attached my own vertical correlations analyzed from an 80 member ensemble over Eastern 2/3 of CONUS:
be_vert_corr

**Comment by jamiebresch** [comment]
@jjguerrette I have finalized the proper formulation for a physically-based log-P method for vertical localization.  Dale also agrees that the new plot looks more reasonable.
vert_corr_20190416

**Comment by jjguerrette** [comment]
That does look very nice!

**Comment by liujake** [comment]
@jamiebresch You may reopen this PR to be merged in for this logP method if you like.

**Comment by jamiebresch** [comment]
Will consider open a new PR in the future for a finalized better log-P implementation.

**Pull request closed without merging**
