### PR TITLE
YSU PBL: check on flag_qi instead of present(rqiblten)

### PR DESCRIPTION
**Pull request by dudhia**
TYPE: bug fix

KEYWORDS: YSU, WSM3, Kessler, ice check

SOURCE: internal

DESCRIPTION OF CHANGES: 
YSU checks on PRESENT(RQIBLTEN) to determine whether to fill local ice part of qv2d, but 
RQIBLTEN is always present, so this does not avoid copy from ice array when WSM3/Kessler MP 
is used. Better to check flag_qi which is also available and true except for WSM3 and Kessler.

LIST OF MODIFIED FILES: 
phys/module_bl_ysu.F

TESTS CONDUCTED: 
 - [x] Check code runs and uses flag_qi for simple MP scheme.

RELEASE NOTE: 
Using the YSU PBL scheme in combination with either the WSM3 or Kessler MP schemes (no ice) is now fixed to not use ice array.

### CODE REVIEW

**Comment by davegill** [comment]
@lfowler58 @dudhia @weiwangncar 
Jimy,
Laura is working on a newer YSU scheme as part of CPF (so eventually to be shared in MPAS and WRF). Her modifications include a cleaned up way to handle the number of moist arrays (using input flag variables, as you are doing). May we hold off with this PR until her shared code is available for consideration?

**Comment by dudhia** [comment]
This is for 4.1.3 as that release is likely to go out before we do any
merging,
so it can be seen as a temporary fix.
Jimy

**Comment by weiwangncar** [comment]
I'm ok with the change.

**Comment by davegill** [comment]
@dudhia 

> This is for 4.1.3 as that release is likely to go out before we do any
merging,
so it can be seen as a temporary fix.

Jimy,
I'm OK with that plan

**Comment by davegill** [comment]
@weiwangncar 
Wei,
Looking over these proposed changes, I am OK with them. You probably need to explicitly approve them.

**Pull request merged**
