### PR TITLE
Add reflectivity calculation back to WSM6 scheme

### PR DESCRIPTION
**Pull request by weiwangncar**
TYPE: bug fix

KEYWORDS: radar reflectivity, WSM6

SOURCE: reported by Gabriel Cassol of Sigma Meteorologia, Brazil, internal

DESCRIPTION OF CHANGES:
Problem:
When moving WSM6 to MMM shared physics directory, the calculation of radar reflectivity was left out.

Solution:
The calculation of radar reflectivity is added back in the WSM6 scheme.

ISSUE: For use when this PR closes an issue.
Fixes https://github.com/wrf-model/WRF/issues/2096

LIST OF MODIFIED FILES:
M phys/module_mp_wsm6.F

TESTS CONDUCTED:

1. The reflectivity is computed now when namelist do_radar_ref is set to 1.
2. The Jenkins tests are all passing.

RELEASE NOTE: Fixed the bug of missing radar reflectivity in WSM6 scheme when do_radar_ref is set to 1.

### CODE REVIEW

**Review by dudhia — DISMISSED** [review]
not seeing if Jenkins tests were done

**Comment by weiwangncar** [comment]
@dudhia As you can see I have been trying to start the tests a few times, but so far no success. Not sure what's going on.

**Comment by weiwangncar** [comment]
The Jenkins test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@dudhia @smileMchen Ready to be reviewed and approved.

**Review by dudhia — APPROVED** [review]

**Review by smileMchen — APPROVED** [review]

**Pull request merged**
