### PR TITLE
Update RUC LSM to the latest version used in version 1 of RRFS.

### PR DESCRIPTION
**Pull request by tanyasmirnova**
TYPE: bug fix, enhancement

KEYWORDS: snow model, irrigation, conductivities

SOURCE: Tanya Smirnova, NOAA/GSL

DESCRIPTION OF CHANGES:
1. Changes to the snow model. Added options to compute thermal snow conductivity and snow cover fraction:
   isncond_opt = 1 or 2 (1 is default, 2 is recommended to use) isncovr_opt = 1, 2 or 3 (1 is default, 2 is recommended to use for more accurate SCF)
2. Changes to irrigation scheme, use real-time vegetation fraction as an indicator of crops maturity.
3. Changes to soil diffusional and hydraulic conductivities.

LIST OF MODIFIED FILES: 
M        phys/module_sf_ruclsm.F

TESTS CONDUCTED: 
1. Tested in RRFS
2. The Jenkins tests are all passing.

RELEASE NOTE: This PR modifies the RUC LSM to add options to the snow model, use real-time vegetation fraction as an indicator for irrigation scheme, and change soil diffusional and hydraulic conductivities.

### CODE REVIEW

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by smileMchen** [comment]
@tanyasmirnova 

Tanya,

Would you please upload sample  namelist.input files that you used to test the changes described in this PR? Specifically, 

(1) For the snow model, I suppose we need the following options: 
isncond_opt =  2 
isncov_opt =  2 
sf_surface_physics = 3
num_soil_layers = 6 ( or 9)

(2) For the test of irrigation scheme,  please clarify what options are used. I suppose the  real-time vegetation fraction is still derived from WPS. Please let me know if I am wrong. 

Thanks !

**Review by dudhia — APPROVED** [review]
Too many changes to check well. Many are just case changes. Will approve as it affects no other files.

**Review by weiwangncar — APPROVED** [review]

**Comment by tanyasmirnova** [comment]
> @tanyasmirnova
> 
> Tanya,
> 
> Would you please upload sample namelist.input files that you used to test the changes described in this PR? Specifically,
> 
> (1) For the snow model, I suppose we need the following options: isncond_opt = 2 isncov_opt = 2 sf_surface_physics = 3 num_soil_layers = 6 ( or 9)
> 
> (2) For the test of irrigation scheme, please clarify what options are used. I suppose the real-time vegetation fraction is still derived from WPS. Please let me know if I am wrong.
> 
> Thanks !

@smileMchen 
Ming, 
The changes to the namelist are not needed with this PR. Please, use the following options with RUC LSM:
sf_surface_physics = 3 
num_soil_layers = 9

The new options in the snow model are specified internally in RUC LSM. I set them to isncond_opt = 2 and  isncovr_opt = 2 as the best options in my opinion.
Thank you!

**Comment by smileMchen** [comment]
@tanyasmirnova 
Tanya, 
Thank you for the information. Just one more question: with num_soil_layers = 9 and num_soil_layers = 6, can we see large differences? Also, is it recommended to run RUC with MYNN SFCLAY and MYNN PBL schemes? 
Thanks again.

**Comment by tanyasmirnova** [comment]
> @tanyasmirnova Tanya, Thank you for the information. Just one more question: with num_soil_layers = 9 and num_soil_layers = 6, can we see large differences? Also, is it recommended to run RUC with MYNN SFCLAY and MYNN PBL schemes? Thanks again.

@smileMchen 
Ming,
There could be quite substantial differences when 6 levels are used instead of 9 because with 6 levels the energy budget is applied to a thicker top soil layer, which may cause damping of the diurnal cycle for skin temperature. 
The use of RUC LSM with MYNN surface and PBL schemes is the most tested configuration. However, RUC LSM could be successfully used with any other option of surface and boundary layer physics.

**Comment by weiwangncar** [comment]
@smileMchen @tanyasmirnova If we use GFS input, we may need to adjust the soil data, like we did in the past.

**Comment by hezisue** [comment]
In this new version, some important code from the old version is missing.
RUC display in WRF 4.0: 
` !--- initializing snow fraction, thereshold = 32 mm of snow water 
!    or ~100 mm of snow height
!
           snowc(i,j) = min(1.,snow(i,j)/32.)
          if(snow(i,j).le.32.) soilt1(i,j)=tso(i,1,j)
!--- initializing inside snow temp if it is not defined
        IF((soilt1(i,j) .LT. 170.) .or. (soilt1(i,j) .GT.400.)) THEN
            IF(snow(i,j).gt.32.) THEN
           soilt1(i,j)=0.5*(soilt(i,j)+tso(i,1,j))`

But in the new version, this is missing, this part should affect the snow calculation, and logically there is a problem with the input value of snowc:
`!--- initializing snow fraction, thereshold = 32 mm of snow water or ~100 mm of snow height
        if((soilt1(i,j) .lt. 170.) .or. (soilt1(i,j) .gt.400.)) then
         if(snowc(i,j).gt.0.) then
           soilt1(i,j)=0.5*(soilt(i,j)+tso(i,1,j))`

**Comment by hezisue** [comment]
@tanyasmirnova 
I also have a quibble with the addition of snow cover fraction, which is that in the code below, display option 1 is the default, but the solution that ends up being used is option 2, which calculates the average value.
`      !-- Snow fraction options
      !-- option 1: original formulation using threshold snow depth to compute snow fraction
      !integer, parameter :: isncovr_opt = 1 (default)
      !-- option 2: the tanh formulation from Niu,G.-Y.,and Yang,Z.-L., 2007,JGR,DOI:10.1029/2007JD008674.
      !integer, parameter :: isncovr_opt = 2
      !-- option 3: the tanh formulation from Niu,G.-Y.,and Yang,Z with
      !   vegetation-dependent parameters from Noah MP (personal communication with
      !   Mike Barlage)
      !integer, parameter :: isncovr_opt = 3
      !-- Values of parameters are scale-dependent, have to be tuned for a given application
      !-- Tables below are for 21-class MODI-RUC (MODIFIED_IGBP_MODIS_NOAH_15s is used in HRRR and RRFS)
      !-- for 3-km RRFS application
        real, dimension(30), parameter ::        sncovfac =     &
     &                    (/ 0.030, 0.030, 0.030, 0.030, 0.030, &
     &                       0.016, 0.016, 0.020, 0.020, 0.020, &
     &                       0.020, 0.014, 0.042, 0.026, 0.030, &
     &                       0.016, 0.030, 0.030, 0.030, 0.030, &
     &                       0.000, 0.000, 0.000, 0.000, 0.000, &
     &                       0.000, 0.000, 0.000, 0.000, 0.000 /)
       real, dimension(30), parameter ::         mfsno =        &
     &                  (/  1.00, 1.00, 1.00, 1.00, 2.00, 2.00, &
     &                      2.00, 2.00, 2.00, 2.00, 2.00, 2.00, &
     &                      3.00, 3.00, 2.00, 2.00, 2.00, 2.00, &
     &                      2.00, 2.00, 0.00, 0.00, 0.00, 0.00, &
     &                      0.00, 0.00, 0.00, 0.00, 0.00, 0.00 /)

      !--
        integer, parameter :: isncovr_opt=2
      !--  `

**Comment by tanyasmirnova** [comment]
> In this new version, some important code from the old version is missing. RUC display in WRF 4.0: ` !--- initializing snow fraction, thereshold = 32 mm of snow water ! or ~100 mm of snow height ! snowc(i,j) = min(1.,snow(i,j)/32.) if(snow(i,j).le.32.) soilt1(i,j)=tso(i,1,j) !--- initializing inside snow temp if it is not defined IF((soilt1(i,j) .LT. 170.) .or. (soilt1(i,j) .GT.400.)) THEN IF(snow(i,j).gt.32.) THEN soilt1(i,j)=0.5*(soilt(i,j)+tso(i,1,j))`
> 
> But in the new version, this is missing, this part should affect the snow calculation, and logically there is a problem with the input value of snowc: `!--- initializing snow fraction, thereshold = 32 mm of snow water or ~100 mm of snow height if((soilt1(i,j) .lt. 170.) .or. (soilt1(i,j) .gt.400.)) then if(snowc(i,j).gt.0.) then soilt1(i,j)=0.5*(soilt(i,j)+tso(i,1,j))`

@hezisue Hello, Do you mean that snowc is not initialized in the new version? I removed this line because snowc should be available in the wrfinput_d01 from the parent model, and it should not be re-initialized in RUC SLM. 
Do you see a problem with this in your runs?

**Comment by tanyasmirnova** [comment]
> @tanyasmirnova I also have a quibble with the addition of snow cover fraction, which is that in the code below, display option 1 is the default, but the solution that ends up being used is option 2, which calculates the average value. ` !-- Snow fraction options !-- option 1: original formulation using threshold snow depth to compute snow fraction !integer, parameter :: isncovr_opt = 1 (default) !-- option 2: the tanh formulation from Niu,G.-Y.,and Yang,Z.-L., 2007,JGR,DOI:10.1029/2007JD008674. !integer, parameter :: isncovr_opt = 2 !-- option 3: the tanh formulation from Niu,G.-Y.,and Yang,Z with ! vegetation-dependent parameters from Noah MP (personal communication with ! Mike Barlage) !integer, parameter :: isncovr_opt = 3 !-- Values of parameters are scale-dependent, have to be tuned for a given application !-- Tables below are for 21-class MODI-RUC (MODIFIED_IGBP_MODIS_NOAH_15s is used in HRRR and RRFS) !-- for 3-km RRFS application real, dimension(30), parameter :: sncovfac = & & (/ 0.030, 0.030, 0.030, 0.030, 0.030, & & 0.016, 0.016, 0.020, 0.020, 0.020, & & 0.020, 0.014, 0.042, 0.026, 0.030, & & 0.016, 0.030, 0.030, 0.030, 0.030, & & 0.000, 0.000, 0.000, 0.000, 0.000, & & 0.000, 0.000, 0.000, 0.000, 0.000 /) real, dimension(30), parameter :: mfsno = & & (/ 1.00, 1.00, 1.00, 1.00, 2.00, 2.00, & & 2.00, 2.00, 2.00, 2.00, 2.00, 2.00, & & 3.00, 3.00, 2.00, 2.00, 2.00, 2.00, & & 2.00, 2.00, 0.00, 0.00, 0.00, 0.00, & & 0.00, 0.00, 0.00, 0.00, 0.00, 0.00 /)
> 
> ```
>   !--
>     integer, parameter :: isncovr_opt=2
>   !--  `
> ```

@hezisue The sncovr_opt=2 is a recommended option to use. It is the options that is used in the experimental MPAS with RUC LSM. sncovr_opt=1 is the oprtion which is used in the operational HRRR, that is why I called it a default option.

**Comment by zhyanyan2023** [comment]
@tanyasmirnova Hello author, I was looking through the RUC Land Surface Model in WRF v4.6 and came across something in the Option 3 of Snow Cover Fraction calculation that piqued my curiosity.The code uses a scaling factor of 10 (likely for 3km grids) multiplied by the vegetation-dependent sncovfac and the density ratio (m=1). Since sncovfac in Noah-MP is typically 2.5×z0, this multiplier of 10 effectively makes the factor 25×z0, which seems like a massive amplification. I’m curious if anyone has tested this Option 3—does it actually produce realistic results? Specifically, what’s the physical rationale for increasing the coefficient for a 3km grid rather than decreasing it?Also, in my own runs with default RUC settings, the snow extent looks okay, but I’ve noticed a significant bias in Land Surface Temperature (LST) over snow-covered areas compared to satellite data. Have you run into this LST performance gap or found a way to tune it? Just curious if this is a known issue or if I’m missing something in the configuration. Thanks!

**Comment by zhyanyan2023** [comment]
I also noticed that 'sncovfac' and 'mfsno' are defined as dimension(30) arrays in the code. However, this doesn't seem to align directly with the standard 21 or 27 vegetation categories typically used in WRF. Could you clarify how these 30 slots map to the land-use categories? I’m particularly curious if there's a specific indexing logic I should be aware of when interpreting these parameters.

**Pull request merged**
