### PR TITLE
Remove temporary files from test/em_real

### PR DESCRIPTION
**Pull request by davegill**
TYPE: no impact

KEYWORDS: remove 

SOURCE: internal

DESCRIPTION OF CHANGES:
There are two files in the test/em_real directory that do not belong in the repository: 
1. landFilenames
2. windturbines.txt

The `landFilenames` has a storied history:
```
commit 7629cd09d63d3d6c60203100f886fcc75bffb26f
Author: John Michalakes <michalak@ucar.edu>
Date:   Fri Feb 18 18:55:16 2005 +0000
    Temporary addition for hires topo input. Should remove later. JM
    git-svn-id: https://svn-wrf-model.cgd.ucar.edu/trunk@753 b0b5d27b-6f0f-0410-a2a3-cb1e977edc3d
```
John's advice was to "remove later". We waited 16 years, and now we are removing the file.

The `windturbines.txt` file is just a template, added  in 2013:
```
    The user locates the turbines with the lat,lon in the
    test/em_real/windturbines.txt file.  This file also includes
    a numeric "type". The sample is a "type" 1.
```
The file is short:
```
 55.574051 6.883480 1
 55.569066 6.884697 1 
 30.000000 -77.000000 1
```

LIST OF MODIFIED FILES: list of changed files (use `git diff --name-status master` to get formatted list)
D    test/em_real/landFilenames
D    test/em_real/windturbines.txt

TESTS CONDUCTED: 
1. Jenkins is OK.

RELEASE NOTE: Include a stand-alone message suitable for the inclusion in the minor and annual releases. A publication citation is appropriate.

### CODE REVIEW

**Comment by davegill** [comment]
@vlakshmanan-scala 
Varun,
I think that this PR spotted an error in the logic of the Jenkins testing. Note that one of the above two files has the extension ".txt". Because of this, the test was INSTANTLY short circuited as a PASS, and no regression test was run.

This should only happen if all of the mods are only to files with special extensions. It looks like the logic now says "if any file has a special extension, do not test".

**Comment by davegill** [comment]
@weiwangncar @dudhia @pedro-jm 
Folks,
What is the opinion of removing the `windturbines.txt` file? Is it useful as a template for the wind energy community?

**Comment by dudhia** [comment]
We need to keep it somewhere as an example.

**Comment by weiwangncar** [comment]
@pedro-jm Do you remember if you intended to commit this file to repository as a template? I know this file was not there after Anna's commit.

**Comment by dudhia** [comment]
I think the code won't  run without this file, so it is needed for any
testing.

**Comment by weiwangncar** [comment]
@dudhia Not sure what people do now, if they run from run/ directory, the windturbines.txt file isn't there.
@davegill I'm ok with removing just the LandFilenames to avoid any controversy.

**Comment by dudhia** [comment]
Since it has lat/long, it is only good for the real-data case, so it makes
sense to have it just in test/em_real.

**Comment by davegill** [comment]
OK, putting the windturbines.txt file back, which is easier with a new PR
#1424 "Remove temporary files from test/em_real" is now the preferred PR

**Pull request closed without merging**
