### PR TITLE
New NoahMP submodule instructions (unary operator bug fix)

### LINKED ISSUE #1659: Problem building WRF v4.4 with dm+sm and Cray compiler
**Describe the bug**
Can't compile WRF v4.4 (from github commit 6e1c57a22d856102277ec16ed369d0cc719a1cb5) in dm+sm

**To Reproduce**
1. Cray Fortran : Version 12.0.3
2. configure and select Compile option 47
3. Tested on Derecho's container environment
4. `compile em_real`

**Expected behavior**
Binaries produced

**Screenshots**
The first error is the following:

```
MODULE MODULE_SF_NOAHMPLSM
       ^
ftn-855 crayftn: ERROR MODULE_SF_NOAHMPLSM, File = module_sf_noahmplsm.f90, Line = 21, Column = 8
  The compiler has detected errors in module "MODULE_SF_NOAHMPLSM".  No module information file will be created for this module.

    TOP_MOIST     = TOP_MOIST + (SMC(IZ)*-1.0*ZSOIL(IZ))
                                         ^
ftn-1725 crayftn: ERROR COMPUTE_VIC_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 7988, Column = 42
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

    TOP_MAX_MOIST = TOP_MAX_MOIST + (parameters%SMCMAX(IZ)*-1.0*ZSOIL(IZ))
                                                           ^
ftn-1725 crayftn: ERROR COMPUTE_VIC_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 7989, Column = 60
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

          SM     = SM + (SMC(IZ) - parameters%SMCREF(IZ) )*-1.0*ZSOIL(IZ)
                                                           ^
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8069, Column = 60
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

          WM     = WM + (parameters%SMCREF(IZ)*-1.0*ZSOIL(IZ))
                                               ^
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8070, Column = 48
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

          WM     = WM + (SMC(IZ)*-1.0*ZSOIL(IZ))
                                 ^
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8072, Column = 34
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

       WM_MAX = WM_MAX + (parameters%SMCREF(IZ)*-1.0*ZSOIL(IZ))
                                                ^
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8074, Column = 49
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

       SM_MAX = SM_MAX + (parameters%SMCMAX(IZ) - parameters%SMCREF(IZ))*-1.0*ZSOIL(IZ)
                                                                         ^
ftn-1725 crayftn: ERROR COMPUTE_XAJ_SURFRUNOFF, File = module_sf_noahmplsm.f90, Line = 8075, Column = 74
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".

    TOP_MOIST     = TOP_MOIST + (SMC(IZ)*-1.0*ZSOIL(IZ))
                                         ^
ftn-1725 crayftn: ERROR DYNAMIC_VIC, File = module_sf_noahmplsm.f90, Line = 8172, Column = 42
  Unexpected syntax while parsing the assignment statement : "operand" was expected but found "-".
```

**Additional context**
Given how trivial the error looks, and given a number of other warnings that happen (a couple quoted below), I suspect the `configure` script making something wrong for option 47 rather than a problem in WRF itself. Moreover, the version `dm` (option 46) compiled fine (however that was the HEAD of the trunk as reported in the other ticket, whereas this is v4.4)

```
Fortran compiler for the model source code:
which FC
which: invalid option -- 'h'
which: invalid option -- 'n'
which: invalid option -- 'o'
which: invalid option -- 'o'
which: invalid option -- 'm'
which: invalid option -- 'p'
```

```
ftn-714 crayftn: WARNING in command line
  The "noomp" command has been overridden by the "omp" command.
```

### PR DESCRIPTION
**Pull request by davegill**
TYPE: bug fix

KEYWORDS: unary operator, NoahMP

SOURCE: Davide Del Vento (CISL/NCAR), internal

DESCRIPTION OF CHANGES:
Problem:
Several occurrences of `a * -b` were caught by the Cray compiler during routine
pre-derecho testing of WRF.

Solution:
The standard requires parentheses: `a * (-b)`.

### How to get a different (probably new) NoahMP version in the WRF repository
1. Get the WRF source code, and the right branch (let's assume `develop`
is the WRF branch).
```
git clone https://github.com/wrf-model/WRF
cd WRF 
git checkout develop
git checkout -b new_noahmp_for_some_reason
```
2. Get the NoahMP repo available and in the WRF source code. You must be in the
top-most level of the WRF directory structure to issue this command on some OS.
```
git submodule update --init --recursive
```
3. Get the correct NoahMP branch. Usually the NoahMP group tells us what to pick up.
Here, let us assume it is the `release-v4.4-WRF` branch from NoahMP.
```
cd phys/noahmp
git checkout release-v4.4-WRF
cd ..
```
4. Stage this modification.
```
git add noahmp
```

ISSUE:
Fixes #1659

ASSOCIATED REPOSITORY CHANGE:
https://github.com/NCAR/noahmp/pull/30

LIST OF MODIFIED FILES:
modified:   phys/noahmp

TESTS CONDUCTED:
1. All non-standard syntax of above form was modified.
2. All jenkins tests are PASS.

### CODE REVIEW

**Comment by davegill** [comment]
@weiwangncar @dudhia @cenlinhe @davidedelvento
Wei and Jimy,
This PR has the recipe for bringing in a new version of the NoahMP repository. Please approve so that we can start the testing back up.

Davide,
PLEASE fix your name in this commit message. Also, once you see that this PR is merged, would you check the dm+sm build again?

**Comment by davidedelvento** [comment]
> Davide,
> PLEASE fix your name in this commit message. 

Not sure what do you mean @davegill ? Is is something related to issue #1659 ? Or to commit a32cbe535da67dbaa713a96f0adcba629366e410 ? If the latter, I don't have permissions to change anything

> Also, once you see that this PR is merged, would you check the dm+sm build again?

Absolutely! It'll remain in my todo list until it builds and runs correctly.

**Comment by davegill** [comment]
@davidedelvento 
Davide DelVento
Davide delVento
Davide Del Vento
Davide del Vento

**Review by dudhia — APPROVED** [review]
Works neatly to show the actual changes by clicking on the submodule file. But this approval is effectively just for the new link.

**Review by kkeene44 — APPROVED** [review]

**Comment by cenlinhe** [comment]
@davegill the second "unary operator bug fix" PR in Noah-MP has been merged into the "develop" and "release-v4.4-WRF" branches

**Comment by davidedelvento** [comment]
> Davide DelVento Davide delVento Davide Del Vento Davide del Vento

Thanks @davegill -- the correct spelling is Davide Del Vento with "Del Vento" being last name with a space and fully capitalized. But that is uncommon, so depending on the database this goes in all the other options are ok too.

**Pull request merged**
