### PR TITLE
P3 update and bug fixes

### PR DESCRIPTION
**Pull request by hmorrison100**
The first line should be a single-line "purpose" for this change

TYPE: bug fix

KEYWORDS: P3, microphysics, 3-moment

SOURCE: Hugh Morrison (NCAR)

DESCRIPTION OF CHANGES:
Problem: Bug in solve_em.F so that 3-moment P3 (MP option 53) was not working properly. Some additional minor bug fixes to the P3 module as well as code clean up. Bug fixes to the 3 lookup tables. Also updated the lookup table generation code.

Solution:
Uncommented 1 line in solve_em.F in the call to microphysics driver.

ISSUE: For use when this PR closes an issue.
Fixes #123

LIST OF MODIFIED FILES: Modified: solve_em.F, module_mp_p3.F
Added: p3_lookupTable_2.dat-2momI_v5.2.2, p3_lookupTable_1.dat-5.3-2momI, create_p3_lookupTable_1.f90-v5.3, create_p3_lookupTable_2.f90-v5.2.2
Deleted: create_p3_lookupTable_1.f90-v5.1.6_b01, p3_lookupTable_1.dat-2momI_v5.1.6_oldDimax, p3_lookupTable_1.dat-3momI_v5.1.6.gz, p3_lookupTable_2.dat-4.1, create_p3_lookupTable_2.f90-v4.1

TESTS CONDUCTED: 
1. Idealized tests in WRf confirm the problems are fixed.
2. Are the Jenkins tests all passing?

RELEASE NOTE: Update and fixes to P3 microphysics.

### CODE REVIEW

**Comment by hmorrison100** [comment]
NOTE: I could not upload the updated 3-moment lookup table because it is 27 MB, this exceeded the maximum file size of 25 MB for uploading to git. Please advise how to get this file uploaded. Thanks.

**Comment by dudhia** [comment]
lots of changes

**Comment by hmorrison100** [comment]
Also: I had to add the old 3-moment lookup table back to get this to compile, otherwise I got this error:

if [ ! -f run/p3_lookupTable_1.dat-3momI_v5.1.6 ] ; then \
  ( cd run ; cp p3_lookupTable_1.dat-3momI_v5.1.6.gz hold.gz ; \
    gunzip hold.gz ; mv hold p3_lookupTable_1.dat-3momI_v5.1.6 ) ; \
fi
cp: cannot stat 'p3_lookupTable_1.dat-3momI_v5.1.6.gz': No such file or directory
gzip: hold.gz: No such file or directory
mv: cannot stat 'hold': No such file or directory

The above .gz file name will need to be updated in the Makefile (not sure which one or where) with the new file name: "p3_lookupTable_1.dat-5.3-3momI.gz". I didn't code this so not sure what has to be changed. Of course, first we need to figure out how to get the new 3-moment lookup table uploaded.

**Comment by hmorrison100** [comment]
@dudhia yes. the bug fixes to the lookup tables meant that all lookup tables files and the codes to create them had to swapped out. That's why so many files were modified. Otherwise only 1 line of code change in solve_em.F. There are a fair number of changes in the P3 module itself to fix the bugs (with some code cleanup). Many of the changes are GEM specific, but we didn't want to back port the bug fixes into the old version of P3 -- it makes sense to swap out the whole P3 module with a newer P3.

**Comment by weiwangncar** [comment]
@hmorrison100 The piece of script that creates the right table for P3 3 mom option is in the top level Makefile starting from line 124.

**Comment by hmorrison100** [comment]
Hi, let's just kill this PR until I figure out how to add the 3-moment lookup table file on command line git, and I modify the Makefile to update the file name. I'll create a new PR then.

**Pull request closed without merging**
