### PR TITLE
Separate chem_opt=100 from opts 108 and 109

### PR DESCRIPTION
**Pull request by jordanschnell**
This splits chem_opt=100 from chem_opt=108 and chem_opt=109 by renamng the original module for chem_opt=100 to *_het and removing the refrences to CLNO2, HCL, and the crustal species from options 108 and 109. Relatedly, the aerosol pointers in the module_data* files are adjusted to reflect this change. In this configuration, ISORROPIA and the N2O5 heterogenous chemistry option will only be available with option 100, but both namelist options must be set.

TYPE: bug fix/enhancment

KEYWORDS: MADE-SORGAM, SOA_VBS, heterogenous chemistry, crustal species, chemistry options

SOURCE: Jordan Schnell (CIRES/NOAA)

DESCRIPTION OF CHANGES:
Problem: Species in chem_opt=100 (HCL, CLNO2, MG, K, CA) are referenced by the aerosol module for chem_opt=108, 109 leading to memory mapping errors. Previous code allowed the user to run with ISORROPIA and N2O5 heterogenous chemistry without the necessary species. 

Solution:
See top

LIST OF MODIFIED FILES: 
M       Registry/registry.chem
M       Registry/registry.noahmp
M       chem/Makefile
M       chem/aerosol_driver.F
M       chem/depend.chem
M       chem/dry_dep_driver.F
M       chem/module_aerosols_soa_vbs.F
A       chem/module_aerosols_soa_vbs_het.F
M       chem/module_data_soa_vbs.F
A       chem/module_data_soa_vbs_het.F

TESTS CONDUCTED: 
1. Do mods fix problem? How can that be demonstrated, and was that test conducted?
2. Are the Jenkins tests all passing?

RELEASE NOTE: chem_opt=100 now separate from chem_opt=108 and 109. No ISORROPIA or N2O5 het for 108, 109.

### CODE REVIEW

**Comment by jordanschnell** [comment]
@rschwant @jianheACM

**Comment by weiwangncar** [comment]
The Jenkins test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by dudhia — APPROVED** [review]
All changes are in chem.
Note that registry.noahmp is listed in PR text but is not changed.

**Comment by jordanschnell** [comment]
@ravanah

**Review by ravanah — APPROVED** [review]

**Pull request merged**
