### PR TITLE
Add git hash and a summary of files changed

### PR DESCRIPTION
**Pull request by davegill**
TYPE: enhancement

KEYWORDS: commit hash, source files verification, provenance, user support, development, version control

SOURCE: Jan Mandel (University of Colorado Denver)

DESCRIPTION OF CHANGES: 

User support is more difficult without knowing if the user may have changed any files in the distribution, and, for 
developers, it is not possible to check if the binary executable is the same version as the source files, leading to 
unnecessary rebuilds. 

This PR includes a line in the WRF print output next to the WRF release version with the git commit hash. If any files 
are not part of a commit (local files changed), this modification prints a short diff statistic. Finally, if the files are not 
under git version control, the print out indicates that the git commit identification is not available. 

The command 
```
strings wrf.exe | grep 'git commit'
``` 
outputs the same line, which identifies what exact version the binary is from. The identification line is also printed in 
the output of `./compile`.

The new functionality is implemented by generating new file `inc/commit_decl` by `./compile`, and using it similarly 
as `inc/version_decl`. This new file is deleted by `./clean`.

Examples:

In WRF output: 
```
WRF V4.2 MODEL
git commit a599473c3c6db6cf00da79a7a7244085ba800f11
```

To identify the binary executable without running it:
```
strings wrf.exe | grep "git commit"
git commit a599473c3c6db6cf00da79a7a7244085ba800f11
```

In ./compile output, with some file changed: 
```
V4.2
git commit ccc58d749be86c1d5ddd45b4c3f82b2c4f9ca980 1 file changed, 1 insertion(+)
```
Content of the generated ```commit_decl``` file: 
```
    CHARACTER (LEN=*), PARAMETER :: commit_version = 'git commit e5d6fe01f5d319405af4f0e7d60aac8d9df02e43'
```

Content of the generated ```commit_decl``` file, with source files not from github, or no git on the system:
```
    CHARACTER (LEN=*), PARAMETER :: commit_version = 'No git found or not a git repository, git commit version not available.'
```

LIST OF MODIFIED FILES:
Scripts:   
modified:   clean
modified:   compile

Files that are associated with the top-level executables:
modified:   main/module_wrf_top.F
modified:   chem/chemics_init.F
modified:   chem/convert_emiss.F
modified:   main/ideal_em.F
modified:   main/ideal_nmm.F
modified:   main/module_wrf_top.F
modified:   main/ndown_em.F
modified:   main/real_em.F
modified:   main/real_nmm.F
modified:   main/tc_em.F

File with the cpp \#include commit_decl
modified:   inc/version_decl

TESTS CONDUCTED: 
1. Built and run with Intel and GNU compilers, with and without git available, in a cloned repository, and in a directory 
not under git control.
2. Jenkins regression test passed.

RELEASE NOTE: The git commit information is part of the WRF modeling system standard output, part of the strings within the executables, and also in the output of the ./compile command.

### CODE REVIEW

**Comment by davegill** [comment]
@janmandel 
Jan,
I made a change. The version_decl file now \#includes the commit_decl file. With that, I was able to add the git commit info into all of our executables.

I tried to push to your repo, and was not given permission.

**Comment by davegill** [comment]
@janmandel @weiwangncar @dudhia @kkeene44 @smileMchen @mgduda 

Folks,
We automatically put git info in several places with this PR: the standard printout, the build log, and contained in the "strings" within the executable.

Currently we get something like this (for example, in the real program's output):
```
REAL_EM V4.2 PREPROCESSOR
git commit 0bbbd089e7d4761cb43fd4f4f5483ef182821235 9 files changed, 9 insertions(+)
```

How about something like this from `git describe`:
```
v4.0.2-364-gef4f36b
```

What would you like to see as available information for support purposes, for your own "what version of the executable is this" information?

**Comment by davegill** [comment]
@janmandel 
Jan,
If you are OK with this PR, would you close #1202

**Comment by davegill** [comment]
Jenkins testing is OK. No KPP reqiuired
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: ef4f36bd48e695add75866af4cf1c1fb11f3a79e, requested by: davegill for PR: https://github.com/wrf-model/WRF/pull/1203. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           18
    Number of Builds       : 48           46
    Number of Simulations  : 166           164        0
    Number of Comparisons  : 105           104        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```

**Comment by janmandel** [comment]
> @janmandel
> Jan,
> I made a change. The version_decl file now #includes the commit_decl file. With that, I was able to add the git commit info into all of our executables.
> 
> I tried to push to your repo, and was not given permission.

@davegill 
Dave,
the repo is not publicly writable. I added you now to the repo with write permissions. If you can accept the invite in case you need to write to it in future that would be great. I also pushed your commit  ef4f36bd48e695add75866af4cf1c1fb11f3a79e

**Comment by janmandel** [comment]
> @janmandel
> Jan,
> If you are OK with this PR, would you close #1202


@davegill 
Dave,
compile was printing an extra line with "include commit_decl", I fixed that 117b75dc44974fe24fa1d3cfc6c49e0d720a7c67 and pushed PR#1202.

**Comment by davegill** [comment]
@janmandel 
> compile was printing an extra line with the text "#include commit_decl", I fixed that 117b75d and pushed to PR #1202. 

Jan,
I have extended an invite to you. Would you please include the commit that removes the  printout of the `rm` command inside the `clean` script. I would like to use this PR, not #1202 

I would like to use this PR, not #1202

**Comment by janmandel** [comment]
> @janmandel
> 
> > compile was printing an extra line with the text "#include commit_decl", I fixed that [117b75d](https://github.com/wrf-model/WRF/commit/117b75dc44974fe24fa1d3cfc6c49e0d720a7c67) and pushed to PR #1202.
> 
> Jan,
> I have extended an invite to you. Would you please include the commit that removes the printout of the `rm` command inside the `clean` script. I would like to use this PR, not #1202
> 
> I would like to use this PR, not #1202

@davegill 
Dave,
I pushed 117b75dc44974fe24fa1d3cfc6c49e0d720a7c67 to https://github.com/davegill/WRF/tree/commit-id and closed PR #1202 
Fixes openwfm#15

**Pull request closed without merging**
