### PR TITLE
Farms check a mundo

### PR DESCRIPTION
**Pull request by juhyejuhye**
TYPE: bug fix

KEYWORDS: FARMS, Microphysics, module_check_a_mundo.F 

SOURCE: Ju Hye Kim and Pedro Jimenez (NCAR/RAL)

DESCRIPTION OF CHANGES: FARMS can work correctly with microphysics schemes that do not provide effective radii of clouds (https://github.com/wrf-model/WRF/pull/1191). But, current WRF model displays an ERROR message and stops when the 'swint_opt is 2' and 'use_mp_re is not 1' condition. So, we remove this constraint from ‘module_check_a_mundo.F’.  

LIST OF MODIFIED FILES: 
M       share/module_check_a_mundo.F

TESTS CONDUCTED: 
1. Do mods fix problem? How can that be demonstrated, and was that test conducted? Yes, it fixed problem. When FARMS and microphysics scheme that do not provide effective radii of clouds (ex: mp=2) are used together, the model does not stop.
2. Are the Jenkins tests all passing?

RELEASE NOTE: FARMS can be used with microphysics parameterizations that do not provide cloud effective radii.

### CODE REVIEW

**Comment by dudhia** [comment]
It looks like the tests have passed.

**Comment by davegill** [comment]
This should be updated so that the base branch is release-v4.2.2

**Comment by weiwangncar** [comment]
@juhyejuhye The base code this change is based on may not be correct as it indicated 31 files have been modified. Did you intend to modify 4.2.1?

**Comment by weiwangncar** [comment]
@juhyejuhye @davegill When I tried to change base to release-v4.2.2, I get this: There are no new commits between base branch 'release-v4.2.2' and head branch 'farms_check_a_mundo.

**Comment by juhyejuhye** [comment]
Hi Wei,
I think I did not commit and just pushed the branch. I'll DO 'commit' and
push it right now and let you know.
Ju-Hye

**Comment by juhyejuhye** [comment]
Hi Wei and Dave,

I pushed the 'farms_check_a_mundo' branch just now. I only changed the file
 'share/module_check_a_mundo.F'. But I checked the differences by 'git diff
--name-status master' and it shows below result,

M       Makefile

M       arch/configure.defaults

M       chem/chemics_init.F

M       chem/module_mosaic_addemiss.F

M       configure

M       dyn_em/module_first_rk_step_part1.F

M       dyn_em/module_first_rk_step_part2.F

M       dyn_em/module_initialize_ideal.F

M       dyn_em/solve_em.F

M       external/RSL_LITE/module_dm.F

M       external/io_int/module_io_int_read.F90

M       phys/module_mp_thompson.F

M       phys/module_mp_wdm5.F

M       phys/module_mp_wdm6.F

M       phys/module_mp_wdm7.F

M       phys/module_mp_wsm3.F

M       phys/module_mp_wsm5.F

M       phys/module_mp_wsm6.F

M       phys/module_mp_wsm7.F

M       phys/module_physics_init.F

M       phys/module_ra_farms.F

M       phys/module_radiation_driver.F

M       phys/module_sf_noahmpdrv.F

M       phys/module_sf_noahmplsm.F

M       phys/module_sf_sfclayrev.F

M       phys/module_shcu_deng.F

M       phys/module_surface_driver.F

M       run/MPTABLE.TBL

M       share/module_check_a_mundo.F

M       share/module_model_constants.F

M       var/da/da_minimisation/da_get_innov_vector.inc

M       var/da/da_setup_structures/da_setup_flow_predictors_ep_format2.inc


If I made some mistakes, please let me know.

Thanks,
Ju-Hye

**Comment by davegill** [comment]
@juhyejuhye 
1. Get a fresh clone from wrf-model
2. checkout the release-v4.2.2 branch
3. Do the checkout -b to get a new branch for your development (different that THIS PR's branch name)
4. Add the check-a-mundo changes into that code
5. Push code to your repo, make a PR (you can steal all of the text from this one)
6. Once all of the above is OK, close this PR and mention the other PR that is taking its place

**Comment by juhyejuhye** [comment]
Thanks, Dave!
I'll do that.

Ju-Hye

**Comment by juhyejuhye** [comment]
This PR is re-issued in PR #1332

**Pull request closed without merging**
