### PR TITLE
Refactoring of gocart dust emission in mosaic

### LINKED ISSUE #711: reason to store fluxes of gravitationally settled and dry deposited dust in GOCART
Dear WRF-Chem developers,

My question is regarding the GOCART aerosol module.
I am trying to understand why the instantaneous fluxes of gravitationally settled and dry deposited dust (ug/m2/s) are being stored instead of accumulated values (ug/m2)?

state    real  dustgraset_1  ij       misc         1         -       r      "graset_1"     "dust gravitational settling  for size 1"        "ug/m2/s"
state    real  dustgraset_2  ij       misc         1         -       r      "graset_2"     "dust gravitational settling  for size 2"        "ug/m2/s"
state    real  dustgraset_3  ij       misc         1         -       r      "graset_3"     "dust gravitational settling  for size 3"        "ug/m2/s"
state    real  dustgraset_4  ij       misc         1         -       r      "graset_4"     "dust gravitational settling  for size 4"        "ug/m2/s"
state    real  dustgraset_5  ij       misc         1         -       r      "graset_5"     "dust gravitational settling  for size 5"        "ug/m2/s"
state    real  dustdrydep_1   ij      misc        1         -       r      "drydep_1"     "dust dry deposition for size 1"        "ug/m2/s"
state    real  dustdrydep_2   ij      misc        1         -       r      "drydep_2"     "dust dry deposition for size 2"        "ug/m2/s"
state    real  dustdrydep_3   ij      misc        1         -       r      "drydep_3"     "dust dry deposition for size 3"        "ug/m2/s"
state    real  dustdrydep_4   ij      misc        1         -       r      "drydep_4"     "dust dry deposition for size 4"        "ug/m2/s"
state    real  dustdrydep_5   ij      misc        1         -       r      "drydep_5"     "dust dry deposition for size 5"        "ug/m2/s"

It is impossible to calculate accumulated values since not all fluxes are being written to the output.
But, it is possible to restore the fluxes if the accumulated values are stored in the output.
Could you please advice?

I could modify the code to store accumulated values instead of fluxes.

### PR DESCRIPTION
**Pull request by saneku**
Code clean-up in dust emissions, when MOSAIC aerosol scheme is used.

TYPE: No impact, enhancement

KEYWORDS: dust emissions, GOCART, MOSAIC, WRF-Chem

SOURCE: Alexander Ukhov (KAUST)

DESCRIPTION OF CHANGES:
Problem:
- Code duplication in dust_opt=13 (GOCART dust emissions, when MOSAIC aerosol scheme is used), i.e. removed duplicate mosaic_source_du(). Instead, source_du() is called from module_gocart_dust.F
- Accumulated fluxes (kg/m2) of grav. settled and dry deposited dust are now being stored. Before instantaneous fluxes  (ug m^-2 s^-1) were stored. See also PR #1431, for details.
- Dust emissions ( EDUST1..5 variables, when dust_opt=13) are also stored as accumulated flux.
- Removed unused  variable ‘p8w’
- Removed unused  variable ‘dx’
- Instead of new variable 'dust_flux' standard variable 'emis_dust' is used.

ISSUE: 
Fixes #711

LIST OF MODIFIED FILES: 
M	Registry/registry.chem
M	chem/chem_driver.F
M	chem/emissions_driver.F
M	chem/module_gocart_drydep.F
M	chem/module_gocart_dust_afwa.F
M	chem/module_gocart_settling.F
M	chem/module_mosaic_addemiss.F

TESTS CONDUCTED: 
1. Two runs have been conducted: 1. chem_opt=10, dust_opt=13, and 2. chem_opt=301, dust_opt=1. Same domain as in PR1431. 
1.1 Dust emissions (sum of EDUST1...5 variables) have been compared.
image
Dust emissions (pattern and values) are the same, which is expected.

cdo expr,'emissions=EDUST1+EDUST2+EDUST3+EDUST4+EDUST5' ./wrfout_d01_2016-06-24_00\:00\:00_gocart ./wrfout_d01_2016-06-24_00\:00\:00_gocart_emissions
cdo expr,'emissions=EDUST1+EDUST2+EDUST3+EDUST4+EDUST5' ./wrfout_d01_2016-06-24_00\:00\:00_mosaic ./wrfout_d01_2016-06-24_00\:00\:00_mosaic_emissions

1.2. Next plot shows comparison of dust column loadings. 
image
Due to difference in size bins dust loadings on the right (GOCART aerosol scheme)  are higher. But spatial patterns are the same, which  is expected.

cdo expr,'LOAD=DUST_1+DUST_2+DUST_3+DUST_4*0.74' ./wrfout_d01_2016-06-24_00\:00\:00_gocart ./wrfout_d01_2016-06-24_00\:00\:00_gocart_load
cdo expr,'LOAD=oin_a01+oin_a02+oin_a03+oin_a04+oin_a05+oin_a06+oin_a07+oin_a08' ./wrfout_d01_2016-06-24_00\:00\:00_mosaic ./wrfout_d01_2016-06-24_00\:00\:00_mosaic_load

2. Are the Jenkins tests all passing?

RELEASE NOTE: Code refactoring in GOCART emissions, when MOSAIC aerosol scheme is used.

### CODE REVIEW

**Comment by weiwangncar** [comment]
Jenkins tests have passed:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           59
    Number of Simulations  : 158           158        0
    Number of Comparisons  : 95           94        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@jordanschnell Can you review this PR? Thanks.

**Review by jordanschnell — APPROVED** [review]
Approved by /chem

**Comment by jordanschnell** [comment]
@weiwangncar - Yes this is also fine for 4.4. I've added @kayeekayee to the reviewer list. I can merge when she also reviews.

**Review by kayeekayee — APPROVED** [review]

**Review by jordanschnell — APPROVED** [review]

**Pull request merged**
