### PR TITLE
Update WRFDA readme and add a ChemDA readme

### PR DESCRIPTION
**Pull request by liujake**
TYPE: text only

KEYWORDS: WRFDA, readme

SOURCE: Jake Liu (NCAR)

DESCRIPTION OF CHANGES:
Update general WRFDA release note readme and add a chemical DA readme.

LIST OF MODIFIED FILES:
A   doc/README.DA_chem
M  doc/README.DA

TESTS CONDUCTED: 
None.

RELEASE NOTE: None.

### CODE REVIEW

**Comment by liujake** [comment]
@kkeene44 Can you add @syha to the 'DA' subgroup so that I can add her as a reviewer for DA-related PR like this one?

**Review by syha — CHANGES_REQUESTED** [review]
Looks good, in general. Several possible edits:
1. How about renaming README.CHEMDA as README.DA_chem, to better align with README.DA?
2. We can edit line 64 in README.CHEMDA for further clarification, or can just add something like "Observation data are assumed to be processed for each analysis time and provided in the unit and the format specified in var/da/da_obs_io/da_read_obs_chem_sfc.inc and var/da/da_obs_io/da_scan_obs_chem_sfc.inc." The unit should be mentioned here, I think.
3. As for the GEN_BE package, did Wei's MOSAIC stuff get into the release yet? I haven't committed mine for MADE-VBS species, just because I was not sure if it was part of the WRF package. Shouldn't we clarify that at the end of line 72?
4. Line 50 in README.CHEMDA: pm2.5+pm10 => pm2.5 and pm10 
5. Same in lines 51 and 52 in README.CHEMDA: We should list them with commas. Otherwise, it reads as the sum of them.
6. Could you add my paper for the MADE-VBS scheme in line 44 in README.DA? Thanks!

**Comment by liujake** [comment]
@syha Thanks for detailed review and helpful comments. I have addressed your comments 1, 2, 4, 5. 
For 3, Yes. GOCART and MOSAIC code and namelist templates provided in this commit https://github.com/wrf-model/GENBE_2.0/commit/be3ca6f2d002864b77b732d75a639e5f82336cab. Can you add corresponding code/namelist for MADE/VBS instead of saying it does not work for MADE/VBS?

For 6, I will add your paper in a later PR that further update README.DA for the release 4.4 note along with other function update.

**Comment by syha** [comment]
Oh, I didn't know GENBE_2.0 was also updated and released from a separate branch.
I just added my stuff to it, but then reminded that configure.gen_be had to be edited for the intel compiler to change the compilation option "-openmp" to "-qopenmp".

Here is the error message:
ifort: command line error: option '-openmp' is not supported. Please use the replacement option '-qopenmp'
Makefile:26: recipe for target 'da_advance_time.exe' failed
make[1]: [da_advance_time.exe] Error 1 (ignored)

I recalled that Wei Sun had told me to edit configure.gen_be to change that manually (after typing 'configure'). Here I'm talking about the compilation option 8 (smpar) for the intel compiler. 
For some reason, the gnu compiler has not worked (and still doesn't work) for the GEN_BE codes on cheyenne. 
When I checked the git log message, it looked like Wei also compiled it using the intel compiler for mosaic.
So I guess he also edit configure.gen_be manually, before compilation.
Do you know where and how we can change the option for configure.gen_be? Or do you want me to just push it with a comment on it? I'm okay with either one, but I think we may need to clarify this, at least.

**Comment by liujake** [comment]
Why using 'smpar'? I think we all use 'dmpar' for MPI. OpenMP does not work or not tested. You must already use GEN_BE2.0 package for your GMD paper. So just use compiler and compilation option worked for you and tested by you. You need to make a PR from your GEN_BE2.0 fork, I will review and approve it before merge.

**Review by syha — APPROVED** [review]
Looks good to me.

**Comment by liujake** [comment]
@junmeiban Can you take a look at this PR and approve if Ok?

**Review by junmeiban — APPROVED** [review]

**Pull request merged**
