### PR TITLE
Fix to allow RRTMG longwave radiation (ra_lw_physics=4) to be used with vertical nesting

### PR DESCRIPTION
**Pull request by rsarthur**
TYPE: Enhancement

KEYWORDS: vertical nesting, RRTMG, longwave radiation, ra_lw_physics

SOURCE: Robert Arthur (LLNL)

DESCRIPTION OF CHANGES: When the RRTMG longwave radiation scheme (ra_lw_physics=4) was 
used in combination with vertical nesting, the longwave radiation was incorrect because the 
variable NLAYERS was set incorrectly. To fix this, NLAYERS is recalculated based on the updated 
number of vertical levels. This fix follows what is done already in the code for ra_lw_physics=1.

LIST OF MODIFIED FILES: 
phys/module_radiation_driver.F
share/module_check_a_mundo.F

TESTS CONDUCTED: 
1. Regression test runs and gives bit-wise identical parallel solutions with RRTMG and vertical 
nesting (21VN), and is also able to run RRTMG without vertical nesting (case=tropical, 
case=conus):
```
SUCCESS_RUN_WRF_d01_em_real_32_em_real_21VN vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_21VN status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_21VN vs SUCCESS_RUN_WRF_d01_em_real_34_em_real_21VN status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_conus vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_conus status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_conus vs SUCCESS_RUN_WRF_d01_em_real_34_em_real_conus status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_tropical vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_tropical status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_tropical vs SUCCESS_RUN_WRF_d01_em_real_34_em_real_tropical status = 0
```

2. A nested case was run with 4 setups, with ra_sw/lw_physics = 1 and 4, and vertical nesting 
on and off on the finest domain (see plot). The non-vertically nested case has 88 vertical levels 
and the nested case has 351. While there are differences in the longwave radiation (GLW) 
depending on whether vertical nesting is used or not, the differences when using option 4 are 
comparable (and slightly smaller) than those with option 1.

glw_comparison

RELEASE NOTE: The vertical refinement option now works with the RRTMG radiation scheme.

### CODE REVIEW

**Comment by davegill** [comment]
@rsarthur 
We would need this change to use the `develop` branch as the base branch, as this is considered new development work.

**Comment by davegill** [comment]
@weiwangncar @dudhia @smileMchen 
Folks,
The proposed mods:
1. are quite small
2. touch only a couple of files
3. require no communications
4. give reasonable results

We should do a 1-month test with these mods to validate that no longer-term biases are being introduced. That would require a set up something like:
test 1 = RRTM / Dudhia + nested
test 2 = RRTM / Dudhia + vertically nested
test 3 = RRTMG + nested
test 4 = RRTMG + vertically nested

**Comment by davegill** [comment]
@rsarthur @weiwangncar @dudhia 
Robert,
When I try to run a simple test case, I get an immediate failure:
```
--- USING: g            =      9.810
--- USING: cvpm         =     -0.714
--- USING: r_d          =    287.000
--- USING: cp           =   1004.500
--- USING: p1000mb      = 100000.000
--- USING: t0           =    300.000
d01 2000-01-24_12:00:00 *** Initializing nest domain # 2 by horizontally interpolating parent domain # 1. ***
INPUT LandUse = "USGS"
 LANDUSE TYPE = "USGS" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           16  SNOW CATEGORY =           24
INITIALIZE THREE Noah LSM RELATED TABLES
 LANDUSE TYPE = USGS FOUND          27  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
Max map factor in domain 1 =  1.03. Scale the dt in the model accordingly.
INPUT LandUse = "USGS"
 LANDUSE TYPE = "USGS" FOUND          33  CATEGORIES           2  SEASONS WATER CATEGORY =           16  SNOW CATEGORY =           24
INITIALIZE THREE Noah LSM RELATED TABLES
 LANDUSE TYPE = USGS FOUND          27  CATEGORIES
 INPUT SOIL TEXTURE CLASSIFICATION = STAS
 SOIL TEXTURE CLASSIFICATION = STAS FOUND          19  CATEGORIES
Timing for Writing wrfout_d01_2000-01-24_12:00:00 for domain        1:    0.29405 elapsed seconds
d01 2000-01-24_12:00:00  Input data is acceptable to use: wrfbdy_d01
Timing for processing lateral boundary for domain        1:    0.02215 elapsed seconds
 Tile Strategy is not specified. Assuming 1D-Y
WRF TILE   1 IS      1 IE     74 JS      1 JE     61
WRF NUMBER OF TILES =   1

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f7760480dfd in ???
#1  0x7f7760480013 in ???
#2  0x7f775f9783af in ???
#3  0x1cd4acf in __rrtmg_lw_rtrnmc_MOD_rtrnmc
	at /wrf/WRF/phys/module_ra_rrtmg_lw.f90:3310
#4  0x1d0ae95 in __rrtmg_lw_rad_MOD_rrtmg_lw
	at /wrf/WRF/phys/module_ra_rrtmg_lw.f90:11049
#5  0x1d20274 in __module_ra_rrtmg_lw_MOD_rrtmg_lwrad
	at /wrf/WRF/phys/module_ra_rrtmg_lw.f90:12538
#6  0x1739c76 in __module_radiation_driver_MOD_radiation_driver
	at /wrf/WRF/phys/module_radiation_driver.f90:1762
#7  0x17e5f35 in __module_first_rk_step_part1_MOD_first_rk_step_part1
	at /wrf/WRF/dyn_em/module_first_rk_step_part1.f90:299
#8  0x130a192 in solve_em_
	at /wrf/WRF/dyn_em/solve_em.f90:890
#9  0x11cf329 in solve_interface_
	at /wrf/WRF/share/solve_interface.f90:139
#10  0x46bd77 in __module_integrate_MOD_integrate
	at /wrf/WRF/frame/module_integrate.f90:329
#11  0x405246 in __module_wrf_top_MOD_wrf_run
	at ../main/module_wrf_top.f90:324
#12  0x404319 in wrf
	at /wrf/WRF/main/wrf.f90:29
#13  0x40436e in main
	at /wrf/WRF/main/wrf.f90:6
```

Here is the source at the offending line:
```
   3301                else
   3302                   if (odepth .le. 0.06_rb) then
   3303                      atrans(lev) = odepth-0.5_rb*odepth*odepth
   3304                      odepth = rec_6*odepth
   3305                      bbd = plfrac*(blay+dplankdn*odepth)
   3306                      bbugas(lev) = plfrac*(blay+dplankup*odepth)
   3307                   else
   3308                      tblind = odepth/(bpade+odepth)
   3309                      itr = tblint*tblind+0.5_rb
   3310                      transc = exp_tbl(itr)
   3311                      atrans(lev) = 1._rb-transc
   3312                      tausfac = tfn_tbl(itr)
   3313                      bbd = plfrac*(blay+tausfac*dplankdn)
   3314                      bbugas(lev) = plfrac * (blay + tausfac * dplankup)
   3315                   endif
   3316                   radld = radld + (bbd-radld)*atrans(lev)
   3317                   drad(lev-1) = drad(lev-1) + radld
   3318                endif
```

Here is my namelist.input file, with just the diffs noted from the standard Jan 2000 case:
```
 &time_control
 input_from_file                     = .true.,.false.,.false.
 /

 &domains
 max_dom                             = 2,
 e_we                                = 74,    31,    31,
 e_sn                                = 61,    31,    31,
 e_vert                              = 35,    45,    30,
 eta_levels(1:35)                    = 1., 0.993, 0.983, 0.97, 0.954, 0.934, 0.909, 0.88, 0.8406663, 0.8013327,
                                       0.761999, 0.7226653, 0.6525755, 0.5877361, 0.5278192, 0.472514,
                                       0.4215262, 0.3745775, 0.3314044, 0.2917579, 0.2554026, 0.2221162,
                                       0.1916888, 0.1639222, 0.1386297, 0.1156351, 0.09525016, 0.07733481,
                                       0.06158983, 0.04775231, 0.03559115, 0.02490328, 0.0155102, 0.007255059, 0.
 eta_levels(36:80)                   = 1.0000, 0.9946, 0.9875, 0.9789, 0.9685, 0.9562, 0.9413, 0.9238, 0.9037, 0.8813, 0.8514,
                                       0.8210, 0.7906, 0.7602, 0.7298, 0.6812, 0.6290, 0.5796, 0.5333, 0.4901, 0.4493, 0.4109,
                                       0.3746, 0.3412, 0.3098, 0.2802, 0.2524, 0.2267, 0.2028, 0.1803, 0.1593, 0.1398, 0.1219,
                                       0.1054, 0.0904, 0.0766, 0.0645, 0.0534, 0.0433, 0.0341, 0.0259, 0.0185, 0.0118, 0.0056, 0.
 vert_refine_method                  = 0,     2,     2,
 /

 &physics
 ra_lw_physics                       = 4,     4,     4,
 ra_sw_physics                       = 4,     4,     4,
 /

 &dynamics
 hybrid_opt                          = 0,
 use_theta_m                         = 0,
 /
```

**Comment by davegill** [comment]
@rsarthur @dudhia @weiwangncar 
If I try to use
```
 &physics
 ra_lw_physics                       = 1,     1,     1,
 ra_sw_physics                       = 1,     1,     1,
 /
```
I _STILL_ get a failure. So, this does not seem to be your issue.

**Comment by davegill** [comment]
@rsarthur 
Please send me your namelist. I must have something set that is not appropriate.

**Comment by rsarthur** [comment]
@davegill 
Thanks for looking into this. Attached is my namelist for the radiation option 4 case with vertical nesting. 
[namelist.input.txt](https://github.com/wrf-model/WRF/files/4105922/namelist.input.txt)

**Pull request merged**
