### PR TITLE
NoahMP bug fix for crop unit and LCZ urban grid identification

### PR DESCRIPTION
**Pull request by cenlinhe**
NoahMP bug fix for crop unit and LCZ urban grid identification

TYPE: bug fix

KEYWORDS: NoahMP crop, unit conversion, LCZ urban

SOURCE: Cenlin He (NCAR)

DESCRIPTION OF CHANGES:
1. A bug was identified in the NoahMP crop and carbon schemes (carbon and carbon_crop subroutines in module_sf_noahmplsm.F) diagnostic variable unit conversion and has been fixed in this PR; This fix is no-answer change because these diagnostic variables are not passed to WRF outputs.
2. Urban pixel identification is updated by including LCZ urban types in addition to the default MODIS/USGS urban type in module_sf_noahmpdrv.F for surface variable initialization.

LIST OF MODIFIED FILES: list of changed files:
M       phys/noahmp

TESTS CONDUCTED: 
1. tested successfully in NCAR Cheyenne HPC
2. reg tests have passed.

RELEASE NOTE: This PR fixes a few variable unit conversion in subroutine CARBON and CARBON_CROP subroutines, and urban grid identification by including LCZ urban types for variable initialization.

### CODE REVIEW

**Comment by weiwangncar** [comment]
The regtests have passed:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by cenlinhe** [comment]
Will this PR be approved soon? I have another bug fix for LCZ, which involves changes for Noah and Noah-MP so I have to wait until this Noah-MP PR is merged to make new PR changes. Thanks!

**Comment by dudhia** [comment]
OK, I can approve it now.

**Review by dudhia — APPROVED** [review]
Approved code update for  NoahMP

**Review by weiwangncar — APPROVED** [review]

**Pull request merged**
