### PR TITLE
A new cloud detection scheme based on Particle Filter

### PR DESCRIPTION
**Pull request by xdmjolly**
TYPE: new feature

KEYWORDS:  WRFDA, Infrared Radiance Data Assimilation, Cloud detection

SOURCE: Dongmei Xu (NUIST/NCAR), Thomas Auligné(JCSDA)

DESCRIPTION OF CHANGES: 
1. Add a new channel-based cloud detection scheme based on the Particle Filter method for Infrared sensors such as AIRS, IASI, GOES-Imager, and AHI. 

2. Same as two other existing schemes (MMR and ECMWF) in WRFDA, this cloud-detection scheme can retain high-peaking channels not affected by cloud even though the pixel scene is covered by cloud. This scheme is computationally more efficient than MMR scheme.

3. Integer namelist parameter 'use_clddet' determines which scheme to use (=0,1,2,3 for no cloud detection, MMR, particle filter, and ECMWF scheme). The default is set to 2 for particle filter.

LIST OF MODIFIED FILES: 
M       Registry/registry.var
M       var/build/depend.txt
A       var/da/da_radiance/da_cloud_detect.inc
D       var/da/da_radiance/da_cloud_detect_airs.inc
D       var/da/da_radiance/da_cloud_detect_iasi.inc
M       var/da/da_radiance/da_crtm.f90
M       var/da/da_radiance/da_get_innov_vector_crtm.inc
M       var/da/da_radiance/da_qc_ahi.inc
M       var/da/da_radiance/da_qc_airs.inc
M       var/da/da_radiance/da_qc_goesimg.inc
M       var/da/da_radiance/da_qc_iasi.inc
M       var/da/da_radiance/da_radiance1.f90
M       var/da/da_radiance/da_rttov.f90

TESTS CONDUCTED: WRFDA regression tests ran successfully with gnu/ifort+mpt on Cheyenne.

RELEASE NOTE: A new channel-based cloud detection scheme for Infrared sensors is added based on the Particle Filter method.
Xu D., T. Auligné, G. Descombes, and C. Snyder, 2016: A method for retrieving clouds with satellite infrared radiances using the particle filter. Geosci. Model Dev., 9, 3919–3932

### CODE REVIEW

**Comment by davegill** [comment]
@xdmjolly 
Dongmei,
Please change the base of this PR to be develop (not master).

**Comment by davegill** [comment]
@xdmjolly 
Dongmei,
There seem to be a number of unintended modifications. For example, you list changing 14 files, but github says youp PR is actually changing 32 files.

**Comment by davegill** [comment]
@xdmjolly 
Dongmei,
Great, it looks like the change in the base branch (to develop) cleaned up most of the file discrepancies! 
Scan through the files and then your commit message to make the modified file count to be consistent (13 vs 14 now).

**Comment by liujake** [comment]
Will review this at later time.

**Comment by liujake** [comment]
'Makefile' is an auto-genetated file during compilation, should NOT be added.

**Comment by xdmjolly** [comment]
The inconsistency between 13 vs 14 is caused bye the var/da/da_radiance/da_cloud_detect_iasi.inc,
which I renamed to be a new one as da_cloud_detect.inc. The github considered this behavior as one change.
A var/da/da_radiance/da_cloud_detect.inc
D var/da/da_radiance/da_cloud_detect_iasi.inc

**Comment by davegill** [comment]
@xdmjolly @liujake @jjguerrette 
>The inconsistency between 13 vs 14 is caused by the var/da/da_radiance/da_cloud_detect_iasi.inc,
which I renamed to be a new one as da_cloud_detect.inc. The github considered this behavior as one change.

Dongmei,
Thanks for clearing up that inconsistency for me.

Jake and JJ,
This PR does not touch any of the code outside of the WRF DA responsibility. I am unfamiliar with your process for accepting new DA code. It might be helpful to have some documentation provided for users. In the commit message for example, references for the technique, instructions on how to activate this option, what the scheme is for, when to use it, assumptions that the technique makes, comparison with other methods, etc. Outside the scope of the PR, do you typically provide README files for users? Should any part of the TechNote or Users_Guide be updated to maintain currency?

**Comment by liujake** [comment]
@xdmjolly Now you have three logical namelist variables use_clddet_mmr, use_clddet_pf, and use_clddet_ecmwf for three different cloud detection schemes for 4 different sensors (airs, iasi, goes-imager, ahi). I guess these three schemes will NOT be activated/used simultaneously. So I think it is better to define an integer namelist parameter 'clddet_scheme=0,1,2,3' for no-detection, mmr, pf, and ecmwf. And I do not see ecmwf cloud-detection scheme even though you have a namelist variable for it. You may make a separate PR for ecmwf scheme. Better also add published references in your PR for MMR scheme.

**Comment by liujake** [comment]
Do mmr and pf work with both CRTM and RTTOV, or just CRTM?

**Comment by xdmjolly** [comment]
mmr and pf work with both CRTM and RTTOV.
A new integer flag named as use_clddet=0,1,2,3 is now used  for no-detection, mmr, pf, and ecmwf.

**Pull request merged**
