### PR TITLE
Print separate numerator and denominator in lightning driver

### PR DESCRIPTION
**Pull request by zxdawn**
TYPE: bug fix
KEYWORDS: lightning driver

SOURCE: J. Wong, NCAR

DESCRIPTION OF CHANGES: 
Correct a print statement for the IC:CG ratio in lightning driver. Originally, this was printed as
a separate numerator and denominator.

LIST OF MODIFIED FILES:
phys/module_lightning_driver.F

TESTS CONDUCTED:
The message prints correctly:
```
lightning_driver: using user-prescribed IC:CG ratio = xx
```

### CODE REVIEW

**Comment by davegill** [comment]
@zxdawn 
Xin,
Since this is a really a bug, and SO small, please make this PR base branch the release-v4.1.3. This does not need to be on develop, where users will not see this for another 5-6 months.

**Comment by zxdawn** [comment]
@davegill Should I just change the `base` to `release-v4.1.3`?
Because I see this warning:
```
Some commits from the old base branch may be removed from the timeline, and old review comments may become outdated.
```

**Comment by zxdawn** [comment]
@davegill BTW, the modification didn't *Print separate numerator and denominator in lightning driver*. Instead, I just keep the message of printing the correct value of IC:CG ratio.

**Comment by davegill** [comment]
@zxdawn 
Xin,
1. This is such a small commit that you can go ahead and try to just change the base. If that does not work (for example, afterwards it says you are changing 237 files, for example), then just close this and do another PR from the release-v.4.1.3 base branch.
2. Thanks for pointing out the oops in the title modification!
3. Please build the code and run the code, then copy the actual print out and place that in the PR commit message.

**Comment by zxdawn** [comment]
@davegill Thanks! I will create the new PR after building the code.

**Pull request closed without merging**
