### PR TITLE
Improved treatment of mixed phase clouds in FARMS

### PR DESCRIPTION
**Pull request by pedro-jm**
TYPE: bug fix

KEYWORDS: FARMS, mixed phase clouds, optically thin clouds

SOURCE: Pedro A. Jimenez (NCAR/RAL), Ju Hye Kim (NCAR/RAL) and Yu Xie (NREL)

DESCRIPTION OF CHANGES: 
Improve treatment of mixed phase clouds in FARMS. 
1. This modification accounts for optically thin clouds (cloud optical depth < 1.0), which
were previously neglected. 
2. This fix avoids discontinuities in the surface irradiance at cloud optical depths of 1.

LIST OF MODIFIED FILES: 
M       phys/module_ra_farms.F

TESTS CONDUCTED: 
1. Jenkins tests are all PASS.
2. We compared the shortwave global horizontal irradiance (GHI) at the surface before and 
after the fix. Results are similar and the fix avoids discontinuities in the GHI. The following 
figures show results comparing simulations and GHI from the National Solar Radiation Data 
Base (NSRDB) at the seven SURFRAD sites:

image
image

### CODE REVIEW

**Comment by dudhia** [comment]
Pedro,
Given the large number of different files, I am not sure that this is done
correctly,
Jimy

**Comment by dudhia** [comment]
However, now I only see one changed file, so the earlier message may have been misleading.

**Comment by pedro-jm** [comment]
@dudhia 
I accidentally tried to merge my branch with master. That is why you saw so many changes. I changed to release-v4.2 once I realized of my mistake. Then the farms module is the one file that was modified.

**Comment by dudhia** [comment]
This is OK with me. It has been tested by the WRF-Solar team.

**Comment by davegill** [comment]
@pedro-jm @dudhia @weiwangncar 
Pedro,
Would you include the jenkins email in these lower comments. Once we see that, we can add the "jenkins test PASS" to the PR message.

Wei and Jimy,
Please wait for the jenkins info before the review.

**Comment by pedro-jm** [comment]
@davegill 
This is the email I got:

Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: f21a5d8f9585547b3836383fb758e4f156d3d99c, requested by: pedro-jm for PR: https://github.com/wrf-model/WRF/pull/1130. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 10           10
    Number of Builds       : 23           23
    Number of Simulations  : 140           140        0
    Number of Comparisons  : 89           89        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Pull request merged**
