### PR TITLE
Fix a bug and update the EEPS PBL scheme

### LINKED ISSUE #1833: Global variable TKE in the E-epsilon PBL scheme is not on middle of layer
**Describe the bug**
The global variable TKE in the E-epsilon PBL scheme is not on middle of layer. Currently, the E-epsilon scheme uses tke_pbl in the Registry.EM_COMMON. However, tke_pbl is defined on model interface. The TKE dissipation rate pep_pbl as well as the advective pek_adv and pep_adv are all on middle of layer. How to remove the issue:  define a new variable pek_pbl on middle of layer.

**To Reproduce**
Dowload WRFv4.2 or above

**Expected behavior**
Model is still stable, but the results will be impacted due to this bug.

### PR DESCRIPTION
**Pull request by hichunxi**
Fixed a bug and added a few features in the EEPS PBL scheme

TYPE: bug fix and new feature

KEYWORDS: eeps, pbl, tke, stratocumulus

SOURCE: Chunxi Zhang 

DESCRIPTION OF CHANGES:
Problem:
1) Bug fix: the variable tke_pbl in on full level while pep_pbl is on half level. The impact of this bug is small because the advective variables pek_adv and pep_adv are on half levels. Pek_adv and pep_adv will be assigned to pek and pep in the scheme, respectively. 
2) New Feature: a) Added the cloud top cooling effect for stratocumulus, which is similar to the one used in the MYNN PBL scheme. The critical step is to identify stratocumulus. We used the method by Marquet and Bechtold (2020). b) Added addtinal source term for stable boundary layer in the epsilon equation to represent the energy drain on the eddy scale (Zeng et al. (2020))

Solution:
Define a new variable named pek_pbl which is on half level, same as pep_pbl, pep_adv and pek_adv. 

ISSUE: For use when this PR closes an issue.
Fixes #1833 

LIST OF MODIFIED FILES: list of changed files (use `git diff --name-status master` to get formatted list)
M       Registry/Registry.EM_COMMON
M       dyn_em/module_first_rk_step_part1.F
M       dyn_em/start_em.F
M       phys/module_bl_eepsilon.F
M       phys/module_pbl_driver.F
M       phys/module_physics_init.F

TESTS CONDUCTED: 
1.  It fixed the TKE problem in WRF-ARW
2. The Jenkins tests have passed

RELEASE NOTE: Bug fix for the vertical levels of TKE in the EEPS scheme and more features are added in this scheme.

### CODE REVIEW

**Comment by weiwangncar** [comment]
@hichunxi Can you let me know your new email? Thanks..

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by dudhia** [comment]
Is the stratocumulus physics always active or is there a switch?

**Comment by hichunxi** [comment]
@dudhia There is a switch inside the code called 'bl_eeps_topdown', which is turned on by default.

**Comment by weiwangncar** [comment]
@hichunxi Why did you need to change to NoahMP? If you used the top of develop branch or check out the release-v4.5 branch, it should already point to the correct NoahMP code.

**Comment by hichunxi** [comment]
@weiwangncar I originally checked out my branch from the master branch. Then I merged remote/upstream/develop branch into my branch (I forgot to change noahmp hash after merge). I just merged remote/upstream/release-v4.5 branch into my branch.

**Review by dudhia — APPROVED** [review]

**Review by weiwangncar — APPROVED** [review]

**Pull request merged**
