### PR TITLE
Add all smoothed fields to FEEDBACK HALO

### PR DESCRIPTION
**Pull request by davegill**
TYPE: bug fix

KEYWORDS: feedback, smoothing, Registry

SOURCE: internal

DESCRIPTION OF CHANGES:
A necessary and sufficient situation for feedback smoothing:
   * a variable has the feedback smoothing `us` option IFF the variable is listed in HALO_EM_FEEDBACK

LIST OF MODIFIED FILES: 
modified:   Registry.EM_COMMON

TESTS CONDUCTED: 
1. Just turning off switches in Registry. However, we do get bit-for-bit results with a restart using the smoothing
options after this fix.
2. Jenkins tests are all PASS.

RELEASE NOTE: ARW Registry cleanup, so that the feedback smoothing options match the list of associated fields in the HALO for feedback.

### CODE REVIEW

**Review by dudhia — DISMISSED** [review]
This looks fine to me.

**Comment by davegill** [comment]
jenkins
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: 0422cab9cf0b7cdabf45f86a9124e5a26b3387ee, requested by: davegill for PR: https://github.com/wrf-model/WRF/pull/1502. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           18
    Number of Builds       : 48           46
    Number of Simulations  : 163           161        0
    Number of Comparisons  : 103           102        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```

**Comment by davegill** [comment]
@dudhia @weiwangncar @kkeene44 @smileMchen 
Folks,
Jimy has already approved these changes, also. With this PR too, I simply did some code alignment to force an additional jenkins test to verify that the tests were working. One this PR also, the jenkins tests are working.  However as on the other PR, those mods invalidate Jimy's previous "approval", so we need another one.
I will merge these - order matters.

**Comment by weiwangncar** [comment]
I'm ok with this PR too.

**Review by weiwangncar — APPROVED** [review]

**Pull request merged**
