### PR TITLE
Add CAMtr_volume_mixing_ratio for SSPs

### PR DESCRIPTION
**Pull request by jesusff**
TYPE: enhancement

KEYWORDS: CMIP6, GHG, SSP, climate, radiation

SOURCE: Jesus Fernandez (Instituto de Fisica de Cantabria CSIC-UC, Santander, Spain)

DESCRIPTION OF CHANGES:
Problem:
Missing GHG concentration files for the new Shared Socioeconomic Pathways used in CMIP6 and IPCC AR6 
([Meinshausen et al. 2020](https://doi.org/10.5194/gmd-13-3571-2020)). They are required to nest WRF into 
CMIP6 global models for future regional climate simulation.

Solution:
Add corresponding GHG concentration files using global average data provided via input4MIP (namely, via CSV files 
provided by https://greenhousegases.science.unimelb.edu.au). Note that yearly hemispheric averages are also 
available from this source, and also 15-degree resolution monthly values. These could be used to tailor GHG 
evolution files for a particular WRF domain (see the code used to generate these files in 
https://github.com/SantanderMetGroup/wrf-ghg-files/tree/v0.1.2). The files included in this PR are global averages, 
consistent with previous CAMtr RCP files.

The files are used as the existing RCP CAMtr files, by renaming or linking the appropriate file with the exact name 
CAMtr_volume_mixing_ratio in the WRF running directory. For this to work, WRF needs to be compiled with the macro 
`-DCLWRFGHG` and the long-wave radiation parameterization set to one of: RRTM, CAM, RRTMG (ra_lw_physics = 1, 
3, 4).

A successful reading of the files leads to messages such as the following at the beginning of the WRF standard output log:
```
d01 2033-12-27_00:00:00  CLWRF reading...: istatus:  0 idata: 1 year: 1765 co2:    277.913000000000      n2o:    274.372000000000      ch4:   738.986000000000
d01 2033-12-27_00:00:00  CLWRF reading...: istatus:  0 idata: 2 year: 1766 co2:    277.958000000000      n2o:    274.392000000000      ch4:   739.831000000000
d01 2033-12-27_00:00:00  CLWRF reading...: istatus:  0 idata: 3 year: 1767 co2:    278.017000000000      n2o:    274.426000000000      ch4:   740.729000000000
d01 2033-12-27_00:00:00  CLWRF reading...: istatus:  0 idata: 4 year: 1768 co2:    278.078000000000      n2o:    274.447000000000      ch4:   741.222000000000
```

LIST OF MODIFIED FILES: 

M       run/README.physics_files
A       run/CAMtr_volume_mixing_ratio.SSP119
A       run/CAMtr_volume_mixing_ratio.SSP126
A       run/CAMtr_volume_mixing_ratio.SSP245
A       run/CAMtr_volume_mixing_ratio.SSP370
A       run/CAMtr_volume_mixing_ratio.SSP585

TESTS CONDUCTED: 
1. Model runs with the new files, which are just ASCII files formatted exactly as the existing ones for RCPs used in 
CMIP5.
2. The new files were compared to the existing ones for RCPs to ensure a consistent order of magnitude and 
evolution of the concentration values. No long-term climate simulation has been yet conducted with the new data 
files, but the files are within the order of magnitude of existing RCP files, which were extensively tested. 
CAMtr file comparison
  
RELEASE NOTE: Added new CAMtr_volume_mixing_ratio data files for CMIP6 SSPs (https://doi.org/10.5281/zenodo.5507554) containing yearly global average concentrations from input4MIPs (v1.2.0 for historical part and v1.2.1 for scenario evolution).

### CODE REVIEW

**Comment by dudhia** [comment]
Thanks. This looks like a nice contribution for us. It should not be aimed
at master,
but rather develop or release-v4.3.1.

**Comment by jesusff** [comment]
Ups, sorry. I branched off from master. It should merge cleanly on any branch, though, since these are just new files. I aimed it now to develop, so you can include it in any future release at your convenience.
The details on how the files were generated are in https://github.com/SantanderMetGroup/wrf-ghg-files, along with scripts which could also generate hemispheric or domain-specific concentrations.

**Comment by dudhia** [comment]
We have to check which tests fail, but it may be something we can ignore and will conform that later.

**Comment by weiwangncar** [comment]
@jesusff If you receive any test results from jenkins@no-reply.scalacomputing.com, please post it in the comments for others to see. Check your spam folder if necessary.

**Comment by jesusff** [comment]
Dear @weiwangncar , I didn't receive any jenkins results (spam checked also). The "details" link to the failing test in this conversation keeps timing out.

**Comment by dudhia** [comment]
Yes, the link has never worked. We can try to find out somehow. Seems you
are just adding
data files, so it is not likely to be a real problem.

**Comment by dudhia** [comment]
@davegill could you check what happened in the tests here? Thanks. It is just adding files.

**Comment by davegill** [comment]
@jesusff @dudhia @weiwangncar 
Wei and Jimy,
This is just adding some files, but not technically a bug fix. Do we want this slated for release v4.3.1 or develop?

Jesus,
Would you please add a bit more information under the "Solution", "TESTS CONDUCTED", and "RELEASE NOTE" sections. For example, what schemes do these files work with? Is there a mechanism to activate these files? Can you show some imagery that indicates these files have been used correctly? The RELEASE NOTE section needs to be a stand-alone description of the modification. It is typical for that information to be a bit redundant (already mentioned in the PR commit message).

**Comment by dudhia** [comment]
This can be in V4.3.1.

**Comment by davegill** [comment]
jenkins:
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: 2fcfe751e7939346b89750f4b7c3ec3747692de7, requested by: jesusff for PR: https://github.com/wrf-model/WRF/pull/1553. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           18
    Number of Builds       : 48           46
    Number of Simulations  : 163           161        0
    Number of Comparisons  : 103           102        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```

**Comment by jesusff** [comment]
I added more information to the first post in this conversation, as suggested by @davegill

**Review by smileMchen — DISMISSED** [review]
run a test case using the data CAMtr_volume_mixing_ratio.SSP119. It works as expected.

**Comment by jesusff** [comment]
Sorry, I just updated the run/README.physics_files to include the new data files. I also took the freedom to briefly explain that the corresponding file needs to be renamed in order to work (this is different to other data files in this README):

https://github.com/jesusff/WRF/blob/0e617c6e2470a1e9c2a939ce2692d6fa7196bcbd/run/README.physics_files#L96

**Review by dudhia — APPROVED** [review]
Checked the README and this looks fine too. It was good to have the graphed functions as a check.

**Review by smileMchen — APPROVED** [review]

**Comment by weiwangncar** [comment]
@jesusff Are you aware that the gas data are not getting into rrtmg shortwave routine?

**Comment by jesusff** [comment]
I'd say it is intentional, but not ideal. If I remember correctly, GHG variation was started by us in U. Cantabria, where Lluis Fita modified the CAM radiation code (thus, the CAMtr naming of the GHG files), which included both SW and LW. This procedure was ported to RRTM in UNSW (Australia), which only handled LW radiation and was typically used in combination with the Dudhia SW scheme. I guess this moved to the LW component of RRTMG when this scheme appeared.

I think there is a need to define the forcings in a consistent way across all physics schemes. E.g. there are also inconsistencies with the NoahMP CO2 levels (SantanderMetGroup/WRF4G#30), which may affect evapotranspiration through stomatal resistance.

This PR only updated the static files with the GHG concentrations, though. No changes were done to the code. Maybe this discussion should be moved to a new issue.

**Comment by weiwangncar** [comment]
@jesusff Thanks for your comment. I've moved this to Issue #1597.

**Comment by dudhia** [comment]
I think this effect would be small, but CO2 and CH4 can be used by the
shortwave. I don't see the other gases used.

**Pull request merged**
