### PR TITLE
Make VEGPARM.TBL for RUC-USGS and RUC-MODIS consistent with RUC scheme

### PR DESCRIPTION
**Pull request by davegill**
TYPE: bug fix

KEYWORDS: RUC, LSM, z0

SOURCE: File supplied by Tanya Smirnova (NOAA), internal

DESCRIPTION OF CHANGES:
Problem:
The attempt to use a RAP/HRRR namelist suite fails when the input
landuse data is USGS due to this computation:
```
ZNTtoday(k) = Z0TBL(K) - 0.125 * factor

```
If the date is close to the minimum of the greenness fraction, such as
January, then the value of `factor` is nearly 1.0. If the value of
Z0TBL (roughness length from the `VEGPARM.TBL` table file) is <= 0.125,
then the resulting seasonally adjusted roughness length is < 0.0.
Computations later fail due to this assignment of an out of range value.

Solution:
Tanya provided a `VEGPARM.TBL` file specifically set up for RUC, where the
low values of roughness length were removed. This fixes the computational
issues.

For completeness, the `SOILPARM.TBL` file has also been updated (only for the
STAS-RUC section) to be consistent with the NOAA RUC developer's table.

LIST OF MODIFIED FILES:
modified:   run/VEGPARM.TBL
modified:   run/VEGPARM.TBL

TESTS CONDUCTED:
1. The Jenkins auto testing is all PASS
2. The new RAP/HRRR test in Jenkins is a PASS

RELEASE NOTE: The default VEGPARM.TBL file has been modified for the RUC LSM scheme. Several roughness length categories were increased for use with both the USGS and the MODIS data sets. Similarly, the STAS-RUC section of the SOILPARM.TBL file was modified to be consistent with the RUC developer's requests. The impact is only to RUC LSM.

### CODE REVIEW

**Comment by davegill** [comment]
@weiwangncar @dudhia @kkeene44 @smileMchen 
Folks,
Here are the SMALL mods to the VEGPARM.TBL file. The only impacts are to the USGS-RUC and MODIS-RUC. The changes are to Z0 and to IFOR. The IFOR == 7 is the one that was causing trouble for small Z0. I did not change anything related to the SOIL tables.

This mod fixes my failure with the RUC scheme in the second time step.

**Comment by dudhia** [comment]
More differences than I expected.

**Comment by weiwangncar** [comment]
@davegill @dudhia Aside from Tanya's addition for SNU data in SOILPARM.TBL, she made some changes to the existing table for RUC. See below. This part we could include.
soil_diff

**Comment by davegill** [comment]
@weiwangncar 
Wei,
Thanks, I have included the SOILPARM.TBL in the PR now.

**Comment by davegill** [comment]
Jenkins:
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: 843e4498b7fe835212155a9ca1a37a4d76e9dd30, requested by: davegill for PR: https://github.com/wrf-model/WRF/pull/1141. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 10           10
    Number of Builds       : 23           23
    Number of Simulations  : 143           143        0
    Number of Comparisons  : 91           91        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```

**Comment by weiwangncar** [comment]
@davegill Did the Jenkins test results posted include the SOILPARM.TBL change? Could also let Tanya see what we put into 4.2.

**Comment by davegill** [comment]
This set of jenkins results are with the mods to both VEGPARM.TBL and SOILPARM.TBL, using the namelist with the RAP/HRRR settings:
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: 00db78222db391d0477e3a2572ada630c2ddc6bb, requested by: davegill for PR: https://github.com/wrf-model/WRF/pull/1141. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 10           10
    Number of Builds       : 23           23
    Number of Simulations  : 158           158         0
    Number of Comparisons  : 101           101         1

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    output_1:SUCCESS_RUN_WRF_d01_em_real_32_em_real_cesm vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_cesm status = 1
```

The major physics settings are:
```
 &physics
 fractional_seaice                   = 0,
 mp_physics                          = 28,    28,    28,
 ra_lw_physics                       = 4,     4,     4,
 ra_sw_physics                       = 4,     4,     4,
 sf_sfclay_physics                   = 5,     5,     5,
 sf_surface_physics                  = 3,     3,     3,
 bl_pbl_physics                      = 5,     5,     5,
 cu_physics                          = 3,     3,     0,
 sf_urban_physics                    = 0,     0,     0,
 shcu_physics                        = 0,     0,     0,
 shcu_physics                        = 0,     0,     0,
 topo_shading                        = 0,     0,     0,
 isfflx                              = 1,
```

**Comment by davegill** [comment]
@weiwangncar 
Wei,
I am happy with this PR. You may review this. The testing has come out OK.

**Comment by dudhia** [comment]
More changes than expected, but OK. Only in the RUC sections.

**Comment by dudhia** [comment]
Maybe need a comparison test to see impact. I know failed before with USGS,
but MODIS was also changed slightly,
Jimy

**Pull request merged**
