### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by davegill**
TYPE: new feature

KEYWORDS: issue template

SOURCE: internal

DESCRIPTION OF CHANGES: 
A first cut at setting up a bug-fix template for issues. I'm not really sure what this will look like.

LIST OF MODIFIED FILES: 
.github/ISSUE_TEMPLATE/bug_report.md 

TESTS CONDUCTED: 
1. Does not impact the build or run of the WRF model, no test required.

### CODE REVIEW

**Comment by davegill** [comment]
@mgduda @kkeene44 @weiwangncar @smileMchen @dudhia 
Folks,
Miles, Michael, and I chatted about this a bit today - trying to get a template for the "issues" for WRF. This is seeing what this could look like for us. Sorry for the atypical PR starting branch, but github sort of did much of this for me.

**Comment by weiwangncar** [comment]
@davegill If this file is this hidden, how do you expect people who report issues to find it? How do you want this file to be used?

**Comment by davegill** [comment]
@weiwangncar 
I agree with everything you say. We are still working this out. :)

**Comment by mgduda** [comment]
@weiwangncar The file is used by GitHub to provide the default text when someone opens a new Issue. To see how this works, go to [https://github.com/mgduda/MPAS-Scratch/issues](https://github.com/mgduda/MPAS-Scratch/issues) and try opening a new issue.

**Comment by mgduda** [comment]
@davegill As an alternative to using the GitHub web interface to create Issue templates for "bug reports", etc., it's possible to create a general template by just committing a new file, `.github/ISSUE_TEMPLATE.md` to the repository. I don't know whether this has to be a commit to the `master` branch or not.

**Comment by weiwangncar** [comment]
@mgduda Thanks. It makes sense if it just pops up when a new issue is opened.

**Pull request merged**
