### PR TITLE
Do not reinitialise SOA_VBS or SORGAM aerosols on restart

### PR DESCRIPTION
**Pull request by theoc**
TYPE: bug fix

KEYWORDS: aerosols, SOA, VBS, SORGAM, restart

SOURCE: Theodoros Christoudias (Cyprus Institute)

DESCRIPTION OF CHANGES: 
Problem:
If using an existing simulation, aerosols (SOA_VBS and SORGAM) should not be reinitialized 
on restart. 

Solution:
This modification checks the restart configuration flag. If this is a restart run, then do not set 
all aerosols to epsilc.

LIST OF MODIFIED FILES:  
WRF/chem/module_aerosols_soa_vbs.F 
WRF/chem/module_aerosols_sorgam.F

TESTS CONDUCTED: 
 - [x] Test conducted without change: aerosols are reinitialized and not recycled at 
simulation restart. 
 - [x] Test conducted with change: fixes problem.

Below are consecutive history outputs before and after the restart point. It's clear that PM 
concentrations are reinitialized and there's no continuity with previous concentrations:

PM2_5_DRY in test_full_d02_00841
PM2_5_DRY in test_full_d02_00842

### CODE REVIEW

**Comment by davegill** [comment]
@weiwangncar @dudhia @ravanah @kayeekayee 
Is there someone that is able to review this PR? 

If NOAA is no longer able to participate, do we have a plan for chemistry updates? For example, we have a PR for WRF Chem to the develop branch that has been sitting since Oct 2018 (#682)

**Comment by davegill** [comment]
@theoc 
Theodoros,
Would you please provide two figures, a before and after pair. With a restart run, please show the impact of the modification. It seems that a pair of figures just one time step after the restart would be quite dramatic.

**Comment by theoc** [comment]
I am attaching consecutive history outputs before and after the restart point. It's clear that PM concentrations are reinitialised and there's no continuity with previous concentrations:

PM2_5_DRY in test_full_d02_00841
PM2_5_DRY in test_full_d02_00842

**Comment by kayeekayee** [comment]
@davegill @theoc We will take a look at it next week. we get back to you soon. Thank you.

**Pull request merged**
