### PR TITLE
Add missing unit conversion for inverse of specific humidity to mixing ratio [g/kg]

### PR DESCRIPTION
**Pull request by jjguerrette**
TYPE: bug fix

KEYWORDS: CRTM, radiance, DA, water vapor, humidity

SOURCE: JJ Guerrette (NCAR)

DESCRIPTION OF CHANGES: There is a missing unit conversion in the inverse of the specific humidity to mixing ratio [g/kg] conversion for the trajectory value of specific humidity.  The 1000 multiplier in the forward conversion needs to be divided out in both usages of `iv%instid(inst)%qm`.  This is an inverse equation, not a TL or AD equation.  Bug was originally introduced in commit 058491a786df6f2.

LIST OF MODIFIED FILES:
M       var/da/da_radiance/da_transform_xtoy_crtm.inc
M       var/da/da_radiance/da_transform_xtoy_crtm_adj.inc
M       var/da/da_transfer_model/da_transfer_wrftoxb.inc

TESTS CONDUCTED: I ran difference tests for convection-permitting clear-sky and all-sky GOES-ABI experiments that use a single water-vapor-sensitive channel (8).   The final quadratic cost function after two outer iterations (50 inner iterations each) for the clear-sky experiment decreases from 4.871D+04 to 4.795D+04.  The final cost function for the all-sky experiment changes in the 6th digit (little to no gross impact).  Both experiments additionally include conventional observations.  I have not looked at detailed results, but the bug is clear enough that it should be fixed.

RELEASE NOTE: A bug fix in the trajectory calculation of specific humidity for CRTM may slightly improve radiance DA results that use water-vapor-sensitive channels.  There is not expected to be a large impact.

### CODE REVIEW

**Comment by jamiebresch** [comment]
I don't think it is a bug.
xb_q is the base state moisture in specific humidity.
It is simply calculated from mixing ratio: q = r/(1+r) in kg/kg.
Then being converted to g/kg by multiplying 1000.

**Comment by jjguerrette** [comment]
Specific Humidity to Mixing Ratio (kg/kg)
r = q / (1 - q)

Mixing Ratio (kg/kg) to Specific Humidity
q = r / (1 + r)


Specific Humidity to Mixing Ratio (g/kg)
r' = 1000 * q / (1 - q)

Mixing Ratio (kg/kg) to Specific Humidity
q = 0.001 * r' / (1 + 0.001 * r')

**Comment by jamiebresch** [comment]
Yes, you are right. Now I see it is a bug.

**Comment by jjguerrette** [comment]
@jamiebresch, would you like to see results from other tests before approval?  @liujake, what do you think?

**Comment by liujake** [comment]
I need to take a closer look at code logic. Will let you know.

**Comment by liujake** [comment]
@jjguerrette Good catch! I add a bit more documentation here for memory. You may consider also add some comments in the code.

in da_transfer_wrftoxb.inc:
grid%xb%q(i,j,k) = grid%moist(i,j,k,P_QV) ! mixing ratio in kg/kg from wrfinput file

grid%xb%q(i,j,k)=grid%xb%q(i,j,k)/(1.0+grid%xb%q(i,j,k)) ! convert to specific humidity in kg/kg

Note that control variable is q/qs, q (specific humidity) is in kg/kg

da_get_innov_vector_crtm.inc:

call da_interp_2d_partial (grid%xb%q(:,:,k), iv%instid(inst)%info,k,n,n,a) ! q in kg/kg
Atmosphere(1)%Absorber(kte-k+1,1)  = 1000.0 * a(1)/(1.0-a(1))  ! Convert to mixing ratio in g/kg
iv%instid(inst)%qm(k,n)  = Atmosphere(1)%absorber(k,1) ! qm is mixing ratio in g/kg

NOTE: CRTM needs mixing ratio input in g/kg

da_transform_xtoy_crtm.inc

call da_interp_2d_partial (grid%xa%q(:,:,k), iv%instid(inst)%info, k, iv%instid(inst)%info%n1, iv%instid(inst)%info%n2, absorber(kte-k+1,:))

dq and absorber in kg/kg, all is still specific humidity

Atmosphere(n)%absorber(k,1) = iv%instid(inst)%qm(k,n)  ! base state mixing ratio in g/kg.

! convert mixing ratio (in g/kg) to specific humidity (in kg/kg)
xb_q(k,n) = 0.001*iv%instid(inst)%qm(k,n)/(1.0+0.001*iv%instid(inst)%qm(k,n))

! compute dr = 1000 * dq / (1-q)^2, both q and dq in kg/kg, dr in g/kg
Atmosphere_TL(n)%Absorber(kts+1:kte,1)=1000.0/(1.0-xb_q(kts+1:kte,n))**2 * &
                                          absorber(kts+1:kte,n)

**Comment by liujake** [comment]
@YaliWu0219 @xdmjolly this bug fix may have some impact on your AHI WV channel DA.

**Comment by jjguerrette** [comment]
@liujake, would you like those comments added in the code?

**Comment by liujake** [comment]
Yes. That would be helpful to remember it.

**Comment by jjguerrette** [comment]
@davegill and @kkeene44, I think both Jake and myself have lost merging privileges for bug fixes.

**Comment by kkeene44** [comment]
@jjguerrette @liujake 
The settings were modified during the last release and were not changed back correctly after. I've corrected them, and it should work. Let me know if that's not the case.

**Comment by jjguerrette** [comment]
Thank you @kkeene44!  @liujake, is this ready to merge?

**Comment by liujake** [comment]
Yes. Good to go.

**Pull request merged**
