### PR TITLE
Restructure radar DA namelist options.

### PR DESCRIPTION
**Pull request by jamiebresch**
TYPE: enhancement

KEYWORDS: WRFDA, radar, namelist

SOURCE: Jamie Bresch (NCAR/MMM)

DESCRIPTION OF CHANGES:
1. In namelist section wrfvar4, keep only use_radarobs for switching on/off reading radar data.
All other radar-related options are in namelist radar_da section.
2. Replace logical use_radar_rv, use_radar_rf, use_radar_rhv, use_radar_rqv switches with
integer options: radar_rv_opt, radar_rf_opt, radar_rqv_opt.
use_radar_rf and use_radar_rhv are consolidated into radar_rf_opt.
Future new radar reflectivity operator can be implemented as radar_rf_opt=3 and beyond.
3. frame/module_configure.F is modified to notify users about the obsolete options.
4. var/README.namelist is updated.
5. Only changing variable names. No impact to the results.

LIST OF MODIFIED FILES:
    modified:   Registry/registry.var
    modified:   frame/module_configure.F
    modified:   var/README.namelist
    modified:   var/da/da_define_structures/da_allocate_y.inc
    modified:   var/da/da_define_structures/da_define_structures.f90
    modified:   var/da/da_main/da_solve.inc
    modified:   var/da/da_main/da_update_firstguess.inc
    modified:   var/da/da_minimisation/da_minimisation.f90
    modified:   var/da/da_obs_io/da_obs_io.f90
    modified:   var/da/da_obs_io/da_read_obs_radar.inc
    modified:   var/da/da_radar/da_ao_stats_radar.inc
    modified:   var/da/da_radar/da_calculate_grady_radar.inc
    modified:   var/da/da_radar/da_check_max_iv_radar.inc
    modified:   var/da/da_radar/da_get_innov_vector_radar.inc
    modified:   var/da/da_radar/da_jo_and_grady_radar.inc
    modified:   var/da/da_radar/da_oi_stats_radar.inc
    modified:   var/da/da_radar/da_radar.f90
    modified:   var/da/da_radar/da_residual_radar.inc
    modified:   var/da/da_radar/da_transform_xtoy_radar.inc
    modified:   var/da/da_radar/da_transform_xtoy_radar_adj.inc
    modified:   var/da/da_radar/da_write_oa_radar_ascii.inc
    modified:   var/da/da_setup_structures/da_setup_be_nmm_regional.inc
    modified:   var/da/da_setup_structures/da_setup_be_regional.inc
    modified:   var/da/da_setup_structures/da_setup_obs_structures.inc
    modified:   var/da/da_setup_structures/da_setup_obs_structures_radar.inc
    modified:   var/da/da_setup_structures/da_setup_structures.f90
    modified:   var/da/da_statistics/da_statistics.f90
    modified:   var/da/da_test/da_check_vptox_adjoint.inc
    modified:   var/da/da_test/da_check_vtox_adjoint.inc
    modified:   var/da/da_test/da_setup_testfield.inc
    modified:   var/da/da_test/da_test.f90
    modified:   var/da/da_transfer_model/da_transfer_model.f90
    modified:   var/da/da_transfer_model/da_transfer_wrftoxb.inc
    modified:   var/da/da_vtox_transforms/da_vtox_transforms.f90

TESTS CONDUCTED:
A radar case to test that the code.

RELEASE NOTE: Major changes to Radar DA namelist options. Namelist usr_radar_rv, use_radar_rf, use_radar_rhv, use_radar_rqv are removed. Please see var/README.namelist for radar DA options in wrfvar4 and radar_da sections.

### CODE REVIEW

**Comment by jamiebresch** [comment]
It is important to get review feedback from other radar DA developers for this PR #953

**Comment by liujake** [comment]
This namelist change looks good to me. I am afraid this will break some radar cases in WRFDA regression tests. Did you change corresponding namelists in WRFDA regtest?

**Comment by davegill** [comment]
@liujake @jjguerrette 
Folks,
If this is a new piece of code to consider for v4.2, we need a decision this week.

**Comment by liujake** [comment]
This one will not go in v4.2.

**Pull request closed without merging**
