### PR TITLE
MP38 Thompson 2-mom graupel/hail (prev #1667, #1728)

### PR DESCRIPTION
**Pull request by mefrediani**
Option to compute two-moment prognostics for graupel/hail

TYPE: enhancement, new feature

KEYWORDS: microphysics, Thompson microphysics, graupel, hail, double-moment

SOURCE: Code developed by Greg Thompson (JCSDA, UCAR) and Anders Jensen (RAL, NCAR).
Implemented in WRF v4.4 by Maria Frediani (RAL, NCAR)

DESCRIPTION OF CHANGES:

This code update includes

a package to compute two-moment prognostics for graupel/hail and a predicted density graupel category (mp_physics=38); an update to the Y-intercept relationship for one-moment graupel; and it replaces air temperature for wet-bulb temperature in riming and mixed phase processes.

Problem:

One-dimensional graupel/hail growth does not couple to the storm dynamics and is insufficient for predicting more detailed microphysical storm characteristics and hazards such as hail size, density, and fall speed, which can be used to provide guidance on the timing and spatial extent of damaging hail.

Sensitivity studies have shown that using a constant intercept parameter and a constant density can significantly constrain predicted hail size: simulated storms either produced only pea-size or baseball-size hail (Gilmore et al. 2004).

Improving the representation of riming and mixed phase processes leads to improvements in predicted storm dynamics and propagation speed through microphysical feedbacks and also improves the spatial distribution and type of precipitation at the surface.

Solution:

Changes related with the new package mp_physics=38 include:

Variable density for graupel (rho_g)
Parameters become a function of rho_g (am_g, av_g, bv_g, cge, cgg, oamg)
Extra dimension in lookup tables to account for graupel variable density (rho_g)
New source/sink terms for 3-moment graupel
Computation of radar reflectivity and nwp diagnostics using graupel volume mixing ratio
Additional modifications affecting mp_physics=8 and mp_physics=28 include:

Fall speed power law relations (av_i from 1847.5 to 1493.9)
Reduced dimension of cse, csg (from 18 to 17)
Use of wet-bulb temperature for riming and mixed-phase process
Modified relationship for the Y-intercept of one-moment graupel to shift the properties of the graupel category to become more hail-like, resulting in a category that represents both graupel and hail.

LIST OF MODIFIED FILES:
M Registry/Registry.EM_COMMON
M phys/module_diag_nwp.F
M phys/module_diagnostics_driver.F
M phys/module_microphysics_driver.F
M phys/module_mp_thompson.F
M phys/module_physics_init.F

TESTS CONDUCTED:
The modifications were initially demonstrated using the original development made for WRF v4.0 (Jensen et al 2021, under review, MWR-D-21-0319). The operational mp28, mp28 with modified graupel Y-intercept, and mp38 were evaluated for a case study during the PECAN campaign using observed hail sizes from storm reports and estimated from radar. The evaluation showed clear improvement of the simulated reflectivity values in the upper-levels of discrete storms, coinciding with a significant reduction in the areal extent of graupel aloft, also seen when using the updated one-moment scheme. The two-moment and predicted density graupel scheme was also better able to predict a wide variety of hail sizes at the surface, including large (>2-inch in diameter) hail that was observed during this case.

The implementation for this develop branch (aiming at the release v4.4) was tested using a case study from the Relampago campaign and results from mp28, mp38-v4.0, mp38-develop-v4.4 were compared. This comparison indicates that the implementation was successful.

It passed regression tests.

RELEASE NOTES: A package to compute two-moment prognostics for graupel/hail and a predicted density graupel category is added in the Thompson scheme (mp_physics=38); Other updates to the scheme include a change to the Y-intercept relationship for one-moment graupel; and replacement of air temperature for wet-bulb temperature in riming and mixed phase processes.
The code requires a data file to run. This data file: qr_acr_qg_mp38V1.dat can be found on NCAR's computer under /glade/work/wrfhelp/WRF_files/, and online at http://www2.mmm.ucar.edu/wrf/src/wrf_files/. If you prefer to compute this file, set namelist write_thompson_mp38table = true. Note that it can take up to 18 min to compute this table using a 12-CPU job, 4 min on 128-CPU, and several hours if computed on a single CPU.

### CODE REVIEW

**Comment by weiwangncar** [comment]
The Jenkins test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@mefrediani Can you add information on how tables can be obtained before running the code, and if the tables are to be computed, expect long (how long) running times?

**Comment by mefrediani** [comment]
@weiwangncar Would you be able to add the table with the other WRF data files on the webpage? 
The only computationally expensive table is the one specific for MP38. I have one on Glade: /glade/work/frediani/Projects/STEP/thompsontables/qr_acr_qg_mp38V1.dat 
It's a 773M file and the computation times are: 

- 18min using 12 cpus and 45G of memory (tested on Cheyenne, using optimized build)
-  4min using 128 cpus and 180 of memory (PBS select string: 4:32:32, tested on Cheyenne, using debug build)

**Comment by weiwangncar** [comment]
@mefrediani I've added something at the end of the release note. Please take a look and edit if you need to. A user will no typically read the entire PR posts, hence release note is a good way to provide the key information.

**Comment by mefrediani** [comment]
Thank you so much @weiwangncar. I made a small modification to discourage users from trying it on a single CPU job.

**Review by weiwangncar — APPROVED** [review]

**Review by dudhia — APPROVED** [review]

**Comment by weiwangncar** [comment]
@mefrediani I just noticed that your PR is missing RELEASE NOTES. I've added something there but please take a look and see it needs change. Thanks.

**Comment by mefrediani** [comment]
@weiwangncar The release notes look good. Thank you!

**Comment by weiwangncar** [comment]
@mefrediani I've merged your code - congratulations! Can you add some comments in the PR message about your bit-for-bit and restart test results? I think you've done these tests before.

**Comment by mefrediani** [comment]
Thanks @weiwangncar. I updated the PR.

**Comment by andrewsoong** [comment]
I'm so sorry for asking questions in this closed issue. Because my questions here (https://forum.mmm.ucar.edu/threads/can-someone-run-wrf-with-the-thompson-scheme-mp_physics-38-%ef%bc%9f.16604/#post-41020) have no further answers. 
When I used MP=38 in WRF4.5 and WRF4.6, the model crashed immediately. When the MP=8 or 28, the model can be normal operation. So I have to ask, is there any special setting required to use MP = 38? I currently use the namelist.input that comes with WRF. The Forcing is FNL. Thanks！

**Comment by mefrediani** [comment]
> I'm so sorry for asking questions in this closed issue. Because my questions here (https://forum.mmm.ucar.edu/threads/can-someone-run-wrf-with-the-thompson-scheme-mp_physics-38-%ef%bc%9f.16604/#post-41020) have no further answers. When I used MP=38 in WRF4.5 and WRF4.6, the model crashed immediately. When the MP=8 or 28, the model can be normal operation. So I have to ask, is there any special setting required to use MP = 38? I currently use the namelist.input that comes with WRF. The Forcing is FNL. Thanks！

Hi Andrew, I responded to you on the forum. Thanks for reaching out about this.

**Pull request merged**
