### PR TITLE
Fix for lh_urb2d diagnostic

### PR DESCRIPTION
**Pull request by dudhia**
TYPE: bug fix

KEYWORDS: lh_urb2d diagnostic for urban models

SOURCE: internal (reported by Xin-Zhong Liang)

DESCRIPTION OF CHANGES:
Problem:
lh_urb2d was inconsistent with other urban budget arrays sh_urb2d, g_urb2d, and rn_urb2d by being the only one multiplied by the urban fraction making it a grid cell average instead of urban area average. This is only a diagnostic for output.

Solution:
Divide lh_urb2d by frc_urb2d
Won't affect model run results apart from this diagnostic. These arrays are not in default history output.

ISSUE: 

LIST OF MODIFIED FILES: 
phys/module_sf_noahmpdrv.F

TESTS CONDUCTED: 
None.

RELEASE NOTE: 
Fix lh_urb2d diagnostic to be urban area average instead of grid cell average consistent with other urb2d diagnostics. No effect on run results.

### CODE REVIEW

**Comment by dudhia** [comment]
Did not succeed in changing the history. It comes from my fork.

**Comment by weiwangncar** [comment]
@dudhia Can you please change the base?

**Comment by dudhia** [comment]
Yes, I just did. I was not able to remove the spurious history after a few
attempts,
so you saw another PR which I closed.

**Comment by dudhia** [comment]
replaced by #1363

**Pull request closed without merging**
