### PR TITLE
Intel oneAPI LLVM Compilers Configuration

### LINKED ISSUE #1884: WRFv4.5 not compatible with intel llvm compilers
**Describe the bug**
In the later half of 2023, intel will be mothballing their intel compilers (icc,ifort,icpc) for new intel compilers that are built on the llvm architecture.

These new commands are:

> export CC=icx
export CXX=icpx
export FC=ifx
export F77=ifx
export F90=ifx
export MPIFC="mpiifort -fc=ifx"
export MPIF77="mpiifort -fc=ifx"
export MPIF90="mpiifort -fc=ifx"
export MPICC="mpiicc -cc=icx"
export MPICXX="mpiicpc -cxx=icpx"

wrf v4.5 is not compatibile with these new llvm compilers and will make the intel compilers for new users useless.  Anyone who has intel compilers and update their intel compiler packages will also lose the ability to use them.  This is a MAJOR problem for the WRF community.

**To Reproduce**

Attached is a couple of scripts that show how to install the required libraries needed to run WRF using the intel llvm compilers.  
All system tests pass so the new intel llvm compilers 

However, when you change the old intel compilers listed in the configure.wrf for the new llvm compilers the wrf will not install.

**Expected behavior**
wrf v4.5 expected to install with new llvm installers without having to modify any major files.

**Attachments**
wrf_4.5_new_intel_commands.sh:  This is a script that installs all the required libraries for WRF.  It works when using the old intel compilers as it is currently being used on github.
wrf.new.inte.compile.log: Build log using the new intel compilers.
configure.wrf: this is the configure file built using the new intel llvm compilers.

~~WRF_v4.5_Intel_LLVM_Compilers.tar.gz~~
*Edit: link removed*

### PR DESCRIPTION
**Pull request by islas**
Addition of compile configuration using the new Intel LLVM compilers ifx and icx for Fortran and C code, respectively

TYPE: enhancement

KEYWORDS: Intel, LLVM, oneAPI, compilation

SOURCE: internal

DESCRIPTION OF CHANGES:
Problem:
Addressing issue #1884 for Intel oneAPI ifx/icx builds

Solution:
Add configuration to `configure.defaults` mirroring original Intel ifort/icc build with minor tweaking

ISSUE: For use when this PR closes an issue.
Fixes #1884 

LIST OF MODIFIED FILES:
M       arch/configure.defaults

TESTS CONDUCTED: 
1. WRF Core em_real compiles with ifx/icx (see attached log)

RELEASE NOTE: 
Added build configuration for new Intel oneAPI LLVM ifx/icx compilers

[build_llvm.log](https://github.com/wrf-model/WRF/files/11941166/build_llvm.log)

### CODE REVIEW

**Comment by HathewayWill** [comment]
> Addition of compile configuration using the new Intel LLVM compilers ifx and icx for Fortran and C code, respectively
> 
> TYPE: enhancement
> 
> KEYWORDS: Intel, LLVM, oneAPI, compilation
> 
> SOURCE: internal
> 
> DESCRIPTION OF CHANGES: Problem: Addressing issue #1884 for Intel oneAPI ifx/icx builds
> 
> Solution: Add configuration to `configure.defaults` mirroring original Intel ifort/icc build with minor tweaking
> 
> ISSUE: For use when this PR closes an issue. Fixes #1884
> 
> LIST OF MODIFIED FILES: M arch/configure.defaults
> 
> TESTS CONDUCTED:
> 
> 1. WRF Core em_real compiles with ifx/icx (see attached log)
> 
> RELEASE NOTE: Added build configuration for new Intel oneAPI LLVM ifx/icx compilers
> 
> [build_llvm.log](https://github.com/wrf-model/WRF/files/11941166/build_llvm.log)

@islas 

So in your merger you put this in:

```
DM_FC           =       mpif90 -f90=$(SFC)
DM_CC           =       mpicc -cc=$(SCC)
```

According to intel support:
https://community.intel.com/t5/Intel-oneAPI-HPC-Toolkit/Future-of-HPCtoolkit/m-p/1429431#M10028
These are the way the commands need to be formatted:

```

  export CC=icx
  export CXX=icpx
  export FC=ifx
  export F77=ifx
  export F90=ifx
  export MPIFC="mpiifort -fc=ifx"
  export MPIF77="mpiifort -fc=ifx"
  export MPIF90="mpiifort -fc=ifx"
  export MPICC="mpiicc -cc=icx"
  export MPICXX="mpiicpc -cxx=icpx"


```

**Comment by islas** [comment]
@HathewayWill I believe the guidance provided in the intel forum by the moderator was to address the specific issues of the `bash export` command not taking spaced arguments without quotes. Using the same methodology other WRF configurations use does yield MPI using the new Intel compilers. A quick peak into the executable produced outputs:
```
strings main/wrf.exe | grep -i oneapi
Intel(R) oneAPI DPC++/C++ Compiler 2022.0.0 (2022.0.0.20211123)
```

**Comment by weiwangncar** [comment]
Regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by HathewayWill** [comment]
> @HathewayWill I believe the guidance provided in the Intel forum by the moderator was to address the specific issues of the `bash export` command not taking spaced arguments without quotes. Using the same methodology other WRF configurations use does yield MPI using the new Intel compilers. A quick peek into the executable produced outputs:
> 
> ```
> strings main/wrf.exe | grep -i oneapi
> Intel(R) oneAPI DPC++/C++ Compiler 2022.0.0 (2022.0.0.20211123)
> ```

@weiwangncar @islas 

I guess my only concern about this merger is what I have read from the configure.wrf file.

```

#        If you have Intel MPI installed and wish to use instead, make the
#        following changes to settings below:
#        DM_FC  = mpiifort
#        DM_CC  = mpiicc
#        and source bin64/mpivars.sh file from your Intel MPI installation
#        before the build.
```

I have tried using the intel LLVM mpiifort commands in WRFv4.5 and the code doesn't not like the "-fc=icx"

**Comment by HathewayWill** [comment]
> > @HathewayWill I believe the guidance provided in the Intel forum by the moderator was to address the specific issues of the `bash export` command not taking spaced arguments without quotes. Using the same methodology other WRF configurations use does yield MPI using the new Intel compilers. A quick peek into the executable produced outputs:
> > ```
> > strings main/wrf.exe | grep -i oneapi
> > Intel(R) oneAPI DPC++/C++ Compiler 2022.0.0 (2022.0.0.20211123)
> > ```
> 
> @weiwangncar @islas
> 
> I guess my only concern about this merger is what I have read from the configure.wrf file.
> 
> ```
> 
> #        If you have Intel MPI installed and wish to use instead, make the
> #        following changes to settings below:
> #        DM_FC  = mpiifort
> #        DM_CC  = mpiicc
> #        and source bin64/mpivars.sh file from your Intel MPI installation
> #        before the build.
> ```
> 
> I have tried using the intel LLVM mpiifort commands in WRFv4.5 and the code doesn't not like the "-fc=icx"

@islas @weiwangncar @kkeene44 

I don't think this merger needs to be blocked I just am curious if the -fc=icx flag for the compiler will take.  Because right now both the non llvm MPI (mpiifort) and LLVM MPI (mpiifort -fc=ifx) exist in the current intel compilers that you can get online.  so mpiifort will still run.

Just my thoughts is all.  Trying to help.

**Comment by weiwangncar** [comment]
@islas @mgduda Should we consider this for 4.5.1 since we will have access to Derecho soon?

**Comment by mgduda** [comment]
> @islas @mgduda Should we consider this for 4.5.1 since we will have access to Derecho soon?

I think this would be good to include.

**Review by mgduda — APPROVED** [review]

**Review by weiwangncar — APPROVED** [review]

**Comment by HathewayWill** [comment]
> @HathewayWill I believe the guidance provided in the Intel forum by the moderator was to address the specific issues of the `bash export` command not taking spaced arguments without quotes. Using the same methodology other WRF configurations use does yield MPI using the new Intel compilers. A quick peek into the executable produced outputs:
> 
> ```
> strings main/wrf.exe | grep -i oneapi
> Intel(R) oneAPI DPC++/C++ Compiler 2022.0.0 (2022.0.0.20211123)
> ```

@islas  @weiwangncar 

How would you use Intel compilers mentioned in the configure.wrf guide with the new llvm compilers

```
#        If you have Intel MPI installed and wish to use instead, make the
#        following changes to settings below:
#        DM_FC  = mpiifort
#        DM_CC  = mpiicc
#        and source bin64/mpivars.sh file from your Intel MPI installation
#        before the build.
```
if DM_FC nedds to be mpiifort -fc=ifx  and DM_CC needs to be mpiicc -cc=icx?

I haven't gotten that to work.   Have you?  If so how did you do it?

**Comment by weiwangncar** [comment]
@islas What modules does one need to use this option on Derecho?

**Comment by islas** [comment]
> @islas What modules does one need to use this option on Derecho?

This will not build on Derecho as it currently is. It will build on Cheyenne with the `intel/2022.1` and `netcdf` modules. Derecho only has later versions that then enforce ISO C99 requirements.
Assuming merged #1823, `intel` or `intel-oneapi` (synonymous) and `netcdf` on Derecho should work. I've tested the latest versions on a separate system and the module on Derecho in an interactive job*

\* I'm having difficulty compiling [with a limited number of make `-j` jobs down to just `-j 1`] on the login node, I suspect this is due to memory issues when compiling very large files. This problem is not evident in my other tests

**Pull request merged**
