### PR TITLE
Bug fix FARMS to use correct cloud transmittance

### PR DESCRIPTION
**Pull request by pedro-jm**
TYPE: bug fix

KEYWORDS: FARMS, undefined variable, cloud transmittance

SOURCE: Pedro A. Jimenez and Jimy Dudhia (NCAR), and Jaemo Yang and Yu Xie (NREL)

DESCRIPTION OF CHANGES:
Problem: Incorrect treatment of transmittance of diffuse radiation by clouds in FARMS

Solution:
Change the cloud transmittance and initialize variables before using them

LIST OF MODIFIED FILES: 
M       phys/module_ra_farms.F

TESTS CONDUCTED: 
1. The impact of these mods should be small.
There is no impact on the results in the test we run. We used Intel compiler which I think initializes values to 0 if the variables are not defined. And 0 happens to be the right value in this case.

2. Jenkins tests are all passing.

RELEASE NOTE: Corrected the incorrect treatment of cloud transmittances of diffuse radiation by clouds in the FARMS system. The impact of these mods are small.

### CODE REVIEW

**Comment by dudhia** [comment]
state something about effect on results if any.

**Comment by dudhia** [comment]
Confirmation of test result needs to be added for approval. Also note that this was mainly to pass a configure -D test as it had no effect on results.

**Comment by pedro-jm** [comment]
@dudhia
There is no impact on the results in the test we run. We used Intel compiler which I think initializes values to 0 if the variables are not defined. And 0 happens to be the right value in this case.
Pedro.

**Comment by pedro-jm** [comment]
Would it be possible to incorporate this fix in v4.3?

**Comment by dudhia** [comment]
Yes, it is already in that queue.

**Comment by pedro-jm** [comment]
wonderful.

**Comment by dudhia** [comment]
@pedro-jm can you update the test result message before I approve this?

**Comment by weiwangncar** [comment]
I'm ok with this PR.

**Comment by pedro-jm** [comment]
@dudhia 
I just updated the result test message.

**Review by dudhia — APPROVED** [review]

**Comment by dudhia** [comment]
OK, I approved it.

**Pull request merged**
