### PR TITLE
AOCC compiler configuration

### PR DESCRIPTION
**Pull request by yaduvanshirishi**
Added AOCC compiler configuration under arc/configure.defaults

### CODE REVIEW

**Comment by yaduvanshirishi** [comment]
Some Fix pending

**Comment by nzahasan** [comment]
@yaduvanshirishi is this usable?

**Comment by yaduvanshirishi** [comment]
Yeah, actually i had used the aocc compiler in WRF using this configuration

**Comment by nzahasan** [comment]
@yaduvanshirishi  thank you!

**Comment by nzahasan** [comment]
@yaduvanshirishi have you noticed any performance difference?

**Comment by davegill** [comment]
@yaduvanshirishi 
Why was this PR closed?

**Comment by yaduvanshirishi** [comment]
Actually that time I didn't have information about PR, so I closed and forked.

**Comment by nzahasan** [comment]
So far serial compilation work, need work to compile with dmpar.

**Pull request closed without merging**
