### PR TITLE
Remove necessity to run 'run_me_first' scripts for ideal cases

### PR DESCRIPTION
**Pull request by davegill**
TYPE: enhancement

KEYWORDS: ideal, run_me_first.csh, link, Makefile, 

SOURCE: Internal

DESCRIPTION OF CHANGES:
Problem:
Several ideal cases (em_b_wave, em_convrad, em_quarter_ss, em_scm_xy, em_seabreeze2d_x, and em_tropical_cyclone) 
need additional linked files to run. Previously it was necessary for users to run a script called 'run_me_first.csh' to 
link-in the necessary files.  

Solution:
Removed all 'run_me_first.csh' scripts from ideal case directories and modified the top-level Makefile so that now the 
files are linked during the compile.

LIST OF MODIFIED FILES: 
M       Makefile
D       test/em_b_wave/run_me_first.csh
D       test/em_convrad/run_me_first.csh
D       test/em_quarter_ss/run_me_first.csh
D       test/em_scm_xy/run_me_first.csh
D       test/em_seabreeze2d_x/run_me_first.csh
D       test/em_tropical_cyclone/run_me_first.csh

TESTS CONDUCTED: 
1. Ensured that code compiles and required files are linked for all modified ideal cases.
2. Jenkins is all pass.

RELEASE NOTE: It is no longer necessary to execute a 'run_me_first.csh' script for any of the idealized cases. All necessary physics input files and look-up tables are linked to the corresponding directory during the compilation step.

### CODE REVIEW

**Comment by davegill** [comment]
replaces PR #1406 "Remove requirement to run 'run_me_first' scripts for ideal cases"

**Comment by davegill** [comment]
@kkeene44 
Kelly,
After the p3 PR, you had six conflicts, because Hugh updated all the files and you deleted all of the files. The git source manager was scratching its head. I tried to push the fixes (basically - delete everything) to your branch, but I was not powerful enough. 

Anyways, once the jenkins tests pass, I'll send you a note, and then would you please approve this (originally your) PR? When this PR becomes super important, now I'll always be remembered as the author.

**Comment by davegill** [comment]
jenkins:
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: afeab4ec0e34598091fa93f776a7a7dd0b7782fd, requested by: davegill for PR: https://github.com/wrf-model/WRF/pull/1415. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           18
    Number of Builds       : 48           46
    Number of Simulations  : 163           161        0
    Number of Comparisons  : 103           102        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```

**Comment by davegill** [comment]
@kkeene44 
Please review _YOUR_ PR, and commit.
Jenkins is OK.
The "run_me's" are gone.

**Review by kkeene44 — APPROVED** [review]

**Comment by weiwangncar** [comment]
@kkeene44 @davegill Maybe we can change 'Remove requirement... ' to 'Remove necessity... ' in the title of this PR?

**Pull request merged**
