### PR TITLE
Begin NMM removal from source code

### PR DESCRIPTION
**Pull request by davegill**
TYPE: feature removed

KEYWORDS: NMM

SOURCE: internal

DESCRIPTION OF CHANGES:
If we consider the act of adding in new features to the WRF repository as a "constructionist" activity, then this
PR begins the largest deconstructionist effort ever undertake in WRF.

The Philosophy of Deconstructivism places an emphasis on appearance.

Perhaps the bard has a quote appropos to someone working on a commit for a PR, where that PR is at once a massive 
change and yet is intended to have exactly zero impact: 
_It is a tale. Told by an idiot, full of sound and fury, Signifying nothing._

LIST OF MODIFIED FILES:
_Deleted:_
D	Registry/Registry.NMM
D	dyn_nmm/BALANCE_COMS.F
D	dyn_nmm/BALANCE_PARS.F
D	dyn_nmm/BUCKETS.F
D	dyn_nmm/CLTEND.F
D	dyn_nmm/DSTRB.F
D	dyn_nmm/Makefile
D	dyn_nmm/NMM_NEST_UTILS1.F
D	dyn_nmm/RDTEMP.F
D	dyn_nmm/adve_optim.h
D	dyn_nmm/adve_orig.h
D	dyn_nmm/depend.dyn_nmm
D	dyn_nmm/init_modules_nmm.F
D	dyn_nmm/module_ADVECTION.F
D	dyn_nmm/module_BC_NMM.F
D	dyn_nmm/module_BNDRY_COND.F
D	dyn_nmm/module_CLDWTR.F
D	dyn_nmm/module_CTLBLK.F
D	dyn_nmm/module_DIFFUSION_NMM.F
D	dyn_nmm/module_GWD.F
D	dyn_nmm/module_HIFREQ.F
D	dyn_nmm/module_IGWAVE_ADJUST.F
D	dyn_nmm/module_INDX.F
D	dyn_nmm/module_MPP.F
D	dyn_nmm/module_MPPINIT.F
D	dyn_nmm/module_NEST_UTIL.F
D	dyn_nmm/module_NONHY_DYNAM.F
D	dyn_nmm/module_PHYSICS_CALLS.F
D	dyn_nmm/module_PRECIP_ADJUST.F
D	dyn_nmm/module_SMOOTH_TERRAIN.F
D	dyn_nmm/module_STATS_FOR_MOVE.F
D	dyn_nmm/module_TERRAIN.F
D	dyn_nmm/module_TIMERS.F
D	dyn_nmm/module_ZEROX.F
D	dyn_nmm/module_initialize_real.F
D	dyn_nmm/module_initialize_tropical_cyclone.F
D	dyn_nmm/module_membrane_mslp.F
D	dyn_nmm/module_relax.F
D	dyn_nmm/module_si_io_nmm.F
D	dyn_nmm/module_swath.F
D	dyn_nmm/module_tornado_genesis.F
D	dyn_nmm/module_tracker.F
D	dyn_nmm/nmm_get_cpu.c
D	dyn_nmm/nmm_loop_basemacros.h
D	dyn_nmm/nmm_loop_macros.h
D	dyn_nmm/shift_domain_nmm.F
D	dyn_nmm/solve_nmm.F
D	dyn_nmm/start_domain_nmm.F
D	frame/module_io_quilt_new.F
D	phys/module_mp_HWRF.F
D	phys/module_ra_HWRF.F
D	test/nmm_real/namelist.input
D	test/nmm_real/namelist.input.HWRF
D	test/nmm_real/tomorrow
D	test/nmm_tropical_cyclone/README.NMM.TROPICAL_CYCLONE
D	test/nmm_tropical_cyclone/input.d
D	test/nmm_tropical_cyclone/land.nml
D	test/nmm_tropical_cyclone/namelist.input
D	test/nmm_tropical_cyclone/namelist.wps
D	test/nmm_tropical_cyclone/sigma.d
D	test/nmm_tropical_cyclone/sound.d
D	test/nmm_tropical_cyclone/sound_gfdl.d
D	test/nmm_tropical_cyclone/sound_jordan.d
D	test/nmm_tropical_cyclone/sound_wet.d
D	test/nmm_tropical_cyclone/storm.center

_Modified:_
M	.github/CODEOWNERS
M	Makefile
M	clean
M	compile
M	configure
M	external/RSL_LITE/gen_comms.c
M	external/RSL_LITE/module_dm.F
M	external/RSL_LITE/tfp_tester.F
M	frame/Makefile
M	frame/module_bdywrite.F
M	frame/module_dm_stubs.F
M	frame/module_domain.F
M	frame/module_integrate.F
M	frame/module_io_quilt.F
M	frame/module_nesting.F
M	frame/module_wrf_error.F
M	main/Makefile
M	main/depend.common
M	phys/Makefile
M	phys/module_cumulus_driver.F
M	phys/module_diagnostics_driver.F
M	phys/module_fddagd_driver.F
M	phys/module_microphysics_driver.F
M	phys/module_pbl_driver.F
M	phys/module_radiation_driver.F
M	phys/module_surface_driver.F
M	share/dfi.F
M	share/init_modules.F
M	share/input_wrf.F
M	share/interp_fcn.F
M	share/mediation_feedback_domain.F
M	share/mediation_force_domain.F
M	share/mediation_integrate.F
M	share/mediation_interp_domain.F
M	share/mediation_nest_move.F
M	share/mediation_wrfmain.F
M	share/module_check_a_mundo.F
M	share/module_interp_store.F
M	share/module_model_constants.F
M	share/module_optional_input.F
M	share/module_soil_pre.F
M	share/module_trajectory.F
M	share/output_wrf.F
M	share/set_timekeeping.F
M	share/solve_interface.F
M	share/start_domain.F
M	share/wrf_ext_write_field.F
M	share/wrf_timeseries.F
M	var/build/depend.txt

TESTS CONDUCTED:
1. No "problems" per se. Just removing deadwood code.
2. All Jenkins tests are a PASS.
3. DA code still builds.
4. Restart tests OK.
5. Results for each regression test are identical before vs after.
6. Results for larger tests cases are also bit-for-bit (Wei Wang).
7. Code passes DA regression tests (Jake Liu).

RELEASE NOTE: Starting with release-v4.4, the NMM dynamical core and some NMM-specific source code are being removed from the WRF repository. WRF release-v4.3.x is the latest release with the NMM build options still available.

### CODE REVIEW

**Comment by davegill** [comment]
@mgduda 
Michael,
Just an FYI ... We are going to be removing NMM options from the WRF repository for the v4.4 April release. This will be a lot of mods, and perhaps not all gets done. Anyways, you may begin removing some high-level NMM functionality in geogrid and metgrid, should you like.

**Comment by davegill** [comment]
@kkeene44 
Kelly,
Since NMM is going away, perhaps review the list of WRF repo administrators. Any NMM folks can be removed.

**Comment by weiwangncar** [comment]
@davegill Would it be possible to check ARW results before and after this 'deconstruction'?

**Comment by davegill** [comment]
@weiwangncar 
Wei,
I was thinking about this also. This will be tricky, but it needs to be done. There are too many possible ways to make a mistake.

**Comment by dudhia** [comment]
Maybe the regtest outputs could be saved and compared before and after for
bit-for-bit differences? This covers a lot of namelist options.

**Comment by davegill** [comment]
[ x ] DA build test pass
[ x ] Feature tests pass
[ x ] standard regression tests pass
```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: 7c3ae81546dbce357e6e593b0d03fd8fb990af0b, requested by: davegill for PR: https://github.com/scala-computing/WRF/pull/1584. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           59
    Number of Simulations  : 159           98        0
    Number of Comparisons  : 101           46        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```

**Comment by weiwangncar** [comment]
@davegill I cloned your repo, and checked out NO_NMM, the compilation using ifort, full optimization, on Cheyenne failed. Here is the first error:
mediation_force_domain.f90(7): error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [MODULE_INTERMEDIATE_NMM]
   USE module_intermediate_nmm
-------^
compilation aborted for mediation_force_domain.f90 (code 1)

**Comment by weiwangncar** [comment]
@davegill Removing 'USE module_intermediate_nmm' in mediation_force_domain.F allowed the code to compile on Cheyenne.

**Comment by weiwangncar** [comment]
@davegill Great job so far! I made one test using wrf.exe before and after code from this PR, and I got identical results.

**Comment by weiwangncar** [comment]
@davegill Another similar, but nested run, also passed check.

**Comment by davegill** [comment]
@weiwangncar 
Wei,
1. I'll take a look at the intermediate_nmm compile issue. There is still a LOT to do, but we _do_ want the code to build with each commit. Thanks for testing this.
2. I think that we can compare EVERY test that the WRF model runs in the regression test. We have these small output files that have L2 norms of the simulation. These are text files with just a few numbers in them. We should be able to do a diff of those BEFORE vs AFTER text files. Not this week, but probably next week.

**Comment by davegill** [comment]
@weiwangncar 
> Removing 'USE module_intermediate_nmm' in mediation_force_domain.F allowed the code to compile on Cheyenne.

Wei,
I tested your mod with GNU and Intel - works fine, so that is merged in.

**Comment by davegill** [comment]
@weiwangncar @dudhia 
>Would it be possible to check ARW results before and after this 'deconstruction'?

Folks,
I have modified the regression system to allow before vs after checking. For each of the tests that are conducted, the mods to this NO_NMM branch give bit-wise identical to the develop branch from which this NO_NMM branch was cut.

**Comment by dudhia** [comment]
Sounds good. Thanks,

**Comment by davegill** [comment]
@liujake 
Jake,
This PR is ready for you to do some testing. The WRFPlus code does build an executable successfully:
```
SUCCESS BUILD WRFPlus
56868 -rwxr-xr-x 1 wrfuser wrf 58230600 Nov 24 20:28 main/wrfplus.exe
```

**Comment by davegill** [comment]
@weiwangncar @dudhia 
Folks,
All of the following tests are bit-for-bit when comparing before and after the NO_NMM mods (basically, every test we run is the same):
```
SUCCESS_RUN_WRF1_em_real_34_restartA_basic
SUCCESS_RUN_WRF1_em_real_34_restartA_dfi
SUCCESS_RUN_WRF2_em_real_34_restartA_basic
SUCCESS_RUN_WRF2_em_real_34_restartA_dfi
SUCCESS_RUN_WRF_d01_em_b_wave_32_em_b_wave_1NE
SUCCESS_RUN_WRF_d01_em_b_wave_32_em_b_wave_2
SUCCESS_RUN_WRF_d01_em_b_wave_32_em_b_wave_2NE
SUCCESS_RUN_WRF_d01_em_b_wave_32_em_b_wave_3
SUCCESS_RUN_WRF_d01_em_b_wave_33_em_b_wave_1NE
SUCCESS_RUN_WRF_d01_em_b_wave_33_em_b_wave_2
SUCCESS_RUN_WRF_d01_em_b_wave_33_em_b_wave_2NE
SUCCESS_RUN_WRF_d01_em_b_wave_33_em_b_wave_3
SUCCESS_RUN_WRF_d01_em_b_wave_34_em_b_wave_1NE
SUCCESS_RUN_WRF_d01_em_b_wave_34_em_b_wave_2
SUCCESS_RUN_WRF_d01_em_b_wave_34_em_b_wave_2NE
SUCCESS_RUN_WRF_d01_em_b_wave_34_em_b_wave_3
SUCCESS_RUN_WRF_d01_em_fire_32_em_fire_01
SUCCESS_RUN_WRF_d01_em_fire_33_em_fire_01
SUCCESS_RUN_WRF_d01_em_fire_34_em_fire_01
SUCCESS_RUN_WRF_d01_em_hill2d_x_32_em_hill2d_x_01
SUCCESS_RUN_WRF_d01_em_quarter_ss_32_em_quarter_ss8_08
SUCCESS_RUN_WRF_d01_em_quarter_ss_32_em_quarter_ss8_09
SUCCESS_RUN_WRF_d01_em_quarter_ss_32_em_quarter_ss_02NE
SUCCESS_RUN_WRF_d01_em_quarter_ss_32_em_quarter_ss_03
SUCCESS_RUN_WRF_d01_em_quarter_ss_32_em_quarter_ss_03NE
SUCCESS_RUN_WRF_d01_em_quarter_ss_33_em_quarter_ss8_08
SUCCESS_RUN_WRF_d01_em_quarter_ss_33_em_quarter_ss8_09
SUCCESS_RUN_WRF_d01_em_quarter_ss_33_em_quarter_ss_02NE
SUCCESS_RUN_WRF_d01_em_quarter_ss_33_em_quarter_ss_03
SUCCESS_RUN_WRF_d01_em_quarter_ss_33_em_quarter_ss_03NE
SUCCESS_RUN_WRF_d01_em_quarter_ss_34_em_quarter_ss8_08
SUCCESS_RUN_WRF_d01_em_quarter_ss_34_em_quarter_ss8_09
SUCCESS_RUN_WRF_d01_em_quarter_ss_34_em_quarter_ss_02NE
SUCCESS_RUN_WRF_d01_em_quarter_ss_34_em_quarter_ss_03
SUCCESS_RUN_WRF_d01_em_quarter_ss_34_em_quarter_ss_03NE
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_1
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_2
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_5
SUCCESS_RUN_WRF_d01_em_real_32_em_real8_14
SUCCESS_RUN_WRF_d01_em_real_32_em_real8_17AD
SUCCESS_RUN_WRF_d01_em_real_32_em_realA_03
SUCCESS_RUN_WRF_d01_em_real_32_em_realA_03DF
SUCCESS_RUN_WRF_d01_em_real_32_em_realB_10
SUCCESS_RUN_WRF_d01_em_real_32_em_realB_11
SUCCESS_RUN_WRF_d01_em_real_32_em_realB_14
SUCCESS_RUN_WRF_d01_em_real_32_em_realB_16
SUCCESS_RUN_WRF_d01_em_real_32_em_realC_17
SUCCESS_RUN_WRF_d01_em_real_32_em_realC_18
SUCCESS_RUN_WRF_d01_em_real_32_em_realC_20
SUCCESS_RUN_WRF_d01_em_real_32_em_realD_38
SUCCESS_RUN_WRF_d01_em_real_32_em_realD_48
SUCCESS_RUN_WRF_d01_em_real_32_em_realD_49
SUCCESS_RUN_WRF_d01_em_real_32_em_realE_52
SUCCESS_RUN_WRF_d01_em_real_32_em_realE_52DF
SUCCESS_RUN_WRF_d01_em_real_32_em_realF_65DF
SUCCESS_RUN_WRF_d01_em_real_32_em_realG_kiaps1NE
SUCCESS_RUN_WRF_d01_em_real_32_em_realG_kiaps2
SUCCESS_RUN_WRF_d01_em_real_32_em_realH_cmt
SUCCESS_RUN_WRF_d01_em_real_32_em_realH_solaraNE
SUCCESS_RUN_WRF_d01_em_real_32_em_realH_urb3bNE
SUCCESS_RUN_WRF_d01_em_real_32_em_realI_03FD
SUCCESS_RUN_WRF_d01_em_real_32_em_realI_06
SUCCESS_RUN_WRF_d01_em_real_32_em_realI_07NE
SUCCESS_RUN_WRF_d01_em_real_32_em_realJ_50
SUCCESS_RUN_WRF_d01_em_real_32_em_realJ_51
SUCCESS_RUN_WRF_d01_em_real_32_em_realK_52FD
SUCCESS_RUN_WRF_d01_em_real_32_em_realK_60
SUCCESS_RUN_WRF_d01_em_real_32_em_realK_60NE
SUCCESS_RUN_WRF_d01_em_real_32_em_realL_66FD
SUCCESS_RUN_WRF_d01_em_real_32_em_realL_71
SUCCESS_RUN_WRF_d01_em_real_32_em_realL_78
SUCCESS_RUN_WRF_d01_em_real_32_em_realL_79
SUCCESS_RUN_WRF_d01_em_real_32_em_real_3dtke
SUCCESS_RUN_WRF_d01_em_real_32_em_real_conus
SUCCESS_RUN_WRF_d01_em_real_32_em_real_rap
SUCCESS_RUN_WRF_d01_em_real_32_em_real_tropical
SUCCESS_RUN_WRF_d01_em_real_33_em_real8_14
SUCCESS_RUN_WRF_d01_em_real_33_em_real8_17AD
SUCCESS_RUN_WRF_d01_em_real_33_em_realA_03
SUCCESS_RUN_WRF_d01_em_real_33_em_realA_03DF
SUCCESS_RUN_WRF_d01_em_real_33_em_realB_10
SUCCESS_RUN_WRF_d01_em_real_33_em_realB_11
SUCCESS_RUN_WRF_d01_em_real_33_em_realB_14
SUCCESS_RUN_WRF_d01_em_real_33_em_realB_16
SUCCESS_RUN_WRF_d01_em_real_33_em_realC_17
SUCCESS_RUN_WRF_d01_em_real_33_em_realC_18
SUCCESS_RUN_WRF_d01_em_real_33_em_realC_20
SUCCESS_RUN_WRF_d01_em_real_33_em_realD_38
SUCCESS_RUN_WRF_d01_em_real_33_em_realD_48
SUCCESS_RUN_WRF_d01_em_real_33_em_realD_49
SUCCESS_RUN_WRF_d01_em_real_33_em_realE_52
SUCCESS_RUN_WRF_d01_em_real_33_em_realE_52DF
SUCCESS_RUN_WRF_d01_em_real_33_em_realF_65DF
SUCCESS_RUN_WRF_d01_em_real_33_em_realG_kiaps1NE
SUCCESS_RUN_WRF_d01_em_real_33_em_realG_kiaps2
SUCCESS_RUN_WRF_d01_em_real_33_em_realI_03FD
SUCCESS_RUN_WRF_d01_em_real_33_em_realI_06
SUCCESS_RUN_WRF_d01_em_real_33_em_realI_07NE
SUCCESS_RUN_WRF_d01_em_real_33_em_realJ_50
SUCCESS_RUN_WRF_d01_em_real_33_em_realJ_51
SUCCESS_RUN_WRF_d01_em_real_33_em_realK_52FD
SUCCESS_RUN_WRF_d01_em_real_33_em_realK_60
SUCCESS_RUN_WRF_d01_em_real_33_em_realK_60NE
SUCCESS_RUN_WRF_d01_em_real_33_em_realL_66FD
SUCCESS_RUN_WRF_d01_em_real_33_em_realL_71
SUCCESS_RUN_WRF_d01_em_real_33_em_realL_78
SUCCESS_RUN_WRF_d01_em_real_33_em_realL_79
SUCCESS_RUN_WRF_d01_em_real_33_em_real_3dtke
SUCCESS_RUN_WRF_d01_em_real_33_em_real_conus
SUCCESS_RUN_WRF_d01_em_real_33_em_real_rap
SUCCESS_RUN_WRF_d01_em_real_33_em_real_tropical
SUCCESS_RUN_WRF_d01_em_real_34_em_chem_1
SUCCESS_RUN_WRF_d01_em_real_34_em_chem_2
SUCCESS_RUN_WRF_d01_em_real_34_em_chem_5
SUCCESS_RUN_WRF_d01_em_real_34_em_move_01
SUCCESS_RUN_WRF_d01_em_real_34_em_real8_14
SUCCESS_RUN_WRF_d01_em_real_34_em_real8_17AD
SUCCESS_RUN_WRF_d01_em_real_34_em_realA_03
SUCCESS_RUN_WRF_d01_em_real_34_em_realA_03DF
SUCCESS_RUN_WRF_d01_em_real_34_em_realB_10
SUCCESS_RUN_WRF_d01_em_real_34_em_realB_11
SUCCESS_RUN_WRF_d01_em_real_34_em_realB_14
SUCCESS_RUN_WRF_d01_em_real_34_em_realB_16
SUCCESS_RUN_WRF_d01_em_real_34_em_realC_17
SUCCESS_RUN_WRF_d01_em_real_34_em_realC_18
SUCCESS_RUN_WRF_d01_em_real_34_em_realC_20
SUCCESS_RUN_WRF_d01_em_real_34_em_realD_38
SUCCESS_RUN_WRF_d01_em_real_34_em_realD_48
SUCCESS_RUN_WRF_d01_em_real_34_em_realD_49
SUCCESS_RUN_WRF_d01_em_real_34_em_realE_52
SUCCESS_RUN_WRF_d01_em_real_34_em_realE_52DF
SUCCESS_RUN_WRF_d01_em_real_34_em_realF_65DF
SUCCESS_RUN_WRF_d01_em_real_34_em_realG_kiaps1NE
SUCCESS_RUN_WRF_d01_em_real_34_em_realG_kiaps2
SUCCESS_RUN_WRF_d01_em_real_34_em_realH_cmt
SUCCESS_RUN_WRF_d01_em_real_34_em_realH_solaraNE
SUCCESS_RUN_WRF_d01_em_real_34_em_realH_urb3bNE
SUCCESS_RUN_WRF_d01_em_real_34_em_realI_03FD
SUCCESS_RUN_WRF_d01_em_real_34_em_realI_06
SUCCESS_RUN_WRF_d01_em_real_34_em_realI_07NE
SUCCESS_RUN_WRF_d01_em_real_34_em_realJ_50
SUCCESS_RUN_WRF_d01_em_real_34_em_realJ_51
SUCCESS_RUN_WRF_d01_em_real_34_em_realK_52FD
SUCCESS_RUN_WRF_d01_em_real_34_em_realK_60
SUCCESS_RUN_WRF_d01_em_real_34_em_realK_60NE
SUCCESS_RUN_WRF_d01_em_real_34_em_realL_66FD
SUCCESS_RUN_WRF_d01_em_real_34_em_realL_71
SUCCESS_RUN_WRF_d01_em_real_34_em_realL_78
SUCCESS_RUN_WRF_d01_em_real_34_em_realL_79
SUCCESS_RUN_WRF_d01_em_real_34_em_real_3dtke
SUCCESS_RUN_WRF_d01_em_real_34_em_real_conus
SUCCESS_RUN_WRF_d01_em_real_34_em_real_rap
SUCCESS_RUN_WRF_d01_em_real_34_em_real_tropical
```

**Comment by davegill** [comment]
@liujake 
Jake,
The regression test now does the two tests:
```
./configure wrfplus
./compile wrfplus
```
and
```
./configure 4dvar
./compile all_wrfvar
```

These both pass:
```
SUCCESS BUILD WRFPlus
56872 -rwxr-xr-x 1 wrfuser wrf 58234696 Nov 25 04:32 main/wrfplus.exe
```
and all 43 executables
```
SUCCESS BUILD WRFDA-4DVar
   36 -rwxr-xr-x 1 wrfuser wrf    34416 Nov 25 04:33 var/build/da_advance_time.exe
  108 -rwxr-xr-x 1 wrfuser wrf   110112 Nov 25 04:33 var/build/da_bias_airmass.exe
   96 -rwxr-xr-x 1 wrfuser wrf    97400 Nov 25 04:33 var/build/da_bias_scan.exe
   44 -rwxr-xr-x 1 wrfuser wrf    43600 Nov 25 04:33 var/build/da_bias_sele.exe
   52 -rwxr-xr-x 1 wrfuser wrf    52208 Nov 25 04:33 var/build/da_bias_verif.exe
   88 -rwxr-xr-x 1 wrfuser wrf    89192 Nov 25 04:33 var/build/da_rad_diags.exe
  124 -rwxr-xr-x 1 wrfuser wrf   125888 Nov 25 04:33 var/build/da_tune_obs_desroziers.exe
  272 -rwxr-xr-x 1 wrfuser wrf   276208 Nov 25 04:33 var/build/da_tune_obs_hollingsworth1.exe
  180 -rwxr-xr-x 1 wrfuser wrf   181968 Nov 25 04:33 var/build/da_tune_obs_hollingsworth2.exe
  164 -rwxr-xr-x 1 wrfuser wrf   164216 Nov 25 04:33 var/build/da_update_bc.exe
  120 -rwxr-xr-x 1 wrfuser wrf   119256 Nov 25 04:33 var/build/da_update_bc_ad.exe
  200 -rwxr-xr-x 1 wrfuser wrf   201504 Nov 25 04:33 var/build/da_verif_grid.exe
   88 -rwxr-xr-x 1 wrfuser wrf    88560 Nov 25 04:33 var/build/da_verif_obs.exe
77340 -rwxr-xr-x 1 wrfuser wrf 79194744 Nov 25 04:36 var/build/da_wrfvar.exe
  684 -rwxr-xr-x 1 wrfuser wrf   696400 Nov 25 04:33 var/build/gen_be_addmean.exe
  672 -rwxr-xr-x 1 wrfuser wrf   687912 Nov 25 04:33 var/build/gen_be_cov2d.exe
  688 -rwxr-xr-x 1 wrfuser wrf   700448 Nov 25 04:33 var/build/gen_be_cov2d3d_contrib.exe
  672 -rwxr-xr-x 1 wrfuser wrf   687912 Nov 25 04:33 var/build/gen_be_cov3d.exe
  688 -rwxr-xr-x 1 wrfuser wrf   700448 Nov 25 04:33 var/build/gen_be_cov3d2d_contrib.exe
  684 -rwxr-xr-x 1 wrfuser wrf   696360 Nov 25 04:33 var/build/gen_be_cov3d3d_bin3d_contrib.exe
  692 -rwxr-xr-x 1 wrfuser wrf   704544 Nov 25 04:33 var/build/gen_be_cov3d3d_contrib.exe
  664 -rwxr-xr-x 1 wrfuser wrf   679720 Nov 25 04:33 var/build/gen_be_diags.exe
  680 -rwxr-xr-x 1 wrfuser wrf   696272 Nov 25 04:33 var/build/gen_be_diags_read.exe
  676 -rwxr-xr-x 1 wrfuser wrf   692112 Nov 25 04:33 var/build/gen_be_ensmean.exe
  692 -rwxr-xr-x 1 wrfuser wrf   708504 Nov 25 04:33 var/build/gen_be_ensrf.exe
  752 -rwxr-xr-x 1 wrfuser wrf   769832 Nov 25 04:33 var/build/gen_be_ep1.exe
  824 -rwxr-xr-x 1 wrfuser wrf   843672 Nov 25 04:33 var/build/gen_be_ep2.exe
  736 -rwxr-xr-x 1 wrfuser wrf   749760 Nov 25 04:33 var/build/gen_be_etkf.exe
  680 -rwxr-xr-x 1 wrfuser wrf   696104 Nov 25 04:33 var/build/gen_be_hist.exe
  784 -rwxr-xr-x 1 wrfuser wrf   799240 Nov 25 04:33 var/build/gen_be_stage0_gsi.exe
  804 -rwxr-xr-x 1 wrfuser wrf   819456 Nov 25 04:33 var/build/gen_be_stage0_wrf.exe
  720 -rwxr-xr-x 1 wrfuser wrf   737072 Nov 25 04:33 var/build/gen_be_stage1.exe
  716 -rwxr-xr-x 1 wrfuser wrf   732976 Nov 25 04:33 var/build/gen_be_stage1_1dvar.exe
  716 -rwxr-xr-x 1 wrfuser wrf   733184 Nov 25 04:33 var/build/gen_be_stage1_gsi.exe
  696 -rwxr-xr-x 1 wrfuser wrf   712496 Nov 25 04:33 var/build/gen_be_stage2.exe
  716 -rwxr-xr-x 1 wrfuser wrf   733032 Nov 25 04:33 var/build/gen_be_stage2_1dvar.exe
  168 -rwxr-xr-x 1 wrfuser wrf   171856 Nov 25 04:33 var/build/gen_be_stage2_gsi.exe
  684 -rwxr-xr-x 1 wrfuser wrf   700208 Nov 25 04:33 var/build/gen_be_stage2a.exe
  692 -rwxr-xr-x 1 wrfuser wrf   708400 Nov 25 04:33 var/build/gen_be_stage3.exe
  672 -rwxr-xr-x 1 wrfuser wrf   687920 Nov 25 04:33 var/build/gen_be_stage4_global.exe
  708 -rwxr-xr-x 1 wrfuser wrf   720960 Nov 25 04:33 var/build/gen_be_stage4_regional.exe
  668 -rwxr-xr-x 1 wrfuser wrf   683880 Nov 25 04:33 var/build/gen_be_vertloc.exe
  800 -rwxr-xr-x 1 wrfuser wrf   819184 Nov 25 04:33 var/build/gen_mbe_stage2.exe
```

**Comment by davegill** [comment]
@weiwangncar @dudhia 
This is ready for a review

**Comment by davegill** [comment]
@weiwangncar @dudhia 
As per our conversation, we should commit this NO NMM PR soon, so that other contributors to the develop branch have a chance to work on their modified mods.

**Comment by davegill** [comment]
@kkeene44 
Kelly, 
Would you please remove the HWRF group, the NMM group, and anyone that has repo privileges from those groups.

**Comment by davegill** [comment]
@mgduda 
Michael,
In the WRF release meeting today, the NMM clean-up was reviewed. For WPS, removing the NMM namelist and TBL files is sufficient for users to get the hint.

**Review by liujake — APPROVED** [review]
WRFDA regression test passed with this branch.

**Comment by mgduda** [comment]
> @mgduda Michael, In the WRF release meeting today, the NMM clean-up was reviewed. For WPS, removing the NMM namelist and TBL files is sufficient for users to get the hint.

That sounds easy enough.

**Comment by weiwangncar** [comment]
@davegill I've repeated my single case test with the latest code, and they produce identical results.

**Review by weiwangncar — APPROVED** [review]

**Comment by kkeene44** [comment]
@davegill 
I have removed HWRF and NMM access to this repository.

**Pull request merged**
