### PR TITLE
Adding Solar diagnostics package

### PR DESCRIPTION
**Pull request by davegill**
TYPE: New feature

KEYWORDS: WRF-Solar, diagnostics

SOURCE: Timothy Juliano, Pedro Jimenez, Ju-Hye Kim (NCAR/RAL)

DESCRIPTION OF CHANGES:

Replaces PR #1047 "Adding Solar diagnostic package"

We have created a new diagnostic package for users with interests in parameters that are potentially relevant to solar applications. In the new package, we calculate: solar zenith angle, clearness index, 2-D max cloud fraction, water vapor path, liquid water path, ice water path, snow water path, total water path (liquid + ice + snow), liquid cloud effective radius, ice effective radius, snow effective radius, liquid cloud optical thickness, ice optical thickness, snow optical thickness, cloud base height, and cloud top height. Also, for liquid and ice variables, we calculate the 'total' water path, effective radius, and optical thickness, where the 'total' variables also account for subgrid (unresolved) hydrometeors. We have re-organized the radiation driver code in order to expose the calculation of unresolved hydrometeors during time steps when the radiation physics is not called. After re-organization of the radiation driver code, we ran two tests: one using the default develop code and the other using our modified code with the solar diagnostics turned off; the outputs are bit-for-bit equivalent.

All of the variables added within the solar diagnostics package are defined on the 2-D grid and also as timeseries variables in Registry/registry.solar_fields and the variables are calculated in phys/module_diag_solar.F. The solar diagnostics package is activated by setting solar_diagnostics = 1 in the WRF namelist.input file:

&diags
 solar_diagnostics         =  1
 /

LIST OF MODIFIED FILES:
M Registry/Registry.EM_COMMON
M Registry/registry.em_shared_collection
M dyn_em/module_first_rk_step_part1.F
M main/depend.common
M phys/Makefile
M phys/module_diagnostics_driver.F
M phys/module_radiation_driver.F
M share/module_check_a_mundo.F
M share/wrf_timeseries.F
M run/README.namelist
M run/README.tslist
M test/em_real/examples.namelist

LIST OF NEW FILES:
A Registry/registry.solar_fields
A phys/module_diag_solar.F

TESTS CONDUCTED: 
- Passed new Jenkins tests, including NMM/HWRF
- Ran a full diurnal cycle of a real case over the Pacific Northwest, USA. The simulation completed, with the output being bit-for-bit equal to the output from a simulation with the same configuration ran using an un-modified version of the code. Shown below are a few images of sample solar package variables for the domain in addition to a time series at the location indicated by a star.

swp

ts_sza

ts_wp

RELEASE NOTES:
A new diagnostic package for users with interests in parameters that are potentially relevant to solar applications is added. In the new package, The following variables are calculated: solar zenith angle, clearness index, 2-D max cloud fraction, water vapor path, liquid water path, ice water path, snow water path, total water path (liquid + ice + snow), liquid cloud effective radius, ice effective radius, snow effective radius, liquid cloud optical thickness, ice optical thickness, snow optical thickness, cloud base height, and cloud top height. Also, for liquid and ice variables, the 'total' water path, effective radius, and optical thickness are computed, where the 'total' variables also account for subgrid (unresolved) hydrometeors. The diagnostics is activated by namelist variable solar_diagnostics (=1) in namelist record @diags. (Thanks to Timothy Juliano, Pedro Jimenez, Ju-Hye Kim of NCAR/RAL)

### CODE REVIEW

**Comment by davegill** [comment]
Replaces #1103 "Adding Solar diagnostics package"
Couldn't merge my mods to fix NMM build (module_radiation_driver.F)

**Comment by davegill** [comment]
@pedro-jm @twjuliano @weiwangncar @dudhia 
Folks,
I added only a few lines to make qi_tot, qc_tot, and solar_opt optional. Associated with that are the required IF(PRESENT()) tests. I made a local copy of solar_opt which is used instead. This PR works with NMM:
```
Timing for  Timing for start_domain on d           2:    0.61054 elapsed seconds
Timing for main: time 2012-10-28_06:09:00 on domain   1:    5.08981 elapsed seconds
GWD usage currently may be problematic for some cases - use at own risk
Timing for main: time 2012-10-28_06:09:15 on domain   2:    1.22741 elapsed seconds
Timing for main: time 2012-10-28_06:09:30 on domain   2:    0.32143 elapsed seconds
Timing for main: time 2012-10-28_06:09:45 on domain   2:    0.42975 elapsed seconds
Timing for main: time 2012-10-28_06:09:45 on domain   1:    9.63119 elapsed seconds
Timing for main: time 2012-10-28_06:10:00 on domain   2:    0.32753 elapsed seconds
Timing for Writing wrfout_d02_2012-10-28_06:10:00 for domain        2:    0.97761 elapsed seconds
Timing for main: time 2012-10-28_06:10:15 on domain   2:    1.40276 elapsed seconds
Timing for main: time 2012-10-28_06:10:30 on domain   2:    0.31932 elapsed seconds
Timing for main: time 2012-10-28_06:10:30 on domain   1:    4.07896 elapsed seconds
Timing for Writing wrfout_d01_2012-10-28_06:10:30 for domain        1:    5.77971 elapsed seconds
d01 2012-10-28_06:10:30 wrf: SUCCESS COMPLETE WRF
```

**Comment by pedro-jm** [comment]
@davegill 
Very good, thanks.

**Comment by dudhia** [comment]
I will note that these are still using the mut integration that only works accurately for non-hybrid coordinates. We have developed a replacement method that we need to add by the release.

**Comment by twjuliano** [comment]
@davegill Thank you very much for your work on this.

**Pull request merged**
