### PR TITLE
NSSL_2mom Snow Reflectivity Correction

### PR DESCRIPTION
**Pull request by MicroTed**
TYPE: bug fix

KEYWORDS: snow radar reflectivity

SOURCE: Ted Mansell (NOAA/National Severe Storms Lab)

DESCRIPTION OF CHANGES:
Fix:
Restored previous formulation of snow reflectivity (before version 4.1.3), as it was realized that the last change 
incorrectly assumed a fixed density independent of size. Generally lower snow reflectivity values as a result (no 
effect on microphysics).

Other:
1. Generic fall speed coefficients (axx,bxx) to accommodate future frozen drops category (no effect).
2. Reordered collection coefficients (dab1lh) to be consistent (no effect).
3. Switched to full calculation of rain number loss via collection by graupel (chacr) to be consistent with collection by 
hail (chlacr) (minor effects).

LIST OF MODIFIED FILES: 
M phys/module_mp_nssl_2mom.F

TESTS CONDUCTED: 
1. Model tests to confirm snow reflectivity and minimal impact from graupel-rain collection (chacr).
2. Are the Jenkins tests all passing? Yes

RELEASE NOTE: For the NSSL 2 moment MP scheme (mp_physics=17, 18, and 22), reverted formulation of snow radar reflectivity back to version (pre-4.1.3) using size-dependent snow density. The diagnosed bright band is still turned on by default: iusewetsnow=1. (Setting iusewetsnow=3 will switch back to old formulation.)

### CODE REVIEW

**Comment by davegill** [comment]
jenkins
```
  Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           18
    Number of Builds       : 48           46
    Number of Simulations  : 163           161        0
    Number of Comparisons  : 103           102        0

    Failed Simulations are:     None
    Which comparisons are not bit-for-bit:     None
```

**Comment by davegill** [comment]
@MicroTed 
Ted,
1. Would you add your affiliation to the commit PR.
2. Please review the RELEASE NOTES. I added in a clause about what MP schemes are impacted. Verify that this additional info is accurate.

**Comment by MicroTed** [comment]
@davegill 
Done. Thanks!

**Review by weiwangncar — APPROVED** [review]

**Review by smileMchen — APPROVED** [review]

**Comment by MicroTed** [comment]
Rats -- there's an array out-of-bounds issue. Fix coming shortly.

**Comment by weiwangncar** [comment]
@MicroTed Is it possible to post a before and after reflectivity plot for this PR?

**Comment by MicroTed** [comment]
> @MicroTed Is it possible to post a before and after reflectivity plot for this PR?

Sure. Here the new default is upper left, old is lower left. Right panels are same but with diagnosed bright band turned off. (This is an idealized squall line, 3D with north-south periodic.) I'll add a bit of logic to be able to run the previous behavior, in case anybody notices a difference.

nssl_refl_snow

**Comment by weiwangncar** [comment]
@MicroTed Thanks! This is good for me.

**Comment by MicroTed** [comment]
Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           17
    Number of Builds       : 48           45
    Number of Simulations  : 163           158        0
    Number of Comparisons  : 103           102        0

    Failed Simulations are:     None
    Which comparisons are not bit-for-bit:     None

**Review by weiwangncar — APPROVED** [review]

**Review by dudhia — APPROVED** [review]
Looks substantive but confined to the scheme.

**Pull request merged**
