### PR TITLE
WSM6: remove unnecessary ifdef for purpose of WRF/MPAS unification

### PR DESCRIPTION
**Pull request by kkeene44**
TYPE: no impact

KEYWORDS: wsm6, wrf, mpas, unify, if loop

SOURCE: internal

DESCRIPTION OF CHANGES: 
At the top of the wsm6 module was an if defined (wrfmodel) loop that included a few 'use' 
statements for models/routines that are currently not used in this MP scheme. Removed that 
loop to unify this routine with MPAS and to clean-up unnecessary dependencies.

LIST OF MODIFIED FILES: 
M   phys/module_mp_wsm6.F

TESTS CONDUCTED: 
 - [x] verified that this builds without problems and produces bit-for-bit results before and after mods.

### CODE REVIEW

**Comment by davegill** [comment]
@kkeene44 
Kelly,
Weird.
These USE associations are used to determine if a particular alarm is ringing, in this case the history alarm (is it time to write to wrfout_d0x). This could have been a "one-off" a long time ago, or perhaps it was used to determine when to compute the radar computations before those were centralized. That computation was expensive and only done when it was a known history output time.

**Comment by davegill** [comment]
@dudhia @weiwangncar 
Jimy and Wei,
This is in the physics dir, so you need to take a look. 
This looks just fine to me. I approve.

**Comment by weiwangncar** [comment]
@kkeene44 @davegill Good point. @kkeene44 Can you do a test with 'do_radar_ref=1 on?  It seems that it will work. But it doesn't hurt to check. Once the model is run, take a look at the output to look for refl_10cm field in 3D (or 4D) list.

**Comment by kkeene44** [comment]
@weiwangncar @davegill 
I verified that refl_10cm looks okay when do_radar_ref is turned on.

**Pull request merged**
