### PR TITLE
Update check_a_mundo to make FARMS work correctly

### PR DESCRIPTION
**Pull request by juhyejuhye**
TYPE: bug fix

KEYWORDS: FARMS, Microphysics, module_check_a_mundo.F

SOURCE: Ju Hye Kim and Pedro Jimenez (NCAR/RAL)

DESCRIPTION OF CHANGES: 

Problem:
FARMS can work correctly with microphysics schemes that do not provide effective radii of clouds. But, current WRF model displays an ERROR message and stops when the 'swint_opt is 2' and 'use_mp_re is not 1'. 

Solution:
We remove this constraint from ‘module_check_a_mundo.F’.

LIST OF MODIFIED FILES: 
M       share/module_check_a_mundo.F

TESTS CONDUCTED: 
1. When FARMS and a microphysics scheme that do not provide effective radii of clouds (ex: mp=2) are used together, the model does not stop anymore.
2. All jenkins tests are passing.

RELEASE NOTE: Fixed an incorrect stop in the model when FARMS radiation is used with microphysics that do not provide effective cloud radii.

### CODE REVIEW

**Comment by davegill** [comment]
@juhyejuhye 
Great!
Close PR #1331, and say that the PR is re-issued in PR #1332. That can be put in the comments (like this box). Then click the "Close with comment" box.

**Comment by juhyejuhye** [comment]
Dave,
Yes I did that.

Thanks,
Ju-Hye

**Comment by dudhia** [comment]
Only one modified file now, so you can update your list.

**Comment by juhyejuhye** [comment]
Yes, I updated the list.

Thanks,
Ju-Hye

**Comment by davegill** [comment]
@weiwangncar @dudhia 
Folks,
I think this PR is ready for review.

**Review by weiwangncar — APPROVED** [review]

**Pull request merged**
