### PR TITLE
Bug Fix for FAST (33 bins) Spectral-Bin Microphysics (FSBM)

### PR DESCRIPTION
**Pull request by JS-WRF-SBM**
TYPE: Bug Fix

KEYWORDS: cloud microphysics

SOURCE: Jacob Shpund

DESCRIPTION OF CHANGES:
Bug Fixes for the Fast Spectral Bin Microphysics (FSBM) cloud microphysical scheme
The bin-wise loops indices as well as output for the polarimetric radar were updated. Small updates inserted across all of the scheme.

LIST OF MODIFIED FILES:
M phys/module_microphysics_driver.F 
M phys/module_mp_fast_sbm.F

TEST RESULTS:
1. Jenkins is OK

### CODE REVIEW

**Comment by JS-WRF-SBM** [comment]
@davegill 
Dave,
Thanks for pointers given so far.
Let me know if there is anything else needed to be changed.

Kobby

**Comment by davegill** [comment]
@JS-WRF-SBM 
Kobby,
Please post the results from the jenkins email in these comments.  It will look like this:

```
Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: d97a13819d233ad9e2a88e77694cd0cbc1717d13, requested by: davegill for PR: https://github.com/wrf-model/WRF/pull/1117. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 10           10
    Number of Builds       : 23           23
    Number of Simulations  : 140           140        0
    Number of Comparisons  : 89           89        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None
```

**Comment by davegill** [comment]
@JS-WRF-SBM 
Kobby,
Also, please post some imagery that indicates a simulation with good results, perhaps with a field indicating success. Take the imagery from a simulation using *THIS* fork/branch.

**Comment by JS-WRF-SBM** [comment]
@davegill 

Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: 62f6c651e46de3648c443cecacf08db67a386a5a, requested by: JS-WRF-SBM for PR: https://github.com/wrf-model/WRF/pull/1127. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 10           10
    Number of Builds       : 23           23
    Number of Simulations  : 140           140        0
    Number of Comparisons  : 89           89        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by JS-WRF-SBM** [comment]
@davegill
 
In `phys/module_mp_fast_sbm.F` around line **4284**, we set the BC for aerosols. We use a user defined parameter  _DX_BOUND_ to identify the outer domain. This is setup dependent and could cause confusion. If not set correctly, the aerosols can deplete significantly. 

1.  Alternatively, we could use:
At the top of the module_mp_fast_sbm >> `USE module_domain, ONLY : domain`
2.  Then, switch between the following lines:
`if (itimestep > 1 .and. dx > dx_bound)then` >> current line
`if (itimestep > 1 .and. **domain** == 1)then` >> this is the new one to be used

Should I send a new PR, or can you fix this?

**Comment by davegill** [comment]
@JS-WRF-SBM @dudhia @weiwangncar 

> In phys/module_mp_fast_sbm.F around line 4284, we set the BC for aerosols. We use a user defined parameter DX_BOUND to identify the outer domain. This is setup dependent and could cause confusion. If not set correctly, the aerosols can deplete significantly.

Kobby,
This is your PR, so go ahead and make the appropriate modifications. If you need to do a check such as "Is this the first time step?", that set of associated computations should be placed in an initialization routine. That initialization routine should be called from phys/module_physics_init.F. There is a subroutine "mp_init" where all of the MP initializations are handled.

**Comment by JS-WRF-SBM** [comment]
@davegill 

I need to check within the FSBM module if the current domain is the _parent domain_.
From `USE module_domain`, should I get  `domain` or `domain_id` ?

**Comment by davegill** [comment]
@JS-WRF-SBM @weiwangncar @dudhia 
> I need to check within the FSBM module if the current domain is the parent domain.

Kobby,
Pass the domain ID from the MP driver (where that variable is already available) to your scheme. If this is in the initialization part, the same variable (id) is available to pass to your routine.

**Comment by JS-WRF-SBM** [comment]
> Kobby,
> Pass the domain ID from the MP driver (where that variable is already available) to your scheme. If this is in the initialization part, the same variable (id) is available to pass to your routine.

Done.

**Comment by davegill** [comment]
@JS-WRF-SBM @dudhia @weiwangncar 
Kobby,
Since these mods are almost entirely inside of your scheme, we are going to approve them without much trouble. Please provide a "TESTS CONDUCTED:" section in your PR commit message. We need to know that the code builds and runs. The jenkins tests that you showed are sufficient to say "All jenkins tests pass". We need you to indicate in the PR message that you have done a before vs after test, and that you are satisfied with the results using your scheme.

**Pull request merged**
