### PR TITLE
TSLIST: add ozone field to vertical profile output files

### PR DESCRIPTION
**Pull request by zxdawn**
TYPE: enhancement

KEYWORDS: tslist, o3, profile

SOURCE: Xin Zhang (NUIST)

DESCRIPTION OF CHANGES:
1. Add the ozone field to those that are included in the vertical profiles.
2. Add ts_o3_profile to Registry/registry.chem

LIST OF MODIFIED FILES:
M Registry/registry.chem
M share/wrf_timeseries.F

TESTS CONDUCTED:
GIF of multiple profiles including O3: 
ozone_tseries

RELEASE NOTES: Add "ozone" to list of profile fields for time series, but only available when building with WRF Chem.

### CODE REVIEW

**Comment by davegill** [comment]
@zxdawn 
We do not need a formal comparison, but if you can manufacture a simple time series of O3 in a figure, that would be great to put into the PR commit message. It is an easy way to demonstrate that the option works.

**Comment by zxdawn** [comment]
@davegill Here's the GIF of multiple profiles including O3: 
ozone_tseries

**Comment by davegill** [comment]
@jordanschnell @kayeekayee @ravanah 
Folks,
This looks reasonable to me.

**Comment by jordanschnell** [comment]
@davegill @ravanah @kayeekayee Looks good to me as well

**Pull request merged**
