### PR TITLE
Adding Solar diagnostic package

### PR DESCRIPTION
**Pull request by twjuliano**
TYPE: New feature

KEYWORDS: WRF-Solar, diagnostics, icloud

SOURCE: Timothy Juliano, Pedro Jimenez, Ju-Hye Kim (NCAR/RAL)

DESCRIPTION OF CHANGES:
There is one main change in this feature addition:
1) We have created a new diagnostic package for users with interests in parameters that are potentially relevant to solar applications. In the new package, we calculate: solar zenith angle, clearness index, 2-D max cloud fraction, water vapor path, liquid water path, ice water path, snow water path, total water path (liquid + ice + snow), liquid cloud effective radius, ice effective radius, snow effective radius, liquid cloud optical thickness, ice optical thickness, snow optical thickness, cloud base height, and cloud top height. Also, for liquid and ice variables, we calculate the 'total' water path, effective radius, and optical thickness, where the 'total' variables account for subgrid hydrometeors when using `icloud = 3`. All of these variables are defined on the 2-D grid and also as timeseries variables in `Registry/registry.solar_fields` and the variables are calculated in `phys/module_diag_solar.F`. The solar package is activated by setting `solar_diagnostics = 1` in the WRF namelist.input file:

```
&diags
 solar_diagnostics         =  1
 /
```

LIST OF MODIFIED FILES:
M Registry/Registry.EM_COMMON
M Registry/registry.em_shared_collection
M dyn_em/module_first_rk_step_part1.F
M main/depend.common
M phys/Makefile
M phys/module_diagnostics_driver.F
M phys/module_radiation_driver.F
M share/module_check_a_mundo.F
M share/wrf_timeseries.F
M run/README.namelist
M run/README.tslist
M test/em_real/examples.namelist

LIST OF NEW FILES:
A Registry/registry.solar_fields
A phys/module_diag_solar.F
A phys/module_ra_farms.F

TESTS CONDUCTED: Ran a full diurnal cycle of a real case over the Pacific Northwest, USA. The simulation completed, with the output being bit-for-bit equal to the output from a simulation with the same configuration ran using an un-modified version of the code. Shown below are a few images of sample solar package variables for the domain in addition to a time series at the location indicated by a star.

swp

ts_sza

ts_wp

### CODE REVIEW

**Comment by twjuliano** [comment]
I see that @pedro-jm submitted FARMS pull request several weeks ago. I believe that I made very similar, if not identical, changes as that request. Apologies for the overlap. Please advise on how to proceed.

**Comment by dudhia** [comment]
At some point we will put Pedro's one in, and then we can see if yours adds
anything else.
Hopefully they will merge easily. You can probably do a comparison or
somehow
merge with Pedro's branch. Let us know what the differences are.
Jimy

**Comment by davegill** [comment]
@twjuliano 
Timothy,
Would you please add an affiliation in the PR commit message. For example:

Original
```
SOURCE: Timothy Juliano, Pedro Jimenez, Ju-Hye Kim
```

New
```
SOURCE: Timothy Juliano (University of Somewhere), Pedro Jimenez (NCAR/RAL), Ju-Hye Kim (University of Other Place)
```

**Comment by davegill** [comment]
@twjuliano @pedro-jm @dudhia 
Team Solar,

1. If this is getting into the v4.2 release, we need these conflicts resolved. Some are trivial (Registry and Makefile and each one-liners).  
2. We also need there to be mods to test/em_real/examples.namelist and run/README.namelist to document this option.
3. Send Kelly a few sentences about the capability for the User's Guide.

This has to be ready by the beginning of next week, with a clean PR (all passes in regression test, demonstrate correct results with develop branch) by the end of Weds.

**Comment by davegill** [comment]
@twjuliano @pedro-jm @dudhia 
Folks,
The only jenkins failures are the expected NMM problems that are now fixed in the develop branch:
```
    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 10           10
    Number of Builds       : 23           23
    Number of Simulations  : 65           65         3
    Number of Comparisons  : 39           39         0

    Failed Simulations are: 
    output_2:2 = STATUS test_002m hwrf nmm_real 34 1NE
output_2:2 = STATUS test_002m hwrf nmm_real 34 2NE
output_2:2 = STATUS test_002m hwrf nmm_real 34 3NE
    Which comparisons are not bit-for-bit: 
    None
```

Once the code is merged (fixing the conflicts), this PR is not breaking anything else right now.

**Comment by twjuliano** [comment]
@davegill @pedro-jm @dudhia 
I have addressed the conflict issue locally and am now running a test simulation to ensure equivalent results. I am out of the office tomorrow and Monday; however, I am hoping to have this finished sometime on Monday before Cheyenne goes down.

**Comment by twjuliano** [comment]
Apologies for multiple commits. I was having issues with resolving conflicts, as some of the modifications would not take. Hopefully this PR is good to go now. Thanks.

**Comment by davegill** [comment]
@twjuliano @dudhia @weiwangncar 
Timothy,
You now have modifications to 181 files - not what you intended.

Screen Shot 2020-02-25 at 7 46 13 AM

**Comment by dudhia** [comment]
We are still seeing too many different files so that needs to be addressed.

**Comment by pedro-jm** [comment]
Replaced by "Adding Solar diagnostics package" #1103

**Comment by gc13141112** [comment]
how use MODIS cloud products to validate WRF simulated cloud droplet effective radius and cloud optical depth?

**Comment by davegill** [comment]
@gc13141112 
> How use MODIS cloud products to validate WRF simulated cloud droplet effective radius and cloud optical depth?

Chao Gao,
This is a question to post to the WRF User forum:
forum.mmm.ucar.edu

**Pull request closed without merging**
