### PR TITLE
Init Henry's Law Constants for MOZART & convective wet scavenging with GF

### PR DESCRIPTION
**Pull request by jordanschnell**
Initialize Henry's Law Constants in phys when using MOZART and convective wet scavenging with GF

TYPE: Bug fix

KEYWORDS: MOZART, GF cumulus (3), conv_tr_wetscav
SOURCE: Dale Allen (UMD)

DESCRIPTION OF CHANGES:
Problem: https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=91&t=11275

This fixes a bug introduced with PR #1354. When a MOZART chemistry option is used in conjuction with cu_physics = 3 and conv_tr_wetscav = 1, the Henry's Law Constants intialized in the chemistry directory are not available to the physics code resulting in a memory mapping error when attemtping to index the allocatable array. This commit adds an additional subroutine in module_cu_gf_ctrans.F that is identical to the intitialzation routine in module_ctrans_grell.F, which is the parameterized convective transport scheme disconnected from physics (i.e., cu_physics /= 3 or 10 & chem_conv_tr = 1).

ISSUE: https://forum.mmm.ucar.edu/phpBB3/viewtopic.php?f=91&t=11275

LIST OF MODIFIED FILES: 

M       main/depend.common
M       phys/module_cu_gf_ctrans.F

TESTS CONDUCTED: 
1. PENDING - user is undergoing final tests 
2. Are the Jenkins tests all passing?

RELEASE NOTE: Fixed issue when using MOZART chemistry and convective wet scavenging with GF cumulus

### CODE REVIEW

**Comment by jordanschnell** [comment]
Waiting on final tests from bug discoverer, will remove "DO NOT MERGE" tag when ready.

**Review by dudhia — APPROVED** [review]

**Comment by jordanschnell** [comment]
@dudhia @weiwangncar  - still not ready...

**Comment by weiwangncar** [comment]
Jenkins tests have passed:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by jordanschnell** [comment]
@weiwangncar @dudhia - My only consideration here is the dependency on a chem module in main/depend.common. Tested with both WRF_CHEM = 0 and = 1 and there are no issues, but a full debug run fails with and without the proposed changes so I couldn't be sure. Can you advise on main/depend.common? I don't think pre-compiler fiags are recognized, are they?

**Comment by weiwangncar** [comment]
@jordanschnell I see that module_cu_gf_ctrans.F uses several modules (after a grep):

  USE module_HLawConst, only:HLC
  USE module_state_description, ONLY: mozart_mosaic_4bin_kpp, &
  USE module_ctrans_aqchem
  USE module_state_description, only:RADM2SORG,RADM2SORG_AQ,  &

So I think the files to be added to the dependencies for this routine should be (note module_state_description.F is a generated file):

module_cu_gf_ctrans.o: \
                ../chem/module_chem_utilities.o \
                ../share/module_HLaw.o \
                ../share/module_ctrans_aqchem.o \
                ../frame/module_state_description.o

**Comment by jordanschnell** [comment]
@weiwangncar I've submitted the commit with these dependencies. Can this still make it in the release?

**Comment by weiwangncar** [comment]
@jordanschnell So it works now even with debug mode?

**Comment by weiwangncar** [comment]
@jordanschnell We will try to get this into the release.

**Comment by jordanschnell** [comment]
@weiwangncar  Well now the regression is failing...

**Comment by weiwangncar** [comment]
@jordanschnell The failed regtest is not likely your fault. It happens from time to time. Will see what happens to the next test.

**Comment by weiwangncar** [comment]
@jordanschnell If you are happy with the PR, we can approve it.

**Comment by jordanschnell** [comment]
@weiwangncar I am still getting a floating invalid error with full debug and cu_phys = 3, and WRF_CHEM = 0 and so unrelated to the PR here (L1012 of module_cu_gf_deep.f90).

**Comment by jordanschnell** [comment]
@weiwangncar  Looks to be a divide by zero error in the calculation of ucd(i,ki) on L1059 of module_cu_gf_deep.F

**Comment by weiwangncar** [comment]
@jordanschnell Do you want to make that a separate fix? If so, we can proceed and approve and merge this PR.

**Comment by jordanschnell** [comment]
@weiwangncar I think that is the best course. The same divide by 0 error occurs in release-v4.2.3, before any of the chem components were coupled to GF.

**Comment by weiwangncar** [comment]
@jordanschnell Do you need anyone from the chemistry group to approve this or just us?

**Comment by jordanschnell** [comment]
@weiwangncar no need for chem approval

**Review by weiwangncar — APPROVED** [review]

**Review by dudhia — APPROVED** [review]

**Pull request merged**
