### PR TITLE
adding custom eta levels to idealized fire runs

### PR DESCRIPTION
**Pull request by masih-e**
Add custom eta_levels capability in idealized WRF-Fire initialization.

TYPE: enhancement

KEYWORDS: idealized, WRF-Fire

SOURCE: Masih Eghdami (NCAR)

DESCRIPTION OF CHANGES:
When using idealized to set up the domain, the eta_levels are ignored for em_fire test. Now if specified, they will be prioritized for calculating the eta levels (znw) in the model.

Solution:
Part of the code for calculating the model levels from module_initialize_ideal.F (Lines 655-706) is copied to module_initialize_fire.F

LIST OF MODIFIED FILES: 
module_initialize_fire.F

TESTS CONDUCTED: 
1. Do mods fix problem? Yes, I checked the wrfinput_d01 after running the ideal.exe and the ph+phb levels look as expected.
2. The Jenkins tests are all passing.

RELEASE NOTE: The idealized.exe for fire runs previously does not support customized model levels specified in the namelist option eta_levels. This PR enables customized vertical levels. Vertical nesting is not supported at this point.

### CODE REVIEW

**Comment by davegill** [comment]
@masih-e @weiwangncar 
> Idealized WRF-Fire ignores the custom eta_levels now prioritized.

Does this mean that if a user specifies eta levels with the WRF fire initialization program, that after this PR those levels will now be used by the WRF model?

This is a fundamental modification to the ideal initialization programs. We will need to see results of some tests to confirm that this works with a single domain, nested domains, nested domains with different numbers of eta levels, nested domains with single input or multiple input files, and with hybrid- and terrain-following vertical coordinates, etc.

**Comment by weiwangncar** [comment]
@masih-e Is this from your PR "Part of the code for calculating the model levels from module_initialize_ideal.F is copied to module_initialize__fire_.F" the right reference?

**Comment by masih-e** [comment]
@weiwangncar  Yes I copied the lines 655-706 from dyn_em/module_initialize_ideal.F to dyn_em/module_initialize_fire.F

I suggest closing the PR and adding it later as a bigger project. I cannot provide results with hybrid coordinates and nested vertical levels. Also, this addition doesn't work with vertical nesting.

**Comment by weiwangncar** [comment]
@masih-e I see that now. Thanks. It is up to you to make that decision to close this PR until later.

**Review by dudhia — DISMISSED** [review]

**Comment by dudhia** [comment]
This one is still targeted towards develop and needs to be changed to the release target.

**Comment by weiwangncar** [comment]
The Jenkins tests have passed:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by weiwangncar — APPROVED** [review]

**Review by dudhia — APPROVED** [review]

**Pull request merged**
