### PR TITLE
Add printing a line with git commit hash and a summary of files changed

### PR DESCRIPTION
**Pull request by janmandel**
TYPE: enhancement

KEYWORDS: commit hash, source files verification, provenance, user support, development, version control

SOURCE: Jan Mandel (University of Colorado Denver)

DESCRIPTION OF CHANGES: 

User support is more difficult without knowing if the user may have changed any files in the distribution, and, for developers, it is not possible to check if the binary executable is the same version as the source files, leading to unneeded rebuilds. 

This PR includes a line  in WRF output next to the WRF release version with the git commit hash and, if any files changed, also a short diff statistics. If the files are not under git version control, the line indicates that git commit identification is not available. The command ```strings wrf.exe | grep 'git commit'``` outputs the same line, which identifies what exact version the binary is from. The identification line is also printed in the output of ```./compile```. 

The new functionality is implemented by generating new file ```inc/commit_decl``` by ```./compile```, and using it similarly as ```inc/version_decl```. The file is deleted by ```./clean```.

Examples:

In WRF output: 
```
WRF V4.2 MODEL
git commit a599473c3c6db6cf00da79a7a7244085ba800f11
```

To identify the binary executable without running it:
```
strings wrf.exe | grep "git commit"
git commit a599473c3c6db6cf00da79a7a7244085ba800f11
```

In ./compile output, with some file changed: 
```
V4.2
git commit ccc58d749be86c1d5ddd45b4c3f82b2c4f9ca980 1 file changed, 1 insertion(+)
```
Content of the generated ```commit_decl``` file: 
```
    CHARACTER (LEN=*), PARAMETER :: commit_version = 'git commit e5d6fe01f5d319405af4f0e7d60aac8d9df02e43'
```

Content of the generated ```commit_decl``` file, with source files not from github, or no git on the system:
```
    CHARACTER (LEN=*), PARAMETER :: commit_version = 'No git found or not a git repository, git commit version not available.'
```

LIST OF MODIFIED FILES:
M clean
M compile
M main/module_wrf_top.F

TESTS CONDUCTED: 
1. Built and run with Intel and GNU compilers, with and without git available, in a cloned 
repository, and in a directory not under git control.
2. Jenkins regression test passed.

RELEASE NOTE: The git commit information is part of the WRF modeling system standard output, part of the strings within the executables, and also in the output of the ./compile command.

### CODE REVIEW

**Comment by davegill** [comment]
@janmandel 
Jan,
I like the idea.

Would you paste the resulting text in the PR commit message, and also paste in the output from the real or WRF run?

**Comment by janmandel** [comment]
@davegill
> Jan,
> I like the idea.

Dave, thank you! We have been doing something similar in the fire model through phys/Makefile for a while since 7b2743f76ce94be48247df98a54d18b684e61a04 and found it very useful, but now it can be done right.  

> Would you paste the resulting text in the PR commit message, and also paste in the output from the real or WRF run?

Done. But I do not know how to prevent the commit hash from getting shortened into a link on github.

I have added the git commit identification only in wrf.exe and ./compile, which are the important ones for me.  I should I add the git commit identification in some other places where version_decl is used? I know how to test ideal.exe and real.exe but not the others. Here are all source files that use version_decl:

main/tc_em.F:#include "version_decl"
main/real_nmm.F:#include "version_decl"
main/ideal_nmm.F:#include "version_decl"
main/ndown_em.F:#include "version_decl"
main/real_em.F:#include "version_decl"
main/module_wrf_top.F:#include "version_decl"
main/ideal_em.F:#include "version_decl"
chem/chemics_init.F:#include "version_decl"
chem/convert_emiss.F:#include "version_decl"
share/input_wrf.F:#include "version_decl"
var/da/da_control/da_control.f90:#include "version_decl"
var/obsproc/src/module_write.F90:  INCLUDE '../../../inc/version_decl'

**Comment by davegill** [comment]
@janmandel @dudhia @liujake @jordanschnell @weiwangncar @kkeene44 @smileMchen @duda
> Should I add the git commit identification also in some other places where version_decl is used?

Jan,
Let's get other opinions on this.

**Comment by davegill** [comment]
@janmandel 
Jan,
Would you also add three more pieces to your PR commit message. 
1. Include the created text file `commit_decl`
2. In what form does the "summary of changes" appear? Add an example.
3. You said it was tested, but what happens when the source code is not from a github repo?

**Comment by davegill** [comment]
@janmandel 
Jan,
Also, I assume you jenkins testing was OK. Please post the text of the email in these comments, and mention that testing passed in the PR commit message.

**Comment by janmandel** [comment]
> @janmandel
> Jan,
> Would you also add three more pieces to your PR commit message.
> 
> 1. Include the created text file `commit_decl`
> 2. In what form does the "summary of changes" appear? Add an example.
> 3. You said it was tested, but what happens when the source code is not from a github repo?

Added two examples of the generated file, one of them when the source code is not from a github repo.

**Comment by janmandel** [comment]
Jenkins testing passed:

Please find result of the WRF regression test cases in the attachment. This build is for Commit ID: ccc58d749be86c1d5ddd45b4c3f82b2c4f9ca980, requested by: janmandel for PR: https://github.com/wrf-model/WRF/pull/1202. For any query please send e-mail to David Gill.

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 19           18
    Number of Builds       : 48           46
    Number of Simulations  : 166           164        0
    Number of Comparisons  : 105           104        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by janmandel** [comment]
@davegill copied this PR #1202 to PR #1203 .

**Pull request closed without merging**
