### PR TITLE
Update urban LCZ parameter table with more reasonable values

### PR DESCRIPTION
**Pull request by cenlinhe**
Update urban LCZ parameter table (URBPARM_LCZ.TBL) with more reasonable values

TYPE: enhancement

KEYWORDS: urban, parameter

SOURCE: Reported by Benjamin Fersch (Karlsruhe Institute of Technology, Germany), fixed by Alberto Martilli (CIEMAT, Spain)

DESCRIPTION OF CHANGES:
Problem:
Current urban LCZ parameter table includes some unreasonable values for urban morphology (e.g., too large road width) and thermal properties (e.g., CAPR, CAPB, CAPG, AKSR, AKPB, AKPG). The LCZ classification is mainly a classification based on morphology, rather than thermal properties, so it should use the same thermal properties for different LCZs unless users have specific information from other local data sources.

Solution:
Use morphological parameters correspond to mid-range values of Stewart and Oke 2012, and all the LCZ classes have the same thermal properties.

ISSUE: [For use when this PR closes an issue.](https://github.com/wrf-model/WRF/issues/1954)

LIST OF MODIFIED FILES: 
URBPARM_LCZ.TBL

TESTS CONDUCTED: 
1. The mods fix the problem.
2. It passed regression tests.

RELEASE NOTE: Update urban LCZ parameter table (URBPARM_LCZ.TBL) with more reasonable values.

### CODE REVIEW

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by smileMchen — DISMISSED** [review]

**Comment by dudhia** [comment]
I would like to know why every line shows up as changed. This makes it hard to see the actual changes.

**Comment by mgduda** [comment]
> I would like to know why every line shows up as changed. This makes it hard to see the actual changes.

It looks like the line endings have been changed from UNIX line endings to DOS line endings in the PR.

@cenlinhe Could you save the `URBPARM_LCZ.TBL` file so that lines end with '\n' rather than '\r\n'?

**Review by weiwangncar — APPROVED** [review]

**Comment by weiwangncar** [comment]
@smileMchen Can you approve this PR one more time? Thanks!

**Review by dudhia — APPROVED** [review]
note that there are many changes

**Pull request merged**
