### PR TITLE
Identify which auxiliary file is missing - stop incorrectly blaming failures on wrfout metadata

### LINKED ISSUE #770: Misleading error message when wrflowinp_d01 file is missing
Somewhat related to Issue #744 , the error message reported by WRF when `sst_update = 1` and the `wrflowinp_d01` file is missing is somewhat misleading:
```
d01 2019-01-28_00:00:00  Error trying to read metadata
d01 2019-01-28_00:00:00 File name that is causing troubles = 
d01 2019-01-28_00:00:00 
d01 2019-01-28_00:00:00  Error trying to read metadata
d01 2019-01-28_00:00:00  You can try 1) ensure that the input file was created with WRF v4 pre-processors, or
d01 2019-01-28_00:00:00  2) use force_use_old_data=T in the time_control record of the namelist.input file
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     324
 ---- ERROR: The input file appears to be from a pre-v4 version of WRF initialization routines
-------------------------------------------
```
It would probably be more helpful for users if we told them that the file was in fact missing, rather than suggesting that the file is "from a pre-v4 version of WRF", which suggests that a file was actually read but found to be incompatible.

### PR DESCRIPTION
**Pull request by davegill**
TYPE: bug fix

KEYWORDS: missing files, input_wrf

SOURCE: identified by Michael Duda (NCAR/MMM), fixed internally

DESCRIPTION OF CHANGES: 
Problem:
The user was given an incorrect diagnostic print when an auxiliary file was missing (such as for
SST update or FDDA). The user was ALWAYS told that the WRF model could not read the 
metadata from the wrfout file. 
```
d01 2000-01-24_12:00:00  Error trying to read metadata
d01 2000-01-24_12:00:00 File name that is causing troubles = wrfout_d01_2000-01-24_12:00:00
d01 2000-01-24_12:00:00 wrfout_d01_2000-01-24_12:00:00
d01 2000-01-24_12:00:00  Error trying to read metadata
d01 2000-01-24_12:00:00  You can try 1) ensure that the input file was created with WRF v4 pre-processors, or
d01 2000-01-24_12:00:00  2) use force_use_old_data=T in the time_control record of the namelist.input file
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     324
 ---- ERROR: The input file appears to be from a pre-v4 version of WRF initialization routines
-------------------------------------------
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     324
 ---- ERROR: The input file appears to be from a pre-v4 version of WRF initialization routines
-------------------------------------------
```

Solution:
If the _filestate_ is either "unopened" or "open for write", we flag the attempt to read the file as
a fatal error. If the file is "unopened", then the file name was wrong or missing. If the _filestate_ is 
"open for write", then the WRF I/O is using the old data from the previous write of the WRF model.
In either case, a print out is issued that maps the _switch_ (stream number) to a more recognizable
WRF namelist identifier (for example, stream 30 is mapped to auxinput4).

ISSUE: 
Fixes #770 "Misleading error message when wrflowinp_d01 file is missing"

LIST OF MODIFIED FILES:
M share/input_wrf.F

TESTS CONDUCTED: 
1. With no missing files, and with FDDA and SST update, bit-wise identical results with a restart.
2. With sst_update activated, and no wrflowinp file
```
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     315
Possibly missing file for = auxinput4
-------------------------------------------
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     315
Possibly missing file for = auxinput4
-------------------------------------------
```
3. With fdda active, and no wrffdda file
```
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     315
Possibly missing file for = auxinput10
-------------------------------------------
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     315
Possibly missing file for = auxinput10
-------------------------------------------
```
4. For the standard WRF Chem case, things behave as expected:
```
Timing for Writing wrfout_d01_2006-04-06_00:00:00 for domain        1:    0.21654 elapsed seconds
d01 2006-04-06_00:00:00  Yes, this special data is acceptable to use:  OUTPUT FROM EMISSIONS V1.0 PREPROCESSOR for WRF version 2.03.1
d01 2006-04-06_00:00:00  Input data is acceptable to use: wrfchemi_d01_2006-04-06_00:00:00
**WARNING** Time in input file not being checked **WARNING**
d01 2006-04-06_00:00:00 Input data processed for aux input   5 for domain   1
d01 2006-04-06_00:00:00  Input data is acceptable to use: wrfbdy_d01
Timing for processing lateral boundary for domain        1:    0.05871 elapsed seconds
 Tile Strategy is not specified. Assuming 1D-Y
WRF TILE   1 IS      1 IE     40 JS      1 JE     40
WRF NUMBER OF TILES =   1
Timing for main: time 2006-04-06_00:04:00 on domain   1:    1.42039 elapsed seconds
Timing for main: time 2006-04-06_00:08:00 on domain   1:    0.45995 elapsed seconds
```

5. For the Chem case, when we remove a file `wrfchemi_d01_2006-04-06_00:00:00`:
```
-------------- FATAL CALLED ---------------
FATAL CALLED FROM FILE:  <stdin>  LINE:     314
Possibly missing file for = auxinput5
-------------------------------------------
```
Then you look in the namelist to find:
```
 &time_control
 auxinput5_inname     = "wrfchemi_d<domain>_<date>"
 /
```

MMM Classroom regtest; em_real, nmm, em_chem; GNU only

Individual tests:
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_1
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_2
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_5
SUCCESS_RUN_WRF_d01_em_real_32_em_real_03FD
SUCCESS_RUN_WRF_d01_em_real_32_em_real_07NE
SUCCESS_RUN_WRF_d01_em_real_32_em_real_10
SUCCESS_RUN_WRF_d01_em_real_32_em_real_11
SUCCESS_RUN_WRF_d01_em_real_33_em_real_03FD
SUCCESS_RUN_WRF_d01_em_real_33_em_real_07NE
SUCCESS_RUN_WRF_d01_em_real_33_em_real_10
SUCCESS_RUN_WRF_d01_em_real_33_em_real_11
SUCCESS_RUN_WRF_d01_em_real_34_em_chem_1
SUCCESS_RUN_WRF_d01_em_real_34_em_chem_2
SUCCESS_RUN_WRF_d01_em_real_34_em_chem_5
SUCCESS_RUN_WRF_d01_em_real_34_em_real_03FD
SUCCESS_RUN_WRF_d01_em_real_34_em_real_07NE
SUCCESS_RUN_WRF_d01_em_real_34_em_real_10
SUCCESS_RUN_WRF_d01_em_real_34_em_real_11
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_01
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_03
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_04a
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_06
SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_01
SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_03
SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_04a
SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_06

Comparison tests:
SUCCESS_RUN_WRF_d01_em_real_32_em_real_03FD vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_03FD status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_03FD vs SUCCESS_RUN_WRF_d01_em_real_34_em_real_03FD status = 0
Files SUCCESS_RUN_WRF_d01_em_real_32_em_real_07NE and SUCCESS_RUN_WRF_d01_em_real_33_em_real_07NE differ
SUCCESS_RUN_WRF_d01_em_real_32_em_real_07NE vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_07NE status = 1
SUCCESS_RUN_WRF_d01_em_real_32_em_real_07NE vs SUCCESS_RUN_WRF_d01_em_real_34_em_real_07NE status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_10 vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_10 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_10 vs SUCCESS_RUN_WRF_d01_em_real_34_em_real_10 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_11 vs SUCCESS_RUN_WRF_d01_em_real_33_em_real_11 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_real_11 vs SUCCESS_RUN_WRF_d01_em_real_34_em_real_11 status = 0
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_01 vs SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_01 status = 0
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_03 vs SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_03 status = 0
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_04a vs SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_04a status = 0
SUCCESS_RUN_WRF_d01_nmm_real_32_nmm_nest_06 vs SUCCESS_RUN_WRF_d01_nmm_real_34_nmm_nest_06 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_1 vs SUCCESS_RUN_WRF_d01_em_real_34_em_chem_1 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_2 vs SUCCESS_RUN_WRF_d01_em_real_34_em_chem_2 status = 0
SUCCESS_RUN_WRF_d01_em_real_32_em_chem_5 vs SUCCESS_RUN_WRF_d01_em_real_34_em_chem_5 status = 0

### CODE REVIEW

**Comment by davegill** [comment]
@dudhia @kkeene44 @smileMchen 
Folks,
I am OK to push these to release-v4.1.1 in a week or so. No rush for v4.1.

**Comment by wgustafson** [comment]
Hi @davegill and @mgduda. I'm glad you figured out this bug. It's been driving me nuts for more than a decade. It is pretty common for me to have to explain to new wrf-chem users that the error messages about file I/O only work in certain conditions and that they have to turn up the debug level to get a reliable message. Because wrf-chem uses so many auxiliary files for things like emissions, we tend to get a lot of file errors. :-)

**Comment by davegill** [comment]
@wgustafson 
Bill,
If you have a case where you can easily make it fail, we would really appreciate if you would test out this PR to verify this works for you. I used FDDA and SST update myself. Adding in a test that verifies that a missing chem file is detected would great.

**Comment by kkeene44** [comment]
@davegill 
This looks okay to me. Do we want to wait for a chem test on this before approving?

**Comment by wgustafson** [comment]
HI @davegill , I don't have any chem setups sitting around with recent enough code to make this quick, so I'd say move forward without the chem test (at least if you are waiting on me). 

If you really want a chem test and have some other chem tests that run nowadays, you could try removing the emissions file from the run directory with the debug setting at zero. In the old code, I think this is sufficient to trigger the error in question.

**Comment by dudhia** [comment]
Our visitor Chris Kruse recently had this problem when he didn't generate a
wrffdda file.
Jimy

**Comment by kkeene44** [comment]
@dudhia 
Did the visitor try this with the fix?

**Comment by dudhia** [comment]
No, it is just an idea for Dave to test his fix.
Jimy

**Comment by davegill** [comment]
@wgustafson @dudhia @kkeene44 @weiwangncar 
Folks,
I just did a quick test with WRF Chem and removed a file. The WRF code acts as we want: it identifies which aux stream is missing. I have updated the PR message to reflect this.

**Comment by weiwangncar** [comment]
@davegill @kkeene44 I'd like this to be tested by Kelly's mini tests to see if it runs ok with normal files.

**Comment by kkeene44** [comment]
@davegill @weiwangncar 
This branch passes all of my basic functionality tests.

**Comment by davegill** [comment]
@weiwangncar @kkeene44 
Kelly,
Woot! Thanks for the testing

**Comment by weiwangncar** [comment]
@kkeene44 @davegill That is great to know!

**Pull request merged**
