### PR TITLE
WRF-Hydro v5.2.0 plus additional improvements

### PR DESCRIPTION
**Pull request by rcabell**
TYPE: update

KEYWORDS: wrf-hydro

SOURCE: WRF-Hydro Team, NCAR/RAL

DESCRIPTION OF ADDITIONS/CHANGES:

* Xinanjiang surface runoff scheme
* Fixes to snow/glacier handling
* Support for National Hydrological Database 64-bit IDs
* MPI improvements
* Compiler support improvements

LIST OF ADDED/MODIFIED FILES:

A hydro/arc/macros.mpp.cray_fortran
M hydro/.version
M hydro/CPL/WRF_cpl/module_wrf_HYDRO.F
M hydro/Data_Rec/module_RT_data.F
M hydro/Data_Rec/rt_include.inc
M hydro/HYDRO_drv/module_HYDRO_drv.F
M hydro/MPP/Makefile
M hydro/MPP/hashtable.F
M hydro/MPP/module_mpp_GWBUCKET.F
M hydro/MPP/module_mpp_ReachLS.F
M hydro/MPP/mpp_land.F
M hydro/Routing/Noah_distr_routing_overland.F
M hydro/Routing/Noah_distr_routing_subsurface.F
M hydro/Routing/Reservoirs/Level_Pool/module_levelpool.F
M hydro/Routing/Reservoirs/Level_Pool/module_levelpool_properties.F
M hydro/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid.F
M hydro/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid_properties.F
M hydro/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts.F
M hydro/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts_properties.F
M hydro/Routing/Reservoirs/module_reservoir_read_rfc_time_series_data.F
M hydro/Routing/Reservoirs/module_reservoir_read_timeslice_data.F
M hydro/Routing/Reservoirs/module_reservoir_utilities.F
M hydro/Routing/module_GW_baseflow.F
M hydro/Routing/module_HYDRO_io.F
M hydro/Routing/module_HYDRO_utils.F
M hydro/Routing/module_NWM_io.F
M hydro/Routing/module_NWM_io_dict.F
M hydro/Routing/module_RT.F
M hydro/Routing/module_UDMAP.F
M hydro/Routing/module_channel_routing.F
M hydro/Routing/module_gw_gw2d.F
M hydro/Routing/module_noah_chan_param_init_rt.F
M hydro/arc/macros.mpp.intel.cray_xc
M hydro/arc/macros.mpp.linux
M hydro/configure
M hydro/nudging/module_nudging_io.F
M hydro/nudging/module_stream_nudging.F
M hydro/template/HYDRO/hydro.namelist

TESTS CONDUCTED:

- WRF-Hydro regression test and coupled evaluation passing
- Jenkins tests all passed.

RELEASE NOTE:
WRF-Hydro is updated to v5.3.

### CODE REVIEW

**Comment by weiwangncar** [comment]
All reg tests have passed:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by kafitzgerald — APPROVED** [review]

**Comment by dudhia** [comment]
Yes, this looks like more than a bug-fix. Did you want to update the code to this extent? Just making sure.

**Review by dudhia — APPROVED** [review]
confined to /hydro so OK for us

**Comment by weiwangncar** [comment]
@rcabell Is there a corresponding WRF-Hydro version this update is based on?

**Comment by rcabell** [comment]
> @rcabell Is there a corresponding WRF-Hydro version this update is based on? 

This is based on the upcoming WRF-Hydro v5.3 release, minus additional NoahMP/LSM changes that aren't applicable to the Coupled WRF/WRF-Hydro system.

**Pull request merged**
