### PR TITLE
Update hydro component to WRF-Hydro v5.2.0

### PR DESCRIPTION
**Pull request by rcabell**
TYPE: enhancement

KEYWORDS: hydro, wrf-hydro

SOURCE: WRF-Hydro Team

DESCRIPTION OF CHANGES:

- Compatibility with GNU Fortran (gfortran) v10.x
- Correctly supports 1D domains (n x 1 grids)
- Correctly supports ISLAKE in NoahMP
- Updated NUOPC cap for LIS coupling
- Updated default channel parameters in gridded configuration
- Updated comments in namelist templates
- Added missing crop and soil NoahMP options
- Removed deprecated / unnecessary namelist options for reach-based lakes
- Performance improvements for channel network initialization
- Output file metadata revisions
- Changed medium-range RTOUT output frequency
- National Water Model template files removed to their own repository

LIST OF MODIFIED FILES: 
M	hydro/CPL/WRF_cpl/module_wrf_HYDRO.F
M	hydro/CPL/WRF_cpl/module_wrf_HYDRO_downscale.F
M	hydro/Data_Rec/module_RT_data.F
M	hydro/Data_Rec/module_namelist.F
M	hydro/Data_Rec/namelist.inc
M	hydro/Data_Rec/rt_include.inc
A      hydro/Debug_Utilities/Makefile
M	hydro/HYDRO_drv/module_HYDRO_drv.F
A      hydro/IO/Makefile
M	hydro/MPP/CPL_WRF.F
M	hydro/MPP/Makefile
A	hydro/MPP/hashtable.F
M	hydro/MPP/module_mpp_ReachLS.F
M	hydro/MPP/mpp_land.F
A      hydro/OrchestratorLayer/Makefile
M	hydro/Routing/Makefile
M	hydro/Routing/Noah_distr_routing.F
A	hydro/Routing/Noah_distr_routing_overland.F
A	hydro/Routing/Noah_distr_routing_subsurface.F
M	hydro/Routing/Overland/module_overland.F
M	hydro/Routing/Overland/module_overland_control.F
M	hydro/Routing/Overland/module_overland_routing_properties.F
A	hydro/Routing/Overland/overland.md
A	hydro/Routing/Reservoirs/.gitignore
A	hydro/Routing/Reservoirs/Level_Pool/Makefile
A	hydro/Routing/Reservoirs/Level_Pool/module_levelpool.F
A	hydro/Routing/Reservoirs/Level_Pool/module_levelpool_properties.F
A	hydro/Routing/Reservoirs/Level_Pool/module_levelpool_state.F
A	hydro/Routing/Reservoirs/Level_Pool/module_levelpool_tests.F
A	hydro/Routing/Reservoirs/Makefile
A	hydro/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/Makefile
A	hydro/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid.F
A	hydro/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid_properties.F
A	hydro/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid_state.F
A	hydro/Routing/Reservoirs/Persistence_Level_Pool_Hybrid/module_persistence_levelpool_hybrid_tests.F
A	hydro/Routing/Reservoirs/Persistence_Level_Pool_Hybrid_Module_README.md
A	hydro/Routing/Reservoirs/RFC_Forecasts/Makefile
A	hydro/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts.F
A	hydro/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts_properties.F
A	hydro/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts_state.F
A	hydro/Routing/Reservoirs/RFC_Forecasts/module_rfc_forecasts_tests.F
A	hydro/Routing/Reservoirs/RFC_Forecasts_Module_README.md
A	hydro/Routing/Reservoirs/module_reservoir.F
A	hydro/Routing/Reservoirs/module_reservoir_read_rfc_time_series_data.F
A	hydro/Routing/Reservoirs/module_reservoir_read_timeslice_data.F
A	hydro/Routing/Reservoirs/module_reservoir_utilities.F
A	hydro/Routing/Reservoirs/reservoir_tests.F
A	hydro/Routing/Subsurface/Makefile
A	hydro/Routing/Subsurface/module_subsurface.F
A	hydro/Routing/Subsurface/module_subsurface_grid_transform.F
A	hydro/Routing/Subsurface/module_subsurface_input.F
A	hydro/Routing/Subsurface/module_subsurface_output.F
A	hydro/Routing/Subsurface/module_subsurface_properties.F
A	hydro/Routing/Subsurface/module_subsurface_state.F
A	hydro/Routing/Subsurface/module_subsurface_static_data.F
A	hydro/Routing/Subsurface/subsurface_tests.F
M	hydro/Routing/module_GW_baseflow.F
M	hydro/Routing/module_HYDRO_io.F
M	hydro/Routing/module_HYDRO_utils.F
M	hydro/Routing/module_NWM_io.F
M	hydro/Routing/module_NWM_io_dict.F
M	hydro/Routing/module_RT.F
M	hydro/Routing/module_UDMAP.F
M	hydro/Routing/module_channel_routing.F
M	hydro/Routing/module_date_utilities_rt.F
M	hydro/Routing/module_gw_gw2d.F
M	hydro/Routing/module_lsm_forcing.F
M	hydro/Routing/module_reservoir_routing.F
M	hydro/arc/Makefile.mpp
M	hydro/arc/macros.gordon
M	hydro/arc/macros.gordon.debug
M	hydro/arc/macros.mpp.IBM.xlf90_r
M	hydro/arc/macros.mpp.gfort
M	hydro/arc/macros.mpp.ifort
M	hydro/arc/macros.mpp.ifort.luna
A	hydro/arc/macros.mpp.ifort.omp
A	hydro/arc/macros.mpp.ifort.summit_has
M	hydro/arc/macros.mpp.ifort.theia
A	hydro/arc/macros.mpp.intel.cray_xc
M	hydro/arc/macros.mpp.linux
M	hydro/arc/macros.mpp.mpiifort
M	hydro/arc/macros.seq.gfort
M	hydro/arc/macros.seq.linux
M	hydro/arc/macros.theia.debug
M	hydro/configure
M	hydro/nudging/module_date_utils_nudging.F
M	hydro/nudging/module_nudging_io.F
M	hydro/nudging/module_stream_nudging.F
M	hydro/template/HYDRO/CHANPARM.TBL
M	hydro/template/HYDRO/hydro.namelist
M	hydro/template/Noah/namelist.hrldas
M	hydro/template/NoahMP/namelist.hrldas
M	hydro/template/setEnvar.sh
M	hydro/utils/Makefile
A	hydro/utils/module_hydro_stop.F
M	hydro/utils/module_version.F

TESTS CONDUCTED: 
1. Code passes internal WRF-Hydro regression testing and output has been validated by team scientists
2. Jenkins test results all pass

RELEASE NOTE: WRF-Hydro has been updated to version v5.2.0

### CODE REVIEW

**Comment by davegill** [comment]
@rcabell @dudhia @weiwangncar 
Folks,
Every single change is in the hydro directory. Once this passes the regression tests, I am OK with it.

**Comment by weiwangncar** [comment]
I'm ok with this PR.

**Review by davegill — APPROVED** [review]

**Comment by rcabell** [comment]
If this PR hasn’t been merged yet, please hold off a moment. I’m seeing a strange build failure on a local test that I’d like to resolve.

thanks,
Ryan

**Comment by davegill** [comment]
@rcabell 
> If this PR hasn’t been merged yet, please hold off a moment.

Sure, no troubles.

**Comment by rcabell** [comment]
Some directories from the upstream WRF-Hydro repository didn't make it into the PR. These have been added (back) to the PR branch.

**Comment by davegill** [comment]
@rcabell 
Ryan,
Let us know when you are OK with the PR, and we'll merge.

**Comment by rcabell** [comment]
> @rcabell
> Ryan,
> Let us know when you are OK with the PR, and we'll merge.

@davegill The PR is ready to; sorry I didn't make that clear

**Pull request merged**
