### PR TITLE
Add three new wind farm parameterizations and their ensembles 

### PR DESCRIPTION
**Pull request by YulongMa**
Add three new wind farm parameterizations and their ensembles

TYPE: new feature

KEYWORDS: wind farm parameterization, windfarm option

SOURCE: Cristina Archer (UDEL), Yulong Ma(UDEL;GWA-MWF) and Ahmad Vasel-Be-Hagh(Tennessee Technological University)

DESCRIPTION OF CHANGES:
Three new wind farm parameterizations and their ensembles have been added. The key innovation of these parameterizations is their ability to directly account for the individual and overlapping sub-grid wakes of wind turbines within a wind farm. This feature was absent in the Fitch parameterization previously used in WRF. Additionally, the three parameterizations differ in their representation of wakes (e.g., top-hat or Gaussian) and their superposition methods (e.g., sum of squared deficits, squared velocities, or empirical fittings).
The new namelist option windfarm_wake_model can be used to select one of the three wind farm parameterizations, the windfarm_overlap_method namelist option can be used to select the desired wake superposition method.
We recommend to use the new wind farm parameterizations, particularly for coarse resolution, high turbine density, and wind directions aligned with the turbine columns.

LIST OF MODIFIED FILES: 
dyn_em/module_first_rk_step_part1.F
phys/module_pbl_driver.F
phys/module_physics_init.F
phys/module_wind_jensen.F
phys/Makefile
Registry/Registry.EM_COMMON
run/README.namelist

TESTS CONDUCTED: 
1. Code tested as shown in references.
2. The Jenkins tests are all passing.

RELEASE NOTE: 
This PR adds options for three new wind farm parameterizations and their ensembles to account for the individual and overlapping sub-grid wakes of wind turbines within a wind farm. It is recommended to use the new wind farm parameterizations, particularly for coarse resolution, high turbine density, and wind directions aligned with the turbine columns. References:
Ma, Yulong, Cristina L. Archer, and Ahmadreza Vasel-Be-Hagh. "The Jensen wind farm parameterization." Wind Energy Science 7.6 (2022): 2407-2431.
Ma, Yulong, Cristina L. Archer, and Ahmad Vasel‐Be‐Hagh. "Comparison of individual versus ensemble wind farm parameterizations inclusive of sub‐grid wakes for the WRF model." Wind Energy 25.9 (2022): 1573-1595.

### CODE REVIEW

**Comment by weiwangncar** [comment]
@YulongMa If you receive an email indicating regression test failure, it may not be your problem. We are currently experiencing issues with regression testing. We will let you know when we can resume testing.

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by dudhia — DISMISSED** [review]

**Comment by weiwangncar** [comment]
@YulongMa Can you add namelist options to run/README.namelist file following windfarm_opt in &physics section?

**Comment by YulongMa** [comment]
> @YulongMa Can you add namelist options to run/README.namelist file following windfarm_opt in &physics section?

The run/README.namelist file has been updated with new namelist options related to the new wind farm parameterizations.

**Review by weiwangncar — APPROVED** [review]

**Comment by weiwangncar** [comment]
@dudhia Will need your approval again after adding the namelists.

**Review by pedro-jm — DISMISSED** [review]
This looks good to me. It is a nice addition.
I have a couple of suggestions that might help improve self documenting the code and perhaps adoption
1. The namelist option to control the parameterization are windfarm_opt, winfarm_model and windfarm_method. These three names have a similar meaning. More descriptive name might be helpful (e.g., wake_model, wake_overlap_model?)
2. The new module is called module_wind_jensen.F and the code seems to go beyond Jensen's wake model. If this is the case, changing the name to one that better reflects the name of the parameterization could be desirable.

**Comment by YulongMa** [comment]
> This looks good to me. It is a nice addition. I have a couple of suggestions that might help improve self documenting the code and perhaps adoption
> 
> 1. The namelist option to control the parameterization are windfarm_opt, winfarm_model and windfarm_method. These three names have a similar meaning. More descriptive name might be helpful (e.g., wake_model, wake_overlap_model?)
> 2. The new module is called module_wind_jensen.F and the code seems to go beyond Jensen's wake model. If this is the case, changing the name to one that better reflects the name of the parameterization could be desirable.

Thank you for your suggestions. I have updated the namelist options as you suggested, (e.g., changing 'windfarm_model' to 'windfarm_wake_model' and 'windfarm_method' to 'windfarm_overlap_method'). Additionally, the name of the new module has been revised to 'module_wind_mav.F', derived from the last names of the three authors of the code.

**Comment by weiwangncar** [comment]
The regression test results from the last change (Commit ID: 5031122a):

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by dudhia — APPROVED** [review]
This should be tested at NCAR later to see if we can run it.

**Comment by weiwangncar** [comment]
@pedro-jm Can you approve this PR?

**Review by pedro-jm — APPROVED** [review]
this looks good again, thanks.
It is not clear why line 42, the one with variables for tke advection, in the phys/module_pbl_driver.F has changed. There is no impact in results but the change does not seem to be necessary for this PR. If this is the case, it would be a cleaner PR if the line is not change it.

**Review by dudhia — APPROVED** [review]

**Comment by islas** [comment]
The addition of `module_wind_mav` to `module_physics_init::phy_init()` was not reflected in updating the `main/depend.common` file causing builds to sporadically fail to compile

**Comment by weiwangncar** [comment]
@islas Can you make a PR to correct this?

**Comment by islas** [comment]
Yes, will do so right now. Mostly wanted to mark this for posterity

**Comment by smileMchen** [comment]
@YulongMa 
Would you please provide a sample file 'windturbines-ll.txt' for us to test this new option? It is better over CONUS. Thanks!

**Comment by YulongMa** [comment]
> @YulongMa Would you please provide a sample file 'windturbines-ll.txt' for us to test this new option? It is better over CONUS. Thanks!
Sure! I will prepare a sample file and a test case in a few days. Thanks!

**Comment by weiwangncar** [comment]
@YulongMa Also, we would appreciate if you could provide a typical namelist setup for a model of 10-20 km grid sizes. Thanks!

**Comment by YulongMa** [comment]
[windfarm_namelist_windturbines-ll.zip](https://github.com/wrf-model/WRF/files/15061253/windfarm_namelist_windturbines-ll.zip)
Please see the attached ZIP file for the namelist and the windturbines-ll.txt for a typical case.
Typical wind turbine setting in windturbines-ll.txt  is as follows:
#latitude, longitude, windfarm_id(random int), windturbine_type (defined in wind-turbine-x.tbl)
33.0563, -78.6556, 2, 1

**Comment by smileMchen** [comment]
@YulongMa 
Thanks for the kind information.

**Comment by weiwangncar** [comment]
@YulongMa I wonder if you would be interested in giving a presentation at our annual users' workshop (June 25-27) about this new option? Let me know.

**Pull request merged**
