### PR TITLE
Fix live fuel moisture content for Anderson fuel category 12

### PR DESCRIPTION
**Pull request by pedro-jm**
TYPE: bug fix

KEYWORDS: fire behavior model, incorrect live fuel moisture content value

SOURCE: Pedro Jimenez (NCAR)

DESCRIPTION OF CHANGES:
Problem:
One value of the live fuel moisture content table was incorrect. The value for the fuel category 12 was 2.3 when it should be zero. See Table 1 in Anderson (1982) available at https://www.fs.usda.gov/rm/pubs_int/int_gtr122.pdf

Solution:
Change the value 2.3 to 0.0.

LIST OF MODIFIED FILES:
M       phys/module_fr_fire_phys.F

TESTS CONDUCTED: 
1. No test conducted. There is only an impact if the fuel moisture model is activated (and there are grid points assigned to fuel category 12). By default the fuel moisture model is turned off. The impact maybe small because the fuel moisture content used is an average of the dead and live fuels.
2. The Jenkins tests are all passing.

RELEASE NOTE: Fix live fuel moisture content for Anderson's fuel category 12

### CODE REVIEW

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by brankokosovic — APPROVED** [review]

**Review by weiwangncar — APPROVED** [review]

**Comment by weiwangncar** [comment]
@pedro-jm There is a conflict in phys/module_fr_fire_phys.F. Can you take a look?

**Comment by pedro-jm** [comment]
@weiwangncar
It appears to me that the changes introduced by the other PR among other things has fixed the live fuel moisture content value I was referring in this PR. So I think we can ignore this PR to resolve the conflict and fix everything.

**Comment by weiwangncar** [comment]
@pedro-jm Thanks for the input. I will close this PR now.

**Pull request closed without merging**
