### PR TITLE
Modified/Corrected LECH's stability functions in the SL Urban Canopy Model following the formulation. 

### PR DESCRIPTION
**Pull request by joshi994**
TYPE: Bug fix

KEYWORDS: LECH stability functions, Latent heat flux, Sensible heat flux, SL Urban Canpy Model

SOURCE: Parag Joshi (Brookhaven National Lab), Katia Lamer (Brookhaven National Lab)

DESCRIPTION OF CHANGES:
Problem:
The stability functions originally proposed by Lech Lobocki which are used in calculating the exchange coefficients between surface layer and roof, building wall, Green roof, and ground are implemented incorrectly. The error surfaced while comparing the formulation suggested in Lobocki 1992 with the equations in commands/lines 3056 and 3062 (WRF-v4.5.2).

Solution:
The code has been corrected by referring to the equations 48 and 49 of the article "A procedure for the derivation of surface layer bulk relationships from simplified second-order closure models" by Lobocki 1992 (Journal of Applied Meteorology).

LIST OF MODIFIED FILES: 
M    phys/module_sf_urban.F

TESTS CONDUCTED: 
1. The significance of the corrections can be highlighted by comparing a test run with the corrected module and current version of the WRF model. 
2. The fix will correct the evaluation of the exchange coefficients between the ground, roof, green roof etc and air. 
3. The Jenkins tests are all passing.

RELEASE NOTE: Lech's stability functions are corrected following the original formulation.

### CODE REVIEW

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@cenlinhe Can you review this PR? Thanks!

**Comment by cenlinhe** [comment]
OK, this is indeed a bug and the proposed fix looks correct to me. I guess this error came from the original code of Noah-MP SFCDIF2 subroutine based on Chen et al., (1997, BLM): https://link.springer.com/article/10.1023/A:1000531001463
which was copied and pasted to the urban part.
The current Noah-MP SFCDIF2 subroutine also has this bug: https://github.com/NCAR/noahmp/blob/noahmp_v4.5_develop/src/module_sf_noahmplsm.F#L4810-L4813
which needs to be fixed too.
@dudhia

**Review by dudhia — APPROVED** [review]
I approve and defer to others on details of this.

**Comment by weiwangncar** [comment]
@cenlinhe Thanks for reviewing this PR. Would you approve this?

**Comment by cenlinhe** [comment]
> @cenlinhe Thanks for reviewing this PR. Would you approve this?

Yes, I approve this. @tslin2 could you please also take a look when you have time?

**Review by weiwangncar — APPROVED** [review]

**Review by dudhia — DISMISSED** [review]
I approve and defer to others on details of this.

**Comment by joshi994** [comment]
@cenlinhe Should I go ahead an make changes in the MoahMP-SFCDIF2 as well or you are going to update the subroutine?

**Comment by cenlinhe** [comment]
> @cenlinhe Should I go ahead an make changes in the MoahMP-SFCDIF2 as well or you are going to update the subroutine?

No, you do not need to do it. I will fix them later.

**Comment by tslin2** [comment]
> > @cenlinhe Thanks for reviewing this PR. Would you approve this?
> 
> Yes, I approve this. @tslin2 could you please also take a look when you have time?

I will try to look at this next week!

**Comment by cenlinhe** [comment]
@joshi994 do you have a reference showing the equations for your latest bug fix commit?

**Comment by cenlinhe** [comment]
> > @joshi994 do you have a reference showing the equations for your latest bug fix commit?
> 
> @cenlinhe I messed up in my latest commit. I have submitted a different pull request. Please refer to the link: #2038

OK, I think you may need to revert back to the original commit by removing the latest one, otherwise this PR seems being messed up.

**Comment by cenlinhe** [comment]
Your previous changes seems gone. They were replaced by your latest code changes.

**Comment by joshi994** [comment]
> Your previous changes seems gone. They were replaced by your latest code changes.

@cenlinhe I am new to GitHub commit. I may need some time to correct the error. What do you suggest?

**Comment by cenlinhe** [comment]
> > Your previous changes seems gone. They were replaced by your latest code changes.
> 
> @cenlinhe I am new to GitHub commit. I may need some time to correct the error. What do you suggest?

Sounds good. It's OK for you to take some time to correct this error. Thanks.

**Comment by joshi994** [comment]
> > > Your previous changes seems gone. They were replaced by your latest code changes.
> > 
> > 
> > @cenlinhe I am new to GitHub commit. I may need some time to correct the error. What do you suggest?
> 
> Sounds good. It's OK for you to take some time to correct this error. Thanks.

@cenlinhe I tried reverting the error. Can you please confirm if the changes are restored and the new PR is still there?

**Comment by cenlinhe** [comment]
looks like this PR is reverted back and correct now.

**Comment by joshi994** [comment]
Thanks for confirming. Please let me know if you need further clarification.

From: Cenlin_He ***@***.***>
Date: Wednesday, April 17, 2024 at 6:10 PM
To: wrf-model/WRF ***@***.***>
Cc: Joshi, Parag ***@***.***>, Mention ***@***.***>
Subject: Re: [wrf-model/WRF] Modified/Corrected LECH's stability functions in the SL Urban Canopy Model following the formulation. (PR #2032)

looks like this PR is reverted back and correct now.

**Comment by cenlinhe** [comment]
@joshi994 just to double check. please see if this is your original PR bug fix code changes: https://github.com/wrf-model/WRF/pull/2032/files
I think it is.

**Comment by joshi994** [comment]
> @joshi994 just to double check. please see if this is your original PR bug fix code changes: https://github.com/wrf-model/WRF/pull/2032/files I think it is.

@cenlinhe Yes, this is the original PR bug fix changes. I accidentally hit my_changes1 for the new PR (https://github.com/wrf-model/WRF/pull/2038) and that's what caused the issue. Thanks for your response.

**Comment by tslin2** [comment]
> > > @cenlinhe Thanks for reviewing this PR. Would you approve this?
> > 
> > 
> > Yes, I approve this. @tslin2 could you please also take a look when you have time?
> 
> I will try to look at this next week!

yes, the changes is consistent with the papers.

**Comment by weiwangncar** [comment]
The regression test results:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@cenlinhe Can you approve this PR?

**Comment by cenlinhe** [comment]
I approve this.

**Review by weiwangncar — APPROVED** [review]
Acting for Cenlin.

**Review by dudhia — APPROVED** [review]
Any idea of the size of the difference?

**Pull request merged**
