### PR TITLE
Remove advance_clock call in ARW real main program

### PR DESCRIPTION
**Pull request by davegill**
TYPE: bug fix

KEYWORDS: advance_clock, ARW, real

SOURCE: Found by Craig Schwartz and Jim Bresch (NCAR), internal

DESCRIPTION OF CHANGES:
Problem:
When two options were selected to be used at the same time in real (multi-file lateral boundaries, and outputting the processed metgrid data at each time), then the file I/O was incorrect.

Solution:
There was a call to domain_clockadvance, which had a side effect of changing the current_date. Removing this call is 
sufficient to give the correct results. This call was superfluous in most cases. However, with the "IF this and also that" 
logic for the failure mode, the call was advancing the time step ahead to the next lateral boundary time in the middle 
processing a metgrid input file. This left a missing file gap in some output streams from the real program.

LIST OF MODIFIED FILES: 
modified:   main/real_em.F

TESTS CONDUCTED: 
1. This change fixes the problem seen by Jim Bresch.
2. Since modifying logic in the real program is a bit scary. For a number of tests that rely on the real program to create 
files, a before vs after bit-wise test was conducted. Note that only test 04 (known to be the problem) shows any 
bit-wise diffs (entirely expected, as the difference is due to a broken vs fixed scenario). All other before vs after tests 
were bit-wise identical (every time period of every additional file that was created). The following tests were 
considered:
   * 01_REGULAR: a standard namelist, no special output files created by real
   * 02_ALL_IC: activating outputting all time periods of the processed metgrid data
   * 03_MULTI_BDY: generating multi-file lateral boundary conditions
   * 04_MULTI_BDY+ALL_IC: output all processed times, and utilize multi-file LBCs (combo of test 02 and 03)
   * 05_FDDA: manufacturing gridded 3d FDDA files
   * 06_SST: turning on the sst_update option
```
============================
01_REGULAR
wrfbdy_d01
 Just plot  F
Diffing ORIG/01_REGULAR/wrfbdy_d01 01_REGULAR/wrfbdy_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_18:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01
 Just plot  F
Diffing ORIG/01_REGULAR/wrfinput_d01 01_REGULAR/wrfinput_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max

============================
02_ALL_IC
wrfbdy_d01
 Just plot  F
Diffing ORIG/02_ALL_IC/wrfbdy_d01 02_ALL_IC/wrfbdy_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_18:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01
 Just plot  F
Diffing ORIG/02_ALL_IC/wrfinput_d01 02_ALL_IC/wrfinput_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01.2021-04-13_15:00:00
 Just plot  F
Diffing ORIG/02_ALL_IC/wrfinput_d01.2021-04-13_15:00:00 02_ALL_IC/wrfinput_d01.2021-04-13_15:00:00
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01.2021-04-13_18:00:00
 Just plot  F
Diffing ORIG/02_ALL_IC/wrfinput_d01.2021-04-13_18:00:00 02_ALL_IC/wrfinput_d01.2021-04-13_18:00:00
 Next Time 2021-04-13_18:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01.2021-04-13_21:00:00
 Just plot  F
Diffing ORIG/02_ALL_IC/wrfinput_d01.2021-04-13_21:00:00 02_ALL_IC/wrfinput_d01.2021-04-13_21:00:00
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01.2021-04-14_00:00:00
 Just plot  F
Diffing ORIG/02_ALL_IC/wrfinput_d01.2021-04-14_00:00:00 02_ALL_IC/wrfinput_d01.2021-04-14_00:00:00
 Next Time 2021-04-14_00:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max

============================
03_MULTI_BDY
wrfbdy_d01_2021-04-13_12:00:00
 Just plot  F
Diffing ORIG/03_MULTI_BDY/wrfbdy_d01_2021-04-13_12:00:00 03_MULTI_BDY/wrfbdy_d01_2021-04-13_12:00:00
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfbdy_d01_2021-04-13_15:00:00
 Just plot  F
Diffing ORIG/03_MULTI_BDY/wrfbdy_d01_2021-04-13_15:00:00 03_MULTI_BDY/wrfbdy_d01_2021-04-13_15:00:00
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfbdy_d01_2021-04-13_18:00:00
 Just plot  F
Diffing ORIG/03_MULTI_BDY/wrfbdy_d01_2021-04-13_18:00:00 03_MULTI_BDY/wrfbdy_d01_2021-04-13_18:00:00
 Next Time 2021-04-13_18:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfbdy_d01_2021-04-13_21:00:00
 Just plot  F
Diffing ORIG/03_MULTI_BDY/wrfbdy_d01_2021-04-13_21:00:00 03_MULTI_BDY/wrfbdy_d01_2021-04-13_21:00:00
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01
 Just plot  F
Diffing ORIG/03_MULTI_BDY/wrfinput_d01 03_MULTI_BDY/wrfinput_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max

============================
04_MULTI_BDY+ALL_IC
wrfbdy_d01_2021-04-13_12:00:00
 Just plot  F
Diffing ORIG/04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_12:00:00 04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_12:00:00
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfbdy_d01_2021-04-13_15:00:00
 Just plot  F
Diffing ORIG/04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_15:00:00 04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_15:00:00
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfbdy_d01_2021-04-13_18:00:00
 Just plot  F
Diffing ORIG/04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_18:00:00 04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_18:00:00
 Next Time 2021-04-13_18:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfbdy_d01_2021-04-13_21:00:00
 Just plot  F
Diffing ORIG/04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_21:00:00 04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_21:00:00
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01
 Just plot  F
Diffing ORIG/04_MULTI_BDY+ALL_IC/wrfinput_d01 04_MULTI_BDY+ALL_IC/wrfinput_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01.2021-04-13_15:00:00
 Just plot  F
Diffing ORIG/04_MULTI_BDY+ALL_IC/wrfinput_d01.2021-04-13_15:00:00 04_MULTI_BDY+ALL_IC/wrfinput_d01.2021-04-13_15:00:00
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01.2021-04-13_21:00:00
 Just plot  F
Diffing ORIG/04_MULTI_BDY+ALL_IC/wrfinput_d01.2021-04-13_21:00:00 04_MULTI_BDY+ALL_IC/wrfinput_d01.2021-04-13_21:00:00
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
         U    132600    3   0.2102650685E+02   0.2087238492E+02   2   0.1778E+01   0.1768E+00
         V    132600    3   0.6919763109E+01   0.7243936327E+01   1   0.1725E+01   0.5585E+00
        PH    130044    3   0.2740479562E+04   0.2730320498E+04   2   0.6694E+02   0.4141E-01
         T    130048    3   0.7433670369E+02   0.7436065080E+02   3   0.1601E+01   0.4406E-01
       THM    130049    3   0.7432648888E+02   0.7435833856E+02   3   0.1655E+01   0.4572E-01
        MU      2601    2   0.1814308883E+04   0.1577946628E+04   0   0.2441E+03   0.2124E+00
         P    128090    3   0.9029695723E+03   0.7928856659E+03   0   0.1138E+03   0.1932E+00
        AL    130025    3   0.2761169246E+00   0.2775874954E+00   2   0.1142E-01   0.1293E+00
     P_HYD    128090    3   0.4933543975E+05   0.4923231817E+05   2   0.1138E+03   0.4171E-02
        Q2      2601    2   0.2771769414E-02   0.3060043876E-02   1   0.3652E-03   0.2326E+00
        T2      2601    2   0.2805432226E+03   0.2829349305E+03   2   0.2659E+01   0.1922E-01
       TH2      2601    2   0.2914374096E+03   0.2941430863E+03   2   0.2989E+01   0.2030E-01
      PSFC      2601    2   0.8827165378E+05   0.8804085858E+05   2   0.2376E+03   0.4176E-02
       U10      2601    2   0.3956576607E+01   0.3961581133E+01   2   0.1029E+01   0.5888E+00
       V10      2601    2   0.4007420071E+01   0.3892980525E+01   1   0.1656E+01   0.4440E+00
    QVAPOR    126931    3   0.1437325426E-02   0.1566339112E-02   1   0.2254E-03   0.3342E+00
      TSLB     10315    3   0.2814085232E+03   0.2820862525E+03   2   0.1431E+01   0.1897E-01
     SMOIS      8908    3   0.1962684431E+00   0.1958141257E+00   2   0.1012E-02   0.2106E-01
      SNOW       176    2   0.1358744695E+01   0.1401775505E+01   1   0.1946E+00   0.1407E+00
     SNOWH       176    2   0.6793723384E-02   0.7008877488E-02   1   0.9731E-03   0.1407E+00
       TSK      2601    2   0.2905976013E+03   0.2914322324E+03   2   0.2044E+01   0.2710E-01
       SST      2601    2   0.2905976013E+03   0.2914322324E+03   2   0.2044E+01   0.2710E-01
wrfinput_d01.2021-04-14_00:00:00
 Just plot  F
Diffing ORIG/04_MULTI_BDY+ALL_IC/wrfinput_d01.2021-04-14_00:00:00 04_MULTI_BDY+ALL_IC/wrfinput_d01.2021-04-14_00:00:00
 Next Time 2021-04-14_00:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max

============================
05_FDDA
wrfbdy_d01
 Just plot  F
Diffing ORIG/05_FDDA/wrfbdy_d01 05_FDDA/wrfbdy_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_18:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrffdda_d01
 Just plot  F
Diffing ORIG/05_FDDA/wrffdda_d01 05_FDDA/wrffdda_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_18:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01
 Just plot  F
Diffing ORIG/05_FDDA/wrfinput_d01 05_FDDA/wrfinput_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max

============================
06_SST
wrfbdy_d01
 Just plot  F
Diffing ORIG/06_SST/wrfbdy_d01 06_SST/wrfbdy_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_18:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01
 Just plot  F
Diffing ORIG/06_SST/wrfinput_d01 06_SST/wrfinput_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrflowinp_d01
 Just plot  F
Diffing ORIG/06_SST/wrflowinp_d01 06_SST/wrflowinp_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_18:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
 Next Time 2021-04-14_00:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
```
3. Additionally, the tests from the case that now works (all ic + multi file lbc) produces results that are identical to the results for when a single option is activated:
```
============================
04_MULTI_BDY+ALL_IC
wrfinput_d01
 Just plot  F
Diffing ORIG/01_REGULAR/wrfinput_d01 04_MULTI_BDY+ALL_IC/wrfinput_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
```
```
============================
04_MULTI_BDY+ALL_IC
wrfbdy_d01_2021-04-13_12:00:00
 Just plot  F
Diffing ORIG/03_MULTI_BDY/wrfbdy_d01_2021-04-13_12:00:00 04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_12:00:00
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfbdy_d01_2021-04-13_15:00:00
 Just plot  F
Diffing ORIG/03_MULTI_BDY/wrfbdy_d01_2021-04-13_15:00:00 04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_15:00:00
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfbdy_d01_2021-04-13_18:00:00
 Just plot  F
Diffing ORIG/03_MULTI_BDY/wrfbdy_d01_2021-04-13_18:00:00 04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_18:00:00
 Next Time 2021-04-13_18:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfbdy_d01_2021-04-13_21:00:00
 Just plot  F
Diffing ORIG/03_MULTI_BDY/wrfbdy_d01_2021-04-13_21:00:00 04_MULTI_BDY+ALL_IC/wrfbdy_d01_2021-04-13_21:00:00
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
```
```
============================
04_MULTI_BDY+ALL_IC
wrfinput_d01
 Just plot  F
Diffing ORIG/02_ALL_IC/wrfinput_d01 04_MULTI_BDY+ALL_IC/wrfinput_d01
 Next Time 2021-04-13_12:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01.2021-04-13_15:00:00
 Just plot  F
Diffing ORIG/02_ALL_IC/wrfinput_d01.2021-04-13_15:00:00 04_MULTI_BDY+ALL_IC/wrfinput_d01.2021-04-13_15:00:00
 Next Time 2021-04-13_15:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01.2021-04-13_18:00:00
 Just plot  F
Diffing ORIG/02_ALL_IC/wrfinput_d01.2021-04-13_18:00:00 04_MULTI_BDY+ALL_IC/wrfinput_d01.2021-04-13_18:00:00
 Next Time 2021-04-13_18:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01.2021-04-13_21:00:00
 Just plot  F
Diffing ORIG/02_ALL_IC/wrfinput_d01.2021-04-13_21:00:00 04_MULTI_BDY+ALL_IC/wrfinput_d01.2021-04-13_21:00:00
 Next Time 2021-04-13_21:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
wrfinput_d01.2021-04-14_00:00:00
 Just plot  F
Diffing ORIG/02_ALL_IC/wrfinput_d01.2021-04-14_00:00:00 04_MULTI_BDY+ALL_IC/wrfinput_d01.2021-04-14_00:00:00
 Next Time 2021-04-14_00:00:00
     Field   Ndifs    Dims       RMS (1)            RMS (2)     DIGITS    RMSE     pntwise max
```
4. Jenkins is OK

RELEASE NOTE: A bug fix was added to handle the incorrect handling file I/O by the ARW real program when both the following are activated: all_ic_times and multi_bdy_files. The real program effectively skipped outputting some of the processed metgrid time periods by putting the data into an incorrect time. If a user has not seen this failure mode, then this PR does not impact them.

### CODE REVIEW

**Comment by davegill** [comment]
@jimbresch
Jim,
I have done some testing. The mod seems general and robust. Tell Jamie I wanted to figure it out before she did.

**Comment by jamiebresch** [comment]
> @jimbresch
> Jim,
> I have done some testing. The mod seems general and robust. Tell Jamie I wanted to figure it out before she did.

No worries @davegill . Jamie is working on something else.

**Comment by davegill** [comment]
@weiwangncar 
Wei,
Would you review this. It impacts relatively few people. I have done some testing (all possible switches to get extra output from the ARW real program). All of the tests indicate that the change is robust. Jim says that the change fixes his error.

**Comment by weiwangncar** [comment]
@davegill Is the only affect real? If it affects output in general, can you do a test of running WRF model with one additional output stream (such as pressure level output)?

**Comment by davegill** [comment]
@weiwangncar 
>  Is the only affect real?

Wei,
Yes, this change is entirely within the main program for real, so it only impacts OUTPUT from the real program. I have tested every option in real that generates additional output. We do not need to test the WRF model model.

**Review by weiwangncar — APPROVED** [review]

**Pull request merged**
