### PR TITLE
bug fix in GOCART gravitational settling

### PR DESCRIPTION
**Pull request by saneku**
TYPE: bug fix

KEYWORDS: GOCART, WRF-Chem, dust and sea salt gravitational settling

SOURCE: Alexander Ukhov, KAUST

DESCRIPTION OF CHANGES:
Problem: It was found that the dust (and sea salt) mass balance is violated in routine _settling_ (module module_gocart_settling.F). In particular, the total mass of the dust (and sea salt) is increasing, when the dust (and sea salt) settles from the upper to the lower layers. In the code the dust (and sea salt) mixing ratios are transfered between the layers, which is not correct, since the air density is changing.

Solution: the discretization scheme was replaced to the one, which accouts for air density change and allows to conserve the dust (and sea salt) total mass.

LIST OF MODIFIED FILES: 
chem/module_gocart_settling.F

TESTS CONDUCTED: To validate our approach we developed a simple case: in the center of the domain (Middle East, 4500x4500 km2) we allocated a small region (100x100 km2), which emits dust for 10 hours. The simulation stops before the dust reachs the boundaries of the domain. No inflow of the dust from the boundaries as well.

Thereby, the dust mass balance is the following:
EMITTED DUST = (dust in the atmosphere) + (gravitationally settled dust) + (dry deposited dust)

 The obtained results demonstrate the dust mass balance before and after the correction.
total

### CODE REVIEW

**Comment by saneku** [comment]
I have attached derivation of the scheme.
derivation

**Comment by davegill** [comment]
@stacywalters @kayeekayee @ravanah 
Folks,
Just a friendly reminder ...
We probably want to roll the v4.0.3 up by the end of December, so that we can push that branch into develop, which will then be the basis of our anticipated v4.1 release in March/April.
Would you please provide a review of this PR.

**Comment by davegill** [comment]
@stacywalters @kayeekayee @ravanah 
Folks,
Just a friendly ping. We need this PR reviewed so that the developer has time to make changes it you request them.

**Comment by davegill** [comment]
@stacywalters 
Stacy,
1. clone saneku's repo
2. checkout the bug_in_GOCART_grav_settling branch

**Comment by davegill** [comment]
@wrf-model/chem 
We plan to release v4.0.3 in a couple of days. After that, we can change this PR to have the develop as the base branch.

**Comment by saneku** [comment]
To get the gravitationally settled and dry deposited dust I modified the code:
instead of storing the instantaneous flux through the ground (ug/m^2/s) I store the accumulated values (ug/m^2). I was wondering, did you see issue #771, where I proposed to implement these changes in the code?

**Comment by stacywalters** [comment]
Alexander,

We indeed have seen PR #771.  Ravan and Kayee at NOAA are handling your PR.

Stacy

**Comment by saneku** [comment]
Stacy,
I talked about issue #771 (https://github.com/wrf-model/WRF/issues/711) not PR (pull request) #771.
It is confusing for me as well, but it is different entities on GitHub.

**Comment by davegill** [comment]
@kayeekayee @ravanah 
Ka Yee and Ravan,
Could we have a review of this PR please? We are close to doing a cut-over to the release branch for v4.1

**Comment by kayeekayee** [comment]
Approved.

**Pull request merged**
