### PR TITLE
Efficiency fix for nwp_diag reflectivity calculation

### PR DESCRIPTION
**Pull request by MicroTed**
REPLACED with #1169 "Efficiency fix for nwp_diag reflectivity calculation"
TYPE:  enhancement

KEYWORDS: nwp_diagnostics, diag_flag

SOURCE: Ted Mansell

DESCRIPTION OF CHANGES: At some point, solve_em was changed so that diag_flag was always set to true when nwp_diagnostics=1. This caused the full 3D radar reflectivity to be calculated on each time step, whereas the diagnostic only needs the lowest level (k=1).  Here, I added a variable 'ke_diag' in solve_em to tell the reflectivity calculation whether to do the full depth (for history output) or only the lowest level (for nwp_diagnostics=1). This avoids unnecessary computation of dBZ for nwp_diag=1, which is expensive for a number of schemes. ke_diag is passed to microphysics driver and from there to individual microphysics schemes. The NSSL and Thompson schemes have been updated to use it, and others could be done in a very similar manner.

LIST OF MODIFIED FILES: 
 dyn_em/solve_em.F
 phys/module_microphysics_driver.F
 phys/module_mp_nssl_2mom.F
 phys/module_mp_thompson.F

TESTS CONDUCTED: Ideal full-physics tests showed that the NWP field REFD_MAX is the same after implementation.

RELEASE NOTE: Improved efficiency of reflectivity calculation for nwp_diagnostics=1 by only computing it at the level where maximum reflectivity is diagnosed.

### CODE REVIEW

**Comment by MicroTed** [comment]
@gthompsnWRF please also review my changes to module_mp_thompson.F

**Comment by MicroTed** [comment]
Second update to module_mp_thompson.F fixes the minor loop issue by adding a loop variable instead of clobbering k_0. The original change caused small differences because k_0 is used to reference an array. Now I see precisely the same values of REFL_MAX in the modified code.

**Comment by davegill** [comment]
@MicroTed @gthompsnWRF @dudhia @weiwangncar 
Ted,
Are only these two MP schemes impacted?

Greg,
Please take a look at the proposed mods to your scheme.

**Comment by davegill** [comment]
@MicroTed 
I am agreeing that this should go on the v414 branch. While not technically a bug, this is certainly something that needs to get fixed.

**Comment by MicroTed** [comment]
@davegill 
Dave,

These are the only two MP schemes that I modified. All scheme are impacted by nwp_diagnostics=1, but especially the ones that use the "rayleigh_soak_wetgraupel" routine (gsfcgce/4ice, lin, morr, wsmX/wdmX). I haven't touched those schemes, but their maintainers could follow the example in Greg's scheme, since they all seem to use the same method of finding the melting level (k_0).

The NSSL scheme doesn't see much difference in timing because the dBZ calc is not so expensive. In the Thompson scheme, I got about a 30% reduction in the wall clock per time step for the test I did, and I think the slowdown could be worse than that with wide-spread convection.

-- Ted 

> @MicroTed @gthompsnWRF @dudhia @weiwangncar
> Ted,
> Are only these two MP schemes impacted?

**Comment by weiwangncar** [comment]
@MicroTed What does 'ke' stand for?
I just want to add a note here so that we know how this diagnostics has evolved. Long time ago when we received these diagnostic code from NSSL, some way to compute radar reflectivity at every model time step was there. The reason was simple, the option wanted to compute maximum radar reflectivity in a model output interval. Some time later, when Greg's radar calculation was added, we realized it was slow so we were simply not computing it at every model time step. By doing so the nwp_diagnostics option lost this useful variable, even though the variable remained in the output. Recently there were some questions about this variable, and this has prompt us to fix it in 4.1, but we didn't consider the efficiency issue.

**Comment by MicroTed** [comment]
@weiwangncar 
> What does 'ke' stand for?

It is for k-end (in the line of kme, kte, etc.) It could be kte_diag or whatever you think would be most easily interpreted.

**Comment by weiwangncar** [comment]
@MicroTed OK. In WRF the first model level is actually kts, not kte.

**Comment by davegill** [comment]
@weiwangncar @dudhia @MicroTed @gthompsnWRF 
Folks,
Are there any "big picture" issues with this PR? Is this a candidate for v4.1.4?

**Comment by MicroTed** [comment]
>  OK. In WRF the first model level is actually kts, not kte.
@weiwangncar 
Yes. Maybe it is clearer if I say that ke_diag gives the vertical loop end limit for the refl_10cm calculation (either 1 or kte.). The loop start is assumed to always be 1 (kts).

**Comment by weiwangncar** [comment]
@MicroTed That's ok.

**Comment by weiwangncar** [comment]
If no one requires this change to be applied to other microphysics option, then this is ok to go.

**Comment by MicroTed** [comment]
@weiwangncar 
Would you want to ask the other developers if they want to add this to their schemes? They may be unaware of the efficiency issue. Of course they can do it later. And I would wait for Greg to return and have a chance to double-check the changes. My refl_10cm calculation is cheap enough that it doesn't have a large impact like some other schemes, so I am happy to wait.

**Comment by weiwangncar** [comment]
@MicroTed It's probably more important to get Greg's approval. We want this to be in 4.1.4. But it could wait for 4.2.

**Comment by davegill** [comment]
REPLACED with #1169 "Efficiency fix for nwp_diag reflectivity calculation"

**Pull request closed without merging**
