### PR TITLE
Fixing the problem that km_opt=5 breaks km_opt=2 and cleaning codes

### PR DESCRIPTION
**Pull request by zhangxsms**
TYPE: bug fix

KEYWORDS: SMS-3DTKE, package

SOURCE: Xu Zhang (Shanghai Typhoon Institute)

DESCRIPTION OF CHANGES:
1. Redefined the variable `l_scale` using a new name `l_diss`, which does not conflict with
variables used in `km_opt=2`.
2. Packaged seven variables used in the `km_opt=5`.
3. Deleted most diagnostic variables such as `u_h_tend`, `v_h_tend`, `w_h_tend` that are 
seldom used by most users, and cleaned up the related codes. Only seven state variables used 
in `km_opt=5` are left.
 
LIST OF MODIFIED FILES:
Registry/Registry.EM_COMMON
Registry/Registry.NMM
dyn_em/module_diffusion_em.F
dyn_em/module_first_rk_step_part2.F
dyn_em/solve_em.F
share/module_check_a_mundo.F

TESTS CONDUCTED:
 - [x] em_fire test with `km_opt=2`.
 - [x] em_les tests with `km_opt=2` and `km_opt=5`.
 - [x] em_tropical_cyclone with `km_opt=2`, `km_opt=5`, and some PBL schemes.

### CODE REVIEW

**Comment by davegill** [comment]
Generic comment to reviewers @weiwangncar @dudhia @smileMchen @kkeene44 
Even though this is a bug fix, this is a bug-fix that correctly belongs on the develop branch. This fixes a problem that is only on the develop branch right now.

**Comment by davegill** [comment]
@zhangxsms @dudhia @weiwangncar 
With km_opt=5, I am trying an idealized case which has sf_sfclay_surface = 0, 0, 0,
I am getting this error:
```
--- ERROR: SMS-3DTKE scheme works with sf_sfclay_physics = 1,5,91
  --- ERROR: Fix km_opt or sf_sfclay_physics in namelist.input.
```
Is it mandatory that a surface layer scheme be used with km_opt=5? If not, the test in check_a_mundo needs to be corrected.

**Comment by zhangxsms** [comment]
> @zhangxsms @dudhia @weiwangncar
> With km_opt=5, I am trying an idealized case which has sf_sfclay_surface = 0, 0, 0,
> I am getting this error:
> 
> ```
> --- ERROR: SMS-3DTKE scheme works with sf_sfclay_physics = 1,5,91
>   --- ERROR: Fix km_opt or sf_sfclay_physics in namelist.input.
> ```
> 
> Is it mandatory that a surface layer scheme be used with km_opt=5? If not, the test in check_a_mundo needs to be corrected.

It is not mandatory, km_opt=5 can be used without surface layer (sf_sfclay_physics = 0).

**Comment by davegill** [comment]
@zhangxsms 
The last commit should address the ability to run with NO surface layer scheme.

**Comment by davegill** [comment]
@weiwangncar @dudhia @llpcarson @kkeene44 
Folks,
I need Wei or Jimy to approve as this is physics related, and I need Laurie to approve as I added a line in the NMM registry (for a check_a_mundo mod).

Kelly is there because she has superpowers and can approve anything at all, but let's do this by the book.

**Pull request merged**
