### PR TITLE
YSU fix for WSM3 and Kessler no-ice test

### PR DESCRIPTION
**Pull request by dudhia**
TYPE: bug fix

KEYWORDS: YSU, WSM3, Kessler, ice check

SOURCE: internal

DESCRIPTION OF CHANGES:
YSU checks on PRESENT(RQIBLTEN) to determine whether to fill local ice part of qv2d, but
RQIBLTEN is always present, so this does not avoid copy from ice array when WSM3/Kessler MP
is used. It is better to check flag_qi which is also available and true (except when using either
WSM3 and Kessler MP schemes).

LIST OF MODIFIED FILES:
phys/module_bl_ysu.F

TESTS CONDUCTED:
Check code runs and uses flag_qi for simple MP scheme.

RELEASE NOTE:
Using the YSU PBL scheme in combination with either the WSM3 or Kessler MP schemes (no ice) is now fixed to not use ice array.

### CODE REVIEW

**Comment by dudhia** [comment]
need approval again

**Comment by dudhia** [comment]
I am undoing reversion instead - sorry for confusion
please approve reverting reversion

**Comment by dudhia** [comment]
this just needs approval again

**Comment by davegill** [comment]
@kkeene44 
I am good with this (no permission to be "official").
You can approve.

**Pull request merged**
