### PR TITLE
Alter graupel intercept

### PR DESCRIPTION
**Pull request by gthompsnWRF**
Relatively small tunings for Thompson MP one-moment graupel Y-intercept parameter diagnosis, creating a better fit to Paul Field et al (2019) analysis of T-28 aircraft hail data.

TYPE: enhancement

KEYWORDS: graupel, hail, microphysics, Y-intercept

SOURCE: gthompsn

DESCRIPTION OF CHANGES:
Problem:
Since prior version with a new relationship was created for Y-intercept parameter of one-moment graupel, the maximum radar reflectivity and max hail size were reduced lower than intended/desired.

Solution:
Minor changes to diagnosis of Y-intercept parameter, resulting in slightly increased highest radar reflectivity and max hail size.  It is not a very significant increase but fits better with the Paul Field et al. (2019) paper that analyzed T-28 aircraft hail data.

ISSUE: None previous

LIST OF MODIFIED FILES: phys/module_mp_thompson.F, phys/module_diag_nwp.F

TESTS CONDUCTED: 
1. Numerous simulations run with HRRR-CONUS-like grid.

### CODE REVIEW

**Comment by dudhia** [comment]
github lists 47 files changed?

**Comment by gthompsnWRF** [comment]
> github lists 47 files changed?


Jimy,
Can you help me understand what happened here?  I have only a few small changes and this happened with *both* my PRs over the weekend.

I think I needed to wipe out my own repo on Git-gthompsnWRF/WRF and start anew with V4.2.1.  That's the one I started with using the git clone command.

If we need to videoconf today, my calendar is open for viewing.

**Comment by dudhia** [comment]
Currently the PR is pointing to master and should point to develop, but I am not sure that will account for it. I notice a lot of diffs in the var directory. Dave should be able to help but he is on PTO this week. Let's defer this until he gets back.

**Comment by weiwangncar** [comment]
@gthompsnWRF @dudhia I've changed base code from master to develop and that has reduced the number of changed files to 1 - 5 for Greg's three PR. Can you please check and make sure those are the files intended to be changed? To check on that, click on 'Files changed' to the top right PR message.

**Comment by gthompsnWRF** [comment]
> @gthompsnWRF @dudhia I've changed base code from master to develop and that has reduced the number of changed files to 1 - 5 for Greg's three PR. Can you please check and make sure those are the files intended to be changed? To check on that, click on 'Files changed' to the top right PR message.


Wei - that worked fantastic, thank you!  I am likely to make another small change to constants to my PR for one-moment graupel. (just FYI), so I can do that now before the PR goes into others' reviews.

**Comment by dudhia** [comment]
I think that PRs #1322, #1323, #1324 have some overlaps(?) so the order they are considered and committed will matter. Probably need to be done one at a time starting with #1322.

**Comment by gthompsnWRF** [comment]
@dudhia  and @davegill   I believe this PR is ready for review again.  One of the PRs is already merged to develop branch, the other is pending but I believe it is finished, just requiring one more check from either/both of you.  Then, this PR would reduce to a single file: module_mp_thompson.F as showing any differences (I think).

**Comment by gthompsnWRF** [comment]
@dudhia @davegill @weiwangncar   Another one, could this get reviewed pleased?  I'd like to see this moving into develop as soon as it can.

**Comment by weiwangncar** [comment]
@gthompsnWRF It may be better if you redo this PR. In your local WRF code directory, do 'git branch' to see what branches you have. If you have either a master or develop branch, do 'git checkout master (or develop)'. Now you should be back to a starting point before you made the two changes. From here, create a new branch for the MP scheme change. You can go back to your branch that has the MP code, and save it somewhere, and come back to the new branch and drop it. This is not elegant, but it can work. Hopefully a PR created by this approach will not have the other changes you made for adding initial cloud, and will make approving the PR easier.

**Comment by weiwangncar** [comment]
@gthompsnWRF Here is a bit better way to do this: Once you create a new branch from your original develop branch, say it is now named 'alter_graupel_intercept_v2', do 'git log alter_graupel_intercept' to find the #hash for your MP change which should be at the top. Then do 'git cherry-pick #hash' which will drop the changes you made from the other branch to the current one. You can then use this branch to push up and make a new PR.

**Comment by gthompsnWRF** [comment]
I shall close this PR as it has now been resumed via PR#1389, which has been based on a newer code branch of v4.2.2 within develop to simplify things.  Only 2 files changed for the new PR because it has now been detached from the mistakes of multiple combined PRs.

**Pull request closed without merging**
