### PR TITLE
User defined values for CO2 content in RRTMG and NOAH-MP

### PR DESCRIPTION
**Pull request by thomasedds**
TYPE:  new feature

KEYWORDS: CO2 content, RRTMG, NOAH-MP

SOURCE: Thomas Schwitalla (UHOH)

DESCRIPTION OF CHANGES:
Problem: 
Currently, the CO2 content in RRTMG is set to a value of 379 ppm while the CO2 content in NOAH-MP is hard-coded to 395 ppm. Users may wish to change these values without applying CLWRFGHG.

Solution:
Two new namelist settings have been introduced:
- co2_content: sets the CO2 content in RRTMG ( namelist&physics)
- co2_content_noahmp: sets the CO2 content in NOAH-MP (namelist&noahmp)
- In the current version, a check is included whether the user defines different CO2 values in RRTMG and NOAH-MP. If this is the case, the user receives a message in rsl.out.0000 but the model will continue.

LIST OF MODIFIED FILES:
M       Registry/Registry.EM_COMMON
M       dyn_em/module_first_rk_step_part1.F
M       phys/module_physics_init.F
M       phys/module_ra_rrtmg_lw.F
M       phys/module_ra_rrtmg_sw.F
M       phys/module_radiation_driver.F
M       phys/module_sf_noahmpdrv.F
M       phys/module_sf_noahmplsm.F
M       phys/module_surface_driver.F
M       share/module_check_a_mundo.F

TESTS CONDUCTED: Short high-resolution simulation to check for erroneous values in radiation and temperature fields. With default values of CO2=379 ppm in RRTMG and 395 ppm in NOAH-MP the results are identical with the original code.

RELEASE NOTE: RRTMG and NOAH-MP can now work with user-defined CO2 values. New namelist switches "co2_content" and "co2_content_noahmp" have been introduced.

### CODE REVIEW

**Comment by davegill** [comment]
@thomasedds 
Thomas,
Would you take a look at #629 "Increase CO2 concentration in RRTMG Routines from 379ppm to 400ppm"
These is a line for Goddard, also. 

If we are incorporating these changes, let's get them all.

**Comment by thomasedds** [comment]
@davegill @dudhia 
Dave, 
It took a while and I hope I found all locations to replace them for the namelist defined CO2. module_ra_clWRF_support.F from #629 does not require any change as the scheme's default value is used as fallback in case CO2 < 0 (which should never happen).

**Comment by dudhia** [comment]
Another idea is to make it a function of year in case someone is doing past simulations.I have a simple function that fits reasonably if interested.Jimy

    On Monday, November 19, 2018, 11:59:04 AM MST, thomasedds <notifications@github.com> wrote:  
 
 
@davegill @dudhia
Dave,
It took a while and I hope I found all locations to replace them for the namelist defined CO2. module_ra_clWRF_support.F from #629 does not require any change as the scheme's default value is used as fallback in case CO2 < 0 (which should never happen).

**Comment by weiwangncar** [comment]
@thomasedds @dudhia If we want CO2 value used in radiation and LSM the same, do we need to declare two variables?

**Comment by dudhia** [comment]
The function I have for year dependence is
co2 = 280. + 90.*exp(0.02*(year-2000))
2000: co2=370
2018: co2=409
1950: co2=313
1900: co2=292
all are reasonable.

**Comment by thomasedds** [comment]
@weiwangncar @dudhia 

Having two variables gives the flexibility for potential impact studies. That's why I kept it separate.

**Comment by dudhia** [comment]
I am thinking of doing this a different way.
I would use a CO2 function of year so that the user does not need to be changing this for each case. There is a good function that fits past CO2.
co2(ppm)=280+90*exp(0.02*(year-2000))
This is graphed against observed values below.
Screen Shot 2020-01-23 at 9 44 40 AM

I would plan to put this in only RRTMG maybe as the default for the next release. Feedback needed.

**Comment by davegill** [comment]
@dudhia 
Jimy,
Given the large range on the ordinate axis, could you generate a similar plot where the y-axis is "Computed - Measured CO2".

**Comment by dudhia** [comment]
Yes, I have that plot. max is about 4 ppm (~1%). Much smaller recently.
Screen Shot 2020-01-23 at 10 10 25 AM

**Comment by dudhia** [comment]
I will leave this PR open as there are still other radiation options and NoahMP that have the old CO2.
The code now has a year-dependent CO2 for RRTMG which supersedes some of this issue. Ideally year-dependent values can be applied to all these other options too.

**Comment by davegill** [comment]
Closed temporarily due to inactivity.

**Pull request closed without merging**
