### PR TITLE
Adding new microphysics WDM7 as mp_physics 26

### PR DESCRIPTION
**Pull request by weiwangncar**
TYPE: new feature

KEYWORDS: WDM7, hail

SOURCE: Sooya Bae, KIAPS

DESCRIPTION OF CHANGES:
This is a new double-moment microphysics with hail as a new prognostic variable. The added hail category helps to reduce the widespread light precipitation (by reducing the formation of graupel) and enhance the heavy precipitation. Both aspects are viewed as improvement over the WDM6 scheme.

LIST OF MODIFIED FILES: list of changed files
M Registry/Registry.EM_COMMON
M Registry/Registry.NMM
M phys/Makefile
M phys/module_microphysics_driver.F
A phys/module_mp_wdm7.F
M phys/module_physics_init.F

TESTS CONDUCTED:
Compiled with EM and NMM. Passed small reg test on Mac and Cheyenne. Restart, nesting, DFI tested.

RELEASE NOTE:
This is a new double-moment microphysics with hail as a new prognostic variable. The added hail category helps to reduce the widespread light precipitation (by reducing the formation of graupel) and enhance the heavy precipitation. Both aspects are viewed as improvement over the WDM6 scheme. (Thanks to Sooya Bae and Songyou Hong of KIAPS, Korea.)

### CODE REVIEW

**Comment by kkeene44** [comment]
@weiwangncar 
Regression test (including new namelists to test this particular option) passes for this scheme. Additionally, I ran some restart tests with some of the basic options (nesting, adaptive time-step, DFI, nest starts later, and sst_update). All of these tests are fine.

**Comment by weiwangncar** [comment]
@kkeene44 Thanks!

**Comment by weiwangncar** [comment]
Here are some test results from a 4 km sub-CONUS run. I have 4 panels in each plot: the top two are from WSM6 and WSM7, and bottom two WDM6 and WDM7. 
The following shows the 12 hour accumulated rainfall from the 4 expts:
rn_12h

The next figure shows reflectivity at model level 18, forecast hour 6:
ref_l18_06h

The next figure shows reflectivity at model level 3, forecast hour 12:
ref_l03_12h

Overall impression is that there is very little difference in this run between WSM6 and WSM7, but differences can be seen between WDM6 and WDM7.

**Comment by weiwangncar** [comment]
Here is a plot of graupel from WSM6 (left), WSM7 (middle) and hail from WSM7 (right) at level 25, forecast hour 6. Yes, some of the graupel became hail. But very little difference in reflectivity.
gr_l25_06h

**Comment by weiwangncar** [comment]
Ran a 12 h 4 km forecast with a 501x501x56 domain for a sub-CONUS case using 180 tasks. The timing for WDM6 is about 27 min, WDM7 about 28 min. Intel compiler is used.

**Pull request merged**
