### PR TITLE
NoahMP bug fix

### PR DESCRIPTION
**Pull request by cenlinhe**
A few bug fixes for NoahMP

TYPE: bug fix

KEYWORDS: two stream inout variable, soil ice in snow combine, water variable unit, generic nsoil treatment

SOURCE: Cenlin He (NCAR) with report from CWB/Taiwan

DESCRIPTION OF CHANGES:
A few bug fixes for NoahMP:
1. Change a few "out" only variables in TWOSTREAM noahmp subroutine to "inout";
2. Change the unit for 3 accumulated noahmp water flux variables in comments and registry;
3. Change the soil ice treatment in subroutine COMBINE to conserve water;
4. Change some hard-coded "4" soil layer number to "nsoil" for more generic treatment.

LIST OF MODIFIED FILES: list of changed files 
M       Registry/registry.noahmp
M       phys/noahmp

TESTS CONDUCTED: 
1. The bug fixes have been tested for NoahMP run over the U.S. for an entire year.
2. Reg tests have passed.

RELEASE NOTE: This PR fixes a few variable declaration in subroutine TWOSTREAM from OUT to INOUT, changes soil ice treatment in subroutine COMBINE, and corrects units for three accumulated flux variables in comments and registry. It also removed hard-coded 4 soil layers, and replaces it with parameter NSOIL.

### CODE REVIEW

**Comment by weiwangncar** [comment]
The Jenkins tests have passed:

   Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@cenlinhe Would you like to make this change available sooner? That would mean 4.4.2.

**Comment by cenlinhe** [comment]
@weiwangncar  Yes, it works for me. Thanks!

**Comment by cenlinhe** [comment]
When will this PR be merged to develop or release-v4.4.2 branch? Recently, two other NoahMP bugs have been identified and I would like to create another PR for those bug fixes based on the updated develop or release-v4.4.2 branch with the current PR bug fix included. Thanks!

**Review by weiwangncar — APPROVED** [review]

**Comment by weiwangncar** [comment]
@dudhia Can you check this PR and approve if it is OK so that Cenlin can move to his next change?

**Comment by dudhia** [comment]
I also saw some dimension changes for nsoil. Were those described?

**Comment by cenlinhe** [comment]
Those are just changing the hard-coded "4" soil layers to "nsoil". By default, NoahMP uses 4 soil layers, so this change is no-answer change. However, this gives more flexibility for users to change nsoil in the future. Otherwise, users need to manually change the hard-coded "4" soil layer in those code files.

**Comment by dudhia** [comment]
OK, it should be added to the description. Thanks.

**Comment by cenlinhe** [comment]
Just added to the description above.

**Review by dudhia — APPROVED** [review]

**Comment by weiwangncar** [comment]
@cenlinhe Can you clarify what 'snow combine subroutine' is? This is in your description of change #3.

**Comment by cenlinhe** [comment]
It is this subroutine "COMBINE" in module_sf_noahmplsm.F. I have included this in the above description.

**Comment by weiwangncar** [comment]
@cenlinhe I added RELEASE NOTE in your PR. Please see if it is ok.

**Comment by cenlinhe** [comment]
The release note looks good to me. Thanks!

**Pull request merged**
