### PR TITLE
bug fix for Noah-MP SFCDIF inout variable

### PR DESCRIPTION
**Pull request by cenlinhe**
Sync with updated Noah-MP Github commit with the bug fix for SFCDIF subroutine inout variable declaration

TYPE: bug fix

KEYWORDS: friction velocity, Noah-MP

SOURCE: Cenlin He (NCAR)

DESCRIPTION OF CHANGES:
Problem:
The friction velocity variable ("FV" or "USTAR") was originally defined as "out" variable in Noah-MP SFCDIF1 and SFCDIF2, which however should be defined as "inout" variable.

Solution:
Change the intent(out) to intent(inout) for the "FV" or "USTAR" variables

LIST OF MODIFIED FILES:
M       phys/noahmp

TESTS CONDUCTED: 
1. The mods fixed the problem.
2. Jenkins tests are all passing.

### CODE REVIEW

**Comment by weiwangncar** [comment]
Jenkins tests have passed:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           58
    Number of Simulations  : 158           156        0
    Number of Comparisons  : 95           92        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Review by dudhia — APPROVED** [review]
Note this has the SICE change too, so it should be merged after that one

**Review by weiwangncar — APPROVED** [review]

**Comment by weiwangncar** [comment]
@cenlinhe It looks like as a submodule, Github does not like PRs that have duplicated changes. You may need to re-do this PR. The merge has been blocked.

**Comment by cenlinhe** [comment]
> @cenlinhe It looks like as a submodule, Github does not like PRs that have duplicated changes. You may need to re-do this PR. The merge has been blocked.

Not sure how to do this. Maybe I should wait until the previous PR has been merged to release-v4.4 and then I use the updated release-v4.4 to re-do this PR?

**Comment by weiwangncar** [comment]
@cenlinhe PR#1699 has been merged to the release-v4.4 branch.

**Comment by cenlinhe** [comment]
OK, I will re-do this PR.

**Comment by weiwangncar** [comment]
Not sure what's going on, but this PR has been replaced by PR#1702.

**Comment by dudhia** [comment]
This PR removed the #1699 changes, so that seems to make it work.

**Comment by dudhia** [comment]
Is it because this PR overlaps with #1699 and has the SICE changes?

**Pull request closed without merging**
