### PR TITLE
The WRF-SoilN-chem: a dynamic ammonia emission model 

### PR DESCRIPTION
**Pull request by RenChuanhua**
The WRF-SoilN-chem: a dynamic ammonia emission model capable of calculating NH3 emission rate interactively with time- and spatial-varying meteorological and soil conditions.

TYPE: enhancement

KEYWORDS: ammonia emission, soil, dynamic, chem, gas phase.

SOURCE: RenChuanhua and Huangxin, Nanjing University.

DESCRIPTION OF CHANGES:  Use a dynamic ammonia emission function instead of a static monthly emission inventory
Problem:
The traditional monthly emission inventory cannot characterize the variation of ammonia emission intensity under different meteorological conditions, which leads to the simulation bias of secondary inorganic aerosol (such as nitrate and sulfate).

Solution:
The meteorological dependent dynamic emission factor (empirical function) is added to the emission file, which can calculate the ammonia emission rate according to hourly meteorological conditions and soil conditions.

LIST OF MODIFIED FILES: list of changed files: 
Registry/Registry.EM_COMMON
Registry/registry.chem
chem/chem_driver.F
chem/emissions_driver.F

TESTS CONDUCTED: 
We compiled and ran the revised model to simulate 2019 East China region, and it can run smoothly, and the running speed has not decreased significantly. Compared with the traditional static emission inventory, the NH3 and nitrate concentrations obtained by dynamic model are obviously optimized.

The code has passed the regression tests.

RELEASE NOTE: 
the whole source code and input dataset (binary data needed to be embedded into WPS geog_data_path) and model userguide can be found in:
https://github.com/RenChuanhua/wrf-nh3-chem_v1.0

Ren, C., Huang, X., Liu, T., Song, Y., Wen, Z., Liu, X., Ding, A., and Zhu, T.: A dynamic ammonia emission model and the online coupling with WRF-Chem (WRF-SoilN-Chem v1.0): development and evaluation, Geosci. Model Dev. Discuss. [preprint], https://doi.org/10.5194/gmd-2022-231, 2022.

### CODE REVIEW

**Comment by weiwangncar** [comment]
@RenChuanhua It looks like the compilation for WRF-Chem had an error from the regression tests:

emissions_driver.f90:1003:2:

 1003 |   emis_ant(ims:ime , config_flags%kemit , jms:jme, p_e_nh3)=0.0
      |  1
Error: Dummy argument 'emis_ant' with INTENT(IN) in variable definition context (assignment) at (1)
emissions_driver.f90:1058:2:

 1058 |   emis_ant(i,1,j,p_e_nh3)=1000.0/(17.0*30.0*24.0)*(emis_house(i,j)+emis_store(i,j)+emis_fert(i,j))  &
      |  1
Error: Dummy argument 'emis_ant' with INTENT(IN) in variable definition context (assignment) at (1)

The regression tests are run using GNU compiler version 9.3.1.

**Comment by RenChuanhua** [comment]
Dear team, 
I checked and corrected the error, and now it has been updated as new commits, can you review it again?
Thank you!

**Comment by jordanschnell** [comment]
> Dear team, I checked and corrected the error, and now it has been updated as new commits, can you review it again? Thank you!

Hi RenChuanhua,

We are currently in the middle of a release cycle for v4.5. Once completed, we will work to get this reviewed and included in the next intermediate release.

**Comment by RenChuanhua** [comment]
ok. Thank you.



---Original---
From: ***@***.***&gt;
Date: Fri, Mar 17, 2023 00:49 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wrf-model/WRF] The WRF-SoilN-chem: a dynamic ammonia emissionmodel  (PR #1826)




  
Dear team, I checked and corrected the error, and now it has been updated as new commits, can you review it again? Thank you!
  
Hi RenChuanhua,
 
We are currently in the middle of a release cycle for v4.5. Once completed, we will work to get this reviewed and included in the next intermediate release.

**Comment by weiwangncar** [comment]
@jordanschnell Can you review this PR?

**Comment by jordanschnell** [comment]
Will do - thanks Wei.Jordan SchnellResearch ScientistCIRES, University of Colorado, BoulderEarth Prediction Advancement Division, Global Systems LaboratoryNational Oceanic and Atmospheric AdministrationOn Jan 11, 2024, at 8:31 PM, weiwangncar ***@***.***> wrote:﻿
@jordanschnell Can you review this PR?

**Comment by weiwangncar** [comment]
@jordanschnell Do you have time to review this PR soon?

**Comment by jordanschnell** [comment]
Hi Wei,

I apologize for the delay. I’ve been trying to get a hold of the developer, but they have not responded. I’ll go ahead and finish the review and they will need to be OK with any changes I make. 

Jordan

Jordan Schnell
Research Scientist
CIRES, University of Colorado, Boulder
Global Systems Laboratory
National Oceanic and Atmospheric Administration

**Comment by weiwangncar** [comment]
@jordanschnell Just leave the comments here. Thanks!
@RenChuanhua Please address any comments a reviewer may have. Thnaks!

**Comment by jordanschnell** [comment]
@RenChuanhua - I have made the commits myself. Please make sure you are OK with them.

**Comment by weiwangncar** [comment]
The regression test results from the latest commit:

    Test Type              | Expected  | Received |  Failed
    = = = = = = = = = = = = = = = = = = = = = = = =  = = = =
    Number of Tests        : 23           24
    Number of Builds       : 60           57
    Number of Simulations  : 158           150        0
    Number of Comparisons  : 95           86        0

    Failed Simulations are: 
    None
    Which comparisons are not bit-for-bit: 
    None

**Comment by weiwangncar** [comment]
@jordanschnell Thanks for doing the review and making the suggested changes. The changes look ok to me. Since we are getting any response from the contributor, do you think we can just approve and merge? Or do you prefer to wait?

**Review by weiwangncar — APPROVED** [review]

**Pull request merged**
